-- HOUSING AND MEALS - WRITTEN BY BUDDY
-- NOT ENROLLED WITH RORPRST_XHS '2' AND SGASTDN RECORD                   
SELECT RORALGS_AMT * 2
FROM SGBSTDN X, RORALGS, RORPRST
WHERE RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '3HSM' -- budget component                        
AND RORALGS_KEY_5 = 'UG'
AND CASE -- campus code
    WHEN X.SGBSTDN_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6

-- max sgbstdn term <= passed period
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND X.SGBSTDN_PIDM = RORPRST_PIDM
AND RORPRST_PERIOD = :PERIOD
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
-- END

-- NOT ENROLLED WITH RORPRST_XHS '2' NO SGASTDN RECORD         
SELECT RORALGS_AMT * 2
FROM SARADAP X, SARAPPD X, RORALGS, STVAPDC, RORPRST
WHERE RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '3HSM' -- budget component                     
AND 
    CASE WHEN X.SARADAP_LEVL_CODE = 'UG' THEN 'UG'
END = RORALGS_KEY_5
AND CASE -- campus code
    WHEN X.SARADAP_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
-- max saradap term <= passed period	
AND X.SARADAP_TERM_CODE_ENTRY = (
     SELECT MAX(Y.SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP Y, ROBINST
    WHERE Y.SARADAP_PIDM = X.SARADAP_PIDM
	AND Y.SARADAP_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
    AND Y.SARADAP_TERM_CODE_ENTRY <= :PERIOD
	AND ROBINST_AIDY_CODE = :AIDY
)
--max application decision code sequence number
AND X.SARAPPD_SEQ_NO = (SELECT MAX (X.SARAPPD_SEQ_NO)
             FROM SARAPPD Y, ROBINST
              WHERE     Y.SARAPPD_PIDM = X.SARAPPD_PIDM
              AND Y.SARAPPD_SEQ_NO < 99
              AND Y.SARAPPD_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
              AND Y.SARAPPD_TERM_CODE_ENTRY <= :PERIOD
              AND ROBINST_AIDY_CODE = :AIDY           
              AND X.SARADAP_APPL_NO = Y.SARAPPD_APPL_NO) 
      
   AND STVAPDC_INST_ACC_IND = 'Y'
   AND STVAPDC_SIGNF_IND = 'Y'
		
AND X.SARADAP_PIDM = RORPRST_PIDM
AND RORPRST_PERIOD = :PERIOD

AND X.SARAPPD_APDC_CODE = STVAPDC_CODE	
AND X.SARADAP_APPL_NO = X.SARAPPD_APPL_NO
AND X.SARADAP_TERM_CODE_ENTRY = X.SARAPPD_TERM_CODE_ENTRY
AND RORALGS_AIDY_CODE = :AIDY
AND X.SARAPPD_PIDM = X.SARADAP_PIDM	
AND X.SARADAP_PIDM = :PIDM
-- END
