SELECT RORSTAT_PIDM
FROM RORSTAT
JOIN ROBINST ON ROBINST_AIDY_CODE = RORSTAT_AIDY_CODE AND ROBINST_STATUS_IND = 'A'
JOIN ROBNYUD ON ROBNYUD_PIDM = RORSTAT_PIDM
WHERE RORSTAT_AIDY_CODE = :AIDY 
-- AND RORSTAT_PIDM = :PIDM
AND ROBNYUD_VALUE_197 = 'Y'
AND ROBNYUD_VALUE_193 = '422801'
AND (( 
    EXISTS (
        SELECT 1
        FROM SATURN.SGBSTDN E
        JOIN SATURN.STVMAJR M on M.STVMAJR_CODE = E.SGBSTDN_MAJR_CODE_1
            and substr(M.STVMAJR_CIPC_CODE, 0, 4) = substr(ROBNYUD_VALUE_193, 0, 4)
        WHERE E.SGBSTDN_PIDM = RORSTAT_PIDM
        AND E.SGBSTDN_STST_CODE IN ('AS', 'IL', 'P1')
        AND E.SGBSTDN_TERM_CODE_EFF = (
            SELECT MAX(F.SGBSTDN_TERM_CODE_EFF)
            FROM SGBSTDN F
            WHERE F.SGBSTDN_PIDM = E.SGBSTDN_PIDM
            AND SUBSTR(F.SGBSTDN_TERM_CODE_EFF,0,4) <= SUBSTR(ROBINST_AIDY_END_YEAR,0,4)
        )
    ) OR EXISTS (
        SELECT 1
        FROM SARADAP A
        JOIN SATURN.STVMAJR M on M.STVMAJR_CODE = A.SARADAP_MAJR_CODE_1
            and substr(M.STVMAJR_CIPC_CODE, 0, 4) = substr(ROBNYUD_VALUE_193, 0, 4)
        JOIN SARAPPD B ON B.SARAPPD_PIDM = A.SARADAP_PIDM
            AND B.SARAPPD_TERM_CODE_ENTRY = A.SARADAP_TERM_CODE_ENTRY
            AND B.SARAPPD_APPL_NO = A.SARADAP_APPL_NO
        JOIN STVAPDC C ON C.STVAPDC_CODE = B.SARAPPD_APDC_CODE
            AND C.STVAPDC_INST_ACC_IND = 'Y'
            AND C.STVAPDC_SIGNF_IND = 'Y'
        WHERE A.SARADAP_PIDM = RORSTAT_PIDM
        AND A.SARADAP_LEVL_CODE = ROBNYUD_VALUE_198
        AND A.SARADAP_TERM_CODE_ENTRY = (
            SELECT MAX(Z.SARADAP_TERM_CODE_ENTRY)
            FROM SARADAP Z
            WHERE Z.SARADAP_PIDM = A.SARADAP_PIDM
            AND Z.SARADAP_TERM_CODE_ENTRY = ROBINST_AIDY_END_YEAR || '00'
        )
        AND A.SARADAP_APPL_NO = (
            SELECT MAX(Z.SARADAP_APPL_NO)
            FROM SARADAP Z
            WHERE Z.SARADAP_PIDM = A.SARADAP_PIDM
            AND Z.SARADAP_TERM_CODE_ENTRY = A.SARADAP_TERM_CODE_ENTRY
        )
        AND B.SARAPPD_SEQ_NO = (
            SELECT MAX(Z.SARAPPD_SEQ_NO)
            FROM SARAPPD Z
            WHERE Z.SARAPPD_PIDM = B.SARAPPD_PIDM
            AND Z.SARAPPD_TERM_CODE_ENTRY = B.SARAPPD_TERM_CODE_ENTRY
            AND Z.SARAPPD_APPL_NO = B.SARAPPD_APPL_NO
        )
    ))
) AND NOT EXISTS (
    SELECT 1
    FROM SARADAP A
    JOIN SATURN.STVMAJR M on M.STVMAJR_CODE = A.SARADAP_MAJR_CODE_1
        and substr(M.STVMAJR_CIPC_CODE, 0, 4) <> substr(ROBNYUD_VALUE_193, 0, 4)
    JOIN SARAPPD B ON B.SARAPPD_PIDM = A.SARADAP_PIDM
        AND B.SARAPPD_TERM_CODE_ENTRY = A.SARADAP_TERM_CODE_ENTRY
        AND B.SARAPPD_APPL_NO = A.SARADAP_APPL_NO
    JOIN STVAPDC C ON C.STVAPDC_CODE = B.SARAPPD_APDC_CODE
        AND C.STVAPDC_INST_ACC_IND = 'Y'
        AND C.STVAPDC_SIGNF_IND = 'Y'
    WHERE A.SARADAP_PIDM = RORSTAT_PIDM
    AND A.SARADAP_TERM_CODE_ENTRY = (
        SELECT MAX(Z.SARADAP_TERM_CODE_ENTRY)
        FROM SARADAP Z
        WHERE Z.SARADAP_PIDM = A.SARADAP_PIDM
        AND Z.SARADAP_TERM_CODE_ENTRY BETWEEN (ROBINST_AIDY_END_YEAR || '10') AND (ROBINST_AIDY_END_YEAR + 1 || '00')
    )
    AND A.SARADAP_APPL_NO = (
        SELECT MAX(Z.SARADAP_APPL_NO)
        FROM SARADAP Z
        WHERE Z.SARADAP_PIDM = A.SARADAP_PIDM
        AND Z.SARADAP_TERM_CODE_ENTRY = A.SARADAP_TERM_CODE_ENTRY
    )
    AND B.SARAPPD_SEQ_NO = (
        SELECT MAX(Z.SARAPPD_SEQ_NO)
        FROM SARAPPD Z
        WHERE Z.SARAPPD_PIDM = B.SARAPPD_PIDM
        AND Z.SARAPPD_TERM_CODE_ENTRY = B.SARAPPD_TERM_CODE_ENTRY
        AND Z.SARAPPD_APPL_NO = B.SARAPPD_APPL_NO
    )
)

;

select * from sgbstdn;
desc stvmajr;