SELECT A.RORSTAT_PIDM
FROM RORSTAT A
JOIN ROBNYUD ON ROBNYUD_PIDM = A.RORSTAT_PIDM
WHERE A.RORSTAT_AIDY_CODE = :AIDY 
AND A.RORSTAT_PIDM = :PIDM   
AND (
   EXISTS (
       SELECT 1 FROM RORSTAT B
	    WHERE B.RORSTAT_PGRP_CODE LIKE 'GR%'
       AND B.RORSTAT_PIDM = A.RORSTAT_PIDM
       AND B.RORSTAT_AIDY_CODE = A.RORSTAT_AIDY_CODE
       AND EXISTS (
           SELECT 1
           FROM RPRAWRD
           WHERE RPRAWRD_FUND_CODE = 'YDPF22'
           AND RPRAWRD_PAID_AMT > 0
           AND RPRAWRD_AIDY_CODE = TO_NUMBER(:AIDY ) - 101
           AND RPRAWRD_PIDM = A.RORSTAT_PIDM
       )
   )
)
AND EXISTS (
   SELECT 1 FROM RBRAPBG
   WHERE RBRAPBG_PIDM = A.RORSTAT_PIDM
   AND RBRAPBG_AIDY_CODE = A.RORSTAT_AIDY_CODE
   AND RBRAPBG_PBGP_CODE = 'GR'
   AND RBRAPBG_RUN_NAME = 'ACTUAL'
)
AND NOT EXISTS (
   SELECT 1 FROM (
       SELECT RPRATRM_PIDM, COUNT(*) AS TERMS
       FROM RPRATRM
       WHERE RPRATRM_PIDM = RORSTAT_PIDM
       AND RPRATRM_FUND_CODE = 'YDPF22'
       AND RPRATRM_PAID_AMT > 0
       GROUP BY RPRATRM_PIDM
   ) WHERE TERMS >= ROBNYUD_VALUE_96
)