-- old seq 1
-- MISC. SEQ 1
SELECT 
   CASE     
WHEN A.SGBSTDN_LEVL_CODE = 'UG' and RBRAPBG_PBGP_CODE LIKE 'UG%' then 1440
    WHEN A.SGBSTDN_LEVL_CODE = 'GR' and RBRAPBG_PBGP_CODE LIKE 'GR%' then 2835
    WHEN A.SGBSTDN_LEVL_CODE = 'PL' and RBRAPBG_PBGP_CODE LIKE 'PR%' then 2835
   WHEN A.SGBSTDN_LEVL_CODE = 'PM' AND A.SGBSTDN_STYP_CODE = 'P' AND A.SGBSTDN_TERM_CODE_ADMIT = 
    '20'||SUBSTR(:aidy,3,2)||'15' THEN 3390 --M1 FEE
    WHEN A.SGBSTDN_LEVL_CODE = 'PM' AND ATTR.SGRSATT_ATTS_CODE = 'M1' THEN 3700 --M2 FEE
    WHEN A.SGBSTDN_LEVL_CODE = 'PM' AND ATTR.SGRSATT_ATTS_CODE = 'M2' THEN 4102 --M3 FEE
    WHEN A.SGBSTDN_LEVL_CODE = 'PM' AND ATTR.SGRSATT_ATTS_CODE = 'M3' THEN 4172 --M4 FEE
   END
      FROM SGBSTDN A, RBRAPBG,(SELECT SGRSATT_PIDM, SGRSATT_ATTS_CODE
                                FROM SGRSATT A
                                WHERE A.SGRSATT_ATTS_CODE in ('M1','M2','M3','M4')
                                AND A.SGRSATT_TERM_CODE_EFF = (SELECT MAX(M.SGRSATT_TERM_CODE_EFF)
                                                            FROM SGRSATT M
                                                            where M.SGRSATT_TERM_CODE_EFF = '20'||SUBSTR(:aidy,1,2)||'15'
                                                            AND  A.SGRSATT_PIDM =  M.SGRSATT_PIDM)) ATTR 
         WHERE A.SGBSTDN_TERM_CODE_EFF = 
               (SELECT MAX(B.SGBSTDN_TERM_CODE_EFF)
                  FROM SGBSTDN B
                 WHERE A.SGBSTDN_PIDM = B.SGBSTDN_PIDM
                   AND B.SGBSTDN_TERM_CODE_EFF <= :PERIOD
               )
AND ATTR.SGRSATT_PIDM(+) = A.SGBSTDN_PIDM 
AND RBRAPBG_PIDM = SGBSTDN_PIDM
AND RBRAPBG_PERIOD = :PERIOD
AND A.SGBSTDN_PIDM = :PIDM

-- old seq 2
--MISC DEFAULT
SELECT
CASE
    WHEN STDN.SGBSTDN_LEVL_CODE = 'UG' AND SUBSTR(RORENRL_TERM_CODE,5,2) IN ('10','20') then 1440
    WHEN STDN.SGBSTDN_LEVL_CODE = 'UG' AND SUBSTR(RORENRL_TERM_CODE,5,2) IN ('00') then 360
    WHEN STDN.SGBSTDN_LEVL_CODE = 'GR' then 2835
    WHEN STDN.SGBSTDN_LEVL_CODE = 'PL' then 2835
    WHEN STDN.SGBSTDN_LEVL_CODE = 'PM' THEN 3390
    WHEN ADAP.SARADAP_LEVL_CODE = 'UG' then 1440
    WHEN ADAP.SARADAP_LEVL_CODE = 'GR' then 2835
    WHEN ADAP.SARADAP_LEVL_CODE = 'PL' then 2835
    WHEN ADAP.SARADAP_LEVL_CODE = 'PM' THEN 3390
END 
FROM RBRAPBG, RORENRL, (SELECT SGBSTDN_PIDM, SGBSTDN_LEVL_CODE,SGBSTDN_COLL_CODE_1, SGBSTDN_STYP_CODE, SGBSTDN_TERM_CODE_ADMIT, SGBSTDN_MAJR_CODE_1, SGBSTDN_CAMP_CODE 
                  FROM SGBSTDN
                  WHERE SGBSTDN_TERM_CODE_EFF = (SELECT MAX (B.SGBSTDN_TERM_CODE_EFF) 
                                                FROM SGBSTDN B
                                               WHERE SGBSTDN_PIDM = SGBSTDN_PIDM
                                               AND B.SGBSTDN_TERM_CODE_EFF <= :PERIOD))STDN,
(SELECT SARADAP_PIDM, SARADAP_LEVL_CODE, SARADAP_COLL_CODE_1, SARADAP_TERM_CODE_ENTRY, SARADAP_STYP_CODE,SARADAP_MAJR_CODE_1, SARADAP_CAMP_CODE
                    FROM SARADAP
                    WHERE SARADAP_TERM_CODE_ENTRY = (SELECT MAX (B.SARADAP_TERM_CODE_ENTRY)
                                          FROM SARADAP B, ROBINST
                                          WHERE SARADAP_PIDM = B.SARADAP_PIDM
                                          AND ROBINST_AIDY_CODE = :AIDY
                                          AND B.SARADAP_TERM_CODE_ENTRY <= ROBINST_CURRENT_TERM_CODE))ADAP
WHERE STDN.SGBSTDN_PIDM(+) = RBRAPBG_PIDM
AND ADAP.SARADAP_PIDM(+) = RBRAPBG_PIDM
AND RBRAPBG_AIDY_CODE = :AIDY                       
AND RBRAPBG_PIDM    = :PIDM
and rorenrl_enrr_code = 'REPEAT'
and rorenrl_term_code = :period