-- should be like fees

-- PERIOD BASED BUDGETING - 9MIS RULES

-- UNDERGRAD NOT PS SEQUENCES ==================================================
-- sequence 100 - UG/GR/PL WITH SGBSTDN
SELECT RORALGS_AMT * 2
FROM SGBSTDN a, RORALGS
WHERE RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '9MIS'
AND RORALGS_KEY_5 = 'UG'
AND a.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN
    WHERE SGBSTDN_PIDM = a.SGBSTDN_PIDM
    AND SGBSTDN_TERM_CODE_EFF <= :PERIOD
)	
AND a.SGBSTDN_STST_CODE IN  ('AS','IL')
AND RORALGS_AIDY_CODE = :AIDY
AND a.SGBSTDN_PIDM = :PIDM
-- ;

-- sequence 110 - UG/GR/PL WITHOUT SGBSTDN
SELECT RORALGS_AMT * 2
FROM SARADAP a
CROSS JOIN RORALGS
INNER JOIN SARAPPD b 
    ON b.SARAPPD_PIDM = a.SARADAP_PIDM
    AND b.SARAPPD_APPL_NO = a.SARADAP_APPL_NO
    AND b.SARAPPD_TERM_CODE_ENTRY = a.SARADAP_TERM_CODE_ENTRY
INNER JOIN STVAPDC c 
    ON c.STVAPDC_CODE = b.SARAPPD_APDC_CODE
    AND c.STVAPDC_INST_ACC_IND = 'Y'
    AND c.STVAPDC_SIGNF_IND = 'Y'
WHERE RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '9MIS'
AND RORALGS_KEY_5 = 'UG'
-- sgbstdn term
AND a.SARADAP_TERM_CODE_ENTRY = (
    SELECT MAX(SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP, ROBINST
    WHERE SARADAP_PIDM = a.SARADAP_PIDM
    AND SARADAP_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
	AND SARADAP_TERM_CODE_ENTRY <= :PERIOD
    AND ROBINST_AIDY_CODE = :AIDY
)
--max application decision code sequence number
AND b.SARAPPD_SEQ_NO = (
    SELECT MAX(SARAPPD_SEQ_NO)
    FROM SARAPPD
    WHERE SARAPPD_PIDM = b.SARAPPD_PIDM
    AND SARAPPD_SEQ_NO < 99
    AND SARAPPD_TERM_CODE_ENTRY <= b.SARAPPD_TERM_CODE_ENTRY
)  
AND RORALGS_AIDY_CODE = :AIDY
AND a.SARADAP_PIDM = :PIDM
-- ;
