-- should be like fees

-- PERIOD BASED BUDGETING - 9MIS RULES

-- UNDERGRAD NOT PS SEQUENCES ==================================================
-- sequence 100 - UG/GR/PL WITH SGBSTDN
SELECT RORALGS_AMT
FROM SGBSTDN a, RORALGS
WHERE RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '9MIS'
AND CASE
    WHEN a.SGBSTDN_LEVL_CODE = 'UG' THEN 'UG'
    WHEN a.SGBSTDN_LEVL_CODE = 'GR' THEN 'GR'
    WHEN a.SGBSTDN_LEVL_CODE = 'PL' THEN 'PL'
END = RORALGS_KEY_5
-- sgbstdn term
AND a.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN
    WHERE SGBSTDN_PIDM = a.SGBSTDN_PIDM
    AND SGBSTDN_TERM_CODE_EFF <= :PERIOD
)	
AND a.SGBSTDN_STST_CODE IN  ('AS','IL')
AND RORALGS_AIDY_CODE = :AIDY
AND a.SGBSTDN_PIDM = :PIDM
-- ;

-- sequence 110 - UG/GR/PL WITHOUT SGBSTDN
SELECT RORALGS_AMT
FROM SARADAP a
CROSS JOIN RORALGS
INNER JOIN SARAPPD b 
    ON b.SARAPPD_PIDM = a.SARADAP_PIDM
    AND b.SARAPPD_APPL_NO = a.SARADAP_APPL_NO
    AND b.SARAPPD_TERM_CODE_ENTRY = a.SARADAP_TERM_CODE_ENTRY
INNER JOIN STVAPDC c 
    ON c.STVAPDC_CODE = b.SARAPPD_APDC_CODE
    AND c.STVAPDC_INST_ACC_IND = 'Y'
    AND c.STVAPDC_SIGNF_IND = 'Y'
WHERE RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '9MIS'
AND CASE
    WHEN a.SARADAP_LEVL_CODE = 'UG' THEN 'UG'
    WHEN a.SARADAP_LEVL_CODE = 'GR' THEN 'GR'
    WHEN a.SARADAP_LEVL_CODE = 'PL' THEN 'PL'
END = RORALGS_KEY_5
-- sgbstdn term
AND a.SARADAP_TERM_CODE_ENTRY = (
    SELECT MAX(SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP, ROBINST
    WHERE SARADAP_PIDM = a.SARADAP_PIDM
    AND SARADAP_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
	AND SARADAP_TERM_CODE_ENTRY <= :PERIOD
    AND ROBINST_AIDY_CODE = :AIDY
)
--max application decision code sequence number
AND b.SARAPPD_SEQ_NO = (
    SELECT MAX(SARAPPD_SEQ_NO)
    FROM SARAPPD
    WHERE SARAPPD_PIDM = b.SARAPPD_PIDM
    AND SARAPPD_APPL_NO = b.SARAPPD_APPL_NO
    AND SARAPPD_SEQ_NO < 99
    AND SARAPPD_TERM_CODE_ENTRY <= b.SARAPPD_TERM_CODE_ENTRY
)  
AND RORALGS_AIDY_CODE = :AIDY
AND a.SARADAP_PIDM = :PIDM
-- ;

-- sequence 500 - MED M1
-- M1 (LOOK FOR APPLICATION TO PM WITHIN THE AID YEAR)
SELECT RORALGS_AMT 
FROM SARADAP a
CROSS JOIN RORALGS
INNER JOIN SARAPPD b 
    ON b.SARAPPD_PIDM = a.SARADAP_PIDM
    AND b.SARAPPD_APPL_NO = a.SARADAP_APPL_NO
    AND b.SARAPPD_TERM_CODE_ENTRY = a.SARADAP_TERM_CODE_ENTRY
INNER JOIN STVAPDC c 
    ON c.STVAPDC_CODE = b.SARAPPD_APDC_CODE
    AND c.STVAPDC_INST_ACC_IND = 'Y'
    AND c.STVAPDC_SIGNF_IND = 'Y'
WHERE RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '9MIS'
AND CASE
	WHEN a.SARADAP_LEVL_CODE = 'PM' THEN 'PM'
END = RORALGS_KEY_5
AND RORALGS_KEY_11 = 'M1'
AND a.SARADAP_TERM_CODE_ENTRY = (
    SELECT MAX(SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP, ROBINST
    WHERE SARADAP_PIDM = a.SARADAP_PIDM
    AND SARADAP_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
	AND SARADAP_TERM_CODE_ENTRY <= :PERIOD
    AND ROBINST_AIDY_CODE = :AIDY
)
--max application decision code sequence number
AND b.SARAPPD_SEQ_NO = (
    SELECT MAX(SARAPPD_SEQ_NO)
    FROM SARAPPD
    WHERE SARAPPD_PIDM = b.SARAPPD_PIDM
    AND SARAPPD_APPL_NO = b.SARAPPD_APPL_NO
    AND SARAPPD_SEQ_NO < 99
    AND SARAPPD_TERM_CODE_ENTRY <= b.SARAPPD_TERM_CODE_ENTRY
)  
AND RORALGS_AIDY_CODE = :AIDY
AND a.SARADAP_PIDM = :PIDM
-- ;

-- sequence 510 - MED M2-4
WITH med_cohort AS (
    SELECT 
        ROBINST_AIDY_END_YEAR || 'MD' as "M4",
        ROBINST_AIDY_END_YEAR + 1 || 'MD' as "M3",
        ROBINST_AIDY_END_YEAR + 2 || 'MD' as "M2"
    FROM ROBINST
    WHERE ROBINST_AIDY_CODE = :AIDY
)
SELECT RORALGS_AMT
FROM SGBSTDN a
CROSS JOIN RORALGS
CROSS JOIN med_cohort -- table derived from with statement above
INNER JOIN ( -- find cohort codes matching those defined above in med_cohort
    SELECT SGRCHRT_PIDM, SGRCHRT_TERM_CODE_EFF, SGRCHRT_CHRT_CODE
    FROM SGRCHRT
    WHERE SGRCHRT_CHRT_CODE in (
        SELECT M4 FROM med_cohort UNION 
        SELECT M3 FROM med_cohort UNION 
        SELECT M2 FROM med_cohort
    )
) b ON b.SGRCHRT_PIDM = a.SGBSTDN_PIDM
    AND b.SGRCHRT_TERM_CODE_EFF = (
        SELECT MAX(z.SGRCHRT_TERM_CODE_EFF)
        FROM SGRCHRT z
        WHERE z.SGRCHRT_CHRT_CODE in (
            SELECT M4 FROM med_cohort UNION 
            SELECT M3 FROM med_cohort UNION 
            SELECT M2 FROM med_cohort
        )
    )
INNER JOIN RORSTAT 
    ON RORSTAT_PIDM = a.SGBSTDN_PIDM 
    AND RORSTAT_AIDY_CODE = :AIDY
WHERE RORALGS_KEY_1 = 'PBDG' 
AND RORALGS_KEY_4 = '9MIS'
AND a.SGBSTDN_STST_CODE IN  ('AS','IL')
AND a.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN
    WHERE SGBSTDN_PIDM = a.SGBSTDN_PIDM
    AND SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND CASE
    WHEN a.SGBSTDN_LEVL_CODE = 'PM' THEN 'PM'
END = RORALGS_KEY_5
AND CASE
    WHEN b.SGRCHRT_CHRT_CODE = (SELECT M4 FROM med_cohort) THEN 'M4'
    WHEN b.SGRCHRT_CHRT_CODE = (SELECT M3 FROM med_cohort) THEN 'M3'
    WHEN b.SGRCHRT_CHRT_CODE = (SELECT M2 FROM med_cohort) THEN 'M2'
END = RORALGS_KEY_11
AND a.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
-- ;