-- SLUPRM RORRULE 12/18/2025 JD

-- First time freshmen 202710 - 202720
-- GPA ROBNYUD_VALUE_29 >=3.00

-- RCRAPP2_MODEL_CDE = 'D'
-- Parent AGI <=60000
-- RCVEDEA_FTI_PAR_AGI + RCVEDEA_FTI_PSP_AGI <60000.  
-- OR RCRAPP1_PAR_US_INC+RCRAPP1.RCVEDEA_PSP_US_INC
-- and Parent Total Assets <= 50000
-- RCRAPP1_PAR_CASH_AMT + .RCRAPP4_PAR_INV_NET_WORTH + RCRAPP4_PAR_BUS_NET_WORTH

-- RCRAPP2_MODEL_CDE = 'I'
-- Parent AGI <=60000
-- RCVEDEA_FTI_AGI + RCVEDEA_FTI_SPS_AGI 
-- OR RCRAPP1_US_INC + RCVEDEA_SPS_US_INC
-- and Parent Total Assets <= 50000
-- RCRAPP1_CASH_AMT + RCRAPP4_INV_NET_WORTH + RCRAPP4_BUS_NET_WORTH

WITH FAFSA AS (
    SELECT 
        a.RCRAPP1_PIDM AS PIDM,
        a.RCRAPP1_AIDY_CODE AS AIDY, 
        b.RCRAPP2_MODEL_CDE AS MODEL_CDE,
        NVL(e.RCVEDEA_FTI_AGI, 0) AS AGI,
        NVL(e.RCVEDEA_FTI_PAR_AGI, 0) AS PAR_AGI,
        NVL(e.RCVEDEA_FTI_PSP_AGI, 0) AS PSP_AGI,
        NVL(e.RCVEDEA_FTI_SPS_AGI, 0) AS SPS_AGI,
        NVL(e.RCVEDEA_SPS_US_INC, 0) AS SPS_INC,
        NVL(e.RCVEDEA_PSP_US_INC, 0) AS PSP_INC,
        NVL(a.RCRAPP1_PAR_US_INC, 0) AS PAR_INC,
        NVL(a.RCRAPP1_PAR_CASH_AMT, 0) AS PAR_CASH, 
        NVL(a.RCRAPP1_US_INC, 0) AS INC,
        NVL(a.RCRAPP1_CASH_AMT, 0) AS CASH,
        NVL(d.RCRAPP4_INV_NET_WORTH, 0) AS INV_NET,
        NVL(d.RCRAPP4_PAR_INV_NET_WORTH, 0) AS PAR_INV_NET,
        NVL(d.RCRAPP4_BUS_NET_WORTH, 0) AS BUS_NET,
        NVL(d.RCRAPP4_PAR_BUS_NET_WORTH, 0) AS PAR_BUS_NET
    FROM RCRAPP1 a
    INNER JOIN RCRAPP2 b ON b.RCRAPP2_PIDM = a.RCRAPP1_PIDM 
        AND b.RCRAPP2_INFC_CODE = a.RCRAPP1_INFC_CODE
        AND b.RCRAPP2_AIDY_CODE = a.RCRAPP1_AIDY_CODE
        AND b.RCRAPP2_SEQ_NO = a.RCRAPP1_SEQ_NO
    INNER JOIN RCRAPP3 c ON c.RCRAPP3_PIDM = a.RCRAPP1_PIDM 
        AND c.RCRAPP3_INFC_CODE = a.RCRAPP1_INFC_CODE
        AND c.RCRAPP3_AIDY_CODE = a.RCRAPP1_AIDY_CODE
        AND c.RCRAPP3_SEQ_NO = a.RCRAPP1_SEQ_NO    
    INNER JOIN RCRAPP4 d ON d.RCRAPP4_PIDM = a.RCRAPP1_PIDM 
        AND d.RCRAPP4_INFC_CODE = a.RCRAPP1_INFC_CODE
        AND d.RCRAPP4_AIDY_CODE = a.RCRAPP1_AIDY_CODE
        AND d.RCRAPP4_SEQ_NO = a.RCRAPP1_SEQ_NO
    INNER JOIN RCVEDEA e ON e.RCVEDEA_PIDM = a.RCRAPP1_PIDM 
        AND e.RCVEDEA_INFC_CODE = a.RCRAPP1_INFC_CODE
        AND e.RCVEDEA_AIDY_CODE = a.RCRAPP1_AIDY_CODE
        AND e.RCVEDEA_SEQ_NO = a.RCRAPP1_SEQ_NO
    WHERE a.RCRAPP1_CURR_REC_IND = 'Y'
    AND a.RCRAPP1_INFC_CODE = 'EDE'
    AND a.RCRAPP1_DEGREE_BY_JULY = 2
    AND c.RCRAPP3_OFFL_UNOFFL_IND = 1
)
SELECT DISTINCT a.RORSTAT_PIDM
FROM RORSTAT a
INNER JOIN ROBINST r ON r.ROBINST_AIDY_CODE = a.RORSTAT_AIDY_CODE
INNER JOIN RORPRST b ON b.RORPRST_PIDM = a.RORSTAT_PIDM
INNER JOIN ROBNYUD c ON c.ROBNYUD_PIDM = a.RORSTAT_PIDM
    AND c.ROBNYUD_VALUE_29 >= 3.0
INNER JOIN SARADAP d ON d.SARADAP_PIDM = a.RORSTAT_PIDM
    AND d.SARADAP_STYP_CODE = 'F'
    AND d.SARADAP_TERM_CODE_ENTRY = (
        SELECT MAX(z.SARADAP_TERM_CODE_ENTRY)
        FROM SARADAP z
        WHERE z.SARADAP_PIDM = d.SARADAP_PIDM
        AND z.SARADAP_TERM_CODE_ENTRY BETWEEN (r.ROBINST_AIDY_END_YEAR || '00') 
            AND (r.ROBINST_AIDY_END_YEAR || '20')
        )
INNER JOIN FAFSA f ON f.PIDM = a.RORSTAT_PIDM AND f.AIDY = a.RORSTAT_AIDY_CODE
WHERE CASE -- AGI/income < 60,000
    WHEN f.MODEL_CDE = 'D' 
        THEN CASE 
            WHEN (f.PAR_AGI + f.PSP_AGI) = 0 THEN (f.PAR_INC + f.PSP_INC)
            ELSE (f.PAR_AGI + f.PSP_AGI)
        END
    WHEN f.MODEL_CDE = 'I'
        THEN CASE
            WHEN (f.AGI + f.SPS_AGI) = 0 THEN (f.INC + f.SPS_INC)
            ELSE (f.AGI + f.SPS_AGI)
        END
END <= 60000
AND CASE -- Cash/investment/assets < 50,000
    WHEN f.MODEL_CDE = 'D' 
        THEN (f.PAR_CASH + f.PAR_INV_NET + f.PAR_BUS_NET)
    WHEN f.MODEL_CDE = 'I'
        THEN (f.CASH + f.INV_NET + f.BUS_NET)
END <= 50000
AND a.RORSTAT_AIDY_CODE = :AIDY
AND a.RORSTAT_PIDM = :PIDM
-- ;