SELECT A.RORSTAT_PIDM
FROM RORSTAT A
INNER JOIN ROBINST R ON R.ROBINST_AIDY_CODE = A.RORSTAT_AIDY_CODE
WHERE A.RORSTAT_AIDY_CODE = '2627'
AND (
    EXISTS (
        SELECT 1
        FROM SGBSTDN B
        WHERE B.SGBSTDN_PIDM = A.RORSTAT_PIDM
        AND B.SGBSTDN_PROGRAM_1 = 'ABSN'
        AND B.SGBSTDN_STST_CODE IN ('AS', 'IL', 'P1')
        AND B.SGBSTDN_TERM_CODE_EFF = (
            SELECT MAX(Z.SGBSTDN_TERM_CODE_EFF) FROM SGBSTDN Z
            WHERE Z.SGBSTDN_PIDM = B.SGBSTDN_PIDM
            AND Z.SGBSTDN_TERM_CODE_EFF <= R.ROBINST_AIDY_END_YEAR || '20'
        )
    )
)
;

select * from sgbstdn where sgbstdn_program_1 = 'ABSN';