-- NEW MED1 PACKAGING GROUP
-- 90
SELECT RORSTAT_PIDM
FROM RORSTAT
JOIN ROBINST on ROBINST_AIDY_CODE = RORSTAT_AIDY_CODE and ROBINST_STATUS_IND = 'A'
WHERE RORSTAT_AIDY_CODE = :AIDY
AND RORSTAT_PIDM = :PIDM
AND EXISTS (
    SELECT 1
    FROM SARADAP C
    INNER JOIN SARAPPD D 
        ON D.SARAPPD_PIDM = C.SARADAP_PIDM
        AND D.SARAPPD_APPL_NO = C.SARADAP_APPL_NO
        AND D.SARAPPD_TERM_CODE_ENTRY = C.SARADAP_TERM_CODE_ENTRY
    INNER JOIN STVAPDC E
        ON E.STVAPDC_CODE = D.SARAPPD_APDC_CODE
        AND E.STVAPDC_INST_ACC_IND = 'Y'
        AND E.STVAPDC_SIGNF_IND = 'Y'
    WHERE C.SARADAP_PIDM = RORSTAT_PIDM
    AND C.SARADAP_LEVL_CODE = 'PM'
    AND C.SARADAP_TERM_CODE_ENTRY = (
        SELECT MAX(Z.SARADAP_TERM_CODE_ENTRY) FROM SARADAP Z
        WHERE Z.SARADAP_PIDM = C.SARADAP_PIDM
        AND Z.SARADAP_TERM_CODE_ENTRY BETWEEN (ROBINST_AIDY_END_YEAR || '00') AND (ROBINST_AIDY_END_YEAR || '20')
        AND Z.SARADAP_APPL_NO = C.SARADAP_APPL_NO
    )
    AND D.SARAPPD_SEQ_NO = (
        SELECT MAX(Z.SARAPPD_SEQ_NO) FROM SARAPPD Z
        WHERE Z.SARAPPD_PIDM = D.SARAPPD_PIDM
        AND Z.SARAPPD_TERM_CODE_ENTRY = D.SARAPPD_TERM_CODE_ENTRY
        AND Z.SARAPPD_APPL_NO = D.SARAPPD_APPL_NO
    )
)
;

-- OLD QUERY FROM BANNER 06/17/2026
-- 152 rows
SELECT RORSTAT_PIDM
  FROM RORSTAT, ROBINST
 WHERE ROBINST_STATUS_IND = 'A'
   AND ROBINST_AIDY_CODE = RORSTAT_AIDY_CODE
   AND (EXISTS
(SELECT 'X'
  FROM SARAPPD A, STVAPDC
 WHERE A.SARAPPD_PIDM = RORSTAT_PIDM
   AND A.SARAPPD_APDC_CODE = STVAPDC_CODE
   AND STVAPDC_INST_ACC_IND = 'Y'
   AND STVAPDC_SIGNF_IND = 'Y'
   AND A.SARAPPD_TERM_CODE_ENTRY||LPAD(A.SARAPPD_APPL_NO,2,0)||LPAD(A.SARAPPD_SEQ_NO,2,0) = 
    (SELECT MAX(B.SARAPPD_TERM_CODE_ENTRY||LPAD(B.SARAPPD_APPL_NO,2,0)||LPAD(B.SARAPPD_SEQ_NO,2,0)) 
       FROM SARAPPD B
      WHERE B.SARAPPD_PIDM = A.SARAPPD_PIDM
	    AND B.SARAPPD_TERM_CODE_ENTRY IN
                (SELECT SORXREF_EDI_QLFR
                    FROM SORXREF
                WHERE SORXREF_EDI_VALUE = 'ALL_TERMS'
                  AND SORXREF_XLBL_CODE = 'ZSFS_VAR'
                  AND SORXREF_BANNER_VALUE = RORSTAT_AIDY_CODE)
            AND B.SARAPPD_PIDM=RORSTAT_PIDM)
   AND EXISTS 
    (SELECT 'X'
	   FROM SARADAP
      WHERE SARADAP_LEVL_CODE = 'PM'
	    AND SARADAP_PIDM = A.SARAPPD_PIDM
		AND SARADAP_TERM_CODE_ENTRY = A.SARAPPD_TERM_CODE_ENTRY
		AND SARADAP_APPL_NO = A.SARAPPD_APPL_NO)))
AND RORSTAT_AIDY_CODE            = :AIDY                                               
-- AND RORSTAT_PIDM    =:PIDM
;
