SELECT RORSTAT_PIDM
FROM RORSTAT
JOIN ROBINST on ROBINST_AIDY_CODE = RORSTAT_AIDY_CODE and ROBINST_STATUS_IND = 'A'
JOIN ROBNYUD on ROBNYUD_PIDM = RORSTAT_PIDM
WHERE RORSTAT_AIDY_CODE = :AIDY
AND RORSTAT_PIDM = :PIDM
AND ROBNYUD_VALUE_197 = 'Y'
AND ROBNYUD_VALUE_198 = 'PM'
AND EXISTS (
    SELECT 1
    FROM SARADAP C
    JOIN SATURN.STVMAJR M on M.STVMAJR_CODE = C.SARADAP_MAJR_CODE_1
        and substr(M.STVMAJR_CIPC_CODE, 0, 4) <> substr(ROBNYUD_VALUE_193, 0, 4)
    INNER JOIN SARAPPD D 
        ON D.SARAPPD_PIDM = C.SARADAP_PIDM
        AND D.SARAPPD_APPL_NO = C.SARADAP_APPL_NO
        AND D.SARAPPD_TERM_CODE_ENTRY = C.SARADAP_TERM_CODE_ENTRY
    INNER JOIN STVAPDC E
        ON E.STVAPDC_CODE = D.SARAPPD_APDC_CODE
        AND E.STVAPDC_INST_ACC_IND = 'Y'
        AND E.STVAPDC_SIGNF_IND = 'Y'
    WHERE C.SARADAP_PIDM = RORSTAT_PIDM
    AND C.SARADAP_LEVL_CODE = 'PM'
    AND C.SARADAP_TERM_CODE_ENTRY = (
        SELECT MAX(Z.SARADAP_TERM_CODE_ENTRY) FROM SARADAP Z
        WHERE Z.SARADAP_PIDM = C.SARADAP_PIDM
        AND Z.SARADAP_TERM_CODE_ENTRY BETWEEN (ROBINST_AIDY_END_YEAR || '00') AND (ROBINST_AIDY_END_YEAR || '20')
        AND Z.SARADAP_APPL_NO = C.SARADAP_APPL_NO
    )
    AND D.SARAPPD_SEQ_NO = (
        SELECT MAX(Z.SARAPPD_SEQ_NO) FROM SARAPPD Z
        WHERE Z.SARAPPD_PIDM = D.SARAPPD_PIDM
        AND Z.SARAPPD_TERM_CODE_ENTRY = D.SARAPPD_TERM_CODE_ENTRY
        AND Z.SARAPPD_APPL_NO = D.SARAPPD_APPL_NO
    )
)
;