SELECT RORSTAT_PIDM
FROM RORSTAT
JOIN ROBINST on ROBINST_AIDY_CODE = RORSTAT_AIDY_CODE and ROBINST_STATUS_IND = 'A'
WHERE RORSTAT_AIDY_CODE = :AIDY
-- AND RORSTAT_PIDM = :PIDM
AND EXISTS (
    SELECT 1
    FROM SGBSTDN E 
    WHERE E.SGBSTDN_PIDM = RORSTAT_PIDM 
    AND E.SGBSTDN_LEVL_CODE = 'PM' 
    AND E.SGBSTDN_STST_CODE IN ('AS','P1')
    AND E.SGBSTDN_TERM_CODE_EFF = (
        SELECT MAX(F.SGBSTDN_TERM_CODE_EFF) 
        FROM SGBSTDN F 
        WHERE F.SGBSTDN_TERM_CODE_EFF <= ROBINST_AIDY_END_YEAR || '10'
        AND F.SGBSTDN_PIDM = E.SGBSTDN_PIDM
    )
)
AND EXISTS (
    SELECT 1
    FROM SGRSATT 
    WHERE SGRSATT_PIDM = RORSTAT_PIDM
    AND SGRSATT_TERM_CODE_EFF = ROBINST_AIDY_START_YEAR || '10'
    AND SGRSATT_ATTS_CODE IN ('M3')
)
   
--    
;

-- OLD QUERY FROM BANNER 06/17/2026
-- 137 rows
SELECT RORSTAT_PIDM
  FROM RORSTAT
WHERE (EXISTS 
(SELECT 'X' 
   FROM SGBSTDN E 
  WHERE E.SGBSTDN_PIDM = RORSTAT_PIDM 
    AND E.SGBSTDN_LEVL_CODE = 'PM' 
    AND E.SGBSTDN_STST_CODE IN ('AS','P1')
    AND E.SGBSTDN_TERM_CODE_EFF = 
     (SELECT MAX(F.SGBSTDN_TERM_CODE_EFF) 
        FROM SGBSTDN F 
       WHERE F.SGBSTDN_TERM_CODE_EFF <= '20' || SUBSTR( :AIDY                  ,3,2) || '10'
         AND F.SGBSTDN_PIDM = E.SGBSTDN_PIDM))) 
AND (EXISTS 
 (SELECT 'X' 
    FROM SGRSATT 
           WHERE (SGRSATT_TERM_CODE_EFF = '20' || SUBSTR( :AIDY              ,0,2) || '10' 
              AND SGRSATT_ATTS_CODE IN ('M3'))
              AND SGRSATT_PIDM = RORSTAT_PIDM)) 
   AND RORSTAT_AIDY_CODE            = :AIDY                                   
--    AND RORSTAT_PIDM    =:PIDM
;

SELECT 
    ROBINST_AIDY_START_YEAR || '10' AS start_term,
    ROBINST_AIDY_END_YEAR || '10'   AS end_term,
    '20' || SUBSTR(:AIDY, 1, 2) || '10' AS orig_start_term,
    '20' || SUBSTR(:AIDY, 3, 2) || '10' AS orig_end_term
FROM ROBINST
WHERE ROBINST_AIDY_CODE = :AIDY
AND ROBINST_STATUS_IND = 'A';