-- LIVING EXPENSES - WRITTEN BY BUDDY
--Living expenses for off cmapus students
--less than half time time housing and food
SELECT case when  
nvl(rokmisc.f_calc_stud_bill_hrs(:PERIOD,X.SGBSTDN_PIDM,'N'),0) < RORCRHR_HALF_TIME_CR_HRS and
nvl(rokmisc.f_calc_stud_bill_hrs(:PERIOD,X.SGBSTDN_PIDM,'N'),0) >0  then 0
            end as calc_amt

FROM SGBSTDN X, RORCRHR, RORALGS, RORPRST
WHERE RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '6LIV' -- budget component 	
AND CASE -- OFF CAMPUS HOUSING FLAG IN RORPRST
    WHEN RORPRST_XHS = '1' THEN '1'   --off campus 
	WHEN (RORPRST_XHS IN ('3','4')) THEN '3'  --with family/relative
END = RORALGS_KEY_3

AND X.SGBSTDN_TERM_CODE_EFF = (SELECT MAX (Y.SGBSTDN_TERM_CODE_EFF)
            FROM SGBSTDN Y
                WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
                    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD)

AND X.SGBSTDN_PIDM = RORPRST_PIDM
AND RORPRST_PERIOD = :PERIOD

AND RORCRHR_AIDY_CODE = :AIDY
AND RORCRHR_LEVL_CODE = X.SGBSTDN_LEVL_CODE
AND RORCRHR_PERIOD = :PERIOD

AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
--END

--UNDERGRAD TRANSFER PS,PL,NR041,TEAC03 ENROLLED WITH SGASTDN AND CHANGED SGASTDN RECORD AFTER FIRST TERM
SELECT CASE
    WHEN NVL(ROKMISC.F_CALC_STUD_CREDIT_HRS(:PERIOD, Y.SGBSTDN_PIDM, 'N'), 0) >= RORCRHR_HALF_TIME_CR_HRS
        THEN (RORALGS_AMT + 300)
    END as calc_amt
FROM SGBSTDN X, SGBSTDN Y, RORCRHR, RORALGS, ROBNYUD
WHERE RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '6LIV'
AND CASE -- transfer student type
    WHEN (X.SGBSTDN_STYP_CODE IN ('1','T')) THEN 'T' 
END = RORALGS_KEY_2
AND CASE -- OFF CAMPUS HOUSING FLAG IN ROBNYUD
    WHEN ROBNYUD_VALUE_120 IS NULL THEN '1'  --off campus 
	WHEN (ROBNYUD_VALUE_120 NOT IN ('C','D')) THEN '1'  --off campus 
	WHEN ROBNYUD_VALUE_120 = 'D' THEN '3'  --with family/relative
END = RORALGS_KEY_3	
AND CASE 
    WHEN Y.SGBSTDN_LEVL_CODE = 'UG' THEN 'UG'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN Y.SGBSTDN_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
		
-- max sgbstdn term <= passed period
AND Y.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y1.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y1
    WHERE Y1.SGBSTDN_PIDM = Y.SGBSTDN_PIDM
    AND Y1.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
	
-- has transfer sgastdn record in the aid year	
AND X.SGBSTDN_TERM_CODE_EFF BETWEEN 
    TRIM(TO_CHAR ('20'||SUBSTR(:AIDY, 3,2) || '00')) 
    AND TRIM(TO_CHAR ('20'||SUBSTR(:AIDY, 3,2)+1 || '00'))	
AND X.SGBSTDN_STYP_CODE IN ('1','T') 
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1') 

AND Y.SGBSTDN_TERM_CODE_EFF > X.SGBSTDN_TERM_CODE_EFF
AND Y.SGBSTDN_LEVL_CODE = 'UG'
AND Y.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND RORCRHR_AIDY_CODE = :AIDY
AND RORCRHR_LEVL_CODE = Y.SGBSTDN_LEVL_CODE
AND RORCRHR_PERIOD = :PERIOD
AND (
    X.SGBSTDN_COLL_CODE_1 IN ('PS','PL') OR 
    X.SGBSTDN_PROGRAM_1  IN ('NR041','NR02','TEAC03')
)            
AND X.SGBSTDN_PIDM = ROBNYUD_PIDM 
AND X.SGBSTDN_PIDM = Y.SGBSTDN_PIDM
AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
-- END

--UNDERGRAD TRANSFER NOT PS,PL,NR041,TEAC03 ENROLLED WITH SGASTDN AND CHANGED SGASTDN RECORD AFTER FIRST TERM
SELECT CASE
    WHEN NVL(ROKMISC.F_CALC_STUD_CREDIT_HRS(:PERIOD, Y.SGBSTDN_PIDM, 'N'), 0) >= RORCRHR_HALF_TIME_CR_HRS
        THEN RORALGS_AMT
    END as calc_amt
FROM SGBSTDN X, SGBSTDN Y, RORCRHR, RORALGS, ROBNYUD
WHERE RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '6LIV'
AND CASE -- transfer student type
    WHEN (X.SGBSTDN_STYP_CODE IN ('1','T')) THEN 'T' 
END = RORALGS_KEY_2
AND CASE -- OFF CAMPUS HOUSING FLAG IN ROBNYUD
    WHEN ROBNYUD_VALUE_120 IS NULL THEN '1'  --off campus 
	WHEN (ROBNYUD_VALUE_120 NOT IN ('C','D')) THEN '1'  --off campus 
	WHEN ROBNYUD_VALUE_120 = 'D' THEN '3'  --with family/relative
END = RORALGS_KEY_3	
AND CASE
    WHEN Y.SGBSTDN_LEVL_CODE = 'UG' THEN 'UG'
END = RORALGS_KEY_5	
AND CASE
    WHEN Y.SGBSTDN_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
AND Y.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y1.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y1
    WHERE Y1.SGBSTDN_PIDM = Y.SGBSTDN_PIDM
    AND Y1.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
	
-- has transfer sgastdn record in the aid year	
AND X.SGBSTDN_TERM_CODE_EFF BETWEEN 
    TRIM(TO_CHAR ('20'||SUBSTR(:AIDY, 3,2) || '00')) AND 
    TRIM(TO_CHAR ('20'||SUBSTR(:AIDY, 3,2)+1 || '00'))	
AND X.SGBSTDN_STYP_CODE IN ('1','T') 
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1') 
AND Y.SGBSTDN_TERM_CODE_EFF > X.SGBSTDN_TERM_CODE_EFF
AND Y.SGBSTDN_LEVL_CODE = 'UG'
AND Y.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND RORCRHR_AIDY_CODE = :AIDY
AND RORCRHR_LEVL_CODE = Y.SGBSTDN_LEVL_CODE
AND RORCRHR_PERIOD = :PERIOD
AND X.SGBSTDN_PIDM = ROBNYUD_PIDM 
AND X.SGBSTDN_PIDM = Y.SGBSTDN_PIDM
AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
-- END
--UNDERGRAD TRANSFER PS,PL,NR041,TEAC03 ENROLLED WITH SGASTDN
SELECT CASE
    WHEN NVL(ROKMISC.F_CALC_STUD_CREDIT_HRS(:PERIOD, Y.SGBSTDN_PIDM, 'N'), 0) >= RORCRHR_HALF_TIME_CR_HRS
        THEN (RORALGS_AMT + 300)
    END as calc_amt
FROM SGBSTDN X, RORCRHR, RORALGS, ROBNYUD
WHERE RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '6LIV'
AND CASE -- transfer student type
    WHEN (X.SGBSTDN_STYP_CODE IN ('1','T')) THEN 'T'                   
END = RORALGS_KEY_2 

AND CASE -- OFF CAMPUS HOUSING FLAG IN ROBNYUD
    WHEN ROBNYUD_VALUE_120 IS NULL THEN '1'  --off campus 
	WHEN (ROBNYUD_VALUE_120 NOT IN ('C','D')) THEN '1'  --off campus 
	WHEN ROBNYUD_VALUE_120 = 'D' THEN '3'  --with family/relative
END = RORALGS_KEY_3
AND CASE -- level code
    WHEN X.SGBSTDN_LEVL_CODE = 'UG' THEN 'UG'
END = RORALGS_KEY_5	
AND CASE -- campus code
    WHEN X.SGBSTDN_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)	
AND RORCRHR_AIDY_CODE = :AIDY
AND RORCRHR_LEVL_CODE = X.SGBSTDN_LEVL_CODE
AND RORCRHR_PERIOD = :PERIOD
AND (
    X.SGBSTDN_COLL_CODE_1 IN ('PS','PL')                      
    OR X.SGBSTDN_PROGRAM_1  IN ('NR041','NR02','TEAC03')
)   
AND X.SGBSTDN_PIDM = ROBNYUD_PIDM 
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
-- END

--UNDERGRAD TRANSFER NOT PS,PL,NR041,TEAC03 ENROLLED WITH SGASTDN
SELECT CASE
    WHEN NVL(ROKMISC.F_CALC_STUD_CREDIT_HRS(:PERIOD, X.SGBSTDN_PIDM, 'N'), 0) >= RORCRHR_HALF_TIME_CR_HRS
        THEN RORALGS_AMT
    END as calc_amt
FROM SGBSTDN X, RORCRHR, RORALGS, ROBNYUD
WHERE RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '6LIV'
AND CASE -- transfer student type
    WHEN (X.SGBSTDN_STYP_CODE IN ('1','T')) THEN 'T'                   
END = RORALGS_KEY_2 
AND CASE -- OFF CAMPUS HOUSING FLAG IN ROBNYUD
    WHEN ROBNYUD_VALUE_120 IS NULL THEN '1'  --off campus 
	WHEN (ROBNYUD_VALUE_120 NOT IN ('C','D')) THEN '1'  --off campus 
	WHEN ROBNYUD_VALUE_120 = 'D' THEN '3'  --with family/relative
END = RORALGS_KEY_3
AND CASE -- level code
    WHEN X.SGBSTDN_LEVL_CODE = 'UG' THEN 'UG'
END = RORALGS_KEY_5	
AND CASE -- campus code
    WHEN X.SGBSTDN_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)	
AND RORCRHR_AIDY_CODE = :AIDY
AND RORCRHR_LEVL_CODE = X.SGBSTDN_LEVL_CODE
AND RORCRHR_PERIOD = :PERIOD
AND X.SGBSTDN_PIDM = ROBNYUD_PIDM 
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
-- END

--UNDERGRAD TRANSFER PS,PL,NR041,TEAC03 NOT ENROLLED WITH SGASTDN
SELECT (RORALGS_AMT + 300)
FROM SGBSTDN X, RORALGS, ROBNYUD
WHERE RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '6LIV'
AND CASE -- freshmen student type
    WHEN (X.SGBSTDN_STYP_CODE IN ('1','T')) THEN 'T'
END = RORALGS_KEY_2

AND CASE -- OFF CAMPUS HOUSING FLAG IN ROBNYUD
    WHEN ROBNYUD_VALUE_120 IS NULL THEN '1'  --off campus 
	WHEN (ROBNYUD_VALUE_120 NOT IN ('C','D')) THEN '1'  --off campus 
	WHEN ROBNYUD_VALUE_120 = 'D' THEN '3'  --with family/relative
END = RORALGS_KEY_3
AND CASE -- level code
    WHEN X.SGBSTDN_LEVL_CODE = 'UG' THEN 'UG'
END = RORALGS_KEY_5
AND CASE -- campus code
    WHEN X.SGBSTDN_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6		
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)	
AND (
    X.SGBSTDN_COLL_CODE_1 IN ('PS','PL')                      
    OR X.SGBSTDN_PROGRAM_1  IN ('NR041','NR02','TEAC03')
)	
AND X.SGBSTDN_PIDM = ROBNYUD_PIDM 
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
-- END

--UNDERGRAD TRANSFER NOT PS,PL,NR041,TEAC03 NOT ENROLLED WITH SGASTDN
SELECT RORALGS_AMT
FROM SGBSTDN X, RORALGS, ROBNYUD
WHERE RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '6LIV'
AND CASE -- freshmen student type
    WHEN (X.SGBSTDN_STYP_CODE IN ('1','T')) THEN 'T'
END = RORALGS_KEY_2 
AND CASE -- OFF CAMPUS HOUSING FLAG IN ROBNYUD
    WHEN ROBNYUD_VALUE_120 IS NULL THEN '1'  --off campus 
	WHEN (ROBNYUD_VALUE_120 NOT IN ('C','D')) THEN '1'  --off campus 
	WHEN ROBNYUD_VALUE_120 = 'D' THEN '3'  --with family/relative
END = RORALGS_KEY_3
AND CASE -- level code
    WHEN X.SGBSTDN_LEVL_CODE = 'UG' THEN 'UG'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SGBSTDN_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6		
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)	
AND X.SGBSTDN_PIDM = ROBNYUD_PIDM 
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
-- END

--UNDERGRAD TRANSFER PS,PL,NR041,TEAC03 NOT ENROLLED NO SGASTDN
SELECT RORALGS_AMT
FROM SARADAP X, SARAPPD X, RORALGS, STVAPDC, ROBNYUD
WHERE RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '6LIV'
AND CASE -- freshmen student type
    WHEN (X.SARADAP_STYP_CODE IN ('1','T')) THEN 'T'
END = RORALGS_KEY_2 
AND CASE -- OFF CAMPUS HOUSING FLAG IN ROBNYUD
    WHEN ROBNYUD_VALUE_120 IS NULL THEN '1'  --off campus 
	WHEN (ROBNYUD_VALUE_120 NOT IN ('C','D')) THEN '1'  --off campus 
	WHEN ROBNYUD_VALUE_120 = 'D' THEN '3'  --with family/relative
END = RORALGS_KEY_3
AND CASE -- level code
    WHEN X.SARADAP_LEVL_CODE = 'UG' THEN 'UG'
END = RORALGS_KEY_5	
AND CASE -- campus code
    WHEN X.SARADAP_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6		
AND X.SARADAP_TERM_CODE_ENTRY = (
    SELECT MAX(Y.SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP Y, ROBINST
    WHERE Y.SARADAP_PIDM = X.SARADAP_PIDM
	AND Y.SARADAP_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
    AND Y.SARADAP_TERM_CODE_ENTRY <= :PERIOD
	AND ROBINST_AIDY_CODE = :AIDY
)
AND X.SARAPPD_SEQ_NO = (
    SELECT MAX (X.SARAPPD_SEQ_NO)
    FROM SARAPPD Y, ROBINST
    WHERE     Y.SARAPPD_PIDM = X.SARAPPD_PIDM
    AND Y.SARAPPD_SEQ_NO < 99
    AND Y.SARAPPD_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
    AND Y.SARAPPD_TERM_CODE_ENTRY <= :PERIOD
    AND ROBINST_AIDY_CODE = :AIDY           
    AND X.SARADAP_APPL_NO = Y.SARAPPD_APPL_NO
)       
AND STVAPDC_INST_ACC_IND = 'Y'
AND STVAPDC_SIGNF_IND = 'Y' 
AND (
    X.SARADAP_COLL_CODE_1 IN ('PS','PL')                      
    OR X.SARADAP_PROGRAM_1  IN ('NR041','NR02','TEAC03')
)   
AND X.SARADAP_PIDM = ROBNYUD_PIDM 
AND X.SARAPPD_APDC_CODE = STVAPDC_CODE	
AND X.SARADAP_APPL_NO = X.SARAPPD_APPL_NO
AND X.SARADAP_TERM_CODE_ENTRY = X.SARAPPD_TERM_CODE_ENTRY
AND RORALGS_AIDY_CODE = :AIDY
AND X.SARAPPD_PIDM = X.SARADAP_PIDM	
AND X.SARADAP_PIDM = :PIDM
-- END

--UNDERGRAD TRANSFER NOT PS,PL,NR041,TEAC03 NOT ENROLLED NO SGASTDN
SELECT RORALGS_AMT
FROM SARADAP X, SARAPPD X, RORALGS, STVAPDC, ROBNYUD
WHERE RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '6LIV'
AND CASE -- freshmen student type
    WHEN (X.SARADAP_STYP_CODE IN ('1','T')) THEN 'T'
END = RORALGS_KEY_2 

AND CASE -- OFF CAMPUS HOUSING FLAG IN ROBNYUD
    WHEN ROBNYUD_VALUE_120 IS NULL THEN '1'  --off campus 
	WHEN (ROBNYUD_VALUE_120 NOT IN ('C','D')) THEN '1'  --off campus 
	WHEN ROBNYUD_VALUE_120 = 'D' THEN '3'  --with family/relative
END = RORALGS_KEY_3
AND CASE -- level code
    WHEN X.SARADAP_LEVL_CODE = 'UG' THEN 'UG'
END = RORALGS_KEY_5	
AND CASE -- campus code
    WHEN X.SARADAP_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6		
AND X.SARADAP_TERM_CODE_ENTRY = (
    SELECT MAX(Y.SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP Y, ROBINST
    WHERE Y.SARADAP_PIDM = X.SARADAP_PIDM
	AND Y.SARADAP_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
    AND Y.SARADAP_TERM_CODE_ENTRY <= :PERIOD
	AND ROBINST_AIDY_CODE = :AIDY
)	
AND X.SARAPPD_SEQ_NO = (
    SELECT MAX (X.SARAPPD_SEQ_NO)
    FROM SARAPPD Y, ROBINST
    WHERE     Y.SARAPPD_PIDM = X.SARAPPD_PIDM
    AND Y.SARAPPD_SEQ_NO < 99
    AND Y.SARAPPD_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
    AND Y.SARAPPD_TERM_CODE_ENTRY <= :PERIOD
    AND ROBINST_AIDY_CODE = :AIDY           
    AND X.SARADAP_APPL_NO = Y.SARAPPD_APPL_NO
)       
AND STVAPDC_INST_ACC_IND = 'Y'
AND STVAPDC_SIGNF_IND = 'Y' 
AND X.SARADAP_PIDM = ROBNYUD_PIDM 
AND X.SARAPPD_APDC_CODE = STVAPDC_CODE	
AND X.SARADAP_APPL_NO = X.SARAPPD_APPL_NO
AND X.SARADAP_TERM_CODE_ENTRY = X.SARAPPD_TERM_CODE_ENTRY
AND RORALGS_AIDY_CODE = :AIDY
AND X.SARAPPD_PIDM = X.SARADAP_PIDM	
AND X.SARADAP_PIDM = :PIDM
-- END

--UNDERGRAD PS,PL,NR041,TEAC03 WITH SGASTDN
SELECT (RORALGS_AMT + 300)
FROM SGBSTDN X, RORALGS, RORPRST
WHERE RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '6LIV'
AND CASE -- OFF CAMPUS HOUSING FLAG IN RORPRST
    WHEN RORPRST_XHS = '1' THEN '1'  --off campus 
	WHEN (RORPRST_XHS IN ('3','4')) THEN '3'  --with family/relative
END = RORALGS_KEY_3
AND CASE -- level code
    WHEN X.SGBSTDN_LEVL_CODE = 'UG' THEN 'UG'
END = RORALGS_KEY_5	
AND CASE -- campus code
    WHEN X.SGBSTDN_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6	
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND (
    X.SGBSTDN_COLL_CODE_1 IN ('PS','PL')                           --check with SLU to confirm this.  Look for these or NOT these?
    OR X.SGBSTDN_PROGRAM_1  IN ('NR041','NR02','TEAC03')
)
AND X.SGBSTDN_PIDM = RORPRST_PIDM
AND RORPRST_PERIOD = :PERIOD
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
-- END

--UNDERGRAD NOT PS,PL,NR014,TEAC03 WITH SGASTDN
SELECT RORALGS_AMT
FROM SGBSTDN X, RORALGS, RORPRST
WHERE RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '6LIV'
AND CASE -- OFF CAMPUS HOUSING FLAG IN RORPRST
    WHEN RORPRST_XHS = '1' THEN '1'  --off campus 
	WHEN (RORPRST_XHS IN ('3','4')) THEN '3'  --with family/relative
END = RORALGS_KEY_3
AND CASE -- level code
    WHEN X.SGBSTDN_LEVL_CODE = 'UG' THEN 'UG'
END = RORALGS_KEY_5	
AND CASE -- campus code
    WHEN X.SGBSTDN_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6	
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND X.SGBSTDN_PIDM = RORPRST_PIDM
AND RORPRST_PERIOD = :PERIOD 	
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
-- END

--UNDERGRAD PS,PL,NR NO SGASTDN
SELECT (RORALGS_AMT + 300)
FROM SARADAP X, SARAPPD X, RORALGS, STVAPDC, RORPRST
WHERE RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '6LIV'
AND CASE -- OFF CAMPUS HOUSING FLAG IN RORPRST
    WHEN RORPRST_XHS = '1' THEN '1'  --off campus 
	WHEN (RORPRST_XHS IN ('3','4')) THEN '3'  --with family/relative
END = RORALGS_KEY_3
AND CASE -- level code
    WHEN X.SARADAP_LEVL_CODE = 'UG' THEN 'UG'
END = RORALGS_KEY_5	
AND CASE -- campus code
    WHEN X.SARADAP_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
AND (
    X.SARADAP_COLL_CODE_1 IN ('PS','PL')
    OR X.SARADAP_PROGRAM_1 IN ('NR041','NR02','TEAC03')
) 
AND X.SARADAP_PIDM = RORPRST_PIDM
AND RORPRST_PERIOD = :PERIOD 	
AND X.SARADAP_TERM_CODE_ENTRY = (
    SELECT MAX(Y.SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP Y, ROBINST
    WHERE Y.SARADAP_PIDM = X.SARADAP_PIDM
	AND Y.SARADAP_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
    AND Y.SARADAP_TERM_CODE_ENTRY <= :PERIOD
	AND ROBINST_AIDY_CODE = :AIDY
)		
AND X.SARAPPD_SEQ_NO = (
    SELECT MAX (X.SARAPPD_SEQ_NO)
    FROM SARAPPD Y, ROBINST
    WHERE     Y.SARAPPD_PIDM = X.SARAPPD_PIDM
    AND Y.SARAPPD_SEQ_NO < 99
    AND Y.SARAPPD_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
    AND Y.SARAPPD_TERM_CODE_ENTRY <= :PERIOD
    AND ROBINST_AIDY_CODE = :AIDY           
    AND X.SARADAP_APPL_NO = Y.SARAPPD_APPL_NO
) 
AND STVAPDC_INST_ACC_IND = 'Y'
AND STVAPDC_SIGNF_IND = 'Y'		
AND X.SARAPPD_APDC_CODE = STVAPDC_CODE	
AND X.SARADAP_APPL_NO = X.SARAPPD_APPL_NO
AND X.SARADAP_TERM_CODE_ENTRY = X.SARAPPD_TERM_CODE_ENTRY
AND RORALGS_AIDY_CODE = :AIDY
AND X.SARADAP_PIDM = X.SARAPPD_PIDM
AND X.SARADAP_PIDM = :PIDM
-- END

--UNDERGRAD NOT PS,PL,NR041,TEAC03 NO SGASTDN
SELECT RORALGS_AMT
FROM SARADAP X, SARAPPD X, RORALGS, STVAPDC, RORPRST
WHERE RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '6LIV'
AND CASE -- OFF CAMPUS HOUSING FLAG IN RORPRST
    WHEN RORPRST_XHS = '1' THEN '1'  --off campus 
	WHEN (RORPRST_XHS IN ('3','4')) THEN '3'  --with family/relative
END = RORALGS_KEY_3
AND CASE -- level code
    WHEN X.SARADAP_LEVL_CODE = 'UG' THEN 'UG'
END = RORALGS_KEY_5	
AND CASE -- campus code
    WHEN X.SARADAP_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
AND X.SARADAP_PIDM = RORPRST_PIDM
AND RORPRST_PERIOD = :PERIOD  
AND X.SARADAP_TERM_CODE_ENTRY = (
    SELECT MAX(Y.SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP Y, ROBINST
    WHERE Y.SARADAP_PIDM = X.SARADAP_PIDM
	AND Y.SARADAP_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
    AND Y.SARADAP_TERM_CODE_ENTRY <= :PERIOD
	AND ROBINST_AIDY_CODE = :AIDY
)
AND X.SARAPPD_SEQ_NO = (
    SELECT MAX (X.SARAPPD_SEQ_NO)
    FROM SARAPPD Y, ROBINST
    WHERE     Y.SARAPPD_PIDM = X.SARAPPD_PIDM
    AND Y.SARAPPD_SEQ_NO < 99
    AND Y.SARAPPD_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
    AND Y.SARAPPD_TERM_CODE_ENTRY <= :PERIOD
    AND ROBINST_AIDY_CODE = :AIDY           
    AND X.SARADAP_APPL_NO = Y.SARAPPD_APPL_NO
)     
AND STVAPDC_INST_ACC_IND = 'Y'
AND STVAPDC_SIGNF_IND = 'Y'		
AND X.SARAPPD_APDC_CODE = STVAPDC_CODE	
AND X.SARADAP_APPL_NO = X.SARAPPD_APPL_NO
AND X.SARADAP_TERM_CODE_ENTRY = X.SARAPPD_TERM_CODE_ENTRY
AND RORALGS_AIDY_CODE = :AIDY
AND X.SARADAP_PIDM = X.SARAPPD_PIDM
AND X.SARADAP_PIDM = :PIDM
-- END

--GRAD, LAW, MED WITH SGASTDN
SELECT RORALGS_AMT
FROM SGBSTDN X, RORALGS, RORPRST
WHERE RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '6LIV'
AND CASE -- OFF CAMPUS HOUSING FLAG IN RORPRST
    WHEN RORPRST_XHS = '1' THEN '1'  --off campus 
	WHEN (RORPRST_XHS IN ('3','4')) THEN '3'  --with family/relative
END = RORALGS_KEY_3
AND CASE -- level code
	WHEN X.SGBSTDN_LEVL_CODE = 'GR' THEN 'GR'
	WHEN X.SGBSTDN_LEVL_CODE = 'PL' THEN 'PL'
	WHEN X.SGBSTDN_LEVL_CODE = 'PM' THEN 'PM'
END = RORALGS_KEY_5	
AND CASE -- campus code
    WHEN X.SGBSTDN_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
AND X.SGBSTDN_PIDM = RORPRST_PIDM
AND RORPRST_PERIOD = :PERIOD  
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)		
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
-- END

--GRAD, LAW NO SGASTDN
SELECT RORALGS_AMT
FROM SARADAP X, SARAPPD X, RORALGS, STVAPDC, RORPRST
WHERE RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '6LIV'
AND CASE -- OFF CAMPUS HOUSING FLAG IN RORPRST
    WHEN RORPRST_XHS = '1' THEN '1'  --off campus 
	WHEN (RORPRST_XHS IN ('3','4')) THEN '3'  --with family/relative
END = RORALGS_KEY_3
AND CASE -- level code
	WHEN X.SARADAP_LEVL_CODE = 'GR' THEN 'GR'
	WHEN X.SARADAP_LEVL_CODE = 'PL' THEN 'PL'
	WHEN X.SARADAP_LEVL_CODE = 'PM' THEN 'PM'
END = RORALGS_KEY_5	
AND CASE -- campus code
    WHEN X.SARADAP_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
AND X.SARADAP_PIDM = RORPRST_PIDM
AND RORPRST_PERIOD = :PERIOD  
AND X.SARADAP_TERM_CODE_ENTRY = (
    SELECT MAX(Y.SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP Y, ROBINST
    WHERE Y.SARADAP_PIDM = X.SARADAP_PIDM
	AND Y.SARADAP_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
    AND Y.SARADAP_TERM_CODE_ENTRY <= :PERIOD
	AND ROBINST_AIDY_CODE = :AIDY
)
AND X.SARAPPD_SEQ_NO = (
    SELECT MAX (X.SARAPPD_SEQ_NO)
    FROM SARAPPD Y, ROBINST
    WHERE     Y.SARAPPD_PIDM = X.SARAPPD_PIDM
    AND Y.SARAPPD_SEQ_NO < 99
    AND Y.SARAPPD_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
    AND Y.SARAPPD_TERM_CODE_ENTRY <= :PERIOD
    AND ROBINST_AIDY_CODE = :AIDY           
    AND X.SARADAP_APPL_NO = Y.SARAPPD_APPL_NO
)       
AND STVAPDC_INST_ACC_IND = 'Y'
AND STVAPDC_SIGNF_IND = 'Y'		
AND X.SARAPPD_APDC_CODE = STVAPDC_CODE	
AND X.SARADAP_APPL_NO = X.SARAPPD_APPL_NO
AND X.SARADAP_TERM_CODE_ENTRY = X.SARAPPD_TERM_CODE_ENTRY
AND RORALGS_AIDY_CODE = :AIDY
AND X.SARADAP_PIDM = X.SARAPPD_PIDM
AND X.SARADAP_PIDM = :PIDM
-- END