-- if they're enrolled, calculate based on hours. otherwise full time is assumed

-- sequence 1: MED, LOOK FOR ENROLLMENT
SELECT CASE 
    WHEN nvl(rokmisc.f_calc_stud_bill_hrs(:PERIOD, a.SGBSTDN_PIDM,'N'),0) >= b.RORCRHR_FULL_TIME_CR_HRS 
    THEN RORALGS_AMT
    WHEN nvl(rokmisc.f_calc_stud_bill_hrs(:PERIOD, a.SGBSTDN_PIDM,'N'),0) >= b.RORCRHR_HALF_TIME_CR_HRS 
    THEN ROUND(RORALGS_AMT / 2)
    WHEN nvl(rokmisc.f_calc_stud_bill_hrs(:PERIOD, a.SGBSTDN_PIDM,'N'),0) < b.RORCRHR_HALF_TIME_CR_HRS 
     and     nvl(rokmisc.f_calc_stud_bill_hrs(:PERIOD, a.SGBSTDN_PIDM,'N'),0) > 0
    THEN ROUND(RORALGS_AMT / 4)
    END
FROM SGBSTDN a
CROSS JOIN RORALGS
INNER JOIN RORCRHR b 
    ON b.RORCRHR_LEVL_CODE = a.SGBSTDN_LEVL_CODE
    AND b.RORCRHR_AIDY_CODE = :AIDY
    AND b.RORCRHR_PERIOD = :PERIOD
WHERE RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '7BS' --check on component code
AND CASE
    WHEN a.SGBSTDN_LEVL_CODE = 'UG' THEN 'UG'
    WHEN a.SGBSTDN_LEVL_CODE = 'GR' THEN 'GR'
    WHEN a.SGBSTDN_LEVL_CODE = 'PL' THEN 'PL'
    WHEN a.SGBSTDN_LEVL_CODE = 'PM' THEN 'PM'
END = RORALGS_KEY_5
AND a.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN
    WHERE SGBSTDN_PIDM = a.SGBSTDN_PIDM
    AND SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND a.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
-- ;

-- sequence 2: SGBSTDN SEQUENCE
SELECT RORALGS_AMT
FROM SGBSTDN a
CROSS JOIN RORALGS
WHERE RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '7BS' --check on component code
AND CASE
    WHEN a.SGBSTDN_LEVL_CODE = 'UG' THEN 'UG'
    WHEN a.SGBSTDN_LEVL_CODE = 'GR' THEN 'GR'
    WHEN a.SGBSTDN_LEVL_CODE = 'PL' THEN 'PL'
    WHEN a.SGBSTDN_LEVL_CODE = 'PM' THEN 'PM'
END = RORALGS_KEY_5
AND a.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN
    WHERE SGBSTDN_PIDM = a.SGBSTDN_PIDM
    AND SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND a.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
-- ;

-- sequence 3: SARADAP SEQUENCE
SELECT RORALGS_AMT
FROM SARADAP a
CROSS JOIN RORALGS
INNER JOIN SARAPPD b 
    ON b.SARAPPD_PIDM = a.SARADAP_PIDM
    AND b.SARAPPD_APPL_NO = a.SARADAP_APPL_NO
    AND b.SARAPPD_TERM_CODE_ENTRY = a.SARADAP_TERM_CODE_ENTRY
INNER JOIN STVAPDC c 
    ON c.STVAPDC_CODE = b.SARAPPD_APDC_CODE
    AND c.STVAPDC_INST_ACC_IND = 'Y'
    AND c.STVAPDC_SIGNF_IND = 'Y'
WHERE RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '7BS'
AND CASE
    WHEN a.SARADAP_LEVL_CODE = 'UG' THEN 'UG'
    WHEN a.SARADAP_LEVL_CODE = 'GR' THEN 'GR'
    WHEN a.SARADAP_LEVL_CODE = 'PL' THEN 'PL'
    WHEN a.SARADAP_LEVL_CODE = 'PM' THEN 'PM'
END = RORALGS_KEY_5
-- sgbstdn term
AND a.SARADAP_TERM_CODE_ENTRY = (
    SELECT MAX(SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP, ROBINST
    WHERE SARADAP_PIDM = a.SARADAP_PIDM
    AND SARADAP_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
	AND SARADAP_TERM_CODE_ENTRY <= :PERIOD
    AND ROBINST_AIDY_CODE = :AIDY
)
--max application decision code sequence number
AND b.SARAPPD_SEQ_NO = (
    SELECT MAX(SARAPPD_SEQ_NO)
    FROM SARAPPD
    WHERE SARAPPD_PIDM = b.SARAPPD_PIDM
    AND SARAPPD_APPL_NO = b.SARAPPD_APPL_NO
    AND SARAPPD_SEQ_NO < 99
    AND SARAPPD_TERM_CODE_ENTRY = b.SARAPPD_TERM_CODE_ENTRY
)  
AND RORALGS_AIDY_CODE = :AIDY
AND a.SARADAP_PIDM = :PIDM
-- ;