-- if they're enrolled, calculate based on hours. otherwise full time is assumed

-- sequence 1: SGBSTDN
SELECT RORALGS_AMT * 2
FROM SGBSTDN a
CROSS JOIN RORALGS
WHERE RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '7BS' --check on component code
AND RORALGS_KEY_5 = 'UG'
AND a.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN
    WHERE SGBSTDN_PIDM = a.SGBSTDN_PIDM
    AND SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND a.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
-- ;

-- SARADAP
SELECT RORALGS_AMT * 2
FROM SARADAP a
CROSS JOIN RORALGS
INNER JOIN SARAPPD b 
    ON b.SARAPPD_PIDM = a.SARADAP_PIDM
    AND b.SARAPPD_APPL_NO = a.SARADAP_APPL_NO
    AND b.SARAPPD_TERM_CODE_ENTRY = a.SARADAP_TERM_CODE_ENTRY
INNER JOIN STVAPDC c 
    ON c.STVAPDC_CODE = b.SARAPPD_APDC_CODE
    AND c.STVAPDC_INST_ACC_IND = 'Y'
    AND c.STVAPDC_SIGNF_IND = 'Y'
WHERE RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '7BS'
AND RORALGS_KEY_5 = 'UG'
AND a.SARADAP_TERM_CODE_ENTRY = (
    SELECT MAX(SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP, ROBINST
    WHERE SARADAP_PIDM = a.SARADAP_PIDM
    AND SARADAP_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
	AND SARADAP_TERM_CODE_ENTRY <= :PERIOD
    AND ROBINST_AIDY_CODE = :AIDY
)
AND b.SARAPPD_SEQ_NO = (
    SELECT MAX(SARAPPD_SEQ_NO)
    FROM SARAPPD
    WHERE SARAPPD_PIDM = b.SARAPPD_PIDM
    AND SARAPPD_SEQ_NO < 99
    AND SARAPPD_TERM_CODE_ENTRY <= b.SARAPPD_TERM_CODE_ENTRY
)  
AND RORALGS_AIDY_CODE = :AIDY
AND a.SARADAP_PIDM = :PIDM
-- ;