-- MADRID CAFETERIA PLAN 

-- The way I understand it. SPSA should always be with a FR campus since it 
-- should be used for a main campus student who is temporarily studying abroad for one term or one year.  
 
-- Likewise, SPDA and SPTR should only be with a SP campus since those students are 
-- permanently enrolled there and seeking a degree from the SP campus.  
 

SELECT RORALGS_AMT
FROM SGBSTDN a
CROSS JOIN RORALGS
INNER JOIN SGRSATT X 
    on X.SGRSATT_PIDM = a.SGBSTDN_PIDM
    and X.SGRSATT_TERM_CODE_EFF = (
        SELECT MAX(SGRSATT_TERM_CODE_EFF)
        FROM SGRSATT
        WHERE SGRSATT_PIDM = X.SGRSATT_PIDM
    )
WHERE RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '5CAF' 
AND CASE -- attribute code
    WHEN X.SGRSATT_ATTS_CODE = 'SPSA' THEN 'SPSA'
END = RORALGS_KEY_10
AND a.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN
    WHERE SGBSTDN_PIDM = a.SGBSTDN_PIDM
    AND SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND a.SGBSTDN_STST_CODE IN ('AS', 'IL')
-- AND a.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
;

SELECT RORALGS_AMT
FROM SGBSTDN a
CROSS JOIN RORALGS
WHERE RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '5CAF' 
AND CASE 
    WHEN SGBSTDN_LEVL_CODE = 'UG' THEN 'UG'
END = RORALGS_KEY_5
AND CASE 
    WHEN SGBSTDN_CAMP_CODE = 'SP' THEN 'SP'
END = RORALGS_KEY_6
AND a.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN
    WHERE SGBSTDN_PIDM = a.SGBSTDN_PIDM
    AND SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND a.SGBSTDN_STST_CODE IN ('AS', 'IL')
AND a.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
;

-- ;;;;;;;;;;
SELECT RORALGS_AMT
FROM SARADAP a
CROSS JOIN RORALGS
INNER JOIN SARAPPD b
    ON b.SARAPPD_PIDM = a.SARADAP_PIDM
    AND b.SARAPPD_APPL_NO = a.SARADAP_APPL_NO
    AND b.SARAPPD_TERM_CODE_ENTRY = a.SARADAP_TERM_CODE_ENTRY
INNER JOIN STVAPDC c
    ON c.STVAPDC_CODE = b.SARAPPD_APDC_CODE
    AND c.STVAPDC_INST_ACC_IND = 'Y'
    AND c.STVAPDC_SIGNF_IND = 'Y'
INNER JOIN ROBINST R on R.ROBINST_AIDY_CODE = RORALGS_AIDY_CODE
INNER JOIN RBRAPBG bg
    ON bg.RBRAPBG_PIDM = a.SARADAP_PIDM
    AND bg.RBRAPBG_PBGP_CODE = 'MR'
    AND bg.RBRAPBG_PERIOD = :PERIOD
    AND bg.RBRAPBG_RUN_NAME = 'ACTUAL'
WHERE RORALGS_AIDY_CODE = :AIDY
-- AND a.SARADAP_PIDM = :PIDM
AND RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '5CAF'
AND CASE
    WHEN a.SARADAP_LEVL_CODE = 'UG' THEN 'UG'
END = RORALGS_KEY_5
AND CASE
    WHEN a.SARADAP_CAMP_CODE = 'SP' THEN 'SP'
END = RORALGS_KEY_6
AND a.SARADAP_TERM_CODE_ENTRY = (
    SELECT MAX(SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP
    WHERE SARADAP_PIDM = a.SARADAP_PIDM
	AND SARADAP_TERM_CODE_ENTRY BETWEEN (R.ROBINST_AIDY_END_YEAR || '00') AND :PERIOD
)
AND b.SARAPPD_SEQ_NO = (
    SELECT MAX(SARAPPD_SEQ_NO)
    FROM SARAPPD
    WHERE SARAPPD_PIDM = b.SARAPPD_PIDM
    AND SARAPPD_SEQ_NO < 99
    AND SARAPPD_TERM_CODE_ENTRY = a.SARADAP_TERM_CODE_ENTRY           
    AND SARAPPD_APPL_NO = a.SARADAP_APPL_NO
)
 
;

-- SELECT RORALGS_AMT
--     FROM SARADAP a, SARAPPD b, ROBINST R, RORALGS, STVAPDC
-- WHERE RORALGS_KEY_1 = 'PBDG'

-- AND RORALGS_KEY_4 = '5CAF' -- budget component

-- AND CASE -- level code
--     WHEN a.SARADAP_LEVL_CODE = 'UG' THEN 'UG'
-- END = RORALGS_KEY_5
	
-- AND CASE -- campus code
--     WHEN a.SARADAP_CAMP_CODE = 'SP' THEN 'SP'
-- END = RORALGS_KEY_6
	
-- -- max saradap term <= passed period	
-- AND a.SARADAP_TERM_CODE_ENTRY = (
--     SELECT MAX(SARADAP_TERM_CODE_ENTRY)
--     FROM SARADAP
--     WHERE SARADAP_PIDM = a.SARADAP_PIDM
-- 	AND SARADAP_TERM_CODE_ENTRY BETWEEN (R.ROBINST_AIDY_END_YEAR || '00') AND :PERIOD
-- )
-- --max application decision code sequence number
-- AND b.SARAPPD_SEQ_NO = (
--     SELECT MAX(SARAPPD_SEQ_NO)
--     FROM SARAPPD
--     WHERE SARAPPD_PIDM = b.SARAPPD_PIDM
--     AND SARAPPD_SEQ_NO < 99
--     AND SARAPPD_TERM_CODE_ENTRY = a.SARADAP_TERM_CODE_ENTRY           
--     AND SARAPPD_APPL_NO = a.SARADAP_APPL_NO
-- ) 
      
-- AND STVAPDC_INST_ACC_IND = 'Y'
-- AND STVAPDC_SIGNF_IND = 'Y'

-- AND b.SARAPPD_APDC_CODE = STVAPDC_CODE	
-- AND a.SARADAP_APPL_NO = b.SARAPPD_APPL_NO
-- AND a.SARADAP_TERM_CODE_ENTRY = b.SARAPPD_TERM_CODE_ENTRY
-- AND RORALGS_AIDY_CODE = :AIDY
-- AND a.SARADAP_PIDM = b.SARAPPD_PIDM
-- AND r.ROBINST_AIDY_CODE = :AIDY
-- -- AND a.SARADAP_PIDM = :PIDM
-- ;
