-- RORALGS INSERT (11 rows) FOR SHEET: <1TUI_UG>
INSERT INTO FAISMGR.RORALGS 
(RORALGS_AIDY_CODE, RORALGS_KEY_1, RORALGS_KEY_2, RORALGS_KEY_3, RORALGS_KEY_4,
RORALGS_KEY_5, RORALGS_KEY_6, RORALGS_KEY_7, RORALGS_KEY_8, RORALGS_KEY_9,
RORALGS_KEY_10, RORALGS_KEY_11, RORALGS_KEY_12, RORALGS_COMMENT_12, RORALGS_AMT,
RORALGS_COMMENT) 
VALUES 
('2627', 'PBDG', NULL, NULL, '1TUI', 'UG', 'FR', NULL, NULL, NULL, NULL, NULL,
'12to18', NULL, 29480, 'flat rate'),
('2627', 'PBDG', NULL, NULL, '1TUI', 'UG', 'FR', 'PS', NULL, 'CSO', NULL, NULL,
NULL, NULL, 0, NULL),
('2627', 'PBDG', NULL, NULL, '1TUI', 'UG', 'FR', 'PS', NULL, NULL, NULL,
'PSUGSSM', NULL, NULL, 0, NULL),
('2627', 'PBDG', NULL, NULL, '1TUI', 'UG', 'FR', 'PS', NULL, NULL, NULL, NULL,
NULL, NULL, 0, NULL),
('2627', 'PBDG', NULL, NULL, '1TUI', 'UG', 'FR', 'PL', NULL, NULL, NULL, NULL,
'PT', NULL, 0, NULL),
('2627', 'PBDG', NULL, NULL, '1TUI', 'UG', 'FR', 'PL', NULL, NULL, NULL, NULL,
'FT', NULL, 0, NULL),
('2627', 'PBDG', NULL, NULL, '1TUI', 'UG', 'FR', 'NR', NULL, 'RN2BSN', NULL, NULL,
NULL, NULL, 0, NULL),
('2627', 'PBDG', NULL, NULL, '1TUI', 'UG', 'FR', 'ED', NULL, 'TEAC03', NULL, NULL,
NULL, NULL, 0, NULL),
('2627', 'PBDG', NULL, NULL, '1TUI', 'UG', 'FR', NULL, NULL, NULL, NULL, NULL,
'PT', NULL, 0, NULL),
('2627', 'PBDG', NULL, NULL, '1TUI', 'UG', 'FR', NULL, NULL, NULL, NULL, NULL,
'12to18', NULL, 0, NULL),
('2627', 'PBDG', NULL, NULL, '1TUI', 'UG', 'FR', NULL, NULL, NULL, NULL, NULL,
'19+', 0, 0, NULL);

-- RORALGS INSERT (12 rows) FOR SHEET: <2FEE>
INSERT INTO FAISMGR.RORALGS 
(RORALGS_AIDY_CODE, RORALGS_KEY_1, RORALGS_KEY_2, RORALGS_KEY_3, RORALGS_KEY_4,
RORALGS_KEY_5, RORALGS_KEY_6, RORALGS_KEY_7, RORALGS_KEY_8, RORALGS_KEY_9,
RORALGS_KEY_10, RORALGS_KEY_11, RORALGS_KEY_12, RORALGS_AMT, RORALGS_COMMENT) 
VALUES 
('2627', 'PBDG', NULL, NULL, '2FEE', NULL, NULL, 'PS', NULL, NULL, NULL, NULL,
NULL, 120, 'SPS (UG and GR same rate)'),
('2627', 'PBDG', NULL, NULL, '2FEE', 'UG', NULL, NULL, NULL, NULL, NULL, NULL,
'FT', 500, 'UG not PS FT'),
('2627', 'PBDG', NULL, NULL, '2FEE', 'UG', NULL, NULL, NULL, NULL, NULL, NULL,
'PT', 315, 'UG not PS PT'),
('2627', 'PBDG', NULL, NULL, '2FEE', 'UG', NULL, NULL, NULL, NULL, NULL, NULL,
'LHT', 0, 'UG not PS LHT'),
('2627', 'PBDG', NULL, NULL, '2FEE', 'GR', NULL, NULL, NULL, NULL, NULL, NULL,
'FT', 465, 'GR not PS FT'),
('2627', 'PBDG', NULL, NULL, '2FEE', 'GR', NULL, NULL, NULL, NULL, NULL, NULL,
'PT', 280, 'GR not PS PT'),
('2627', 'PBDG', NULL, NULL, '2FEE', 'PL', NULL, NULL, NULL, NULL, NULL, NULL,
'FT', 465, 'LAW FT'),
('2627', 'PBDG', NULL, NULL, '2FEE', 'PL', NULL, NULL, NULL, NULL, NULL, NULL,
'PT', 280, 'LAW PT'),
('2627', 'PBDG', NULL, NULL, '2FEE', 'PM', NULL, NULL, NULL, NULL, 'M1', NULL,
NULL, 0, 'Med1'),
('2627', 'PBDG', NULL, NULL, '2FEE', 'PM', NULL, NULL, NULL, NULL, 'M2', NULL,
NULL, 0, 'Med2'),
('2627', 'PBDG', NULL, NULL, '2FEE', 'PM', NULL, NULL, NULL, NULL, 'M3', NULL,
NULL, 0, 'Med3'),
('2627', 'PBDG', NULL, NULL, '2FEE', 'PM', NULL, NULL, NULL, NULL, 'M4', NULL,
NULL, 0, 'Med4');

-- RORALGS INSERT (7 rows) FOR SHEET: <3HSM>
INSERT INTO FAISMGR.RORALGS 
(RORALGS_AIDY_CODE, RORALGS_KEY_1, RORALGS_KEY_2, RORALGS_KEY_3, RORALGS_KEY_4,
RORALGS_KEY_5, RORALGS_KEY_6, RORALGS_KEY_7, RORALGS_KEY_8, RORALGS_KEY_9,
RORALGS_KEY_10, RORALGS_KEY_11, RORALGS_KEY_12, RORALGS_AMT, RORALGS_COMMENT) 
VALUES 
('2627', 'PBDG', NULL, NULL, '3HSM', NULL, NULL, NULL, NULL, NULL, NULL, NULL,
NULL, 0, NULL),
('2627', 'PBDG', 'F', NULL, '3HSM', 'UG', 'FR', NULL, NULL, NULL, NULL, NULL,
NULL, 8180, NULL),
('2627', 'PBDG', 'T', NULL, '3HSM', 'UG', 'FR', NULL, NULL, NULL, NULL, NULL,
NULL, 8180, NULL),
('2627', 'PBDG', NULL, 2, '3HSM', 'UG', 'FR', NULL, NULL, NULL, NULL, NULL, NULL,
8180, NULL),
('2627', 'PBDG', NULL, 2, '3HSM', 'GR', 'FR', NULL, NULL, NULL, NULL, NULL, NULL,
8180, NULL),
('2627', 'PBDG', NULL, 2, '3HSM', 'PL', 'FR', NULL, NULL, NULL, NULL, NULL, NULL,
8180, NULL),
('2627', 'PBDG', NULL, 2, '3HSM', 'PM', 'FR', NULL, NULL, NULL, NULL, NULL, NULL,
8180, NULL);

-- RORALGS INSERT (1 rows) FOR SHEET: <4COM>
INSERT INTO FAISMGR.RORALGS 
(RORALGS_AIDY_CODE, RORALGS_KEY_1, RORALGS_KEY_2, RORALGS_KEY_3, RORALGS_KEY_4,
RORALGS_KEY_5, RORALGS_KEY_6, RORALGS_KEY_7, RORALGS_KEY_8, RORALGS_KEY_9,
RORALGS_KEY_10, RORALGS_KEY_11, RORALGS_KEY_12, RORALGS_AMT, RORALGS_COMMENT) 
VALUES 
('2627', 'PBDG', NULL, 1, '4COM', 'UG', 'FR', NULL, NULL, NULL, NULL, NULL, NULL,
300, NULL);

-- RORALGS INSERT (1 rows) FOR SHEET: <5CAF>
INSERT INTO FAISMGR.RORALGS 
(RORALGS_AIDY_CODE, RORALGS_KEY_1, RORALGS_KEY_2, RORALGS_KEY_3, RORALGS_KEY_4,
RORALGS_KEY_5, RORALGS_KEY_6, RORALGS_KEY_7, RORALGS_KEY_8, RORALGS_KEY_9,
RORALGS_KEY_10, RORALGS_KEY_11, RORALGS_KEY_12, RORALGS_AMT, RORALGS_COMMENT) 
VALUES 
('2627', 'PBDG', NULL, NULL, '5CAF', NULL, NULL, NULL, NULL, NULL, NULL, NULL,
NULL, 128, NULL);

-- RORALGS INSERT (10 rows) FOR SHEET: <6LIV>
INSERT INTO FAISMGR.RORALGS 
(RORALGS_AIDY_CODE, RORALGS_KEY_1, RORALGS_KEY_2, RORALGS_KEY_3, RORALGS_KEY_4,
RORALGS_KEY_5, RORALGS_KEY_6, RORALGS_KEY_7, RORALGS_KEY_8, RORALGS_KEY_9,
RORALGS_KEY_10, RORALGS_KEY_11, RORALGS_KEY_12, RORALGS_AMT, RORALGS_COMMENT) 
VALUES 
('2627', 'PBDG', NULL, 1, '6LIV', 'UG', 'FR', NULL, NULL, NULL, NULL, NULL, NULL,
7880, NULL),
('2627', 'PBDG', NULL, 3, '6LIV', 'UG', 'FR', NULL, NULL, NULL, NULL, NULL, NULL,
3790, NULL),
('2627', 'PBDG', 'T', 1, '6LIV', 'UG', 'FR', NULL, NULL, NULL, NULL, NULL, NULL,
7880, NULL),
('2627', 'PBDG', 'T', 3, '6LIV', 'UG', 'FR', NULL, NULL, NULL, NULL, NULL, NULL,
3790, NULL),
('2627', 'PBDG', NULL, 1, '6LIV', 'GR', 'FR', NULL, NULL, NULL, NULL, NULL, NULL,
8180, NULL),
('2627', 'PBDG', NULL, 3, '6LIV', 'GR', 'FR', NULL, NULL, NULL, NULL, NULL, NULL,
8180, NULL),
('2627', 'PBDG', NULL, 1, '6LIV', 'PL', 'FR', NULL, NULL, NULL, NULL, NULL, NULL,
8180, NULL),
('2627', 'PBDG', NULL, 3, '6LIV', 'PL', 'FR', NULL, NULL, NULL, NULL, NULL, NULL,
8180, NULL),
('2627', 'PBDG', NULL, 1, '6LIV', 'PM', 'FR', NULL, NULL, NULL, NULL, NULL, NULL,
8180, NULL),
('2627', 'PBDG', NULL, 3, '6LIV', 'PM', 'FR', NULL, NULL, NULL, NULL, NULL, NULL,
8180, NULL);

-- RORALGS INSERT (4 rows) FOR SHEET: <7BS>
INSERT INTO FAISMGR.RORALGS 
(RORALGS_AIDY_CODE, RORALGS_KEY_1, RORALGS_KEY_2, RORALGS_KEY_3, RORALGS_KEY_4,
RORALGS_KEY_5, RORALGS_KEY_6, RORALGS_KEY_7, RORALGS_KEY_8, RORALGS_KEY_9,
RORALGS_KEY_10, RORALGS_KEY_11, RORALGS_KEY_12, RORALGS_AMT, RORALGS_COMMENT) 
VALUES 
('2627', 'PBDG', NULL, NULL, '7BS', 'UG', NULL, NULL, NULL, NULL, NULL, NULL,
NULL, 645, 'books and supplies'),
('2627', 'PBDG', NULL, NULL, '7BS', 'GR', NULL, NULL, NULL, NULL, NULL, NULL,
NULL, 0, 'books and supplies'),
('2627', 'PBDG', NULL, NULL, '7BS', 'PL', NULL, NULL, NULL, NULL, NULL, NULL,
NULL, 0, 'books and supplies'),
('2627', 'PBDG', NULL, NULL, '7BS', 'PM', NULL, NULL, NULL, NULL, NULL, NULL,
NULL, 0, 'books and supplies');

-- RORALGS INSERT (4 rows) FOR SHEET: <8TRS>
INSERT INTO FAISMGR.RORALGS 
(RORALGS_AIDY_CODE, RORALGS_KEY_1, RORALGS_KEY_2, RORALGS_KEY_3, RORALGS_KEY_4,
RORALGS_KEY_5, RORALGS_KEY_6, RORALGS_KEY_7, RORALGS_KEY_8, RORALGS_KEY_9,
RORALGS_KEY_10, RORALGS_KEY_11, RORALGS_KEY_12, RORALGS_AMT, RORALGS_COMMENT) 
VALUES 
('2627', 'PBDG', NULL, NULL, '8TRS', 'UG', NULL, NULL, NULL, NULL, NULL, NULL,
NULL, 1610, 'UG Transportation'),
('2627', 'PBDG', NULL, NULL, '8TRS', 'GR', NULL, NULL, NULL, NULL, NULL, NULL,
NULL, 0, 'GR Transportation'),
('2627', 'PBDG', NULL, NULL, '8TRS', 'PL', NULL, NULL, NULL, NULL, NULL, NULL,
NULL, 0, 'Law Transportation'),
('2627', 'PBDG', NULL, NULL, '8TRS', 'PM', NULL, NULL, NULL, NULL, NULL, NULL,
NULL, 0, 'Med Transportation');

-- RORALGS INSERT (7 rows) FOR SHEET: <9MIS>
INSERT INTO FAISMGR.RORALGS 
(RORALGS_AIDY_CODE, RORALGS_KEY_1, RORALGS_KEY_2, RORALGS_KEY_3, RORALGS_KEY_4,
RORALGS_KEY_5, RORALGS_KEY_6, RORALGS_KEY_7, RORALGS_KEY_8, RORALGS_KEY_9,
RORALGS_KEY_10, RORALGS_KEY_11, RORALGS_KEY_12, RORALGS_AMT, RORALGS_COMMENT) 
VALUES 
('2627', 'PBDG', NULL, NULL, '9MIS', 'UG', NULL, NULL, NULL, NULL, NULL, NULL,
NULL, 1440, 'UG MISC'),
('2627', 'PBDG', NULL, NULL, '9MIS', 'GR', NULL, NULL, NULL, NULL, NULL, NULL,
NULL, 0, 'GR MISC'),
('2627', 'PBDG', NULL, NULL, '9MIS', 'PL', NULL, NULL, NULL, NULL, NULL, NULL,
NULL, 0, 'PL MISC'),
('2627', 'PBDG', NULL, NULL, '9MIS', 'PM', NULL, NULL, NULL, NULL, NULL, 'M1',
NULL, 0, 'M1 MISC'),
('2627', 'PBDG', NULL, NULL, '9MIS', 'PM', NULL, NULL, NULL, NULL, NULL, 'M2',
NULL, 0, 'M2 MISC'),
('2627', 'PBDG', NULL, NULL, '9MIS', 'PM', NULL, NULL, NULL, NULL, NULL, 'M3',
NULL, 0, 'M3 MISC'),
('2627', 'PBDG', NULL, NULL, '9MIS', 'PM', NULL, NULL, NULL, NULL, NULL, 'M4',
NULL, 0, 'M4 MISC');

-- RORALGS INSERT (1 rows) FOR SHEET: <21BF>
INSERT INTO FAISMGR.RORALGS 
(RORALGS_AIDY_CODE, RORALGS_KEY_1, RORALGS_KEY_2, RORALGS_KEY_3, RORALGS_KEY_4,
RORALGS_KEY_5, RORALGS_KEY_6, RORALGS_KEY_7, RORALGS_KEY_8, RORALGS_KEY_9,
RORALGS_KEY_10, RORALGS_KEY_11, RORALGS_KEY_12, RORALGS_AMT, RORALGS_COMMENT) 
VALUES 
('2627', 'PBDG', NULL, NULL, '21BF', 'UG', NULL, 'BA', NULL, NULL, NULL, NULL,
NULL, 20, 'BUSINESS SOFTWARE FEE');

-- RORALGS INSERT (1 rows) FOR SHEET: <22DF>
INSERT INTO FAISMGR.RORALGS 
(RORALGS_AIDY_CODE, RORALGS_KEY_1, RORALGS_KEY_2, RORALGS_KEY_3, RORALGS_KEY_4,
RORALGS_KEY_5, RORALGS_KEY_6, RORALGS_KEY_7, RORALGS_KEY_8, RORALGS_KEY_9,
RORALGS_KEY_10, RORALGS_KEY_11, RORALGS_KEY_12, RORALGS_AMT, RORALGS_COMMENT) 
VALUES 
('2627', 'PBDG', NULL, NULL, '22DF', NULL, NULL, 'AH', NULL, NULL, NULL, NULL,
NULL, 75, 'DOISY SOFTWARE FEE');

-- RORALGS INSERT (1 rows) FOR SHEET: <23PF>
INSERT INTO FAISMGR.RORALGS 
(RORALGS_AIDY_CODE, RORALGS_KEY_1, RORALGS_KEY_2, RORALGS_KEY_3, RORALGS_KEY_4,
RORALGS_KEY_5, RORALGS_KEY_6, RORALGS_KEY_7, RORALGS_KEY_8, RORALGS_KEY_9,
RORALGS_KEY_10, RORALGS_KEY_11, RORALGS_KEY_12, RORALGS_AMT, RORALGS_COMMENT) 
VALUES 
('2627', 'PBDG', NULL, NULL, '23PF', 'UG', NULL, 'SE', NULL, NULL, NULL, NULL,
NULL, 350, 'PARKS COLLEGE FEE');

-- RORALGS INSERT (1 rows) FOR SHEET: <24SF>
INSERT INTO FAISMGR.RORALGS 
(RORALGS_AIDY_CODE, RORALGS_KEY_1, RORALGS_KEY_2, RORALGS_KEY_3, RORALGS_KEY_4,
RORALGS_KEY_5, RORALGS_KEY_6, RORALGS_KEY_7, RORALGS_KEY_8, RORALGS_KEY_9,
RORALGS_KEY_10, RORALGS_KEY_11, RORALGS_KEY_12, RORALGS_AMT, RORALGS_COMMENT) 
VALUES 
('2627', 'PBDG', NULL, NULL, '24SF', 'UG', 'FR', NULL, NULL, NULL, 'SPSA', NULL,
NULL, 350, NULL);

