-- RORALGS INSERT (2 rows) FOR SHEET: <columns template>
INSERT INTO FAISMGR.RORALGS 
(RORALGS_AIDY_CODE, RORALGS_KEY_1, RORALGS_COMMENT_1, RORALGS_KEY_2,
RORALGS_COMMENT_2, RORALGS_KEY_3, RORALGS_COMMENT_3, RORALGS_KEY_4,
RORALGS_COMMENT_4, RORALGS_KEY_5, RORALGS_COMMENT_5, RORALGS_KEY_6,
RORALGS_COMMENT_6, RORALGS_KEY_7, RORALGS_COMMENT_7, RORALGS_KEY_8,
RORALGS_COMMENT_8, RORALGS_KEY_9, RORALGS_COMMENT_9, RORALGS_KEY_10,
RORALGS_COMMENT_10, RORALGS_KEY_11, RORALGS_COMMENT_11, RORALGS_KEY_12,
RORALGS_COMMENT_12, RORALGS_AMT, RORALGS_COMMENT) 
VALUES 
('2526', 'PBDG', 'period-based budgeting', NULL, NULL, NULL, NULL, '2FEE',
'FEES rule', 'UG', 'student level', NULL, NULL, 'college', 'PS', NULL, NULL,
NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 120,
'used for all SPS students UG and GR, part time gets half');

-- RORALGS INSERT (2 rows) FOR SHEET: <fees>
INSERT INTO FAISMGR.RORALGS 
(RORALGS_AIDY_CODE, RORALGS_KEY_1, RORALGS_KEY_2, RORALGS_KEY_3, RORALGS_KEY_4,
RORALGS_KEY_5, RORALGS_KEY_6, RORALGS_KEY_7, RORALGS_KEY_8, RORALGS_KEY_9,
RORALGS_KEY_10, RORALGS_KEY_11, RORALGS_KEY_12, RORALGS_AMT, RORALGS_COMMENT) 
VALUES 
('2627', 'PBDG', NULL, NULL, '2FEE', NULL, NULL, 'PS', NULL, NULL, NULL, NULL,
NULL, 120, 'SPS'),
('2627', 'PBDG', NULL, NULL, '2FEE', 'UG', NULL, '<> PS', NULL, NULL, NULL, NULL,
'FT', 422, 'UG not PS FT'),
('2627', 'PBDG', NULL, NULL, '2FEE', 'UG', NULL, '<> PS', NULL, NULL, NULL, NULL,
'PT', 270, 'UG not PS PT'),
('2627', 'PBDG', NULL, NULL, '2FEE', 'UG', NULL, '<> PS', NULL, NULL, NULL, NULL,
'LHT', 0, 'UG not PS LHT'),
('2627', 'PBDG', NULL, NULL, '2FEE', 'GR', NULL, '<> PS', NULL, NULL, NULL, NULL,
'FT', 387, 'GR not PS FT'),
('2627', 'PBDG', NULL, NULL, '2FEE', 'GR', NULL, '<> PS', NULL, NULL, NULL, NULL,
'PT', 235, 'GR not PS PT'),
('2627', 'PBDG', NULL, NULL, '2FEE', 'PL', NULL, NULL, NULL, NULL, NULL, NULL,
'FT', 387, 'LAW FT'),
('2627', 'PBDG', NULL, NULL, '2FEE', 'PL', NULL, NULL, NULL, NULL, NULL, NULL,
'PT', 235, 'LAW PT');

