select spriden_id from shrlgpa join spriden on spriden_change_ind is null and spriden_pidm = shrlgpa_pidm where shrlgpa_gpa like '%._95';
select spriden_id from shrlgpa join spriden on spriden_change_ind is null and spriden_pidm = shrlgpa_pidm where shrlgpa_gpa = '2.695';

select spriden_id from (

SELECT DISTINCT A.SGBSTDN_PIDM
FROM SGBSTDN A 
JOIN SHRLGPA B ON B.SHRLGPA_PIDM = A.SGBSTDN_PIDM
    AND B.SHRLGPA_LEVL_CODE = A.SGBSTDN_LEVL_CODE
    AND B.SHRLGPA_GPA_TYPE_IND = 'I'
JOIN SHRLGPA C ON C.SHRLGPA_PIDM = A.SGBSTDN_PIDM
    AND C.SHRLGPA_LEVL_CODE = A.SGBSTDN_LEVL_CODE
    AND C.SHRLGPA_GPA_TYPE_IND = 'O'
WHERE A.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Z.SGBSTDN_TERM_CODE_EFF) FROM SGBSTDN Z
    WHERE Z.SGBSTDN_PIDM = A.SGBSTDN_PIDM
    AND Z.SGBSTDN_TERM_CODE_EFF <= :TERM  
)
AND A.SGBSTDN_LEVL_CODE = 'GR'
AND (B.SHRLGPA_GPA < 2.995 OR C.SHRLGPA_HOURS_EARNED < (C.SHRLGPA_HOURS_ATTEMPTED * 0.665))
-- AND A.SGBSTDN_PIDM = :PIDM
) a 
left join (
-- AND A.SGBSTDN_PIDM = :PIDM
SELECT DISTINCT A.SGBSTDN_PIDM
FROM SGBSTDN A 
JOIN SHRLGPA B ON B.SHRLGPA_PIDM = A.SGBSTDN_PIDM
    AND B.SHRLGPA_LEVL_CODE = A.SGBSTDN_LEVL_CODE
    AND B.SHRLGPA_GPA_TYPE_IND = 'I'
JOIN SHRLGPA C ON C.SHRLGPA_PIDM = A.SGBSTDN_PIDM
    AND C.SHRLGPA_LEVL_CODE = A.SGBSTDN_LEVL_CODE
    AND C.SHRLGPA_GPA_TYPE_IND = 'O'
WHERE A.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Z.SGBSTDN_TERM_CODE_EFF) FROM SGBSTDN Z
    WHERE Z.SGBSTDN_PIDM = A.SGBSTDN_PIDM
    AND Z.SGBSTDN_TERM_CODE_EFF <= :TERM  
)
AND A.SGBSTDN_LEVL_CODE = 'GR'
AND (
    B.SHRLGPA_GPA <= case a.sgbstdn_degc_code_1 when 'DPT' then 2.695 else 2.995 end 
    OR C.SHRLGPA_HOURS_EARNED < (C.SHRLGPA_HOURS_ATTEMPTED * 0.665)
)
-- AND A.SGBSTDN_PIDM = :PIDM
) b on b.sgbstdn_pidm = a.sgbstdn_pidm
join spriden on spriden_pidm = a.sgbstdn_pidm and spriden_change_ind is null
where b.sgbstdn_pidm is null

;

select spriden_id from rorsapr 
join spriden on spriden_pidm = rorsapr_pidm and spriden_change_ind is null
where rorsapr_term_code in ('202700', '202710', '202720') and rorsapr_cumulative_gpa = 2.695;

-- 001192596
SELECT DISTINCT A.SGBSTDN_PIDM
FROM SGBSTDN A 
JOIN SHRLGPA B ON B.SHRLGPA_PIDM = A.SGBSTDN_PIDM
    AND B.SHRLGPA_LEVL_CODE = A.SGBSTDN_LEVL_CODE
    AND B.SHRLGPA_GPA_TYPE_IND = 'I'
JOIN SHRLGPA C ON C.SHRLGPA_PIDM = A.SGBSTDN_PIDM
    AND C.SHRLGPA_LEVL_CODE = A.SGBSTDN_LEVL_CODE
    AND C.SHRLGPA_GPA_TYPE_IND = 'O'
WHERE A.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Z.SGBSTDN_TERM_CODE_EFF) FROM SGBSTDN Z
    WHERE Z.SGBSTDN_PIDM = A.SGBSTDN_PIDM
    AND Z.SGBSTDN_TERM_CODE_EFF <= :TERM  
)
AND A.SGBSTDN_LEVL_CODE = 'UG'
AND (B.SHRLGPA_GPA < 1.995 OR C.SHRLGPA_HOURS_EARNED < (C.SHRLGPA_HOURS_ATTEMPTED * 0.665))
AND A.SGBSTDN_PIDM = (select spriden_pidm from spriden where spriden_id = '001192596' and spriden_change_ind is null);

select * from shrtckn where shrtckn_pidm = (select spriden_pidm from spriden where spriden_id = '001192596' and spriden_change_ind is null);
select * from shrtckg where shrtckg_pidm = (select spriden_pidm from spriden where spriden_id = '001192596' and spriden_change_ind is null);

select * from shrtckg 
join spriden on spriden_pidm = shrtckg_pidm and spriden_change_ind is null
where shrtckg_grde_code_final = 'S' and shrtckg_term_code = '202700' and shrtckg_gmod_code = 'V';

SELECT DISTINCT A.SGBSTDN_PIDM
FROM SGBSTDN A 
JOIN SHRLGPA B ON B.SHRLGPA_PIDM = A.SGBSTDN_PIDM
    AND B.SHRLGPA_LEVL_CODE = CASE WHEN A.SGBSTDN_LEVL_CODE = 'AC' THEN 'UG' ELSE A.SGBSTDN_LEVL_CODE END
    AND B.SHRLGPA_GPA_TYPE_IND = 'I'
JOIN SHRLGPA C ON C.SHRLGPA_PIDM = A.SGBSTDN_PIDM
    AND C.SHRLGPA_LEVL_CODE = CASE WHEN A.SGBSTDN_LEVL_CODE = 'AC' THEN 'UG' ELSE A.SGBSTDN_LEVL_CODE END
    AND C.SHRLGPA_GPA_TYPE_IND = 'O'
WHERE SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Z.SGBSTDN_TERM_CODE_EFF) FROM SGBSTDN Z
    WHERE Z.SGBSTDN_PIDM = A.SGBSTDN_PIDM
    AND Z.SGBSTDN_TERM_CODE_EFF <= :TERM  
)
AND (
    B.SHRLGPA_GPA_HOURS = 0 or B.SHRLGPA_GPA >= CASE
    WHEN B.SHRLGPA_LEVL_CODE IN ('UG', 'AC') THEN 1.995
    WHEN B.SHRLGPA_LEVL_CODE = 'GR' THEN case a.sgbstdn_degc_code_1 when 'DPT' then 2.695 else 2.995 end
    WHEN B.SHRLGPA_LEVL_CODE = 'PL' THEN 2.095
    END
)
AND C.SHRLGPA_HOURS_EARNED >= (C.SHRLGPA_HOURS_ATTEMPTED * 0.665)
AND A.SGBSTDN_PIDM = :PIDM
-- (select spriden_pidm from spriden where spriden_id = '001493505' and spriden_change_ind is null)
;


SELECT DISTINCT A.SGBSTDN_PIDM
FROM SGBSTDN A 
JOIN SHRLGPA B ON B.SHRLGPA_PIDM = A.SGBSTDN_PIDM
    AND B.SHRLGPA_LEVL_CODE = A.SGBSTDN_LEVL_CODE
    AND B.SHRLGPA_GPA_TYPE_IND = 'I'
JOIN SHRLGPA C ON C.SHRLGPA_PIDM = A.SGBSTDN_PIDM
    AND C.SHRLGPA_LEVL_CODE = A.SGBSTDN_LEVL_CODE
    AND C.SHRLGPA_GPA_TYPE_IND = 'O'
WHERE A.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Z.SGBSTDN_TERM_CODE_EFF) FROM SGBSTDN Z
    WHERE Z.SGBSTDN_PIDM = A.SGBSTDN_PIDM
    AND Z.SGBSTDN_TERM_CODE_EFF <= :TERM   
)
AND A.SGBSTDN_LEVL_CODE = 'UG'
AND (
    (B.SHRLGPA_GPA <= 1.995 AND B.SHRLGPA_GPA_HOURS > 0) 
    OR (C.SHRLGPA_HOURS_EARNED < (C.SHRLGPA_HOURS_ATTEMPTED * 0.665))
)
AND A.SGBSTDN_PIDM = :PIDM   

;

SELECT DISTINCT A.SGBSTDN_PIDM
FROM SGBSTDN A 
JOIN SHRLGPA B ON B.SHRLGPA_PIDM = A.SGBSTDN_PIDM
    AND B.SHRLGPA_LEVL_CODE = A.SGBSTDN_LEVL_CODE
    AND B.SHRLGPA_GPA_TYPE_IND = 'I'
JOIN SHRLGPA C ON C.SHRLGPA_PIDM = A.SGBSTDN_PIDM
    AND C.SHRLGPA_LEVL_CODE = A.SGBSTDN_LEVL_CODE
    AND C.SHRLGPA_GPA_TYPE_IND = 'O'
WHERE A.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Z.SGBSTDN_TERM_CODE_EFF) FROM SGBSTDN Z
    WHERE Z.SGBSTDN_PIDM = A.SGBSTDN_PIDM
    AND Z.SGBSTDN_TERM_CODE_EFF <= :TERM   
)
AND A.SGBSTDN_LEVL_CODE = 'PL'
AND (
    (B.SHRLGPA_GPA <= 2.095 AND B.SHRLGPA_GPA_HOURS > 0) 
    OR (C.SHRLGPA_HOURS_EARNED < (C.SHRLGPA_HOURS_ATTEMPTED * 0.665))
)
-- AND A.SGBSTDN_PIDM = :PIDM
;
