-- PERIOD BASED BUDGETING - 2FEE RULES

-- SPS SEQUENCES ======================================================
-- UG AND GR GET THE SAME 120 OR 60 REGARDLESS OF LEVEL
-- BASED ON PART OF TERM ENROLLMENT
-- sequence 100 - UG PS FULL TERM
-- P1 FOR ACTIVE STUDENTS IS ONLY NECESSARY FOR SPS
SELECT CASE 
    -- BOTH PARTS OF TERM GET FULL
    WHEN ( -- both PS1 AND PS2        
        EXISTS (
            SELECT 'X' FROM SFRSTCR
            WHERE SFRSTCR_PIDM = a.SGBSTDN_PIDM
            AND SFRSTCR_PTRM_CODE = 'PS1'
            AND SFRSTCR_BILL_HR > '0'
        )
        AND EXISTS (
            SELECT 'X' FROM SFRSTCR
            WHERE SFRSTCR_PIDM = a.SGBSTDN_PIDM
            AND SFRSTCR_PTRM_CODE = 'PS2'
            AND SFRSTCR_BILL_HR > '0'
        )
    ) OR EXISTS ( -- ONLY PSF
            SELECT 'X' FROM SFRSTCR
            WHERE SFRSTCR_PIDM = a.SGBSTDN_PIDM
            AND SFRSTCR_PTRM_CODE = 'PSF'
            AND SFRSTCR_BILL_HR > '0'
    ) OR EXISTS ( -- ONLY 1
            SELECT 'X' FROM SFRSTCR
            WHERE SFRSTCR_PIDM = a.SGBSTDN_PIDM
            AND SFRSTCR_PTRM_CODE = '1'
            AND SFRSTCR_BILL_HR > '0'    
    ) THEN RORALGS_AMT
    -- ONLY ONE PART OF TERM GETS HALF
    WHEN EXISTS (
        SELECT 'X' FROM SFRSTCR
        WHERE SFRSTCR_PIDM = a.SGBSTDN_PIDM
        AND SFRSTCR_PTRM_CODE in ('PS1', 'PS2') -- FINDS PS1 OR PS2
        AND SFRSTCR_BILL_HR > '0'
    ) THEN RORALGS_AMT / 2
END
FROM SGBSTDN a, RORALGS
WHERE RORALGS_KEY_1 = 'PBDG' 
AND RORALGS_KEY_4 = '2FEE'
AND CASE 
    WHEN a.SGBSTDN_COLL_CODE_1 = 'PS' then 'PS' 
END = RORALGS_KEY_7
-- sgbstdn term
AND a.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN
    WHERE SGBSTDN_PIDM = a.SGBSTDN_PIDM
    AND SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
-- EXCLUDE GLOBAL GRADS
AND a.SGBSTDN_PIDM NOT IN (
    SELECT SGRSATT_PIDM
    FROM SGRSATT
    WHERE SGRSATT_ATTS_CODE IN ('GG2','GG3','GG4','GG5','GG6')
    AND SGRSATT_TERM_CODE_EFF = (
        SELECT MAX(z.SGRSATT_TERM_CODE_EFF)
        FROM SGRSATT z
        WHERE z.SGRSATT_PIDM = SGRSATT_PIDM
        AND z.SGRSATT_TERM_CODE_EFF <= a.SGBSTDN_TERM_CODE_EFF
    )
)
AND a.SGBSTDN_STST_CODE IN  ('AS','IL','P1') -- P1 only needed for SPS
AND RORALGS_AIDY_CODE = :AIDY
AND a.SGBSTDN_PIDM = :PIDM
-- ;

-- UNDERGRAD NOT PS SEQUENCES ==================================================
-- sequence 200 - UG NOT PS FT
SELECT 
    CASE WHEN 
    NVL(ROKMISC.F_CALC_STUD_CREDIT_HRS(a.SGBSTDN_TERM_CODE_EFF, a.SGBSTDN_PIDM, 'N'), 0) >= 12
    THEN RORALGS_AMT
END
FROM SGBSTDN a, RORALGS
WHERE RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '2FEE'
AND CASE
    WHEN a.SGBSTDN_LEVL_CODE = 'UG' THEN 'UG'
END = RORALGS_KEY_5
AND RORALGS_KEY_12 = 'FT'
-- sgbstdn term
AND a.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN
    WHERE SGBSTDN_PIDM = a.SGBSTDN_PIDM
    AND SGBSTDN_TERM_CODE_EFF <= :PERIOD
)	
AND a.SGBSTDN_STST_CODE IN  ('AS','IL')
AND RORALGS_AIDY_CODE = :AIDY
AND a.SGBSTDN_PIDM = :PIDM
-- ;

-- sequence 210 - UG NOT PS PT (1-11 hours)
SELECT 
    CASE WHEN 
        NVL(ROKMISC.F_CALC_STUD_CREDIT_HRS(a.SGBSTDN_TERM_CODE_EFF, a.SGBSTDN_PIDM, 'N'), 0) >= 1
    THEN RORALGS_AMT
END
FROM SGBSTDN a, RORALGS
WHERE RORALGS_KEY_1 = 'PBDG' 
AND RORALGS_KEY_4 = '2FEE'
AND CASE
    WHEN a.SGBSTDN_LEVL_CODE = 'UG' THEN 'UG'
END = RORALGS_KEY_5
AND RORALGS_KEY_12 = 'PT'
-- sgbstdn term
AND a.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN
    WHERE SGBSTDN_PIDM = a.SGBSTDN_PIDM
    AND SGBSTDN_TERM_CODE_EFF <= :PERIOD
)	
AND a.SGBSTDN_STST_CODE IN  ('AS','IL')
AND RORALGS_AIDY_CODE = :AIDY
AND a.SGBSTDN_PIDM = :PIDM
-- ;

-- sequence 220 - UG NOT PS FT
SELECT RORALGS_AMT
FROM SGBSTDN a, RORALGS
WHERE RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '2FEE'
AND CASE
    WHEN a.SGBSTDN_LEVL_CODE = 'UG' THEN 'UG'
END = RORALGS_KEY_5
AND RORALGS_KEY_12 = 'FT'
-- sgbstdn term
AND a.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN
    WHERE SGBSTDN_PIDM = a.SGBSTDN_PIDM
    AND SGBSTDN_TERM_CODE_EFF <= :PERIOD
)	
AND a.SGBSTDN_STST_CODE IN  ('AS','IL')
AND RORALGS_AIDY_CODE = :AIDY
AND a.SGBSTDN_PIDM = :PIDM
-- ;

-- sequence 230 - UG WITHOUT SGBSTDN
SELECT RORALGS_AMT
FROM SARADAP a
CROSS JOIN RORALGS
INNER JOIN SARAPPD b 
    ON b.SARAPPD_PIDM = a.SARADAP_PIDM
    AND b.SARAPPD_APPL_NO = a.SARADAP_APPL_NO
    AND b.SARAPPD_TERM_CODE_ENTRY = a.SARADAP_TERM_CODE_ENTRY
INNER JOIN STVAPDC c 
    ON c.STVAPDC_CODE = b.SARAPPD_APDC_CODE
    AND c.STVAPDC_INST_ACC_IND = 'Y'
    AND c.STVAPDC_SIGNF_IND = 'Y'
WHERE RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '2FEE'
AND CASE
    WHEN a.SARADAP_LEVL_CODE = 'UG' THEN 'UG'
END = RORALGS_KEY_5
AND RORALGS_KEY_12 = 'FT'
-- sgbstdn term
AND a.SARADAP_TERM_CODE_ENTRY = (
    SELECT MAX(SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP, ROBINST
    WHERE SARADAP_PIDM = a.SARADAP_PIDM
    AND SARADAP_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
	AND SARADAP_TERM_CODE_ENTRY <= :PERIOD
    AND ROBINST_AIDY_CODE = :AIDY
)
--max application decision code sequence number
AND b.SARAPPD_SEQ_NO = (
    SELECT MAX(SARAPPD_SEQ_NO)
    FROM SARAPPD
    WHERE SARAPPD_PIDM = b.SARAPPD_PIDM
    AND SARAPPD_APPL_NO = b.SARAPPD_APPL_NO
    AND SARAPPD_SEQ_NO < 99
    AND SARAPPD_TERM_CODE_ENTRY <= b.SARAPPD_TERM_CODE_ENTRY
)  
AND RORALGS_AIDY_CODE = :AIDY
AND a.SARADAP_PIDM = :PIDM
-- ;

-- GRAD NOT PS SEQUENCES =======================================================
-- sequence 300 - GR NOT PS FT
SELECT 
    CASE WHEN 
        NVL(ROKMISC.F_CALC_STUD_CREDIT_HRS(a.SGBSTDN_TERM_CODE_EFF, a.SGBSTDN_PIDM, 'N'), 0) >= 6
    THEN RORALGS_AMT
END
FROM SGBSTDN a, RORALGS
WHERE RORALGS_KEY_1 = 'PBDG' 
AND RORALGS_KEY_4 = '2FEE'
AND CASE
    WHEN a.SGBSTDN_LEVL_CODE = 'GR' THEN 'GR'
END = RORALGS_KEY_5
AND RORALGS_KEY_12 = 'FT'
-- sgbstdn term
AND a.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN
    WHERE SGBSTDN_PIDM = a.SGBSTDN_PIDM
    AND SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
-- EXCLUDE GLOBAL GRADS
AND a.SGBSTDN_PIDM NOT IN (
    SELECT SGRSATT_PIDM
    FROM SGRSATT
    WHERE SGRSATT_ATTS_CODE IN ('GG2','GG3','GG4','GG5','GG6')
    AND SGRSATT_TERM_CODE_EFF = (
        SELECT MAX(z.SGRSATT_TERM_CODE_EFF)
        FROM SGRSATT z
        WHERE z.SGRSATT_PIDM = SGRSATT_PIDM
        AND z.SGRSATT_TERM_CODE_EFF <= a.SGBSTDN_TERM_CODE_EFF
    )
)
AND a.SGBSTDN_STST_CODE IN  ('AS','IL')
AND RORALGS_AIDY_CODE = :AIDY
AND a.SGBSTDN_PIDM = :PIDM
-- ;

-- sequence 310 - GR NOT PS PT
SELECT 
    CASE WHEN 
        NVL(ROKMISC.F_CALC_STUD_CREDIT_HRS(a.SGBSTDN_TERM_CODE_EFF, a.SGBSTDN_PIDM, 'N'), 0) < 6
        AND NVL(ROKMISC.F_CALC_STUD_CREDIT_HRS(a.SGBSTDN_TERM_CODE_EFF, a.SGBSTDN_PIDM, 'N'), 0) > 0
    THEN RORALGS_AMT
END
FROM SGBSTDN a, RORALGS
WHERE RORALGS_KEY_1 = 'PBDG' 
AND RORALGS_KEY_4 = '2FEE'
AND CASE
    WHEN a.SGBSTDN_LEVL_CODE = 'GR' THEN 'GR'
END = RORALGS_KEY_5
AND RORALGS_KEY_12 = 'PT'
-- sgbstdn term
AND a.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN
    WHERE SGBSTDN_PIDM = a.SGBSTDN_PIDM
    AND SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
-- EXCLUDE GLOBAL GRADS
AND a.SGBSTDN_PIDM NOT IN (
    SELECT SGRSATT_PIDM
    FROM SGRSATT
    WHERE SGRSATT_ATTS_CODE IN ('GG2','GG3','GG4','GG5','GG6')
    AND SGRSATT_TERM_CODE_EFF = (
        SELECT MAX(z.SGRSATT_TERM_CODE_EFF)
        FROM SGRSATT z
        WHERE z.SGRSATT_PIDM = SGRSATT_PIDM
        AND z.SGRSATT_TERM_CODE_EFF <= a.SGBSTDN_TERM_CODE_EFF
    )
)
AND a.SGBSTDN_STST_CODE IN  ('AS','IL')
AND RORALGS_AIDY_CODE = :AIDY
AND a.SGBSTDN_PIDM = :PIDM
-- ;

-- sequence 320 - GR not enrolled
SELECT RORALGS_AMT
FROM SGBSTDN a, RORALGS
WHERE RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '2FEE'
AND CASE
    WHEN a.SGBSTDN_LEVL_CODE = 'GR' THEN 'GR'
END = RORALGS_KEY_5
AND RORALGS_KEY_12 = 'FT'
-- sgbstdn term
AND a.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN
    WHERE SGBSTDN_PIDM = a.SGBSTDN_PIDM
    AND SGBSTDN_TERM_CODE_EFF <= :PERIOD
)	
AND a.SGBSTDN_STST_CODE IN  ('AS','IL')
AND RORALGS_AIDY_CODE = :AIDY
AND a.SGBSTDN_PIDM = :PIDM
-- ;

-- sequence 330 - GR WITHOUT SGBSTDN
SELECT RORALGS_AMT
FROM SARADAP a
CROSS JOIN RORALGS
INNER JOIN SARAPPD b 
    ON b.SARAPPD_PIDM = a.SARADAP_PIDM
    AND b.SARAPPD_APPL_NO = a.SARADAP_APPL_NO
    AND b.SARAPPD_TERM_CODE_ENTRY = a.SARADAP_TERM_CODE_ENTRY
INNER JOIN STVAPDC c 
    ON c.STVAPDC_CODE = b.SARAPPD_APDC_CODE
    AND c.STVAPDC_INST_ACC_IND = 'Y'
    AND c.STVAPDC_SIGNF_IND = 'Y'
WHERE RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '2FEE'
AND CASE
    WHEN a.SARADAP_LEVL_CODE = 'GR' THEN 'GR'
END = RORALGS_KEY_5
AND RORALGS_KEY_12 = 'FT'
-- sgbstdn term
AND a.SARADAP_TERM_CODE_ENTRY = (
    SELECT MAX(SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP, ROBINST
    WHERE SARADAP_PIDM = a.SARADAP_PIDM
    AND SARADAP_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
	AND SARADAP_TERM_CODE_ENTRY <= :PERIOD
    AND ROBINST_AIDY_CODE = :AIDY
)
--max application decision code sequence number
AND b.SARAPPD_SEQ_NO = (
    SELECT MAX(SARAPPD_SEQ_NO)
    FROM SARAPPD
    WHERE SARAPPD_PIDM = b.SARAPPD_PIDM
    AND SARAPPD_APPL_NO = b.SARAPPD_APPL_NO
    AND SARAPPD_SEQ_NO < 99
    AND SARAPPD_TERM_CODE_ENTRY <= b.SARAPPD_TERM_CODE_ENTRY
)  
AND RORALGS_AIDY_CODE = :AIDY
AND a.SARADAP_PIDM = :PIDM
-- ;

-- LAW SEQUENCES ===============================================================
-- sequence 400 - LAW FT
SELECT 
    CASE WHEN 
        NVL(ROKMISC.F_CALC_STUD_CREDIT_HRS(a.SGBSTDN_TERM_CODE_EFF, a.SGBSTDN_PIDM, 'N'), 0) >= 12
    THEN RORALGS_AMT
END
FROM SGBSTDN a, RORALGS
WHERE RORALGS_KEY_1 = 'PBDG' 
AND RORALGS_KEY_4 = '2FEE'
AND CASE
    WHEN a.SGBSTDN_LEVL_CODE = 'PL' THEN 'PL'
END = RORALGS_KEY_5
-- sgbstdn term
AND a.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN
    WHERE SGBSTDN_PIDM = a.SGBSTDN_PIDM
    AND SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND a.SGBSTDN_STST_CODE IN  ('AS','IL')
AND RORALGS_AIDY_CODE = :AIDY
AND a.SGBSTDN_PIDM = :PIDM
-- ;



-- sequence 410 - LAW PT
SELECT 
    CASE WHEN 
        NVL(ROKMISC.F_CALC_STUD_CREDIT_HRS(a.SGBSTDN_TERM_CODE_EFF, a.SGBSTDN_PIDM, 'N'), 0) < 12
        AND NVL(ROKMISC.F_CALC_STUD_CREDIT_HRS(a.SGBSTDN_TERM_CODE_EFF, a.SGBSTDN_PIDM, 'N'), 0) > 0
    THEN RORALGS_AMT
END
FROM SGBSTDN a, RORALGS
WHERE RORALGS_KEY_1 = 'PBDG' 
AND RORALGS_KEY_4 = '2FEE'
AND CASE
    WHEN a.SGBSTDN_LEVL_CODE = 'PL' THEN 'PL'
END = RORALGS_KEY_5
-- sgbstdn term
AND a.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN
    WHERE SGBSTDN_PIDM = a.SGBSTDN_PIDM
    AND SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND a.SGBSTDN_STST_CODE IN  ('AS','IL')
AND RORALGS_AIDY_CODE = :AIDY
AND a.SGBSTDN_PIDM = :PIDM
-- ;


-- sequence 420 - PL not enrolled
SELECT RORALGS_AMT
FROM SGBSTDN a, RORALGS
WHERE RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '2FEE'
AND CASE
    WHEN a.SGBSTDN_LEVL_CODE = 'PL' THEN 'PL'
END = RORALGS_KEY_5
AND RORALGS_KEY_12 = 'FT'
-- sgbstdn term
AND a.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN
    WHERE SGBSTDN_PIDM = a.SGBSTDN_PIDM
    AND SGBSTDN_TERM_CODE_EFF <= :PERIOD
)	
AND a.SGBSTDN_STST_CODE IN  ('AS','IL')
AND RORALGS_AIDY_CODE = :AIDY
AND a.SGBSTDN_PIDM = :PIDM
-- ;

-- sequence 430 - PL WITHOUT SGBSTDN
SELECT RORALGS_AMT
FROM SARADAP a
CROSS JOIN RORALGS
INNER JOIN SARAPPD b 
    ON b.SARAPPD_PIDM = a.SARADAP_PIDM
    AND b.SARAPPD_APPL_NO = a.SARADAP_APPL_NO
    AND b.SARAPPD_TERM_CODE_ENTRY = a.SARADAP_TERM_CODE_ENTRY
INNER JOIN STVAPDC c 
    ON c.STVAPDC_CODE = b.SARAPPD_APDC_CODE
    AND c.STVAPDC_INST_ACC_IND = 'Y'
    AND c.STVAPDC_SIGNF_IND = 'Y'
WHERE RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '2FEE'
AND CASE
    WHEN a.SARADAP_LEVL_CODE = 'PL' THEN 'PL'
END = RORALGS_KEY_5
AND RORALGS_KEY_12 = 'FT'
-- sgbstdn term
AND a.SARADAP_TERM_CODE_ENTRY = (
    SELECT MAX(SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP, ROBINST
    WHERE SARADAP_PIDM = a.SARADAP_PIDM
    AND SARADAP_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
	AND SARADAP_TERM_CODE_ENTRY <= :PERIOD
    AND ROBINST_AIDY_CODE = :AIDY
)
--max application decision code sequence number
AND b.SARAPPD_SEQ_NO = (
    SELECT MAX(SARAPPD_SEQ_NO)
    FROM SARAPPD
    WHERE SARAPPD_PIDM = b.SARAPPD_PIDM
    AND SARAPPD_APPL_NO = b.SARAPPD_APPL_NO
    AND SARAPPD_SEQ_NO < 99
    AND SARAPPD_TERM_CODE_ENTRY <= b.SARAPPD_TERM_CODE_ENTRY
)  
AND RORALGS_AIDY_CODE = :AIDY
AND a.SARADAP_PIDM = :PIDM
-- ;


-- sequence 500 - MED M1
-- M1 (LOOK FOR APPLICATION TO PM WITHIN THE AID YEAR)
SELECT RORALGS_AMT 
    FROM SARADAP X, SARAPPD X, RORALGS, STVAPDC
WHERE	
RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '2FEE' -- budget component
AND CASE -- level code
	WHEN X.SARADAP_LEVL_CODE = 'PM' THEN 'PM'
END = RORALGS_KEY_5
AND RORALGS_KEY_11 = 'M1'
-- max saradap term <= passed period
AND X.SARADAP_TERM_CODE_ENTRY = (
    SELECT MAX(X.SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP Y, ROBINST
    WHERE Y.SARADAP_PIDM = X.SARADAP_PIDM
    AND Y.SARADAP_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')   	
	AND Y.SARADAP_TERM_CODE_ENTRY <= :PERIOD
	AND ROBINST_AIDY_CODE = :AIDY   
)
--max application decision code sequence number
AND X.SARAPPD_SEQ_NO = (
    SELECT MAX (X.SARAPPD_SEQ_NO)
    FROM SARAPPD Y, ROBINST
    WHERE     Y.SARAPPD_PIDM = X.SARAPPD_PIDM
    AND Y.SARAPPD_SEQ_NO < 99
    AND Y.SARAPPD_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
    AND Y.SARAPPD_TERM_CODE_ENTRY <= :PERIOD
    AND ROBINST_AIDY_CODE = :AIDY           
    AND X.SARADAP_APPL_NO = Y.SARAPPD_APPL_NO
)  
AND STVAPDC_INST_ACC_IND = 'Y'
AND STVAPDC_SIGNF_IND = 'Y'
AND X.SARAPPD_APDC_CODE = STVAPDC_CODE	
AND X.SARADAP_APPL_NO = X.SARAPPD_APPL_NO
AND X.SARADAP_TERM_CODE_ENTRY = X.SARAPPD_TERM_CODE_ENTRY
AND RORALGS_AIDY_CODE = :AIDY
AND X.SARAPPD_PIDM = X.SARADAP_PIDM	
AND X.SARADAP_PIDM = :PIDM

-- sequence 510 - MED M2-4
WITH med_cohort AS (
    SELECT 
        ROBINST_AIDY_END_YEAR || 'MD' as "M4",
        ROBINST_AIDY_END_YEAR + 1 || 'MD' as "M3",
        ROBINST_AIDY_END_YEAR + 2 || 'MD' as "M2"
    FROM ROBINST
    WHERE ROBINST_AIDY_CODE = :AIDY
)
SELECT RORALGS_AMT
FROM SGBSTDN a
CROSS JOIN RORALGS
CROSS JOIN med_cohort -- table derived from with statement above
INNER JOIN ( -- find cohort codes matching those defined above in med_cohort
    SELECT SGRCHRT_PIDM, SGRCHRT_TERM_CODE_EFF, SGRCHRT_CHRT_CODE
    FROM SGRCHRT
    WHERE SGRCHRT_CHRT_CODE in (
        SELECT M4 FROM med_cohort UNION 
        SELECT M3 FROM med_cohort UNION 
        SELECT M2 FROM med_cohort
    )
) b ON b.SGRCHRT_PIDM = a.SGBSTDN_PIDM
    AND b.SGRCHRT_TERM_CODE_EFF = (
        SELECT MAX(z.SGRCHRT_TERM_CODE_EFF)
        FROM SGRCHRT z
        WHERE z.SGRCHRT_CHRT_CODE in (
            SELECT M4 FROM med_cohort UNION 
            SELECT M3 FROM med_cohort UNION 
            SELECT M2 FROM med_cohort
        )
    )
INNER JOIN RORSTAT on RORSTAT_PIDM = a.SGBSTDN_PIDM and RORSTAT_AIDY_CODE = :AIDY
WHERE a.SGBSTDN_STST_CODE IN  ('AS','IL')
AND a.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN
    WHERE SGBSTDN_PIDM = a.SGBSTDN_PIDM
    AND SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND RORALGS_KEY_1 = 'PBDG' 
AND RORALGS_KEY_4 = '2FEE'
AND CASE
    WHEN a.SGBSTDN_LEVL_CODE = 'PM' THEN 'PM'
END = RORALGS_KEY_5
AND CASE
    WHEN b.SGRCHRT_CHRT_CODE = (SELECT M4 FROM med_cohort) THEN 'M4'
    WHEN b.SGRCHRT_CHRT_CODE = (SELECT M3 FROM med_cohort) THEN 'M3'
    WHEN b.SGRCHRT_CHRT_CODE = (SELECT M2 FROM med_cohort) THEN 'M2'
END = RORALGS_KEY_11
AND a.SGBSTDN_STST_CODE IN  ('AS','IL')
AND a.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY

-- ;