
--UG NOT ENROLLED WITH SGASTDN 
SELECT RORALGS_AMT
FROM SGBSTDN X, RORALGS
WHERE RORALGS_KEY_1 = 'PBDG'

AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
    WHEN X.SGBSTDN_LEVL_CODE = 'UG' THEN 'UG'
END = RORALGS_KEY_5

AND CASE -- campus code
    WHEN X.SGBSTDN_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
AND RORALGS_KEY_10 IS NULL
AND RORALGS_KEY_12 = '12TO18'

-- max sgbstdn term <= passed period
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND NOT EXISTS (
    SELECT 1
    FROM SARADAP
    INNER JOIN SARAPPD
        ON SARAPPD_PIDM = SARADAP_PIDM
        AND SARAPPD_APPL_NO = SARADAP_APPL_NO
        AND SARAPPD_TERM_CODE_ENTRY = SARADAP_TERM_CODE_ENTRY
    INNER JOIN STVAPDC
        ON STVAPDC_CODE = SARAPPD_APDC_CODE
        AND STVAPDC_INST_ACC_IND = 'Y'
        AND STVAPDC_SIGNF_IND = 'Y'
    WHERE SARADAP_PIDM = X.SGBSTDN_PIDM
    AND SARADAP_TERM_CODE_ENTRY > X.SGBSTDN_TERM_CODE_EFF 
    AND SARADAP_TERM_CODE_ENTRY <= ('20' || cast(substr(:AIDY, 2, 2) as int) + 1 || '00')
    AND SARADAP_PROGRAM_1 <> X.SGBSTDN_PROGRAM_1
)
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
--AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
-- END
;


--UG ENROLLED 19+ HOURS 
with stu as (
    select 
        x.sgbstdn_pidm as pidm, 
        x.sgbstdn_levl_code as levl,
        x.sgbstdn_camp_code as camp,
        ROKMISC.F_CALC_STUD_BILL_HRS(:period, x.sgbstdn_pidm, 'N') as hrs
    from sgbstdn x
    where X.SGBSTDN_LEVL_CODE = 'UG'
    AND X.SGBSTDN_CAMP_CODE = 'FR' 
    AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
    -- max sgbstdn term <= passed period
    AND X.SGBSTDN_TERM_CODE_EFF = (
        SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
        FROM SGBSTDN Y
        WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
        AND Y.SGBSTDN_TERM_CODE_EFF <= :period
    )
)
SELECT round(roralgs_amt + (stu.hrs - 18) * roralgs_comment_12) as calc_amt
--need to add text to RORALGS_COMMENT SAYING DO NOT CHANGE TEXT IN RORALGS_COMMENT_12 BECASUE IT'S USED IN THE ALGO CALC
--VALUE TO ADD TO ADD TO RORALGS_COMMENT_12 IS OVERLOAD RATE, ALL NUMERIC, WOULD BE 1830 BASED ON FY2024 RATE
from stu
inner join sfs_utility.pbdg_cutoff_dates on period = :period and sysdate >= cutoff
inner join RORALGS on RORALGS_AIDY_CODE = :AIDY
    and RORALGS_KEY_1 = 'PBDG'
    and RORALGS_KEY_4 = '1TUI'
    and RORALGS_KEY_5 = stu.levl
    and RORALGS_KEY_6 = stu.camp
    and RORALGS_KEY_10 IS NULL
    and RORALGS_KEY_12 = '19+'
where stu.hrs > 18


--AND X.SGBSTDN_PIDM = :PIDM
-- END
;
select * from sfs_utility.pbdg_cutoff_dates;


--UG ENROLLED 19+ HOURS 
SELECT CASE
    WHEN NVL(ROKMISC.F_CALC_STUD_BILL_HRS(:PERIOD, X.SGBSTDN_PIDM, 'N'), 0) > 18
        THEN round(roralgs_amt + ((NVL(ROKMISC.F_CALC_STUD_BILL_HRS(:PERIOD, X.SGBSTDN_PIDM, 'N'), 0) - 18) * roralgs_comment_12)) 
    END as calc_amt
--need to add text to RORALGS_COMMENT SAYING DO NOT CHANGE TEXT IN RORALGS_COMMENT_12 BECASUE IT'S USED IN THE ALGO CALC
--VALUE TO ADD TO ADD TO RORALGS_COMMENT_12 IS OVERLOAD RATE, ALL NUMERIC, WOULD BE 1830 BASED ON FY2024 RATE
	FROM SGBSTDN X, RORALGS
    inner join sfs_utility.pbdg_cutoff_dates on period = :PERIOD and sysdate >= cutoff
WHERE RORALGS_KEY_1 = 'PBDG'

AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
    WHEN X.SGBSTDN_LEVL_CODE = 'UG' THEN 'UG'
END = RORALGS_KEY_5

AND CASE -- campus code
    WHEN X.SGBSTDN_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
AND RORALGS_KEY_10 IS NULL
AND RORALGS_KEY_12 = '19+'

-- max sgbstdn term <= passed period
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
--AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
-- END
;


--UG PS COLLEGE ENROLLED 
SELECT (roralgs_amt * NVL(ROKMISC.F_CALC_STUD_BILL_HRS(:PERIOD, X.SGBSTDN_PIDM, 'N'), 0))
FROM SGBSTDN X, RORALGS
inner join sfs_utility.pbdg_cutoff_dates on period = :PERIOD and sysdate <= cutoff
WHERE RORALGS_KEY_1 = 'PBDG'

AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
    WHEN X.SGBSTDN_LEVL_CODE = 'UG' THEN 'UG'
END = RORALGS_KEY_5

AND CASE -- campus code
    WHEN X.SGBSTDN_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6

AND CASE -- college code
    WHEN X.SGBSTDN_COLL_CODE_1 = 'PS' THEN 'PS'
END = RORALGS_KEY_7

AND RORALGS_KEY_9 IS NULL
AND RORALGS_KEY_11 IS NULL

-- max sgbstdn term <= passed period
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
--AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
-- END

;


--UG PS COLLEGE NOT ENROLLED WITH SGASTDN 
SELECT (roralgs_amt * 12)
FROM SGBSTDN X, RORALGS
WHERE RORALGS_KEY_1 = 'PBDG'

AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
    WHEN X.SGBSTDN_LEVL_CODE = 'UG' THEN 'UG'
END = RORALGS_KEY_5

AND CASE -- campus code
    WHEN X.SGBSTDN_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6

AND CASE -- college code
    WHEN X.SGBSTDN_COLL_CODE_1 = 'PS' THEN 'PS'
END = RORALGS_KEY_7

AND RORALGS_KEY_9 IS NULL
AND RORALGS_KEY_11 IS NULL

-- max sgbstdn term <= passed period
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND NOT EXISTS (
    SELECT 1
    FROM SARADAP
    INNER JOIN SARAPPD
        ON SARAPPD_PIDM = SARADAP_PIDM
        AND SARAPPD_APPL_NO = SARADAP_APPL_NO
        AND SARAPPD_TERM_CODE_ENTRY = SARADAP_TERM_CODE_ENTRY
    INNER JOIN STVAPDC
        ON STVAPDC_CODE = SARAPPD_APDC_CODE
        AND STVAPDC_INST_ACC_IND = 'Y'
        AND STVAPDC_SIGNF_IND = 'Y'
    WHERE SARADAP_PIDM = X.SGBSTDN_PIDM
    AND SARADAP_TERM_CODE_ENTRY > X.SGBSTDN_TERM_CODE_EFF 
    AND SARADAP_TERM_CODE_ENTRY <= ('20' || cast(substr(:AIDY, 2, 2) as int) + 1 || '00')
    AND SARADAP_PROGRAM_1 <> X.SGBSTDN_PROGRAM_1
)
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
--AND X.SGBSTDN_PIDM = :PIDM

AND X.SGBSTDN_PIDM = (select spriden_pidm from spriden where spriden_id = '001394715' and spriden_change_ind is null)
AND RORALGS_AIDY_CODE = :AIDY
-- END

