-- refactor 7BS to consider enrollment

-- sequence 2: SGBSTDN SEQUENCE
SELECT case
	when (
            (a.SGBSTDN_LEVL_CODE = 'PL' and a.SGBSTDN_FULL_PART_IND = 'P')
            or (
                sysdate >= (select cutoff from sfs_utility.pbdg_cutoff_dates where period = :PERIOD) and (
                    (
                        a.SGBSTDN_LEVL_CODE = 'UG' 
                        and rokmisc.F_CALC_STUD_BILL_HRS(:PERIOD, a.SGBSTDN_PIDM, 'N') < 12
                    ) or (
                        a.SGBSTDN_LEVL_CODE = 'GR' 
                        and rokmisc.F_CALC_STUD_BILL_HRS(:PERIOD, a.SGBSTDN_PIDM, 'N') < 6
                    )
                )
            ) 
        ) then (RORALGS_AMT / 2)

	else RORALGS_AMT
end as amt
FROM SGBSTDN a
INNER JOIN RORALGS on RORALGS_AIDY_CODE = :AIDY
    AND RORALGS_KEY_1 = 'PBDG'
    AND RORALGS_KEY_4 = '7BS'
    AND RORALGS_KEY_5 = a.SGBSTDN_LEVL_CODE
WHERE a.SGBSTDN_LEVL_CODE in ('UG', 'GR', 'PL', 'PM')
and a.SGBSTDN_STST_CODE in ('AS', 'IL')
AND a.SGBSTDN_PIDM = :PIDM
AND a.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN
    WHERE SGBSTDN_PIDM = a.SGBSTDN_PIDM
    AND SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND NOT EXISTS (
    SELECT 1
    FROM SARADAP
    INNER JOIN SARAPPD
        ON SARAPPD_PIDM = SARADAP_PIDM
        AND SARAPPD_APPL_NO = SARADAP_APPL_NO
        AND SARAPPD_TERM_CODE_ENTRY = SARADAP_TERM_CODE_ENTRY
    INNER JOIN STVAPDC
        ON STVAPDC_CODE = SARAPPD_APDC_CODE
        AND STVAPDC_INST_ACC_IND = 'Y'
        AND STVAPDC_SIGNF_IND = 'Y'
    WHERE SARADAP_PIDM = a.SGBSTDN_PIDM
    AND SARADAP_TERM_CODE_ENTRY > a.SGBSTDN_TERM_CODE_EFF 
    AND SARADAP_TERM_CODE_ENTRY <= ('20' || cast(substr(:AIDY, 2, 2) as int) + 1 || '00')
    AND SARADAP_PROGRAM_1 <> a.SGBSTDN_PROGRAM_1
);

-- sequence 3: SARADAP SEQUENCE
SELECT case
	when (a.SARADAP_FULL_PART_IND = 'P' and a.SARADAP_LEVL_CODE = 'PL') then (RORALGS_AMT / 2)
	else RORALGS_AMT
end
FROM SARADAP a
INNER JOIN RORALGS ON RORALGS_AIDY_CODE = :AIDY
    AND RORALGS_KEY_1 = 'PBDG'
    AND RORALGS_KEY_4 = '7BS'
    AND RORALGS_KEY_5 = a.SARADAP_LEVL_CODE
INNER JOIN SARAPPD b 
    ON b.SARAPPD_PIDM = a.SARADAP_PIDM
    AND b.SARAPPD_APPL_NO = a.SARADAP_APPL_NO
    AND b.SARAPPD_TERM_CODE_ENTRY = a.SARADAP_TERM_CODE_ENTRY
INNER JOIN STVAPDC c 
    ON c.STVAPDC_CODE = b.SARAPPD_APDC_CODE
    AND c.STVAPDC_INST_ACC_IND = 'Y'
    AND c.STVAPDC_SIGNF_IND = 'Y'
WHERE a.SARADAP_LEVL_CODE in ('UG', 'GR', 'PL', 'PM')
-- sgbstdn term
AND a.SARADAP_TERM_CODE_ENTRY = (
    SELECT MAX(SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP, ROBINST
    WHERE SARADAP_PIDM = a.SARADAP_PIDM
    AND SARADAP_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
	AND SARADAP_TERM_CODE_ENTRY <= :PERIOD
    AND ROBINST_AIDY_CODE = :AIDY
)
--max application decision code sequence number
AND b.SARAPPD_SEQ_NO = (
    SELECT MAX(SARAPPD_SEQ_NO)
    FROM SARAPPD
    WHERE SARAPPD_PIDM = b.SARAPPD_PIDM
    AND SARAPPD_APPL_NO = b.SARAPPD_APPL_NO
    AND SARAPPD_SEQ_NO < 99
    AND SARAPPD_TERM_CODE_ENTRY = b.SARAPPD_TERM_CODE_ENTRY
)  
;
-- AND a.SARADAP_PIDM = :PIDM
-- ;
