SELECT DISTINCT A.RORSTAT_PIDM
FROM RORSTAT A, ROBINST R, RORPRST B, ROBNYUD C, SARADAP D, RCRAPP1 R1, 
    RCRAPP2 R2, RCRAPP3 R3,RCRAPP4 R4, RCVEDEA RC, RORPRST RP
WHERE R.ROBINST_AIDY_CODE = A.RORSTAT_AIDY_CODE
AND A.RORSTAT_AIDY_CODE = :AIDY  
AND A.RORSTAT_PIDM = :PIDM  
AND B.RORPRST_PIDM = A.RORSTAT_PIDM
AND C.ROBNYUD_PIDM = A.RORSTAT_PIDM
AND D.SARADAP_PIDM = A.RORSTAT_PIDM
AND R1.RCRAPP1_PIDM = A.RORSTAT_PIDM 
AND R1.RCRAPP1_AIDY_CODE = A.RORSTAT_AIDY_CODE
AND R2.RCRAPP2_PIDM = R1.RCRAPP1_PIDM 
AND R2.RCRAPP2_INFC_CODE = R1.RCRAPP1_INFC_CODE
AND R2.RCRAPP2_AIDY_CODE = R1.RCRAPP1_AIDY_CODE
AND R2.RCRAPP2_SEQ_NO = R1.RCRAPP1_SEQ_NO
AND R3.RCRAPP3_PIDM = R1.RCRAPP1_PIDM 
AND R3.RCRAPP3_INFC_CODE = R1.RCRAPP1_INFC_CODE
AND R3.RCRAPP3_AIDY_CODE = R1.RCRAPP1_AIDY_CODE
AND R3.RCRAPP3_SEQ_NO = R1.RCRAPP1_SEQ_NO   
AND R4.RCRAPP4_PIDM = R1.RCRAPP1_PIDM 
AND R4.RCRAPP4_INFC_CODE = R1.RCRAPP1_INFC_CODE
AND R4.RCRAPP4_AIDY_CODE = R1.RCRAPP1_AIDY_CODE
AND R4.RCRAPP4_SEQ_NO = R1.RCRAPP1_SEQ_NO
AND RC.RCVEDEA_PIDM = R1.RCRAPP1_PIDM 
AND RC.RCVEDEA_INFC_CODE = R1.RCRAPP1_INFC_CODE
AND RC.RCVEDEA_AIDY_CODE = R1.RCRAPP1_AIDY_CODE
AND RC.RCVEDEA_SEQ_NO = R1.RCRAPP1_SEQ_NO
AND RP.RORPRST_PIDM = A.RORSTAT_PIDM(+)
AND RP.RORPRST_PERIOD = D.SARADAP_TERM_CODE_ENTRY(+)
AND (RP.RORPRST_XHS <> 1 OR RP.RORPRST_XHS IS NULL)
AND R1.RCRAPP1_CURR_REC_IND = 'Y'
AND R1.RCRAPP1_INFC_CODE = 'EDE'
AND R1.RCRAPP1_DEGREE_BY_JULY = 2
AND R3.RCRAPP3_OFFL_UNOFFL_IND = 1
AND D.SARADAP_STYP_CODE IN ('F', '1')
AND C.ROBNYUD_VALUE_29 >= 3.0
AND D.SARADAP_TERM_CODE_ENTRY = (
    SELECT MAX(Z.SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP Z
    WHERE Z.SARADAP_PIDM = D.SARADAP_PIDM
    AND Z.SARADAP_TERM_CODE_ENTRY BETWEEN (R.ROBINST_AIDY_END_YEAR || '00') 
        AND (R.ROBINST_AIDY_END_YEAR || '20')
)
AND CASE -- AGI/INCOME < 60,000
    WHEN R2.RCRAPP2_MODEL_CDE = 'D' 
        THEN CASE 
            WHEN (NVL(RC.RCVEDEA_FTI_PAR_AGI, 0) + NVL(RC.RCVEDEA_FTI_PSP_AGI, 0)) = 0 
                THEN (NVL(R1.RCRAPP1_PAR_US_INC, 0) + NVL(RC.RCVEDEA_PSP_US_INC, 0))
            ELSE (NVL(RC.RCVEDEA_FTI_PAR_AGI, 0) + NVL(RC.RCVEDEA_FTI_PSP_AGI, 0))
        END
    WHEN R2.RCRAPP2_MODEL_CDE = 'I'
        THEN CASE
            WHEN (NVL(RC.RCVEDEA_FTI_AGI, 0) + NVL(RC.RCVEDEA_FTI_SPS_AGI, 0)) = 0 
                THEN (NVL(R1.RCRAPP1_US_INC, 0)  + NVL(RC.RCVEDEA_SPS_US_INC, 0))
            ELSE (NVL(RC.RCVEDEA_FTI_AGI, 0) + NVL(RC.RCVEDEA_FTI_SPS_AGI, 0))
        END
END <= 60000
AND CASE -- CASH/INVESTMENT/ASSETS < 50,000
    WHEN R2.RCRAPP2_MODEL_CDE = 'D' 
        THEN (
            NVL(R1.RCRAPP1_PAR_CASH_AMT, 0) 
            + NVL(R4.RCRAPP4_PAR_INV_NET_WORTH, 0) 
            + NVL(R4.RCRAPP4_PAR_BUS_NET_WORTH, 0)
        )
    WHEN R2.RCRAPP2_MODEL_CDE = 'I'
        THEN (
            NVL(R1.RCRAPP1_CASH_AMT, 0) 
            + NVL(R4.RCRAPP4_INV_NET_WORTH, 0) 
            + NVL(R4.RCRAPP4_BUS_NET_WORTH, 0)
        )
END <= 50000

; -- ;;;;;;;;;;;



SELECT DISTINCT A.RORSTAT_PIDM
FROM RORSTAT A, ROBINST R, RORPRST B, ROBNYUD C, SARADAP D, RCRAPP1 R1, 
    RCRAPP2 R2, RCRAPP3 R3,RCRAPP4 R4, RCVEDEA RC, RORPRST RP, spriden s
WHERE R.ROBINST_AIDY_CODE = A.RORSTAT_AIDY_CODE
and s.spriden_pidm = a.rorstat_pidm
and s.spriden_change_ind is null
AND A.RORSTAT_AIDY_CODE = :AIDY  
-- AND A.RORSTAT_PIDM = :PIDM  
AND B.RORPRST_PIDM = A.RORSTAT_PIDM
AND C.ROBNYUD_PIDM = A.RORSTAT_PIDM
AND D.SARADAP_PIDM = A.RORSTAT_PIDM
AND R1.RCRAPP1_PIDM = A.RORSTAT_PIDM 
AND R1.RCRAPP1_AIDY_CODE = A.RORSTAT_AIDY_CODE
AND R2.RCRAPP2_PIDM = R1.RCRAPP1_PIDM 
AND R2.RCRAPP2_INFC_CODE = R1.RCRAPP1_INFC_CODE
AND R2.RCRAPP2_AIDY_CODE = R1.RCRAPP1_AIDY_CODE
AND R2.RCRAPP2_SEQ_NO = R1.RCRAPP1_SEQ_NO
AND R3.RCRAPP3_PIDM = R1.RCRAPP1_PIDM 
AND R3.RCRAPP3_INFC_CODE = R1.RCRAPP1_INFC_CODE
AND R3.RCRAPP3_AIDY_CODE = R1.RCRAPP1_AIDY_CODE
AND R3.RCRAPP3_SEQ_NO = R1.RCRAPP1_SEQ_NO   
AND R4.RCRAPP4_PIDM = R1.RCRAPP1_PIDM 
AND R4.RCRAPP4_INFC_CODE = R1.RCRAPP1_INFC_CODE
AND R4.RCRAPP4_AIDY_CODE = R1.RCRAPP1_AIDY_CODE
AND R4.RCRAPP4_SEQ_NO = R1.RCRAPP1_SEQ_NO
AND RC.RCVEDEA_PIDM = R1.RCRAPP1_PIDM 
AND RC.RCVEDEA_INFC_CODE = R1.RCRAPP1_INFC_CODE
AND RC.RCVEDEA_AIDY_CODE = R1.RCRAPP1_AIDY_CODE
AND RC.RCVEDEA_SEQ_NO = R1.RCRAPP1_SEQ_NO
AND RP.RORPRST_PIDM = A.RORSTAT_PIDM(+)
AND RP.RORPRST_PERIOD = D.SARADAP_TERM_CODE_ENTRY(+)
AND (RP.RORPRST_XHS <> 1 OR RP.RORPRST_XHS IS NULL)
AND R1.RCRAPP1_CURR_REC_IND = 'Y'
AND R1.RCRAPP1_INFC_CODE = 'EDE'
AND R1.RCRAPP1_DEGREE_BY_JULY = 2
AND R3.RCRAPP3_OFFL_UNOFFL_IND = 1
AND D.SARADAP_STYP_CODE IN ('F', '1')
AND C.ROBNYUD_VALUE_29 >= 3.0
AND D.SARADAP_TERM_CODE_ENTRY = (
    SELECT MAX(Z.SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP Z
    WHERE Z.SARADAP_PIDM = D.SARADAP_PIDM
    AND Z.SARADAP_TERM_CODE_ENTRY BETWEEN (R.ROBINST_AIDY_END_YEAR || '00') 
        AND (R.ROBINST_AIDY_END_YEAR || '20')
)
AND NVL(NVL(RC.RCVEDEA_FTI_PSP_AGI, RC.RCVEDEA_PSP_US_INC), 0) <= 60000
AND CASE -- AGI/INCOME < 60,000
    WHEN R2.RCRAPP2_MODEL_CDE = 'D' 
        THEN NVL(NVL(RC.RCVEDEA_FTI_PAR_AGI, R1.RCRAPP1_PAR_US_INC), 0)
           + NVL(NVL(RC.RCVEDEA_FTI_PSP_AGI, RC.RCVEDEA_PSP_US_INC), 0)
    WHEN R2.RCRAPP2_MODEL_CDE = 'I'
        THEN NVL(NVL(RC.RCVEDEA_FTI_AGI, R1.RCRAPP1_US_INC), 0) 
           + NVL(NVL(RC.RCVEDEA_FTI_SPS_AGI, RC.RCVEDEA_SPS_US_INC), 0)
END <= 60000
AND CASE -- CASH/INVESTMENT/ASSETS < 50,000
    WHEN R2.RCRAPP2_MODEL_CDE = 'D' 
        THEN (
            NVL(R1.RCRAPP1_PAR_CASH_AMT, 0) 
            + NVL(R4.RCRAPP4_PAR_INV_NET_WORTH, 0) 
            + NVL(R4.RCRAPP4_PAR_BUS_NET_WORTH, 0)
        )
    WHEN R2.RCRAPP2_MODEL_CDE = 'I'
        THEN (
            NVL(R1.RCRAPP1_CASH_AMT, 0) 
            + NVL(R4.RCRAPP4_INV_NET_WORTH, 0) 
            + NVL(R4.RCRAPP4_BUS_NET_WORTH, 0)
        )
END <= 50000
-- and s.spriden_id = '001497702'