-- TRAN rule

-- sequence 100 - UG, GR, LAW WITH SGBSTDN RECORD
SELECT RORALGS_AMT
FROM SGBSTDN a, RORALGS
WHERE a.SGBSTDN_STST_CODE IN  ('AS','IL')
AND a.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN
    WHERE SGBSTDN_PIDM = a.SGBSTDN_PIDM
    AND SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND RORALGS_KEY_1 = 'PBDG' 
AND RORALGS_KEY_4 = '8TRS'
AND CASE
    WHEN a.SGBSTDN_LEVL_CODE = 'UG' THEN 'UG'
    WHEN a.SGBSTDN_LEVL_CODE = 'GR' THEN 'GR'
    WHEN a.SGBSTDN_LEVL_CODE = 'PL' THEN 'PL'
    WHEN a.SGBSTDN_LEVL_CODE = 'PM' THEN 'PM'
END = RORALGS_KEY_5
AND a.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY

-- sequence 110 - UG, GR, LAW WITHOUT SGBSTDN RECORD
SELECT RORALGS_AMT 
    FROM SARADAP a, SARAPPD b, STVAPDC c, RORALGS
WHERE RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '8TRS' -- budget component
AND CASE -- level code
    WHEN a.SARADAP_LEVL_CODE = 'UG' THEN 'UG'
    WHEN a.SARADAP_LEVL_CODE = 'GR' THEN 'GR'
    WHEN a.SARADAP_LEVL_CODE = 'PL' THEN 'PL'
    WHEN a.SARADAP_LEVL_CODE = 'PM' THEN 'PM'
END = RORALGS_KEY_5
-- max saradap term <= passed period
AND a.SARADAP_TERM_CODE_ENTRY = (
    SELECT MAX(SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP, ROBINST
    WHERE SARADAP_PIDM = a.SARADAP_PIDM
    AND SARADAP_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')   	
	AND SARADAP_TERM_CODE_ENTRY <= :PERIOD
	AND ROBINST_AIDY_CODE = :AIDY   
)
--max application decision code sequence number
AND b.SARAPPD_SEQ_NO = (
    SELECT MAX (SARAPPD_SEQ_NO)
    FROM SARAPPD, ROBINST
    WHERE SARAPPD_PIDM = b.SARAPPD_PIDM
    AND SARAPPD_SEQ_NO < 99
    AND SARAPPD_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
    AND SARAPPD_TERM_CODE_ENTRY <= :PERIOD
    AND ROBINST_AIDY_CODE = :AIDY           
    AND SARADAP_APPL_NO = b.SARAPPD_APPL_NO
)  
AND c.STVAPDC_INST_ACC_IND = 'Y'
AND c.STVAPDC_SIGNF_IND = 'Y'
AND b.SARAPPD_APDC_CODE = c.STVAPDC_CODE	
AND a.SARADAP_APPL_NO = b.SARAPPD_APPL_NO
AND a.SARADAP_TERM_CODE_ENTRY = b.SARAPPD_TERM_CODE_ENTRY
AND RORALGS_AIDY_CODE = :AIDY
AND b.SARAPPD_PIDM = a.SARADAP_PIDM	
AND a.SARADAP_PIDM = :PIDM