

SELECT DISTINCT a.RORSTAT_PIDM
FROM RORSTAT a, ROBINST r, RORPRST b, ROBNYUD c, SARADAP d, RCRAPP1 r1, 
    RCRAPP2 r2, RCRAPP3 r3,RCRAPP4 r4, RCVEDEA rc
WHERE r.ROBINST_AIDY_CODE = a.RORSTAT_AIDY_CODE
AND a.RORSTAT_AIDY_CODE = :AIDY
AND a.RORSTAT_PIDM = :PIDM
AND b.RORPRST_PIDM = a.RORSTAT_PIDM
AND c.ROBNYUD_PIDM = a.RORSTAT_PIDM
AND d.SARADAP_PIDM = a.RORSTAT_PIDM
AND r1.RCRAPP1_PIDM = a.RORSTAT_PIDM 
AND r1.RCRAPP1_AIDY_CODE = a.RORSTAT_AIDY_CODE
AND r2.RCRAPP2_PIDM = r1.RCRAPP1_PIDM 
AND r2.RCRAPP2_INFC_CODE = r1.RCRAPP1_INFC_CODE
AND r2.RCRAPP2_AIDY_CODE = r1.RCRAPP1_AIDY_CODE
AND r2.RCRAPP2_SEQ_NO = r1.RCRAPP1_SEQ_NO
AND r3.RCRAPP3_PIDM = r1.RCRAPP1_PIDM 
AND r3.RCRAPP3_INFC_CODE = r1.RCRAPP1_INFC_CODE
AND r3.RCRAPP3_AIDY_CODE = r1.RCRAPP1_AIDY_CODE
AND r3.RCRAPP3_SEQ_NO = r1.RCRAPP1_SEQ_NO   
AND r4.RCRAPP4_PIDM = r1.RCRAPP1_PIDM 
AND r4.RCRAPP4_INFC_CODE = r1.RCRAPP1_INFC_CODE
AND r4.RCRAPP4_AIDY_CODE = r1.RCRAPP1_AIDY_CODE
AND r4.RCRAPP4_SEQ_NO = r1.RCRAPP1_SEQ_NO
AND rc.RCVEDEA_PIDM = r1.RCRAPP1_PIDM 
AND rc.RCVEDEA_INFC_CODE = r1.RCRAPP1_INFC_CODE
AND rc.RCVEDEA_AIDY_CODE = r1.RCRAPP1_AIDY_CODE
AND rc.RCVEDEA_SEQ_NO = r1.RCRAPP1_SEQ_NO
AND r1.RCRAPP1_CURR_REC_IND = 'Y'
AND r1.RCRAPP1_INFC_CODE = 'EDE'
AND r1.RCRAPP1_DEGREE_BY_JULY = 2
AND r3.RCRAPP3_OFFL_UNOFFL_IND = 1
AND d.SARADAP_STYP_CODE in ('F', '1')
AND c.ROBNYUD_VALUE_29 >= 3.0
AND d.SARADAP_TERM_CODE_ENTRY = (
    SELECT MAX(z.SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP z
    WHERE z.SARADAP_PIDM = d.SARADAP_PIDM
    AND z.SARADAP_TERM_CODE_ENTRY BETWEEN (r.ROBINST_AIDY_END_YEAR || '00') 
        AND (r.ROBINST_AIDY_END_YEAR || '20')
)
AND CASE -- AGI/income < 60,000
    WHEN r2.RCRAPP2_MODEL_CDE = 'D' 
        THEN CASE 
            WHEN (NVL(rc.RCVEDEA_FTI_PAR_AGI, 0) + NVL(rc.RCVEDEA_FTI_PSP_AGI, 0)) = 0 
                THEN (NVL(r1.RCRAPP1_PAR_US_INC, 0) + NVL(rc.RCVEDEA_PSP_US_INC, 0))
            ELSE (NVL(rc.RCVEDEA_FTI_PAR_AGI, 0) + NVL(rc.RCVEDEA_FTI_PSP_AGI, 0))
        END
    WHEN r2.RCRAPP2_MODEL_CDE = 'I'
        THEN CASE
            WHEN (NVL(rc.RCVEDEA_FTI_AGI, 0) + NVL(rc.RCVEDEA_FTI_SPS_AGI, 0)) = 0 
                THEN (NVL(r1.RCRAPP1_US_INC, 0)  + NVL(rc.RCVEDEA_SPS_US_INC, 0))
            ELSE (NVL(rc.RCVEDEA_FTI_AGI, 0) + NVL(rc.RCVEDEA_FTI_SPS_AGI, 0))
        END
END <= 60000
AND CASE -- Cash/investment/assets < 50,000
    WHEN r2.RCRAPP2_MODEL_CDE = 'D' 
        THEN (
            NVL(r1.RCRAPP1_PAR_CASH_AMT, 0) 
            + NVL(r4.RCRAPP4_PAR_INV_NET_WORTH, 0) 
            + NVL(r4.RCRAPP4_PAR_BUS_NET_WORTH, 0)
        )
    WHEN r2.RCRAPP2_MODEL_CDE = 'I'
        THEN (
            NVL(r1.RCRAPP1_CASH_AMT, 0) 
            + NVL(r4.RCRAPP4_INV_NET_WORTH, 0) 
            + NVL(r4.RCRAPP4_BUS_NET_WORTH, 0)
        )
END <= 50000

-- AND a.RORSTAT_PIDM = :PIDM

;

