-- TESTING QUERY FOR M2 M3 M4
WITH med_cohort AS (
    SELECT 
        ROBINST_AIDY_END_YEAR || 'MD' as "M4",
        ROBINST_AIDY_END_YEAR + 1 || 'MD' as "M3",
        ROBINST_AIDY_END_YEAR + 2 || 'MD' as "M2"
    FROM ROBINST
    WHERE ROBINST_AIDY_CODE = :AIDY
)
SELECT a.sgbstdn_pidm, a.sgbstdn_term_code_eff, b.*, rorstat_pgrp_code
FROM SGBSTDN a, RORALGS
CROSS JOIN med_cohort -- table derived from with statement above
INNER JOIN ( -- find cohort codes matching those defined above in med_cohort
    SELECT SGRCHRT_PIDM, SGRCHRT_TERM_CODE_EFF, SGRCHRT_CHRT_CODE
    FROM SGRCHRT
    WHERE SGRCHRT_CHRT_CODE in (
        SELECT M4 FROM med_cohort UNION 
        SELECT M3 FROM med_cohort UNION 
        SELECT M2 FROM med_cohort
    )
) b ON b.SGRCHRT_PIDM = a.SGBSTDN_PIDM
    AND b.SGRCHRT_TERM_CODE_EFF = (
        SELECT MAX(z.SGRCHRT_TERM_CODE_EFF)
        FROM SGRCHRT z
        WHERE z.SGRCHRT_CHRT_CODE in (
            SELECT M4 FROM med_cohort UNION 
            SELECT M3 FROM med_cohort UNION 
            SELECT M2 FROM med_cohort
        )
    )
INNER JOIN RORSTAT on RORSTAT_PIDM = a.SGBSTDN_PIDM and RORSTAT_AIDY_CODE = :AIDY
WHERE a.SGBSTDN_STST_CODE IN  ('AS','IL')
AND a.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN
    WHERE SGBSTDN_PIDM = a.SGBSTDN_PIDM
    AND SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND RORALGS_KEY_1 = 'PBDG' 
AND RORALGS_KEY_4 = '2FEE'
AND CASE
    WHEN a.SGBSTDN_LEVL_CODE = 'PM' THEN 'PM'
END = RORALGS_KEY_5
AND CASE
    WHEN b.SGRCHRT_CHRT_CODE = (SELECT M4 FROM med_cohort) THEN 'M4'
    WHEN b.SGRCHRT_CHRT_CODE = (SELECT M3 FROM med_cohort) THEN 'M3'
    WHEN b.SGRCHRT_CHRT_CODE = (SELECT M2 FROM med_cohort) THEN 'M2'
END = RORALGS_KEY_11
AND a.SGBSTDN_STST_CODE IN  ('AS','IL')
AND a.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY

; 

-- M1 (LOOK FOR APPLICATION TO PM WITHIN THE AID YEAR)
SELECT RORALGS_AMT 
    FROM SARADAP X, SARAPPD X, RORALGS, STVAPDC
WHERE	
RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '2FEE' -- budget component
AND CASE -- level code
	WHEN X.SARADAP_LEVL_CODE = 'PM' THEN 'PM'
END = RORALGS_KEY_5
AND RORALGS_KEY_11 = 'M1'
-- max saradap term <= passed period
AND X.SARADAP_TERM_CODE_ENTRY = (
    SELECT MAX(X.SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP Y, ROBINST
    WHERE Y.SARADAP_PIDM = X.SARADAP_PIDM
    AND Y.SARADAP_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')   	
	AND Y.SARADAP_TERM_CODE_ENTRY <= :PERIOD
	AND ROBINST_AIDY_CODE = :AIDY   
)
--max application decision code sequence number
AND X.SARAPPD_SEQ_NO = (
    SELECT MAX (X.SARAPPD_SEQ_NO)
    FROM SARAPPD Y, ROBINST
    WHERE     Y.SARAPPD_PIDM = X.SARAPPD_PIDM
    AND Y.SARAPPD_SEQ_NO < 99
    AND Y.SARAPPD_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
    AND Y.SARAPPD_TERM_CODE_ENTRY <= :PERIOD
    AND ROBINST_AIDY_CODE = :AIDY           
    AND X.SARADAP_APPL_NO = Y.SARAPPD_APPL_NO
)  
AND STVAPDC_INST_ACC_IND = 'Y'
AND STVAPDC_SIGNF_IND = 'Y'
AND X.SARAPPD_APDC_CODE = STVAPDC_CODE	
AND X.SARADAP_APPL_NO = X.SARAPPD_APPL_NO
AND X.SARADAP_TERM_CODE_ENTRY = X.SARAPPD_TERM_CODE_ENTRY
AND RORALGS_AIDY_CODE = :AIDY
AND X.SARAPPD_PIDM = X.SARADAP_PIDM	
AND X.SARADAP_PIDM = :PIDM
;