--GRAD DEN WITH SGASTDN
SELECT RORALGS_AMT
FROM SGBSTDN X, RORALGS
WHERE RORALGS_KEY_1 = 'PBDG'

AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
    WHEN X.SGBSTDN_LEVL_CODE = 'GR' THEN 'GR'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SGBSTDN_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
	
AND CASE -- college code
    WHEN X.SGBSTDN_COLL_CODE_1 = 'DEN' THEN 'DEN'
END = RORALGS_KEY_7
		
-- max sgbstdn term <= passed period
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
-- END

--GRAD DEN NO SGASTDN
SELECT RORALGS_AMT
FROM SARADAP X, SARAPPD X, RORALGS, STVAPDC
WHERE RORALGS_KEY_1 = 'PBDG'

AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
    WHEN X.SARADAP_LEVL_CODE = 'GR' THEN 'GR'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SARADAP_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
	
AND CASE -- college code
    WHEN X.SARADAP_COLL_CODE_1 = 'DEN' THEN 'DEN'
END = RORALGS_KEY_7
		
-- max saradap term <= passed period	
AND X.SARADAP_TERM_CODE_ENTRY = (
     SELECT MAX(Y.SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP Y, ROBINST
    WHERE Y.SARADAP_PIDM = X.SARADAP_PIDM
	AND Y.SARADAP_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
    AND Y.SARADAP_TERM_CODE_ENTRY <= :PERIOD
	AND ROBINST_AIDY_CODE = :AIDY
)
--max application decision code sequence number
AND X.SARAPPD_SEQ_NO = (SELECT MAX (X.SARAPPD_SEQ_NO)
	FROM SARAPPD Y, ROBINST
	WHERE     Y.SARAPPD_PIDM = X.SARAPPD_PIDM
	AND Y.SARAPPD_SEQ_NO < 99
	AND Y.SARAPPD_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
	AND Y.SARAPPD_TERM_CODE_ENTRY <= :PERIOD
	AND ROBINST_AIDY_CODE = :AIDY           
	AND X.SARADAP_APPL_NO = Y.SARAPPD_APPL_NO) 
      
AND STVAPDC_INST_ACC_IND = 'Y'
AND STVAPDC_SIGNF_IND = 'Y'

AND X.SARAPPD_APDC_CODE = STVAPDC_CODE	
AND X.SARADAP_APPL_NO = X.SARAPPD_APPL_NO
AND X.SARADAP_TERM_CODE_ENTRY = X.SARAPPD_TERM_CODE_ENTRY
AND RORALGS_AIDY_CODE = :AIDY
AND X.SARAPPD_PIDM = X.SARADAP_PIDM	
AND X.SARADAP_PIDM = :PIDM
-- END




--need to insert sequences for doctor of phy ther, new program starting summer 2025, rate sheet line 160




--GRAD MPH DEGREE ENROLLED OR NOT ENROLLED WITH SGASTDN 
SELECT RORALGS_AMT
FROM SGBSTDN X, RORALGS
WHERE RORALGS_KEY_1 = 'PBDG'

AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
    WHEN X.SGBSTDN_LEVL_CODE = 'GR' THEN 'GR'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SGBSTDN_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
	
AND CASE -- degree code
    WHEN X.SGBSTDN_DEGC_CODE_1 = 'MPH' THEN 'MPH'
END = RORALGS_KEY_8		
			
-- max sgbstdn term <= passed period
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
-- END

--GRAD MPH DEGREE NO SGASTDN 
SELECT RORALGS_AMT
FROM SARADAP X, SARAPPD X, RORALGS, STVAPDC
WHERE RORALGS_KEY_1 = 'PBDG'

AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
    WHEN X.SARADAP_LEVL_CODE = 'GR' THEN 'GR'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SARADAP_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
	
AND CASE -- degree code
    WHEN X.SARADAP_DEGC_CODE_1 = 'MPH' THEN 'MPH'
END = RORALGS_KEY_8		
			
-- max saradap term <= passed period	
AND X.SARADAP_TERM_CODE_ENTRY = (
     SELECT MAX(Y.SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP Y, ROBINST
    WHERE Y.SARADAP_PIDM = X.SARADAP_PIDM
	AND Y.SARADAP_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
    AND Y.SARADAP_TERM_CODE_ENTRY <= :PERIOD
	AND ROBINST_AIDY_CODE = :AIDY
)
--max application decision code sequence number
AND X.SARAPPD_SEQ_NO = (SELECT MAX (X.SARAPPD_SEQ_NO)
	FROM SARAPPD Y, ROBINST
	WHERE     Y.SARAPPD_PIDM = X.SARAPPD_PIDM
	AND Y.SARAPPD_SEQ_NO < 99
	AND Y.SARAPPD_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
	AND Y.SARAPPD_TERM_CODE_ENTRY <= :PERIOD
	AND ROBINST_AIDY_CODE = :AIDY           
	AND X.SARADAP_APPL_NO = Y.SARAPPD_APPL_NO) 
      
AND STVAPDC_INST_ACC_IND = 'Y'
AND STVAPDC_SIGNF_IND = 'Y'

AND X.SARAPPD_APDC_CODE = STVAPDC_CODE	
AND X.SARADAP_APPL_NO = X.SARAPPD_APPL_NO
AND X.SARADAP_TERM_CODE_ENTRY = X.SARAPPD_TERM_CODE_ENTRY
AND RORALGS_AIDY_CODE = :AIDY
AND X.SARAPPD_PIDM = X.SARADAP_PIDM	
AND X.SARADAP_PIDM = :PIDM
-- END



--GRAD ATHT12 WITH SGASTDN
SELECT RORALGS_AMT
FROM SGBSTDN X, SGRCHRT X, RORALGS, ROBINST
WHERE RORALGS_KEY_1 = 'PBDG'

AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
    WHEN X.SGBSTDN_LEVL_CODE = 'GR' THEN 'GR'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SGBSTDN_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
	
AND CASE -- college code
    WHEN X.SGBSTDN_COLL_CODE_1 = 'AH' THEN 'AH'
END = RORALGS_KEY_7

AND CASE -- major/program code
    WHEN X.SGBSTDN_PROGRAM_1 = 'ATHT12' THEN 'ATHT12'
END = RORALGS_KEY_9	

AND CASE -- cohort code
    WHEN X.SGRCHRT_CHRT_CODE = (ROBINST_AIDY_START_YEAR || 'AT') THEN (ROBINST_AIDY_START_YEAR || 'AT')              --2025 FOR FY26
	WHEN X.SGRCHRT_CHRT_CODE = (ROBINST_AIDY_END_YEAR || 'AT') THEN (ROBINST_AIDY_END_YEAR || 'AT')                  --2026 FOR FY26
END = RORALGS_KEY_11	
	
		-- max cohort term <= passed period
AND X.SGRCHRT_TERM_CODE_EFF = (
    SELECT MAX(Y.SGRCHRT_TERM_CODE_EFF)
    FROM SGRCHRT Y
    WHERE Y.SGRCHRT_PIDM = X.SGRCHRT_PIDM
    AND Y.SGRCHRT_TERM_CODE_EFF <= :PERIOD
)
-- max sgbstdn term <= passed period
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_PIDM = X.SGRCHRT_PIDM
AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = ROBINST_AIDY_CODE
AND RORALGS_AIDY_CODE = :AIDY
-- END

--GRAD ATHT12 NO SGASTDN
SELECT RORALGS_AMT
FROM SARADAP X, SARAPPD X, SARCHRT, RORALGS, STVAPDC, ROBINST
WHERE RORALGS_KEY_1 = 'PBDG'

AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
    WHEN X.SARADAP_LEVL_CODE = 'GR' THEN 'GR'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SARADAP_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
	
AND CASE -- college code
    WHEN X.SARADAP_COLL_CODE_1 = 'AH' THEN 'AH'
END = RORALGS_KEY_7

AND CASE -- major/program code
    WHEN X.SARADAP_PROGRAM_1 = 'ATHT12' THEN 'ATHT12'
END = RORALGS_KEY_9	

--likely only need one of these for new students, but need to check witrh SLU
AND CASE -- cohort code
    WHEN SARCHRT_CHRT_CODE = (ROBINST_AIDY_START_YEAR || 'AT') THEN (ROBINST_AIDY_START_YEAR || 'AT')              --2025 FOR FY26
	WHEN SARCHRT_CHRT_CODE = (ROBINST_AIDY_END_YEAR || 'AT') THEN (ROBINST_AIDY_END_YEAR || 'AT')                  --2026 FOR FY26
END = RORALGS_KEY_11	
	
-- max saradap term <= passed period	
AND X.SARADAP_TERM_CODE_ENTRY = (
     SELECT MAX(Y.SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP Y, ROBINST
    WHERE Y.SARADAP_PIDM = X.SARADAP_PIDM
	AND Y.SARADAP_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
    AND Y.SARADAP_TERM_CODE_ENTRY <= :PERIOD
	AND ROBINST_AIDY_CODE = :AIDY
)
--max application decision code sequence number
AND X.SARAPPD_SEQ_NO = (SELECT MAX (X.SARAPPD_SEQ_NO)
	FROM SARAPPD Y, ROBINST
	WHERE     Y.SARAPPD_PIDM = X.SARAPPD_PIDM
	AND Y.SARAPPD_SEQ_NO < 99
	AND Y.SARAPPD_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
	AND Y.SARAPPD_TERM_CODE_ENTRY <= :PERIOD
	AND ROBINST_AIDY_CODE = :AIDY           
	AND X.SARADAP_APPL_NO = Y.SARAPPD_APPL_NO) 
      
AND STVAPDC_INST_ACC_IND = 'Y'
AND STVAPDC_SIGNF_IND = 'Y'
		
AND X.SARAPPD_APDC_CODE = STVAPDC_CODE	
AND X.SARADAP_APPL_NO = X.SARAPPD_APPL_NO
AND X.SARADAP_APPL_NO = SARCHRT_APPL_NO
AND X.SARADAP_TERM_CODE_ENTRY = X.SARAPPD_TERM_CODE_ENTRY
AND X.SARADAP_TERM_CODE_ENTRY = SARCHRT_TERM_CODE_ENTRY
AND RORALGS_AIDY_CODE = ROBINST_AIDY_CODE
AND RORALGS_AIDY_CODE = :AIDY
AND X.SARADAP_PIDM = X.SARAPPD_PIDM
AND X.SARADAP_PIDM = SARCHRT_PIDM
AND X.SARADAP_PIDM = :PIDM
-- END




--GRAD PT MAJOR ENROLLED OR NOT ENROLLED WITH SGASTDN
SELECT RORALGS_AMT
FROM SGBSTDN X, RORALGS, SGRCHRT X, ROBINST
WHERE RORALGS_KEY_1 = 'PBDG'

AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
    WHEN X.SGBSTDN_LEVL_CODE = 'GR' THEN 'GR'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SGBSTDN_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
	
AND CASE -- college code
    WHEN X.SGBSTDN_COLL_CODE_1 = 'AH' THEN 'AH'
END = RORALGS_KEY_7

AND CASE -- major/program code
	WHEN X.SGBSTDN_MAJR_CODE_1 = 'PT' THEN 'PT'
END = RORALGS_KEY_9		
		
--NEED TO HAVE SIX ROWS ON RORALGS, A FALL AND SPRING ROW FOR EACH COHORT CODE 2026PT, 2027PT, AND ONE MORE FOR THE TRANSFER COHORT	
AND CASE -- cohort code
    WHEN X.SGRCHRT_CHRT_CODE = (ROBINST_AIDY_END_YEAR || 'PT') THEN (ROBINST_AIDY_END_YEAR || 'PT')                   --2027PT FOR FY27
    WHEN X.SGRCHRT_CHRT_CODE = (ROBINST_AIDY_START_YEAR || 'PT') THEN (ROBINST_AIDY_START_YEAR || 'PT')                 --2026PT FOR FY27
	--Janice will visit with Hayley about a cohort that transfers in
	--WHEN X.SGRCHRT_CHRT_CODE = ?? THEN ??
END = RORALGS_KEY_11		

AND CASE -- term
    WHEN (ROBINST_AIDY_END_YEAR || '10') = :PERIOD THEN 'FALL'
    WHEN (ROBINST_AIDY_END_YEAR || '20') = :PERIOD THEN 'SPRING'
END = RORALGS_KEY_12

-- max sgbstdn term <= passed period
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD)

	-- max cohort term <= passed period
AND X.SGRCHRT_TERM_CODE_EFF = (
    SELECT MAX(Y.SGRCHRT_TERM_CODE_EFF)
    FROM SGRCHRT Y
    WHERE Y.SGRCHRT_PIDM = X.SGRCHRT_PIDM
    AND Y.SGRCHRT_TERM_CODE_EFF <= :PERIOD
)
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_PIDM = X.SGRCHRT_PIDM
AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = ROBINST_AIDY_CODE
AND RORALGS_AIDY_CODE = :AIDY
-- END

--GRAD PT MAJOR NO SGASTDN
SELECT RORALGS_AMT
FROM SARADAP X, SARAPPD X, SARCHRT, RORALGS, STVAPDC, ROBINST
WHERE RORALGS_KEY_1 = 'PBDG'

AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
    WHEN X.SARADAP_LEVL_CODE = 'GR' THEN 'GR'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SARADAP_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
	
AND CASE -- college code
    WHEN X.SARADAP_COLL_CODE_1 = 'AH' THEN 'AH'
END = RORALGS_KEY_7

AND CASE -- major/program code
	WHEN X.SARADAP_MAJR_CODE_1 = 'PT' THEN 'PT'
END = RORALGS_KEY_9		
		
--Likely only need ot have one of these for new students but need to check with SLU, will be two rows on RORALGS if only one cohort is needed
AND CASE -- cohort code
    WHEN SARCHRT_CHRT_CODE = (ROBINST_AIDY_END_YEAR || 'PT') THEN (ROBINST_AIDY_END_YEAR || 'PT')                   --2027PT FOR FY27
    WHEN SARCHRT_CHRT_CODE = (ROBINST_AIDY_START_YEAR || 'PT') THEN (ROBINST_AIDY_START_YEAR || 'PT')                 --2026PT FOR FY27
	--Janice will visit with Hayley about a cohort that transfers in
	--WHEN X.SGRCHRT_CHRT_CODE = ?? THEN ??
END = RORALGS_KEY_11		

AND CASE -- term
    WHEN (ROBINST_AIDY_END_YEAR || '10') = :PERIOD THEN 'FALL'
    WHEN (ROBINST_AIDY_END_YEAR || '20') = :PERIOD THEN 'SPRING'
END = RORALGS_KEY_12

-- max saradap term <= passed period	
AND X.SARADAP_TERM_CODE_ENTRY = (
     SELECT MAX(Y.SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP Y, ROBINST
    WHERE Y.SARADAP_PIDM = X.SARADAP_PIDM
	AND Y.SARADAP_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
    AND Y.SARADAP_TERM_CODE_ENTRY <= :PERIOD
	AND ROBINST_AIDY_CODE = :AIDY
)
--max application decision code sequence number
AND X.SARAPPD_SEQ_NO = (SELECT MAX (X.SARAPPD_SEQ_NO)
	FROM SARAPPD Y, ROBINST
	WHERE     Y.SARAPPD_PIDM = X.SARAPPD_PIDM
	AND Y.SARAPPD_SEQ_NO < 99
	AND Y.SARAPPD_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
	AND Y.SARAPPD_TERM_CODE_ENTRY <= :PERIOD
	AND ROBINST_AIDY_CODE = :AIDY           
	AND X.SARADAP_APPL_NO = Y.SARAPPD_APPL_NO) 
      
AND STVAPDC_INST_ACC_IND = 'Y'
AND STVAPDC_SIGNF_IND = 'Y'
	
AND X.SARAPPD_APDC_CODE = STVAPDC_CODE	
AND X.SARADAP_APPL_NO = X.SARAPPD_APPL_NO
AND X.SARADAP_APPL_NO = SARCHRT_APPL_NO
AND X.SARADAP_TERM_CODE_ENTRY = X.SARAPPD_TERM_CODE_ENTRY
AND X.SARADAP_TERM_CODE_ENTRY = SARCHRT_TERM_CODE_ENTRY
AND RORALGS_AIDY_CODE = ROBINST_AIDY_CODE
AND RORALGS_AIDY_CODE = :AIDY
AND X.SARADAP_PIDM = X.SARAPPD_PIDM
AND X.SARADAP_PIDM = SARCHRT_PIDM
AND X.SARADAP_PIDM = :PIDM
-- END




--GRAD AH WITH MAJOR IN IN OCTH, MIT ENROLLED FULL TIME
SELECT CASE
    WHEN NVL(ROKMISC.F_CALC_STUD_CREDIT_HRS(:PERIOD, X.SGBSTDN_PIDM, 'N'), 0) >= 12
        THEN RORALGS_AMT
    END as calc_amt
FROM SGBSTDN X, RORALGS
WHERE RORALGS_KEY_1 = 'PBDG'

AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
    WHEN X.SGBSTDN_LEVL_CODE = 'GR' THEN 'GR'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SGBSTDN_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
	
AND CASE -- college code
    WHEN X.SGBSTDN_COLL_CODE_1 = 'AH' THEN 'AH'
END = RORALGS_KEY_7

AND CASE -- major/program code
	WHEN X.SGBSTDN_MAJR_CODE_1 = 'OCTH' THEN 'OCTH'
	WHEN X.SGBSTDN_MAJR_CODE_1 = 'MIT' THEN 'MIT'
END = RORALGS_KEY_9		
	
AND RORALGS_KEY_12 = 'FT'
		
-- max sgbstdn term <= passed period
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
-- END

--GRAD AH WITH MAJOR IN IN OCTH, MIT ENROLLED PART TIME
SELECT CASE
    WHEN NVL(ROKMISC.F_CALC_STUD_CREDIT_HRS(:PERIOD, X.SGBSTDN_PIDM, 'N'), 0) < 12
	AND  NVL(ROKMISC.F_CALC_STUD_CREDIT_HRS(:PERIOD, X.SGBSTDN_PIDM, 'N'), 0) > 0
        THEN round(roralgs_amt * NVL(ROKMISC.F_CALC_STUD_CREDIT_HRS(:PERIOD, X.SGBSTDN_PIDM, 'N'), 0))
    END as calc_amt
FROM SGBSTDN X, RORALGS
WHERE RORALGS_KEY_1 = 'PBDG'

AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
    WHEN X.SGBSTDN_LEVL_CODE = 'GR' THEN 'GR'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SGBSTDN_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
	
AND CASE -- college code
    WHEN X.SGBSTDN_COLL_CODE_1 = 'AH' THEN 'AH'
END = RORALGS_KEY_7

AND CASE -- major/program code
	WHEN X.SGBSTDN_MAJR_CODE_1 = 'OCTH' THEN 'OCTH'
	WHEN X.SGBSTDN_MAJR_CODE_1 = 'MIT' THEN 'MIT'
END = RORALGS_KEY_9		
	
AND RORALGS_KEY_12 = 'PT'
		
-- max sgbstdn term <= passed period
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
-- END

--GRAD AH WITH MAJOR IN IN OCTH, MIT NOT ENROLLED WITH SGASTDN
SELECT (RORALGS_AMT * 6)                                                           
FROM SGBSTDN X, RORALGS
WHERE RORALGS_KEY_1 = 'PBDG'

AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
    WHEN X.SGBSTDN_LEVL_CODE = 'GR' THEN 'GR'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SGBSTDN_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
	
AND CASE -- college code
    WHEN X.SGBSTDN_COLL_CODE_1 = 'AH' THEN 'AH'
END = RORALGS_KEY_7

AND CASE -- major/program code
	WHEN X.SGBSTDN_MAJR_CODE_1 = 'OCTH' THEN 'OCTH'
	WHEN X.SGBSTDN_MAJR_CODE_1 = 'MIT' THEN 'MIT'
END = RORALGS_KEY_9		
	
-- max sgbstdn term <= passed period
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
-- END

--GRAD AH WITH MAJOR IN IN OCTH, MIT NO SGASTDN
SELECT (RORALGS_AMT * 6)                                                           
FROM SARADAP X, SARAPPD X, RORALGS, STVAPDC
WHERE RORALGS_KEY_1 = 'PBDG'

AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
    WHEN X.SARADAP_LEVL_CODE = 'GR' THEN 'GR'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SARADAP_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
	
AND CASE -- college code
    WHEN X.SARADAP_COLL_CODE_1 = 'AH' THEN 'AH'
END = RORALGS_KEY_7

AND CASE -- major/program code
	WHEN X.SARADAP_MAJR_CODE_1 = 'OCTH' THEN 'OCTH'
	WHEN X.SARADAP_MAJR_CODE_1 = 'MIT' THEN 'MIT'
END = RORALGS_KEY_9		
		
-- max saradap term <= passed period	
AND X.SARADAP_TERM_CODE_ENTRY = (
     SELECT MAX(Y.SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP Y, ROBINST
    WHERE Y.SARADAP_PIDM = X.SARADAP_PIDM
	AND Y.SARADAP_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
    AND Y.SARADAP_TERM_CODE_ENTRY <= :PERIOD
	AND ROBINST_AIDY_CODE = :AIDY
)
--max application decision code sequence number
AND X.SARAPPD_SEQ_NO = (SELECT MAX (X.SARAPPD_SEQ_NO)
	FROM SARAPPD Y, ROBINST
	WHERE     Y.SARAPPD_PIDM = X.SARAPPD_PIDM
	AND Y.SARAPPD_SEQ_NO < 99
	AND Y.SARAPPD_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
	AND Y.SARAPPD_TERM_CODE_ENTRY <= :PERIOD
	AND ROBINST_AIDY_CODE = :AIDY           
	AND X.SARADAP_APPL_NO = Y.SARAPPD_APPL_NO) 
      
AND STVAPDC_INST_ACC_IND = 'Y'
AND STVAPDC_SIGNF_IND = 'Y'

AND X.SARAPPD_APDC_CODE = STVAPDC_CODE	
AND X.SARADAP_APPL_NO = X.SARAPPD_APPL_NO
AND X.SARADAP_TERM_CODE_ENTRY = X.SARAPPD_TERM_CODE_ENTRY
AND RORALGS_AIDY_CODE = :AIDY
AND X.SARAPPD_PIDM = X.SARADAP_PIDM	
AND X.SARADAP_PIDM = :PIDM
-- END




--GRAD NP23, NP26, NR12 ENROLLED
SELECT CASE
    WHEN NVL(ROKMISC.F_CALC_STUD_CREDIT_HRS(:PERIOD, X.SGBSTDN_PIDM, 'N'), 0) > 0
        THEN round(roralgs_amt * NVL(ROKMISC.F_CALC_STUD_CREDIT_HRS(:PERIOD, X.SGBSTDN_PIDM, 'N'), 0))
    END as calc_amt
FROM SGBSTDN X, RORALGS
WHERE RORALGS_KEY_1 = 'PBDG'

AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
    WHEN X.SGBSTDN_LEVL_CODE = 'GR' THEN 'GR'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SGBSTDN_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
	
AND CASE -- major/program code
	WHEN X.SGBSTDN_PROGRAM_1 = 'NP23' THEN 'NP23'
	WHEN X.SGBSTDN_PROGRAM_1 = 'NP26' THEN 'NP26'
	WHEN X.SGBSTDN_PROGRAM_1 = 'NR12' THEN 'NR12'
END = RORALGS_KEY_9		
		
-- max sgbstdn term <= passed period
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
-- END

--GRAD NP23, NP26, NR12 NOT ENROLLED WITH SGASTDN
SELECT (RORALGS_AMT * 6)                                                         
FROM SGBSTDN X, RORALGS
WHERE RORALGS_KEY_1 = 'PBDG'

AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
    WHEN X.SGBSTDN_LEVL_CODE = 'GR' THEN 'GR'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SGBSTDN_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
	
AND CASE -- major/program code
	WHEN X.SGBSTDN_PROGRAM_1 = 'NP23' THEN 'NP23'
	WHEN X.SGBSTDN_PROGRAM_1 = 'NP26' THEN 'NP26'
	WHEN X.SGBSTDN_PROGRAM_1 = 'NR12' THEN 'NR12'
END = RORALGS_KEY_9		
		
-- max sgbstdn term <= passed period
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
-- END

--GRAD NP23, NP26, NR12 NO SGASTDN
SELECT (RORALGS_AMT * 6)                                                         
FROM SARADAP X, SARAPPD X, RORALGS, STVAPDC
WHERE RORALGS_KEY_1 = 'PBDG'

AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
    WHEN X.SARADAP_LEVL_CODE = 'GR' THEN 'GR'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SARADAP_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
	
AND CASE -- major/program code
	WHEN X.SARADAP_PROGRAM_1 = 'NP23' THEN 'NP23'
	WHEN X.SARADAP_PROGRAM_1 = 'NP26' THEN 'NP26'
	WHEN X.SARADAP_PROGRAM_1 = 'NR12' THEN 'NR12'
END = RORALGS_KEY_9		
		
-- max saradap term <= passed period	
AND X.SARADAP_TERM_CODE_ENTRY = (
     SELECT MAX(Y.SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP Y, ROBINST
    WHERE Y.SARADAP_PIDM = X.SARADAP_PIDM
	AND Y.SARADAP_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
    AND Y.SARADAP_TERM_CODE_ENTRY <= :PERIOD
	AND ROBINST_AIDY_CODE = :AIDY
)
--max application decision code sequence number
AND X.SARAPPD_SEQ_NO = (SELECT MAX (X.SARAPPD_SEQ_NO)
	FROM SARAPPD Y, ROBINST
	WHERE     Y.SARAPPD_PIDM = X.SARAPPD_PIDM
	AND Y.SARAPPD_SEQ_NO < 99
	AND Y.SARAPPD_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
	AND Y.SARAPPD_TERM_CODE_ENTRY <= :PERIOD
	AND ROBINST_AIDY_CODE = :AIDY           
	AND X.SARADAP_APPL_NO = Y.SARAPPD_APPL_NO) 
      
AND STVAPDC_INST_ACC_IND = 'Y'
AND STVAPDC_SIGNF_IND = 'Y'

AND X.SARAPPD_APDC_CODE = STVAPDC_CODE	
AND X.SARADAP_APPL_NO = X.SARAPPD_APPL_NO
AND X.SARADAP_TERM_CODE_ENTRY = X.SARAPPD_TERM_CODE_ENTRY
AND RORALGS_AIDY_CODE = :AIDY
AND X.SARAPPD_PIDM = X.SARADAP_PIDM	
AND X.SARADAP_PIDM = :PIDM
-- END




--need to insert sequences for advanced standing MWS with and without SWP rate code
--need to insert sequences for accelerated MWS with and without SWP rate code
--check with SLU, if Adv Stand and Accel MSW have different major codes or program codes, 
     --we can account for all three options in one sequence since all are flat rate programs

--GRAD MSW WITH SGASTDN 
--DON'T NEED SEQUENCE FOR ENROLLED SINCE IT'S ALWAYS A FLAT RATE
SELECT RORALGS_AMT
FROM SGBSTDN X, RORALGS
WHERE RORALGS_KEY_1 = 'PBDG'

--NEED TWO RECORDS ON RORALGS, ONE WITH KEY 3=SWP AND ONE WITH KEY 3=NA
--IF WE CAN COMBINE ADV STAND AND ACCEL OPTIONS WE'LL NEED SIX ROWS ON RORALGS, THREE WITH RATE CODE, THREE WITHOUT
AND CASE -- rate code
    WHEN X.SGBSTDN_RATE_CODE = 'SWP' THEN 'SWP'
	WHEN (X.SGBSTDN_RATE_CODE IS NULL 
         OR X.SGBSTDN_RATE_CODE <> 'SWP') THEN 'NA' 
END = RORALGS_KEY_3	

AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
    WHEN X.SGBSTDN_LEVL_CODE = 'GR' THEN 'GR'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SGBSTDN_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
	
AND CASE -- college code
    WHEN X.SGBSTDN_COLL_CODE_1 = 'SS' THEN 'SS'
END = RORALGS_KEY_7

AND CASE -- degree code
    WHEN X.SGBSTDN_DEGC_CODE_1 = 'MSW' THEN 'MSW'
END = RORALGS_KEY_8		

/*--use this if they have different program codes
AND CASE -- major/program code
	WHEN X.SGBSTDN_PROGRAM_1 = '?' THEN '?'
	WHEN X.SGBSTDN_PROGRAM_1 = '?' THEN '?'
	WHEN X.SGBSTDN_PROGRAM_1 = '?' THEN '?'
END = RORALGS_KEY_9	
	
--OR USE THIS IF THEY HAVE DIFFERENT MAJOR CODES
AND CASE -- major/program code
	WHEN X.SGBSTDN_MAJR_CODE_1 = '?' THEN '?'
	WHEN X.SGBSTDN_MAJR_CODE_1 = '?' THEN '?'
	WHEN X.SGBSTDN_MAJR_CODE_1 = '?' THEN '?'
END = RORALGS_KEY_9	
*/
			
-- max sgbstdn term <= passed period
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
-- END

--GRAD MSW NO SGASTDN 
SELECT RORALGS_AMT
FROM SARADAP X, SARAPPD X, RORALGS, STVAPDC
WHERE RORALGS_KEY_1 = 'PBDG'

--ASSUME RATE WITHOUT RATE CODE
AND RORALGS_KEY_3 = 'NA'	

AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
    WHEN X.SARADAP_LEVL_CODE = 'GR' THEN 'GR'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SARADAP_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
	
AND CASE -- college code
    WHEN X.SARADAP_COLL_CODE_1 = 'SS' THEN 'SS'
END = RORALGS_KEY_7

AND CASE -- degree code
    WHEN X.SARADAP_DEGC_CODE_1 = 'MSW' THEN 'MSW'
END = RORALGS_KEY_8		

/*--use this if they have different program codes
AND CASE -- major/program code
	WHEN X.SARADAP_PROGRAM_1 = '?' THEN '?'
	WHEN X.SARADAP_PROGRAM_1 = '?' THEN '?'
	WHEN X.SARADAP_PROGRAM_1 = '?' THEN '?'
END = RORALGS_KEY_9	
	
--OR USE THIS IF THEY HAVE DIFFERENT MAJOR CODES
AND CASE -- major/program code
	WHEN X.SARADAP_MAJR_CODE_1 = '?' THEN '?'
	WHEN X.SARADAP_MAJR_CODE_1 = '?' THEN '?'
	WHEN X.SARADAP_MAJR_CODE_1 = '?' THEN '?'
END = RORALGS_KEY_9	
*/
			
-- max saradap term <= passed period	
AND X.SARADAP_TERM_CODE_ENTRY = (
     SELECT MAX(Y.SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP Y, ROBINST
    WHERE Y.SARADAP_PIDM = X.SARADAP_PIDM
	AND Y.SARADAP_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
    AND Y.SARADAP_TERM_CODE_ENTRY <= :PERIOD
	AND ROBINST_AIDY_CODE = :AIDY
)
--max application decision code sequence number
AND X.SARAPPD_SEQ_NO = (SELECT MAX (X.SARAPPD_SEQ_NO)
	FROM SARAPPD Y, ROBINST
	WHERE     Y.SARAPPD_PIDM = X.SARAPPD_PIDM
	AND Y.SARAPPD_SEQ_NO < 99
	AND Y.SARAPPD_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
	AND Y.SARAPPD_TERM_CODE_ENTRY <= :PERIOD
	AND ROBINST_AIDY_CODE = :AIDY           
	AND X.SARADAP_APPL_NO = Y.SARAPPD_APPL_NO) 
      
AND STVAPDC_INST_ACC_IND = 'Y'
AND STVAPDC_SIGNF_IND = 'Y'

AND X.SARAPPD_APDC_CODE = STVAPDC_CODE	
AND X.SARADAP_APPL_NO = X.SARAPPD_APPL_NO
AND X.SARADAP_TERM_CODE_ENTRY = X.SARAPPD_TERM_CODE_ENTRY
AND RORALGS_AIDY_CODE = :AIDY
AND X.SARAPPD_PIDM = X.SARADAP_PIDM	
AND X.SARADAP_PIDM = :PIDM
-- END




--GRAD CCJ, ABA MAJOR WITH SGASTDN
--DON'T NEED SEQUENCE FOR ENROLLED SINCE IT'S ALWAYS A FLAT RATE
SELECT RORALGS_AMT
FROM SGBSTDN X, RORALGS
WHERE RORALGS_KEY_1 = 'PBDG'

--NEED FOUR RECORDS ON RORALGS, TWO WITH KEY 3=SWP AND TWO WITH KEY 3=NA
AND CASE -- rate code
    WHEN X.SGBSTDN_RATE_CODE = 'SWP' THEN 'SWP'
	WHEN (X.SGBSTDN_RATE_CODE IS NULL 
         OR X.SGBSTDN_RATE_CODE <> 'SWP') THEN 'NA' 
END = RORALGS_KEY_3	

AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
    WHEN X.SGBSTDN_LEVL_CODE = 'GR' THEN 'GR'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SGBSTDN_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
	
AND CASE -- college code
    WHEN X.SGBSTDN_COLL_CODE_1 = 'SS' THEN 'SS'
END = RORALGS_KEY_7
	
AND CASE -- degree code
    WHEN X.SGBSTDN_DEGC_CODE_1 = 'MA' THEN 'MA'
	WHEN X.SGBSTDN_DEGC_CODE_1 = 'MS' THEN 'MS'
END = RORALGS_KEY_8		
		
AND CASE -- major code
    WHEN X.SGBSTDN_MAJR_CODE_1 = 'ABA' THEN 'ABA'
	WHEN X.SGBSTDN_MAJR_CODE_1 = 'CCJ' THEN 'CCJ'
END = RORALGS_KEY_9
		
-- max sgbstdn term <= passed period
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
-- END

--GRAD CCJ, ABA MAJOR NO SGASTDN
SELECT RORALGS_AMT
FROM SARADAP X, SARAPPD X, RORALGS, STVAPDC
WHERE RORALGS_KEY_1 = 'PBDG'

--ASSUME RATE WITHOUT RATE CODE
AND RORALGS_KEY_3 = 'NA'

AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
    WHEN X.SARADAP_LEVL_CODE = 'GR' THEN 'GR'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SARADAP_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
	
AND CASE -- college code
    WHEN X.SARADAP_COLL_CODE_1 = 'SS' THEN 'SS'
END = RORALGS_KEY_7
	
AND CASE -- degree code
    WHEN X.SARADAP_DEGC_CODE_1 = 'MA' THEN 'MA'
	WHEN X.SARADAP_DEGC_CODE_1 = 'MS' THEN 'MS'
END = RORALGS_KEY_8		
		
AND CASE -- major code
    WHEN X.SARADAP_MAJR_CODE_1 = 'ABA' THEN 'ABA'
	WHEN X.SARADAP_MAJR_CODE_1 = 'CCJ' THEN 'CCJ'
END = RORALGS_KEY_9
		
-- max saradap term <= passed period	
AND X.SARADAP_TERM_CODE_ENTRY = (
     SELECT MAX(Y.SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP Y, ROBINST
    WHERE Y.SARADAP_PIDM = X.SARADAP_PIDM
	AND Y.SARADAP_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
    AND Y.SARADAP_TERM_CODE_ENTRY <= :PERIOD
	AND ROBINST_AIDY_CODE = :AIDY
)
--max application decision code sequence number
AND X.SARAPPD_SEQ_NO = (SELECT MAX (X.SARAPPD_SEQ_NO)
	FROM SARAPPD Y, ROBINST
	WHERE     Y.SARAPPD_PIDM = X.SARAPPD_PIDM
	AND Y.SARAPPD_SEQ_NO < 99
	AND Y.SARAPPD_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
	AND Y.SARAPPD_TERM_CODE_ENTRY <= :PERIOD
	AND ROBINST_AIDY_CODE = :AIDY           
	AND X.SARADAP_APPL_NO = Y.SARAPPD_APPL_NO) 
      
AND STVAPDC_INST_ACC_IND = 'Y'
AND STVAPDC_SIGNF_IND = 'Y'

AND X.SARAPPD_APDC_CODE = STVAPDC_CODE	
AND X.SARADAP_APPL_NO = X.SARAPPD_APPL_NO
AND X.SARADAP_TERM_CODE_ENTRY = X.SARAPPD_TERM_CODE_ENTRY
AND RORALGS_AIDY_CODE = :AIDY
AND X.SARAPPD_PIDM = X.SARADAP_PIDM	
AND X.SARADAP_PIDM = :PIDM
-- END




--GRAD BADS, INTB MAJOR WITH SGASTDN
--DON'T NEED SEQUENCE FOR ENROLLED SINCE IT'S ALWAYS A FLAT RATE
SELECT RORALGS_AMT
FROM SGBSTDN X, RORALGS
WHERE RORALGS_KEY_1 = 'PBDG'

AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
    WHEN X.SGBSTDN_LEVL_CODE = 'GR' THEN 'GR'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SGBSTDN_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
	
		
AND CASE -- major code
    WHEN X.SGBSTDN_MAJR_CODE_1 = 'BADS' THEN 'BADS'
	WHEN X.SGBSTDN_MAJR_CODE_1 = 'INTB' THEN 'INTB'
END = RORALGS_KEY_9
		
-- max sgbstdn term <= passed period
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
-- END

--GRAD BADS, INTB MAJOR NO SGASTDN
SELECT RORALGS_AMT
FROM SARADAP X, SARAPPD X, RORALGS, STVAPDC
WHERE RORALGS_KEY_1 = 'PBDG'

AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
    WHEN X.SARADAP_LEVL_CODE = 'GR' THEN 'GR'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SARADAP_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
	
		
AND CASE -- major code
    WHEN X.SARADAP_MAJR_CODE_1 = 'BADS' THEN 'BADS'
	WHEN X.SARADAP_MAJR_CODE_1 = 'INTB' THEN 'INTB'
END = RORALGS_KEY_9
		
-- max saradap term <= passed period	
AND X.SARADAP_TERM_CODE_ENTRY = (
     SELECT MAX(Y.SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP Y, ROBINST
    WHERE Y.SARADAP_PIDM = X.SARADAP_PIDM
	AND Y.SARADAP_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
    AND Y.SARADAP_TERM_CODE_ENTRY <= :PERIOD
	AND ROBINST_AIDY_CODE = :AIDY
)
--max application decision code sequence number
AND X.SARAPPD_SEQ_NO = (SELECT MAX (X.SARAPPD_SEQ_NO)
	FROM SARAPPD Y, ROBINST
	WHERE     Y.SARAPPD_PIDM = X.SARAPPD_PIDM
	AND Y.SARAPPD_SEQ_NO < 99
	AND Y.SARAPPD_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
	AND Y.SARAPPD_TERM_CODE_ENTRY <= :PERIOD
	AND ROBINST_AIDY_CODE = :AIDY           
	AND X.SARADAP_APPL_NO = Y.SARAPPD_APPL_NO) 
      
AND STVAPDC_INST_ACC_IND = 'Y'
AND STVAPDC_SIGNF_IND = 'Y'

AND X.SARAPPD_APDC_CODE = STVAPDC_CODE	
AND X.SARADAP_APPL_NO = X.SARAPPD_APPL_NO
AND X.SARADAP_TERM_CODE_ENTRY = X.SARAPPD_TERM_CODE_ENTRY
AND RORALGS_AIDY_CODE = :AIDY
AND X.SARAPPD_PIDM = X.SARADAP_PIDM	
AND X.SARADAP_PIDM = :PIDM
-- END




--GRAD PA/SLH WITH SGASTDN
SELECT RORALGS_AMT
FROM SGBSTDN X, SGRCHRT X, RORALGS, ROBINST
WHERE RORALGS_KEY_1 = 'PBDG'

AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
    WHEN X.SGBSTDN_LEVL_CODE = 'GR' THEN 'GR'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SGBSTDN_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
	
AND CASE -- major code
    WHEN X.SGBSTDN_MAJR_CODE_1 = 'PA' THEN 'PA'
	WHEN X.SGBSTDN_MAJR_CODE_1 = 'SLH' THEN 'SLH'
END = RORALGS_KEY_9
	
--NEED TO HAVE TEN ROWS ON RORALGS, A FALL AND SPRING ROW FOR EACH COHORT CODE PA2024, PA2025, PA2026, 2025SLH, 2026SLH			
AND CASE -- cohort code
    WHEN X.SGRCHRT_CHRT_CODE = ('PA' || ROBINST_AIDY_END_YEAR) THEN ('PA' || ROBINST_AIDY_END_YEAR)                     --PA2026 FOR FY26
    WHEN X.SGRCHRT_CHRT_CODE = ('PA' || ROBINST_AIDY_START_YEAR) THEN ('PA' || ROBINST_AIDY_START_YEAR)                 --PA2025 FOR FY26
	WHEN X.SGRCHRT_CHRT_CODE = ('PA' || (TO_NUMBER(ROBINST_AIDY_START_YEAR)-1)) THEN ('PA' || (TO_NUMBER(ROBINST_AIDY_START_YEAR)-1))     --PA2024 FOR FY26
    WHEN X.SGRCHRT_CHRT_CODE = (ROBINST_AIDY_END_YEAR || 'SLH') THEN (ROBINST_AIDY_END_YEAR || 'SLH')                   --2026SLH FOR FY26
    WHEN X.SGRCHRT_CHRT_CODE = (ROBINST_AIDY_END_YEAR || 'SLH') THEN (ROBINST_AIDY_END_YEAR || 'SLH')                   --2025SLH FOR FY26
END = RORALGS_KEY_11

AND CASE -- term
    WHEN (ROBINST_AIDY_END_YEAR || '10') = :PERIOD THEN 'FALL'
    WHEN (ROBINST_AIDY_END_YEAR || '20') = :PERIOD THEN 'SPRING'
END = RORALGS_KEY_12
			
-- max sgbstdn term <= passed period
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
	-- max cohort term <= passed period
AND X.SGRCHRT_TERM_CODE_EFF = (
    SELECT MAX(Y.SGRCHRT_TERM_CODE_EFF)
    FROM SGRCHRT Y
    WHERE Y.SGRCHRT_PIDM = X.SGRCHRT_PIDM
    AND Y.SGRCHRT_TERM_CODE_EFF <= :PERIOD
)
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_PIDM = X.SGRCHRT_PIDM
AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = ROBINST_AIDY_CODE
AND RORALGS_AIDY_CODE = :AIDY
--END

--GRAD PA/SLH NO SGASTDN
SELECT RORALGS_AMT
FROM SARADAP X, SARAPPD X, SARCHRT, RORALGS, STVAPDC, ROBINST
WHERE RORALGS_KEY_1 = 'PBDG'

AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
    WHEN X.SARADAP_LEVL_CODE = 'GR' THEN 'GR'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SARADAP_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
	
AND CASE -- major code
    WHEN X.SARADAP_MAJR_CODE_1 = 'PA' THEN 'PA'
	WHEN X.SARADAP_MAJR_CODE_1 = 'SLH' THEN 'SLH'
END = RORALGS_KEY_9
	
--Likely only need one of these for new students, but need to check with SLU
AND CASE -- cohort code
    WHEN SARCHRT_CHRT_CODE = ('PA' || ROBINST_AIDY_END_YEAR) THEN ('PA' || ROBINST_AIDY_END_YEAR)                     --PA2026 FOR FY26
    WHEN SARCHRT_CHRT_CODE = ('PA' || ROBINST_AIDY_START_YEAR) THEN ('PA' || ROBINST_AIDY_START_YEAR)                 --PA2025 FOR FY26
	WHEN SARCHRT_CHRT_CODE = ('PA' || (TO_NUMBER(ROBINST_AIDY_START_YEAR)-1)) THEN ('PA' || (TO_NUMBER(ROBINST_AIDY_START_YEAR)-1))     --PA2024 FOR FY26
    WHEN SARCHRT_CHRT_CODE = (ROBINST_AIDY_END_YEAR || 'SLH') THEN (ROBINST_AIDY_END_YEAR || 'SLH')                   --2026SLH FOR FY26
    WHEN SARCHRT_CHRT_CODE = (ROBINST_AIDY_END_YEAR || 'SLH') THEN (ROBINST_AIDY_END_YEAR || 'SLH')                   --2025SLH FOR FY26
END = RORALGS_KEY_11

AND CASE -- term
    WHEN (ROBINST_AIDY_END_YEAR || '10') = :PERIOD THEN 'FALL'
    WHEN (ROBINST_AIDY_END_YEAR || '20') = :PERIOD THEN 'SPRING'
END = RORALGS_KEY_12
			
-- max saradap term <= passed period	
AND X.SARADAP_TERM_CODE_ENTRY = (
     SELECT MAX(Y.SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP Y, ROBINST
    WHERE Y.SARADAP_PIDM = X.SARADAP_PIDM
	AND Y.SARADAP_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
    AND Y.SARADAP_TERM_CODE_ENTRY <= :PERIOD
	AND ROBINST_AIDY_CODE = :AIDY
)
--max application decision code sequence number
AND X.SARAPPD_SEQ_NO = (SELECT MAX (X.SARAPPD_SEQ_NO)
	FROM SARAPPD Y, ROBINST
	WHERE     Y.SARAPPD_PIDM = X.SARAPPD_PIDM
	AND Y.SARAPPD_SEQ_NO < 99
	AND Y.SARAPPD_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
	AND Y.SARAPPD_TERM_CODE_ENTRY <= :PERIOD
	AND ROBINST_AIDY_CODE = :AIDY           
	AND X.SARADAP_APPL_NO = Y.SARAPPD_APPL_NO) 
      
AND STVAPDC_INST_ACC_IND = 'Y'
AND STVAPDC_SIGNF_IND = 'Y'
		
AND X.SARAPPD_APDC_CODE = STVAPDC_CODE	
AND X.SARADAP_APPL_NO = X.SARAPPD_APPL_NO
AND X.SARADAP_APPL_NO = SARCHRT_APPL_NO
AND X.SARADAP_TERM_CODE_ENTRY = X.SARAPPD_TERM_CODE_ENTRY
AND X.SARADAP_TERM_CODE_ENTRY = SARCHRT_TERM_CODE_ENTRY
AND RORALGS_AIDY_CODE = ROBINST_AIDY_CODE
AND RORALGS_AIDY_CODE = :AIDY
AND X.SARADAP_PIDM = X.SARAPPD_PIDM
AND X.SARADAP_PIDM = SARCHRT_PIDM
AND X.SARADAP_PIDM = :PIDM
--END




--GRAD SE, BA, PS, G% ATTRIBUTES WITH SGASTDN
--DON'T NEED SEQUENCE FOR ENROLLED SINCE IT'S ALWAYS A FLAT RATE
SELECT RORALGS_AMT
FROM SGBSTDN X, SGRSATT X, RORALGS
WHERE RORALGS_KEY_1 = 'PBDG'

AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
    WHEN X.SGBSTDN_LEVL_CODE = 'GR' THEN 'GR'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SGBSTDN_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
	
AND CASE -- college code
    WHEN X.SGBSTDN_COLL_CODE_1 = 'SE' THEN 'SE'
    WHEN X.SGBSTDN_COLL_CODE_1 = 'BA' THEN 'BA'
	WHEN X.SGBSTDN_COLL_CODE_1 = 'PS' THEN 'PS'
END = RORALGS_KEY_7
	
AND CASE -- cohort code
    WHEN X.SGRSATT_ATTS_CODE = 'GG2' THEN 'GG2'
    WHEN X.SGRSATT_ATTS_CODE = 'GG3' THEN 'GG3'
	WHEN X.SGRSATT_ATTS_CODE = 'GG4' THEN 'GG4'
	WHEN X.SGRSATT_ATTS_CODE = 'GG5' THEN 'GG5'
	WHEN X.SGRSATT_ATTS_CODE = 'GGI2' THEN 'GGI2'
	WHEN X.SGRSATT_ATTS_CODE = 'GGI3' THEN 'GGI3'
END = RORALGS_KEY_10
	
-- max sgbstdn term <= passed period
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
	--max attribute term <= passed term
AND X.SGRSATT_TERM_CODE_EFF = (
SELECT MAX(Y.SGRSATT_TERM_CODE_EFF)
    FROM SGRSATT Y
    WHERE Y.SGRSATT_TERM_CODE_EFF <= :PERIOD
	AND X.SGRSATT_PIDM =  Y.SGRSATT_PIDM
)
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_PIDM = X.SGRSATT_PIDM
AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
--END

--GRAD SE, BA, PS, G% ATTRIBUTES NO SGASTDN
SELECT RORALGS_AMT
FROM SARADAP X, SARAPPD X, SARAATT, RORALGS, STVAPDC
WHERE RORALGS_KEY_1 = 'PBDG'

AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
    WHEN X.SARADAP_LEVL_CODE = 'GR' THEN 'GR'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SARADAP_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
	
AND CASE -- college code
    WHEN X.SARADAP_COLL_CODE_1 = 'SE' THEN 'SE'
    WHEN X.SARADAP_COLL_CODE_1 = 'BA' THEN 'BA'
	WHEN X.SARADAP_COLL_CODE_1 = 'PS' THEN 'PS'
END = RORALGS_KEY_7
	
AND CASE -- cohort code
    WHEN SARAATT_ATTS_CODE = 'GG2' THEN 'GG2'
    WHEN SARAATT_ATTS_CODE = 'GG3' THEN 'GG3'
	WHEN SARAATT_ATTS_CODE = 'GG4' THEN 'GG4'
	WHEN SARAATT_ATTS_CODE = 'GG5' THEN 'GG5'
	WHEN SARAATT_ATTS_CODE = 'GGI2' THEN 'GGI2'
	WHEN SARAATT_ATTS_CODE = 'GGI3' THEN 'GGI3'
END = RORALGS_KEY_10
	
-- max saradap term <= passed period	
AND X.SARADAP_TERM_CODE_ENTRY = (
     SELECT MAX(Y.SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP Y, ROBINST
    WHERE Y.SARADAP_PIDM = X.SARADAP_PIDM
	AND Y.SARADAP_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
    AND Y.SARADAP_TERM_CODE_ENTRY <= :PERIOD
	AND ROBINST_AIDY_CODE = :AIDY
)
--max application decision code sequence number
AND X.SARAPPD_SEQ_NO = (SELECT MAX (X.SARAPPD_SEQ_NO)
	FROM SARAPPD Y, ROBINST
	WHERE     Y.SARAPPD_PIDM = X.SARAPPD_PIDM
	AND Y.SARAPPD_SEQ_NO < 99
	AND Y.SARAPPD_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
	AND Y.SARAPPD_TERM_CODE_ENTRY <= :PERIOD
	AND ROBINST_AIDY_CODE = :AIDY           
	AND X.SARADAP_APPL_NO = Y.SARAPPD_APPL_NO) 
      
AND STVAPDC_INST_ACC_IND = 'Y'
AND STVAPDC_SIGNF_IND = 'Y'
		
AND X.SARAPPD_APDC_CODE = STVAPDC_CODE	
AND X.SARADAP_APPL_NO = X.SARAPPD_APPL_NO
AND X.SARADAP_APPL_NO = SARAATT_APPL_NO
AND X.SARADAP_TERM_CODE_ENTRY = X.SARAPPD_TERM_CODE_ENTRY
AND X.SARADAP_TERM_CODE_ENTRY = SARAATT_TERM_CODE
AND RORALGS_AIDY_CODE = :AIDY
AND X.SARADAP_PIDM = X.SARAPPD_PIDM
AND X.SARADAP_PIDM = SARAATT_PIDM
AND X.SARADAP_PIDM = :PIDM
--END




--GRAD SS, BA, PS, NO ATTRIBUTES/RATES/COHORT ENROLLED
SELECT CASE
    WHEN NVL(ROKMISC.F_CALC_STUD_CREDIT_HRS(:PERIOD, X.SGBSTDN_PIDM, 'N'), 0) > 0
        THEN round(roralgs_amt * NVL(ROKMISC.F_CALC_STUD_CREDIT_HRS(:PERIOD, X.SGBSTDN_PIDM, 'N'), 0))
    END as calc_amt
FROM SGBSTDN X, RORALGS
WHERE RORALGS_KEY_1 = 'PBDG'

AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
    WHEN X.SGBSTDN_LEVL_CODE = 'GR' THEN 'GR'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SGBSTDN_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
	
AND CASE -- college code
    WHEN X.SGBSTDN_COLL_CODE_1 = 'SS' THEN 'SS'              --$1,400 in FY26
    WHEN X.SGBSTDN_COLL_CODE_1 = 'BA' THEN 'BA'              --$1,250 in FY26
	WHEN X.SGBSTDN_COLL_CODE_1 = 'PS' THEN 'PS'              --$810 in FY26
END = RORALGS_KEY_7
	
-- max sgbstdn term <= passed period
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
--END

--GRAD SS, BA, PS, NO ATTRIBUTES/RATES/COHORT NOT ENROLLED WITH SGASTDN
SELECT (RORALGS_AMT * 6)                                                           
FROM SGBSTDN X, RORALGS
WHERE RORALGS_KEY_1 = 'PBDG'

AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
    WHEN X.SGBSTDN_LEVL_CODE = 'GR' THEN 'GR'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SGBSTDN_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
	
AND CASE -- college code
    WHEN X.SGBSTDN_COLL_CODE_1 = 'SS' THEN 'SS'              --$1,400 in FY26
    WHEN X.SGBSTDN_COLL_CODE_1 = 'BA' THEN 'BA'              --$1,250 in FY26
	WHEN X.SGBSTDN_COLL_CODE_1 = 'PS' THEN 'PS'              --$810 in FY26
END = RORALGS_KEY_7
	
-- max sgbstdn term <= passed period
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
--END

--GRAD SS, BA, PS, NO ATTRIBUTES/RATES/COHORT NO SGASTDN
SELECT (RORALGS_AMT * 6)                                                           
FROM SARADAP X, SARAPPD X, RORALGS, STVAPDC
WHERE RORALGS_KEY_1 = 'PBDG'

AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
    WHEN X.SARADAP_LEVL_CODE = 'GR' THEN 'GR'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SARADAP_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
	
AND CASE -- college code
    WHEN X.SARADAP_COLL_CODE_1 = 'SS' THEN 'SS'              --$1,400 in FY26
    WHEN X.SARADAP_COLL_CODE_1 = 'BA' THEN 'BA'              --$1,250 in FY26
	WHEN X.SARADAP_COLL_CODE_1 = 'PS' THEN 'PS'              --$810 in FY26
END = RORALGS_KEY_7
	
-- max saradap term <= passed period	
AND X.SARADAP_TERM_CODE_ENTRY = (
     SELECT MAX(Y.SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP Y, ROBINST
    WHERE Y.SARADAP_PIDM = X.SARADAP_PIDM
	AND Y.SARADAP_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
    AND Y.SARADAP_TERM_CODE_ENTRY <= :PERIOD
	AND ROBINST_AIDY_CODE = :AIDY
)
--max application decision code sequence number
AND X.SARAPPD_SEQ_NO = (SELECT MAX (X.SARAPPD_SEQ_NO)
	FROM SARAPPD Y, ROBINST
	WHERE     Y.SARAPPD_PIDM = X.SARAPPD_PIDM
	AND Y.SARAPPD_SEQ_NO < 99
	AND Y.SARAPPD_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
	AND Y.SARAPPD_TERM_CODE_ENTRY <= :PERIOD
	AND ROBINST_AIDY_CODE = :AIDY           
	AND X.SARADAP_APPL_NO = Y.SARAPPD_APPL_NO) 
      
AND STVAPDC_INST_ACC_IND = 'Y'
AND STVAPDC_SIGNF_IND = 'Y'

AND X.SARAPPD_APDC_CODE = STVAPDC_CODE	
AND X.SARADAP_APPL_NO = X.SARAPPD_APPL_NO
AND X.SARADAP_TERM_CODE_ENTRY = X.SARAPPD_TERM_CODE_ENTRY
AND RORALGS_AIDY_CODE = :AIDY
AND X.SARAPPD_PIDM = X.SARADAP_PIDM	
AND X.SARADAP_PIDM = :PIDM
--END




--Haley will send new program codes and rates for school of education
--GRAD WITH SELECT EDUCATION PROGRAM CODES ENROLLED
SELECT CASE
    WHEN NVL(ROKMISC.F_CALC_STUD_CREDIT_HRS(:PERIOD, X.SGBSTDN_PIDM, 'N'), 0) > 0
        THEN round(roralgs_amt * NVL(ROKMISC.F_CALC_STUD_CREDIT_HRS(:PERIOD, X.SGBSTDN_PIDM, 'N'), 0))
    END as calc_amt
FROM SGBSTDN X, RORALGS
WHERE RORALGS_KEY_1 = 'PBDG'

AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
    WHEN X.SGBSTDN_LEVL_CODE = 'GR' THEN 'GR'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SGBSTDN_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
	
AND CASE -- major/program code
	WHEN X.SGBSTDN_PROGRAM_1 = 'ELCE12' THEN 'ELCE12'         --$450 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'ELCE13' THEN 'ELCE13'         --$450 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'ELCE14' THEN 'ELCE14'         --$450 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'ELCE16' THEN 'ELCE16'         --$450 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'ELCE17' THEN 'ELCE17'         --$450 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'ELCE18' THEN 'ELCE18'         --$450 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'TEAC12' THEN 'TEAC12'         --$450 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'TEAC13' THEN 'TEAC13'         --$450 for FY26
	
	WHEN X.SGBSTDN_PROGRAM_1 = 'EALM41' THEN 'ELAM41'         --$690 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDI11' THEN 'EDI11'         --$690 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDL11' THEN 'EDL11'         --$690 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDL13' THEN 'EDL13'         --$690 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDL18' THEN 'EDL18'         --$690 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDE41' THEN 'EDE41'         --$690 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'EIP41' THEN 'EIP41'         --$690 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'ELCE21' THEN 'ELCE21'         --$690 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'ELCE22' THEN 'ELCE22'         --$690 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'ELCE23' THEN 'ELCE23'         --$690 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'EPP11' THEN 'EPP11'         --$690 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'HESA11' THEN 'HESA11'         --$690 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'TEAC11' THEN 'TEAC11'         --$690 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'TEAC14' THEN 'TEAC14'         --$690 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'TEAC15' THEN 'TEAC15'         --$690 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'TEAC17' THEN 'TEAC17'         --$690 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'TEAC18' THEN 'TEAC18'         --$690 for FY26
	
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDL15' THEN 'EDL15'         --$990 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDL21' THEN 'EDL21'         --$990 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDL22' THEN 'EDL22'         --$990 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDL221' THEN 'EDL221'         --$990 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDL222' THEN 'EDL222'         --$990 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDL223' THEN 'EDL223'         --$990 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDL225' THEN 'EDL225'         --$990 for FY26
	
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDF22' THEN 'EDF22'         --$1,400 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDHA22' THEN 'EDHA22'         --$1,400 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDI21' THEN 'EDI21'         --$1,400 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDL24' THEN 'EDL24'         --$1,400 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDS22' THEN 'EDS22'         --$1,400 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'EPE21' THEN 'EPE21'         --$1,400 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'UNCL883' THEN 'UNCL883'         --$1,400 for FY26
END = RORALGS_KEY_9		
		
-- max sgbstdn term <= passed period
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
-- END


--Haley will send new program codes and rates for school of education
--GRAD WITH SELECT EDUCATION PROGRAM CODES NOT ENROLLED WITH SGASTDN
SELECT (RORALGS_AMT * 6)                                                           
FROM SGBSTDN X, RORALGS
WHERE RORALGS_KEY_1 = 'PBDG'

AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
    WHEN X.SGBSTDN_LEVL_CODE = 'GR' THEN 'GR'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SGBSTDN_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
	
AND CASE -- major/program code
	WHEN X.SGBSTDN_PROGRAM_1 = 'ELCE12' THEN 'ELCE12'         --$450 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'ELCE13' THEN 'ELCE13'         --$450 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'ELCE14' THEN 'ELCE14'         --$450 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'ELCE16' THEN 'ELCE16'         --$450 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'ELCE17' THEN 'ELCE17'         --$450 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'ELCE18' THEN 'ELCE18'         --$450 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'TEAC12' THEN 'TEAC12'         --$450 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'TEAC13' THEN 'TEAC13'         --$450 for FY26
	
	WHEN X.SGBSTDN_PROGRAM_1 = 'EALM41' THEN 'ELAM41'         --$690 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDI11' THEN 'EDI11'         --$690 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDL11' THEN 'EDL11'         --$690 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDL13' THEN 'EDL13'         --$690 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDL18' THEN 'EDL18'         --$690 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDE41' THEN 'EDE41'         --$690 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'EIP41' THEN 'EIP41'         --$690 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'ELCE21' THEN 'ELCE21'         --$690 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'ELCE22' THEN 'ELCE22'         --$690 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'ELCE23' THEN 'ELCE23'         --$690 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'EPP11' THEN 'EPP11'         --$690 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'HESA11' THEN 'HESA11'         --$690 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'TEAC11' THEN 'TEAC11'         --$690 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'TEAC14' THEN 'TEAC14'         --$690 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'TEAC15' THEN 'TEAC15'         --$690 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'TEAC17' THEN 'TEAC17'         --$690 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'TEAC18' THEN 'TEAC18'         --$690 for FY26
	
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDL15' THEN 'EDL15'         --$990 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDL21' THEN 'EDL21'         --$990 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDL22' THEN 'EDL22'         --$990 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDL221' THEN 'EDL221'         --$990 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDL222' THEN 'EDL222'         --$990 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDL223' THEN 'EDL223'         --$990 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDL225' THEN 'EDL225'         --$990 for FY26
	
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDF22' THEN 'EDF22'         --$1,400 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDHA22' THEN 'EDHA22'         --$1,400 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDI21' THEN 'EDI21'         --$1,400 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDL24' THEN 'EDL24'         --$1,400 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDS22' THEN 'EDS22'         --$1,400 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'EPE21' THEN 'EPE21'         --$1,400 for FY26
	WHEN X.SGBSTDN_PROGRAM_1 = 'UNCL883' THEN 'UNCL883'         --$1,400 for FY26
END = RORALGS_KEY_9		
		
-- max sgbstdn term <= passed period
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
-- END

--Haley will send new program codes and rates for school of education
--GRAD WITH SELECT EDUCATION PROGRAM CODES NO SGASTDN ENROLLED
SELECT (RORALGS_AMT * 6)                                                           
FROM SARADAP X, SARAPPD X, RORALGS, STVAPDC
WHERE RORALGS_KEY_1 = 'PBDG'

AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
    WHEN X.SARADAP_LEVL_CODE = 'GR' THEN 'GR'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SARADAP_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
	
AND CASE -- major/program code
	WHEN X.SARADAP_PROGRAM_1 = 'ELCE12' THEN 'ELCE12'         --$450 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'ELCE13' THEN 'ELCE13'         --$450 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'ELCE14' THEN 'ELCE14'         --$450 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'ELCE16' THEN 'ELCE16'         --$450 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'ELCE17' THEN 'ELCE17'         --$450 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'ELCE18' THEN 'ELCE18'         --$450 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'TEAC12' THEN 'TEAC12'         --$450 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'TEAC13' THEN 'TEAC13'         --$450 for FY26
	
	WHEN X.SARADAP_PROGRAM_1 = 'EALM41' THEN 'ELAM41'         --$690 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'EDI11' THEN 'EDI11'         --$690 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'EDL11' THEN 'EDL11'         --$690 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'EDL13' THEN 'EDL13'         --$690 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'EDL18' THEN 'EDL18'         --$690 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'EDE41' THEN 'EDE41'         --$690 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'EIP41' THEN 'EIP41'         --$690 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'ELCE21' THEN 'ELCE21'         --$690 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'ELCE22' THEN 'ELCE22'         --$690 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'ELCE23' THEN 'ELCE23'         --$690 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'EPP11' THEN 'EPP11'         --$690 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'HESA11' THEN 'HESA11'         --$690 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'TEAC11' THEN 'TEAC11'         --$690 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'TEAC14' THEN 'TEAC14'         --$690 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'TEAC15' THEN 'TEAC15'         --$690 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'TEAC17' THEN 'TEAC17'         --$690 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'TEAC18' THEN 'TEAC18'         --$690 for FY26
	
	WHEN X.SARADAP_PROGRAM_1 = 'EDL15' THEN 'EDL15'         --$990 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'EDL21' THEN 'EDL21'         --$990 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'EDL22' THEN 'EDL22'         --$990 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'EDL221' THEN 'EDL221'         --$990 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'EDL222' THEN 'EDL222'         --$990 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'EDL223' THEN 'EDL223'         --$990 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'EDL225' THEN 'EDL225'         --$990 for FY26
	
	WHEN X.SARADAP_PROGRAM_1 = 'EDF22' THEN 'EDF22'         --$1,400 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'EDHA22' THEN 'EDHA22'         --$1,400 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'EDI21' THEN 'EDI21'         --$1,400 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'EDL24' THEN 'EDL24'         --$1,400 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'EDS22' THEN 'EDS22'         --$1,400 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'EPE21' THEN 'EPE21'         --$1,400 for FY26
	WHEN X.SARADAP_PROGRAM_1 = 'UNCL883' THEN 'UNCL883'         --$1,400 for FY26
END = RORALGS_KEY_9		
		
-- max saradap term <= passed period	
AND X.SARADAP_TERM_CODE_ENTRY = (
     SELECT MAX(Y.SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP Y, ROBINST
    WHERE Y.SARADAP_PIDM = X.SARADAP_PIDM
	AND Y.SARADAP_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
    AND Y.SARADAP_TERM_CODE_ENTRY <= :PERIOD
	AND ROBINST_AIDY_CODE = :AIDY
)
--max application decision code sequence number
AND X.SARAPPD_SEQ_NO = (SELECT MAX (X.SARAPPD_SEQ_NO)
	FROM SARAPPD Y, ROBINST
	WHERE     Y.SARAPPD_PIDM = X.SARAPPD_PIDM
	AND Y.SARAPPD_SEQ_NO < 99
	AND Y.SARAPPD_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
	AND Y.SARAPPD_TERM_CODE_ENTRY <= :PERIOD
	AND ROBINST_AIDY_CODE = :AIDY           
	AND X.SARADAP_APPL_NO = Y.SARAPPD_APPL_NO) 
      
AND STVAPDC_INST_ACC_IND = 'Y'
AND STVAPDC_SIGNF_IND = 'Y'

AND X.SARAPPD_APDC_CODE = STVAPDC_CODE	
AND X.SARADAP_APPL_NO = X.SARAPPD_APPL_NO
AND X.SARADAP_TERM_CODE_ENTRY = X.SARAPPD_TERM_CODE_ENTRY
AND RORALGS_AIDY_CODE = :AIDY
AND X.SARAPPD_PIDM = X.SARADAP_PIDM	
AND X.SARADAP_PIDM = :PIDM
-- END




--GRAD FR CAMPUS ...FALL THROUGH GROUP ENROLLED
SELECT CASE
    WHEN NVL(ROKMISC.F_CALC_STUD_CREDIT_HRS(:PERIOD, X.SGBSTDN_PIDM, 'N'), 0) > 0
        THEN round(roralgs_amt * NVL(ROKMISC.F_CALC_STUD_CREDIT_HRS(:PERIOD, X.SGBSTDN_PIDM, 'N'), 0))
    END as calc_amt
FROM SGBSTDN X, RORALGS
WHERE RORALGS_KEY_1 = 'PBDG'

AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
    WHEN X.SGBSTDN_LEVL_CODE = 'GR' THEN 'GR'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SGBSTDN_CAMP_CODE = 'FR' THEN 'FR'                   
END = RORALGS_KEY_6
	
-- max sgbstdn term <= passed period
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
--END


--GRAD FR CAMPUS ...FALL THROUGH GROUP NOT ENROLLED WITH SGASTDN
SELECT (roralgs_amt * 6)
FROM SGBSTDN X, RORALGS
WHERE RORALGS_KEY_1 = 'PBDG'

AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
    WHEN X.SGBSTDN_LEVL_CODE = 'GR' THEN 'GR'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SGBSTDN_CAMP_CODE = 'FR' THEN 'FR'                   
END = RORALGS_KEY_6
	
-- max sgbstdn term <= passed period
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
--END

--GRAD FR CAMPUS ...FALL THROUGH GROUP NO SGASTDN
SELECT (roralgs_amt * 6)
FROM SARADAP X, SARAPPD X, RORALGS, STVAPDC
WHERE RORALGS_KEY_1 = 'PBDG'

AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
    WHEN X.SARADAP_LEVL_CODE = 'GR' THEN 'GR'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SARADAP_CAMP_CODE = 'FR' THEN 'FR'                   
END = RORALGS_KEY_6
	
-- max saradap term <= passed period	
AND X.SARADAP_TERM_CODE_ENTRY = (
     SELECT MAX(Y.SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP Y, ROBINST
    WHERE Y.SARADAP_PIDM = X.SARADAP_PIDM
	AND Y.SARADAP_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
    AND Y.SARADAP_TERM_CODE_ENTRY <= :PERIOD
	AND ROBINST_AIDY_CODE = :AIDY
)
--max application decision code sequence number
AND X.SARAPPD_SEQ_NO = (SELECT MAX (X.SARAPPD_SEQ_NO)
	FROM SARAPPD Y, ROBINST
	WHERE     Y.SARAPPD_PIDM = X.SARAPPD_PIDM
	AND Y.SARAPPD_SEQ_NO < 99
	AND Y.SARAPPD_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
	AND Y.SARAPPD_TERM_CODE_ENTRY <= :PERIOD
	AND ROBINST_AIDY_CODE = :AIDY           
	AND X.SARADAP_APPL_NO = Y.SARAPPD_APPL_NO) 
      
AND STVAPDC_INST_ACC_IND = 'Y'
AND STVAPDC_SIGNF_IND = 'Y'

AND X.SARAPPD_APDC_CODE = STVAPDC_CODE	
AND X.SARADAP_APPL_NO = X.SARAPPD_APPL_NO
AND X.SARADAP_TERM_CODE_ENTRY = X.SARAPPD_TERM_CODE_ENTRY
AND RORALGS_AIDY_CODE = :AIDY
AND X.SARAPPD_PIDM = X.SARADAP_PIDM	
AND X.SARADAP_PIDM = :PIDM
--END