select *
from sgbstdn x
-- WHERE X.SGBSTDN_PROGRAM_1 in ('HOR23', 'AN11', 'MDSC11')
WHERE X.SGBSTDN_DEGC_CODE_1 in ('PBC', 'PHD')
and X.SGBSTDN_LEVL_CODE = 'GR'
and x.sgbstdn_coll_code_1 = 'SS';

desc sgbstdn;
select *
from RORALGS where RORALGS_AIDY_CODE = '2627'
    AND RORALGS_KEY_1 = 'PBDG'
    AND RORALGS_KEY_4 = '1TUI'    
    AND RORALGS_KEY_5 = 'PM'
    AND (RORALGS_KEY_9 in ('HOR23', 'AN11', 'MDSC11') or RORALGS_KEY_9 IS NULL);

select X.SGBSTDN_LEVL_CODE, X.SGBSTDN_PROGRAM_1, count(*)
from sgbstdn x
WHERE X.SGBSTDN_PROGRAM_1 in ('HOR23', 'AN11', 'MDSC11')
and X.SGBSTDN_LEVL_CODE = 'PM'
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= '202710'
)
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
group by X.SGBSTDN_LEVL_CODE, X.SGBSTDN_PROGRAM_1;
--MED ENROLLED OR NOT ENROLLED WITH SGASTDN
-- 926 rows before changes made
SELECT RORALGS_AMT, X.SGBSTDN_PIDM
FROM SGBSTDN X
INNER JOIN RORALGS on RORALGS_AIDY_CODE = :AIDY
    AND RORALGS_KEY_1 = 'PBDG'
    AND RORALGS_KEY_4 = '1TUI'    
    AND RORALGS_KEY_5 = X.SGBSTDN_LEVL_CODE
    AND RORALGS_KEY_9 IS NULL
    -- AND (RORALGS_KEY_9 = X.SGBSTDN_PROGRAM_1 or RORALGS_KEY_9 IS NULL)
WHERE X.SGBSTDN_LEVL_CODE = 'PM'
-- AND X.SGBSTDN_PROGRAM_1 in ('HOR23', 'AN11', 'MDSC11') or X.SGBSTDN_PROGRAM_1 LIKE 'MED%'
-- max sgbstdn term <= passed period
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)

-- no application within the aid year for a different program
AND NOT EXISTS (
    SELECT 1
    FROM SARADAP
    INNER JOIN ROBINST on ROBINST_AIDY_CODE = :AIDY
    INNER JOIN SARAPPD
        ON SARAPPD_PIDM = SARADAP_PIDM
        AND SARAPPD_APPL_NO = SARADAP_APPL_NO
        AND SARAPPD_TERM_CODE_ENTRY = SARADAP_TERM_CODE_ENTRY
    INNER JOIN STVAPDC
        ON STVAPDC_CODE = SARAPPD_APDC_CODE
        AND STVAPDC_INST_ACC_IND = 'Y'
        AND STVAPDC_SIGNF_IND = 'Y'
    WHERE SARADAP_PIDM = X.SGBSTDN_PIDM
    AND SARADAP_TERM_CODE_ENTRY > X.SGBSTDN_TERM_CODE_EFF 
    AND SARADAP_TERM_CODE_ENTRY <= ((ROBINST_AIDY_END_YEAR + 1) || '00')
    AND SARADAP_PROGRAM_1 <> X.SGBSTDN_PROGRAM_1
)
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
-- AND X.SGBSTDN_PIDM = :PIDM
--END

;

--MED NOT ENROLLED no SGASTDN
SELECT RORALGS_AMT
FROM SARADAP a
INNER JOIN ROBINST on ROBINST_AIDY_CODE = :AIDY
INNER JOIN SARAPPD b
    ON SARAPPD_PIDM = SARADAP_PIDM
    AND SARAPPD_APPL_NO = SARADAP_APPL_NO
    AND SARAPPD_TERM_CODE_ENTRY = SARADAP_TERM_CODE_ENTRY
INNER JOIN STVAPDC c
    ON STVAPDC_CODE = SARAPPD_APDC_CODE
    AND STVAPDC_INST_ACC_IND = 'Y'
    AND STVAPDC_SIGNF_IND = 'Y'
INNER JOIN RORALGS on RORALGS_AIDY_CODE = :AIDY
    AND RORALGS_KEY_1 = 'PBDG'
    AND RORALGS_KEY_4 = '1TUI'    
    AND RORALGS_KEY_5 = SARADAP_LEVL_CODE
    AND RORALGS_KEY_9 IS NULL
WHERE SARADAP_LEVL_CODE = 'PM'
AND SARADAP_TERM_CODE_ENTRY = (
    SELECT MAX(Y.SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP Y
    WHERE Y.SARADAP_PIDM = a.SARADAP_PIDM
    AND Y.SARADAP_TERM_CODE_ENTRY between (ROBINST_AIDY_END_YEAR || '00') and :PERIOD
)
AND SARAPPD_SEQ_NO = (
    SELECT MAX(Y.SARAPPD_SEQ_NO)
    FROM SARAPPD Y
    WHERE Y.SARAPPD_PIDM = b.SARAPPD_PIDM
    AND Y.SARAPPD_TERM_CODE_ENTRY = b.SARAPPD_TERM_CODE_ENTRY
    AND Y.SARAPPD_APPL_NO = b.SARAPPD_APPL_NO
) 
-- AND SARADAP_PIDM = :PIDM
--END
;


--MED NOT ENROLLED no SGASTDN
SELECT RORALGS_AMT, SARADAP_PIDM
    FROM SARADAP X, SARAPPD X, RORALGS, STVAPDC
WHERE RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
	WHEN X.SARADAP_LEVL_CODE = 'PM' THEN 'PM'
END = RORALGS_KEY_5

-- max saradap term <= passed period
AND X.SARADAP_TERM_CODE_ENTRY = (
    SELECT MAX(X.SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP Y, ROBINST
    WHERE Y.SARADAP_PIDM = X.SARADAP_PIDM
    AND Y.SARADAP_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')   	
	AND Y.SARADAP_TERM_CODE_ENTRY <= :PERIOD
	AND ROBINST_AIDY_CODE = :AIDY   
)

--max application decision code sequence number
AND X.SARAPPD_SEQ_NO = (
    SELECT MAX (X.SARAPPD_SEQ_NO)
    FROM SARAPPD Y, ROBINST
    WHERE     Y.SARAPPD_PIDM = X.SARAPPD_PIDM
    AND Y.SARAPPD_SEQ_NO < 99
    AND Y.SARAPPD_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
    AND Y.SARAPPD_TERM_CODE_ENTRY <= :PERIOD
    AND ROBINST_AIDY_CODE = :AIDY           
    AND X.SARADAP_APPL_NO = Y.SARAPPD_APPL_NO
) 

AND STVAPDC_INST_ACC_IND = 'Y'
AND STVAPDC_SIGNF_IND = 'Y'
AND X.SARAPPD_APDC_CODE = STVAPDC_CODE	
AND X.SARADAP_APPL_NO = X.SARAPPD_APPL_NO
AND X.SARADAP_TERM_CODE_ENTRY = X.SARAPPD_TERM_CODE_ENTRY
AND RORALGS_AIDY_CODE = :AIDY
AND X.SARAPPD_PIDM = X.SARADAP_PIDM	
-- AND X.SARADAP_PIDM = :PIDM
--END
