SELECT RORSTAT_PIDM
FROM RORSTAT
JOIN ROBINST on ROBINST_AIDY_CODE = RORSTAT_AIDY_CODE
    AND ROBINST_STATUS_IND = 'A'
WHERE RORSTAT_AIDY_CODE = :AIDY  
-- AND RORSTAT_PIDM = :PIDM                                         
AND EXISTS (
    SELECT 1
    FROM SARADAP a
    JOIN SARAPPD b on b.SARAPPD_PIDM = a.SARADAP_PIDM
        and b.SARAPPD_TERM_CODE_ENTRY = a.SARADAP_TERM_CODE_ENTRY
        and b.SARAPPD_APPL_NO = a.SARADAP_APPL_NO
    JOIN STVAPDC c on c.STVAPDC_CODE = b.SARAPPD_APDC_CODE
        and c.STVAPDC_INST_ACC_IND = 'Y'
        and c.STVAPDC_SIGNF_IND = 'Y'
    WHERE a.SARADAP_PIDM = RORSTAT_PIDM
    AND a.SARADAP_LEVL_CODE = 'UG'
    and a.SARADAP_COLL_CODE_1 = 'PL'
    and a.SARADAP_MAJR_CODE_1 <> 'CAST02'
    AND a.SARADAP_TERM_CODE_ENTRY = (
        SELECT MAX(z.SARADAP_TERM_CODE_ENTRY) 
        FROM SARADAP z
        WHERE z.SARADAP_PIDM = a.SARADAP_PIDM
        AND z.SARADAP_TERM_CODE_ENTRY between 
            SUBSTR(ROBINST_AIDY_END_YEAR,0,4) || '10' 
            and SUBSTR(ROBINST_AIDY_END_YEAR + 1,0,4) || '00'
    )
    AND a.SARADAP_APPL_NO = (
        SELECT MAX(z.SARADAP_APPL_NO) 
        FROM SARADAP z
        WHERE z.SARADAP_PIDM = a.SARADAP_PIDM
        AND z.SARADAP_TERM_CODE_ENTRY = a.SARADAP_TERM_CODE_ENTRY
    )
    AND b.SARAPPD_SEQ_NO = (
        SELECT MAX(z.SARAPPD_SEQ_NO) 
        FROM SARAPPD z
        WHERE z.SARAPPD_PIDM = b.SARAPPD_PIDM
        AND z.SARAPPD_TERM_CODE_ENTRY = b.SARAPPD_TERM_CODE_ENTRY
        AND z.SARAPPD_APPL_NO = b.SARAPPD_APPL_NO
    )
);
-- AND RORSTAT_PIDM    =:PIDM

-- 26