--UG PS COLLEGE NOT ENROLLED WITH SGASTDN 
SELECT (roralgs_amt * 12) as amt
FROM SGBSTDN X
left join SGRSATT b on b.SGRSATT_PIDM = x.SGBSTDN_PIDM
    AND b.SGRSATT_TERM_CODE_EFF = (
        SELECT MAX(Y.SGRSATT_TERM_CODE_EFF)
        FROM SGRSATT Y
        WHERE Y.SGRSATT_TERM_CODE_EFF <= :PERIOD
        AND Y.SGRSATT_PIDM =  b.SGRSATT_PIDM
    )
    and sgrsatt_atts_code in ('PSMV', 'PS15', 'REGV', 'REGF')
left join RORALGS on RORALGS_AIDY_CODE = :AIDY
    and RORALGS_KEY_1 = 'PBDG'
    AND RORALGS_KEY_4 = '1TUI'
    and RORALGS_KEY_5 = X.SGBSTDN_LEVL_CODE
    and RORALGS_KEY_6 = X.SGBSTDN_CAMP_CODE
    and RORALGS_KEY_7 = X.SGBSTDN_COLL_CODE_1
    and RORALGS_KEY_9 is null
    and (
        RORALGS_KEY_10 = b.SGRSATT_ATTS_CODE
        or (RORALGS_KEY_10 IS NULL and b.SGRSATT_ATTS_CODE is null)
    )
    and RORALGS_KEY_11 is null
WHERE X.SGBSTDN_LEVL_CODE = 'UG'
AND X.SGBSTDN_CAMP_CODE = 'FR'
AND X.SGBSTDN_COLL_CODE_1 = 'PS'
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND X.SGBSTDN_PIDM = :PIDM
AND NOT EXISTS (
    SELECT 1
    FROM SARADAP
    INNER JOIN SARAPPD
        ON SARAPPD_PIDM = SARADAP_PIDM
        AND SARAPPD_APPL_NO = SARADAP_APPL_NO
        AND SARAPPD_TERM_CODE_ENTRY = SARADAP_TERM_CODE_ENTRY
    INNER JOIN STVAPDC
        ON STVAPDC_CODE = SARAPPD_APDC_CODE
        AND STVAPDC_INST_ACC_IND = 'Y'
        AND STVAPDC_SIGNF_IND = 'Y'
    WHERE SARADAP_PIDM = X.SGBSTDN_PIDM
    AND SARADAP_TERM_CODE_ENTRY > X.SGBSTDN_TERM_CODE_EFF 
    AND SARADAP_TERM_CODE_ENTRY <= ('20' || cast(substr(:AIDY, 3, 2) as int) + 1 || '00')
    AND SARADAP_PROGRAM_1 <> X.SGBSTDN_PROGRAM_1
)
