--UG PS COLLEGE NOT ENROLLED NO SGASTDN 
SELECT (roralgs_amt * 12) as amt
FROM SARADAP a
JOIN SARAPPD b on b.SARAPPD_PIDM = a.SARADAP_PIDM
    and b.SARAPPD_APPL_NO = a.SARADAP_APPL_NO
    and b.SARAPPD_TERM_CODE_ENTRY = a.SARADAP_TERM_CODE_ENTRY
JOIN STVAPDC c on c.STVAPDC_CODE = b.SARAPPD_APDC_CODE
    and STVAPDC_INST_ACC_IND = 'Y'
    and STVAPDC_SIGNF_IND = 'Y'
JOIN ROBINST on ROBINST_AIDY_CODE = :AIDY
LEFT JOIN SARAATT s on s.SARAATT_PIDM = a.SARADAP_PIDM
    and s.SARAATT_ATTS_CODE in ('PSMV', 'PS15', 'REGV', 'REGF')
    and s.SARAATT_TERM_CODE = (
        SELECT MAX(z.SARAATT_TERM_CODE)
        FROM SARAATT z
        WHERE z.SARAATT_PIDM = s.SARAATT_PIDM
        AND z.SARAATT_TERM_CODE <= :PERIOD
    )
LEFT JOIN RORALGS on RORALGS_AIDY_CODE = :AIDY
    and RORALGS_KEY_1 = 'PBDG'
    AND RORALGS_KEY_4 = '1TUI'
    and RORALGS_KEY_5 = a.SARADAP_LEVL_CODE
    and RORALGS_KEY_6 = a.SARADAP_CAMP_CODE
    and RORALGS_KEY_7 = a.SARADAP_COLL_CODE_1
    and RORALGS_KEY_9 is null
    and (
        RORALGS_KEY_10 = s.SARAATT_ATTS_CODE
        or (RORALGS_KEY_10 IS NULL and s.SARAATT_ATTS_CODE is null)
    )
    and RORALGS_KEY_11 is null
WHERE a.SARADAP_LEVL_CODE = 'UG'
AND a.SARADAP_CAMP_CODE = 'FR'
AND a.SARADAP_COLL_CODE_1 = 'PS'
AND a.SARADAP_TERM_CODE_ENTRY = (
    SELECT MAX(z.SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP z
    WHERE z.SARADAP_PIDM = a.SARADAP_PIDM
    AND z.SARADAP_TERM_CODE_ENTRY <= :PERIOD
)
AND a.SARADAP_TERM_CODE_ENTRY = (
    SELECT MAX(Y.SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP Y
    WHERE Y.SARADAP_PIDM = a.SARADAP_PIDM
	AND Y.SARADAP_TERM_CODE_ENTRY between (ROBINST_AIDY_END_YEAR || '00') and :PERIOD
)
AND a.SARADAP_APPL_NO = (
    SELECT MAX(z.SARADAP_APPL_NO)
    FROM SARADAP z
    WHERE z.SARADAP_PIDM = a.SARADAP_PIDM
    and z.SARADAP_TERM_CODE_ENTRY = a.SARADAP_TERM_CODE_ENTRY
)
AND b.SARAPPD_SEQ_NO = (
    SELECT MAX(Y.SARAPPD_SEQ_NO)
    FROM SARAPPD Y
    WHERE Y.SARAPPD_PIDM = b.SARAPPD_PIDM
    AND Y.SARAPPD_TERM_CODE_ENTRY = b.SARAPPD_TERM_CODE_ENTRY
    AND Y.SARAPPD_APPL_NO = b.SARAPPD_APPL_NO
)
AND a.SARADAP_PIDM = :PIDM 
;