-- PKTF PERIOD BUDGET RULE - written by JD 10/3/2025
-- Parks Tech Fee (previously PARKS_TECH_FEE)
SELECT RORALGS_AMT * 2
FROM SGBSTDN a, RORALGS
WHERE RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '23PF' -- budget component
AND RORALGS_KEY_5 = 'UG' -- student level
AND CASE -- college code
    WHEN a.SGBSTDN_COLL_CODE_1 = 'SE' THEN 'SE'
    WHEN a.SGBSTDN_COLL_CODE_1 = 'PK' THEN 'PK'
END = RORALGS_KEY_7
AND a.SGBSTDN_TERM_CODE_EFF = ( -- max sgbstdn term <= passed period
    SELECT MAX(z.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN z
    WHERE z.SGBSTDN_PIDM = a.SGBSTDN_PIDM
    AND z.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND a.SGBSTDN_CAMP_CODE = 'FR'
AND a.SGBSTDN_PIDM = :PIDM
;
-- ;

SELECT RORALGS_AMT * 2
FROM SARADAP a
CROSS JOIN RORALGS
INNER JOIN SARAPPD b 
    ON b.SARAPPD_PIDM = a.SARADAP_PIDM
    AND b.SARAPPD_APPL_NO = a.SARADAP_APPL_NO
    AND b.SARAPPD_TERM_CODE_ENTRY = a.SARADAP_TERM_CODE_ENTRY
INNER JOIN STVAPDC c 
    ON c.STVAPDC_CODE = b.SARAPPD_APDC_CODE
    AND c.STVAPDC_INST_ACC_IND = 'Y'
    AND c.STVAPDC_SIGNF_IND = 'Y'
WHERE RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '23PF' -- budget component
AND RORALGS_KEY_5 = 'UG' -- student level
AND CASE -- college code
    WHEN a.SARADAP_COLL_CODE_1 = 'SE' THEN 'SE'
    WHEN a.SARADAP_COLL_CODE_1 = 'PK' THEN 'PK'
END = RORALGS_KEY_7
AND a.SARADAP_TERM_CODE_ENTRY = (
    SELECT MAX(SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP, ROBINST
    WHERE SARADAP_PIDM = a.SARADAP_PIDM
    AND SARADAP_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
	AND SARADAP_TERM_CODE_ENTRY <= :PERIOD
    AND ROBINST_AIDY_CODE = :AIDY
)
AND b.SARAPPD_SEQ_NO = (
    SELECT MAX(SARAPPD_SEQ_NO)
    FROM SARAPPD
    WHERE SARAPPD_PIDM = b.SARAPPD_PIDM
    AND SARAPPD_APPL_NO = b.SARAPPD_APPL_NO
    AND SARAPPD_SEQ_NO < 99
    AND SARAPPD_TERM_CODE_ENTRY = b.SARAPPD_TERM_CODE_ENTRY
)  
AND a.SARADAP_CAMP_CODE = 'FR'
AND RORALGS_AIDY_CODE = :AIDY
AND a.SARADAP_PIDM = :PIDM
-- ;