-- NEW GRAD PACKAGING GROUP
SELECT RORSTAT_PIDM
FROM RORSTAT
JOIN ROBINST on ROBINST_AIDY_CODE = RORSTAT_AIDY_CODE and ROBINST_STATUS_IND = 'A'
JOIN ROBNYUD on ROBNYUD_PIDM = RORSTAT_PIDM
WHERE RORSTAT_AIDY_CODE = :AIDY
AND RORSTAT_PIDM = :PIDM
AND EXISTS (
    SELECT 1
    FROM SARADAP C
    INNER JOIN SARAPPD D 
        ON D.SARAPPD_PIDM = C.SARADAP_PIDM
        AND D.SARAPPD_APPL_NO = C.SARADAP_APPL_NO
        AND D.SARAPPD_TERM_CODE_ENTRY = C.SARADAP_TERM_CODE_ENTRY
    INNER JOIN STVAPDC E
        ON E.STVAPDC_CODE = D.SARAPPD_APDC_CODE
        AND E.STVAPDC_INST_ACC_IND = 'Y'
        AND E.STVAPDC_SIGNF_IND = 'Y'
    WHERE C.SARADAP_PIDM = RORSTAT_PIDM
    AND C.SARADAP_LEVL_CODE = 'GR'
    AND C.SARADAP_TERM_CODE_ENTRY = (
        SELECT MAX(Z.SARADAP_TERM_CODE_ENTRY) 
        FROM SARADAP Z
        WHERE Z.SARADAP_PIDM = C.SARADAP_PIDM
        AND Z.SARADAP_TERM_CODE_ENTRY BETWEEN (ROBINST_AIDY_END_YEAR || '10') AND (ROBINST_AIDY_END_YEAR + 1 || '00')
    )
    AND C.SARADAP_APPL_NO = (
        select max(z.saradap_appl_no)
        from saradap z
        WHERE Z.SARADAP_PIDM = C.SARADAP_PIDM
        and z.saradap_term_code_entry = c.saradap_term_code_entry

    )
    AND D.SARAPPD_SEQ_NO = (
        SELECT MAX(Z.SARAPPD_SEQ_NO) FROM SARAPPD Z
        WHERE Z.SARAPPD_PIDM = D.SARAPPD_PIDM
        AND Z.SARAPPD_TERM_CODE_ENTRY = D.SARAPPD_TERM_CODE_ENTRY
        AND Z.SARAPPD_APPL_NO = D.SARAPPD_APPL_NO
    )
)
;

-- OLD QUERY TAKEN FROM BANNER 6/17/2026
SELECT RORSTAT_PIDM
  FROM RORSTAT, ROBINST
WHERE ROBINST_STATUS_IND = 'A'
   AND ROBINST_AIDY_CODE = RORSTAT_AIDY_CODE
   AND (EXISTS

        (SELECT 1
        FROM SARADAP C
        INNER JOIN SARAPPD D 
            ON D.SARAPPD_PIDM = C.SARADAP_PIDM
            AND D.SARAPPD_APPL_NO = C.SARADAP_APPL_NO
            AND D.SARAPPD_TERM_CODE_ENTRY = C.SARADAP_TERM_CODE_ENTRY
        INNER JOIN STVAPDC E
            ON E.STVAPDC_CODE = D.SARAPPD_APDC_CODE
            AND E.STVAPDC_INST_ACC_IND = 'Y'
            AND E.STVAPDC_SIGNF_IND = 'Y'
        WHERE C.SARADAP_PIDM = RORSTAT_PIDM
        AND C.SARADAP_LEVL_CODE = 'GR'
        AND C.SARADAP_TERM_CODE_ENTRY = (
            SELECT MAX(Z.SARADAP_TERM_CODE_ENTRY) FROM SARADAP Z
            WHERE Z.SARADAP_PIDM = C.SARADAP_PIDM
            AND Z.SARADAP_TERM_CODE_ENTRY BETWEEN (ROBINST_AIDY_END_YEAR || '00') AND ((ROBINST_AIDY_END_YEAR + 1) || '00')   
            AND Z.SARADAP_APPL_NO = C.SARADAP_APPL_NO
        )
        AND D.SARAPPD_SEQ_NO = (
            SELECT MAX(Z.SARAPPD_SEQ_NO) FROM SARAPPD Z
            WHERE Z.SARAPPD_PIDM = D.SARAPPD_PIDM
            AND Z.SARAPPD_TERM_CODE_ENTRY = D.SARAPPD_TERM_CODE_ENTRY
            AND Z.SARAPPD_APPL_NO = D.SARAPPD_APPL_NO
        ) 
    )
)
AND RORSTAT_AIDY_CODE            = :AIDY                                                  
AND RORSTAT_PIDM    =:PIDM
;