-- RETURNING GRAD PACKAGING GROUP
SELECT RORSTAT_PIDM
FROM RORSTAT
JOIN ROBINST on ROBINST_AIDY_CODE = RORSTAT_AIDY_CODE and ROBINST_STATUS_IND = 'A'
WHERE RORSTAT_AIDY_CODE = :AIDY
AND RORSTAT_PIDM = (select spriden_pidm from spriden where spriden_change_ind is null and spriden_id = '001340032')
-- AND RORSTAT_PIDM = :PIDM
AND ((
    EXISTS (
        SELECT 1
        FROM SATURN.SGBSTDN E
        WHERE E.SGBSTDN_PIDM = RORSTAT_PIDM
        AND E.SGBSTDN_LEVL_CODE = 'GR'
        AND E.SGBSTDN_STST_CODE IN ('AS', 'IL', 'P1')
        AND E.SGBSTDN_TERM_CODE_EFF = (
            SELECT MAX(F.SGBSTDN_TERM_CODE_EFF)
            FROM SGBSTDN F
            WHERE F.SGBSTDN_PIDM = E.SGBSTDN_PIDM
            AND SUBSTR(F.SGBSTDN_TERM_CODE_EFF,0,4) <= SUBSTR(ROBINST_AIDY_END_YEAR,0,4)
        )
    ) OR EXISTS (
        SELECT 1
        FROM SARADAP a
        JOIN SARAPPD b on b.SARAPPD_PIDM = a.SARADAP_PIDM
            AND b.SARAPPD_TERM_CODE_ENTRY = a.SARADAP_TERM_CODE_ENTRY
            AND b.SARAPPD_APPL_NO = a.SARADAP_APPL_NO
        JOIN STVAPDC c on c.STVAPDC_CODE = b.SARAPPD_APDC_CODE
            AND c.STVAPDC_INST_ACC_IND = 'Y'
            AND c.STVAPDC_SIGNF_IND = 'Y'
        WHERE a.SARADAP_PIDM = RORSTAT_PIDM
        AND a.SARADAP_LEVL_CODE = 'GR'
        AND a.SARADAP_TERM_CODE_ENTRY = (
            SELECT MAX(z.SARADAP_TERM_CODE_ENTRY)
            FROM SARADAP z
            WHERE z.SARADAP_PIDM = a.SARADAP_PIDM
            AND Z.SARADAP_TERM_CODE_ENTRY = ROBINST_AIDY_END_YEAR || '00'
        )
        AND a.SARADAP_APPL_NO = (
            SELECT MAX(z.SARADAP_APPL_NO)
            FROM SARADAP z
            WHERE z.SARADAP_PIDM = a.SARADAP_PIDM
            AND z.SARADAP_TERM_CODE_ENTRY = a.SARADAP_TERM_CODE_ENTRY
        )
        AND b.SARAPPD_SEQ_NO = (
            SELECT MAX(z.SARAPPD_SEQ_NO)
            FROM SARAPPD z
            WHERE z.SARAPPD_PIDM = b.SARAPPD_PIDM
            AND z.SARAPPD_TERM_CODE_ENTRY = b.SARAPPD_TERM_CODE_ENTRY
            AND z.SARAPPD_APPL_NO = b.SARAPPD_APPL_NO
        )
    ))
) AND NOT EXISTS (
    SELECT 1
    FROM SARADAP a
    JOIN SARAPPD b on b.SARAPPD_PIDM = a.SARADAP_PIDM
        AND b.SARAPPD_TERM_CODE_ENTRY = a.SARADAP_TERM_CODE_ENTRY
        AND b.SARAPPD_APPL_NO = a.SARADAP_APPL_NO
    JOIN STVAPDC c on c.STVAPDC_CODE = b.SARAPPD_APDC_CODE
        AND c.STVAPDC_INST_ACC_IND = 'Y'
        AND c.STVAPDC_SIGNF_IND = 'Y'
    WHERE a.SARADAP_PIDM = RORSTAT_PIDM
    AND a.SARADAP_LEVL_CODE <> 'GR'
    AND a.SARADAP_TERM_CODE_ENTRY = (
        SELECT MAX(z.SARADAP_TERM_CODE_ENTRY)
        FROM SARADAP z
        WHERE z.SARADAP_PIDM = a.SARADAP_PIDM
        AND Z.SARADAP_TERM_CODE_ENTRY BETWEEN (ROBINST_AIDY_END_YEAR || '10') AND (ROBINST_AIDY_END_YEAR + 1 || '00')
    )
    AND a.SARADAP_APPL_NO = (
        SELECT MAX(z.SARADAP_APPL_NO)
        FROM SARADAP z
        WHERE z.SARADAP_PIDM = a.SARADAP_PIDM
        AND z.SARADAP_TERM_CODE_ENTRY = a.SARADAP_TERM_CODE_ENTRY
    )
    AND b.SARAPPD_SEQ_NO = (
        SELECT MAX(z.SARAPPD_SEQ_NO)
        FROM SARAPPD z
        WHERE z.SARAPPD_PIDM = b.SARAPPD_PIDM
        AND z.SARAPPD_TERM_CODE_ENTRY = b.SARAPPD_TERM_CODE_ENTRY
        AND z.SARAPPD_APPL_NO = b.SARAPPD_APPL_NO
    )
)
;
-- AND RORSTAT_PIDM = (select spriden_pidm from spriden where spriden_change_ind is null and spriden_id = '001397936')
-- OLD RULE TAKEN FROM BANNER 06/17/2026
SELECT RORSTAT_PIDM
  FROM RORSTAT, ROBINST
 WHERE ROBINST_STATUS_IND = 'A'
   AND ROBINST_AIDY_CODE = RORSTAT_AIDY_CODE
   AND (EXISTS
(SELECT 'X'
   FROM SATURN.SGBSTDN E
  WHERE E.SGBSTDN_PIDM = RORSTAT_PIDM
    AND E.SGBSTDN_LEVL_CODE = 'GR'
    AND E.SGBSTDN_STST_CODE IN ('AS', 'IL', 'P1')
    AND E.SGBSTDN_TERM_CODE_EFF =
     (SELECT MAX(F.SGBSTDN_TERM_CODE_EFF)
        FROM SGBSTDN F 
	WHERE SUBSTR(F.SGBSTDN_TERM_CODE_EFF,0,4) <= SUBSTR(ROBINST_AIDY_END_YEAR,0,4)
         AND F.SGBSTDN_PIDM = E.SGBSTDN_PIDM))
 AND NOT EXISTS (SELECT 'X'
  FROM SARAPPD A, STVAPDC
 WHERE A.SARAPPD_PIDM = RORSTAT_PIDM
   AND A.SARAPPD_APDC_CODE = STVAPDC_CODE
   AND STVAPDC_INST_ACC_IND = 'Y'
   AND STVAPDC_SIGNF_IND = 'Y'
   AND A.SARAPPD_TERM_CODE_ENTRY = 
    (SELECT MAX(B.SARAPPD_TERM_CODE_ENTRY) 
       FROM SARAPPD B
      WHERE B.SARAPPD_PIDM = A.SARAPPD_PIDM
	    AND SUBSTR(B.SARAPPD_TERM_CODE_ENTRY,0,4) >= SUBSTR(ROBINST_AIDY_END_YEAR,0,4))
   AND A.SARAPPD_APPL_NO = 
    (SELECT MAX(C.SARAPPD_APPL_NO) 
       FROM SARAPPD C
      WHERE C.SARAPPD_PIDM = A.SARAPPD_PIDM
	    AND C.SARAPPD_TERM_CODE_ENTRY = A.SARAPPD_TERM_CODE_ENTRY)
   AND A.SARAPPD_SEQ_NO = 
    (SELECT MAX(D.SARAPPD_SEQ_NO) 
       FROM SARAPPD D
      WHERE D.SARAPPD_PIDM = A.SARAPPD_PIDM
	    AND D.SARAPPD_TERM_CODE_ENTRY = A.SARAPPD_TERM_CODE_ENTRY
	    AND D.SARAPPD_APPL_NO = A.SARAPPD_APPL_NO)))
AND RORSTAT_AIDY_CODE            = :AIDY                                                
AND RORSTAT_PIDM    =:PIDM   

;
