-- legacy med3
-- 109 rows
SELECT RORSTAT_PIDM
FROM RORSTAT
JOIN ROBINST on ROBINST_AIDY_CODE = RORSTAT_AIDY_CODE and ROBINST_STATUS_IND = 'A'
JOIN ROBNYUD on ROBNYUD_PIDM = RORSTAT_PIDM
WHERE RORSTAT_AIDY_CODE = :AIDY
AND RORSTAT_PIDM = :PIDM
AND ROBNYUD_VALUE_197 = 'Y'
AND ROBNYUD_VALUE_198 = 'PM'
AND EXISTS (
    SELECT 1
    FROM SGBSTDN E 
    JOIN SATURN.STVMAJR M on M.STVMAJR_CODE = E.SGBSTDN_MAJR_CODE_1
        and substr(M.STVMAJR_CIPC_CODE, 0, 4) = substr(ROBNYUD_VALUE_193, 0, 4)
    WHERE E.SGBSTDN_PIDM = RORSTAT_PIDM 
    AND E.SGBSTDN_STST_CODE IN ('AS','P1')
    AND E.SGBSTDN_TERM_CODE_EFF = (
        SELECT MAX(F.SGBSTDN_TERM_CODE_EFF) 
        FROM SGBSTDN F 
        WHERE F.SGBSTDN_TERM_CODE_EFF <= ROBINST_AIDY_END_YEAR || '10'
        AND F.SGBSTDN_PIDM = E.SGBSTDN_PIDM
    )
)
AND EXISTS (
    SELECT 1
    FROM SGRSATT 
    WHERE SGRSATT_PIDM = RORSTAT_PIDM
    AND SGRSATT_TERM_CODE_EFF = ROBINST_AIDY_START_YEAR || '10'
    AND SGRSATT_ATTS_CODE IN ('M2')
)

;