
-- insert 5 rows into 6 FAISMGR.RBRPBGP fields
INSERT INTO FAISMGR.RBRPBGP (
    RBRPBGP_AIDY_CODE, RBRPBGP_PBGP_CODE, RBRPBGP_PRIORITY, RBRPBGP_LONG_DESC, 
    RBRPBGP_COMMENT, RBRPBGP_ACTIVITY_DATE
) VALUES (
    '2627', 'GR', 20, 'Graduate', NULL, 
    TO_DATE('12/10/2025 11:34:36', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBGP (
    RBRPBGP_AIDY_CODE, RBRPBGP_PBGP_CODE, RBRPBGP_PRIORITY, RBRPBGP_LONG_DESC, 
    RBRPBGP_COMMENT, RBRPBGP_ACTIVITY_DATE
) VALUES (
    '2627', 'MR', 10, 'Madrid', NULL, 
    TO_DATE('12/10/2025 11:34:08', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBGP (
    RBRPBGP_AIDY_CODE, RBRPBGP_PBGP_CODE, RBRPBGP_PRIORITY, RBRPBGP_LONG_DESC, 
    RBRPBGP_COMMENT, RBRPBGP_ACTIVITY_DATE
) VALUES (
    '2627', 'PL', 25, 'LAW', NULL, 
    TO_DATE('12/10/2025 11:34:36', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBGP (
    RBRPBGP_AIDY_CODE, RBRPBGP_PBGP_CODE, RBRPBGP_PRIORITY, RBRPBGP_LONG_DESC, 
    RBRPBGP_COMMENT, RBRPBGP_ACTIVITY_DATE
) VALUES (
    '2627', 'PM', 30, 'MED', NULL, 
    TO_DATE('12/10/2025 11:34:36', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBGP (
    RBRPBGP_AIDY_CODE, RBRPBGP_PBGP_CODE, RBRPBGP_PRIORITY, RBRPBGP_LONG_DESC, 
    RBRPBGP_COMMENT, RBRPBGP_ACTIVITY_DATE
) VALUES (
    '2627', 'UG', 15, 'Undergraduate', NULL, 
    TO_DATE('12/10/2025 11:34:36', 'MM/DD/YYYY HH24:MI:SS')
);
-- insert 13 rows into 13 FAISMGR.RBRPBCP fields
INSERT INTO FAISMGR.RBRPBCP (
    RBRPBCP_AIDY_CODE, RBRPBCP_PBCP_CODE, RBRPBCP_DEFAULT_IND, 
    RBRPBCP_PELL_LT_HALF_IND, RBRPBCP_DIRECT_COST_IND, RBRPBCP_BCAT_CODE, 
    RBRPBCP_LONG_DESC, RBRPBCP_COMMENT, RBRPBCP_AMT_DFLT, 
    RBRPBCP_ABRC_CODE_DFLT, RBRPBCP_AMT_PELL_DFLT, RBRPBCP_ABRC_CODE_PELL_DFLT, 
    RBRPBCP_ACTIVITY_DATE
) VALUES (
    '2627', '1TUI', 'Y', 'Y', 'N', 'TUIT', 'Tuition', NULL, 0.0, NULL, NULL, 
    '1TUI_UG_PELL', TO_DATE('12/10/2025 12:21:59', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBCP (
    RBRPBCP_AIDY_CODE, RBRPBCP_PBCP_CODE, RBRPBCP_DEFAULT_IND, 
    RBRPBCP_PELL_LT_HALF_IND, RBRPBCP_DIRECT_COST_IND, RBRPBCP_BCAT_CODE, 
    RBRPBCP_LONG_DESC, RBRPBCP_COMMENT, RBRPBCP_AMT_DFLT, 
    RBRPBCP_ABRC_CODE_DFLT, RBRPBCP_AMT_PELL_DFLT, RBRPBCP_ABRC_CODE_PELL_DFLT, 
    RBRPBCP_ACTIVITY_DATE
) VALUES (
    '2627', '21BF', 'Y', 'N', 'N', 'FEES', 'Business Technology Fee', NULL, 
    NULL, '21BF', NULL, '21BF_PELL', 
    TO_DATE('12/12/2025 08:34:44', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBCP (
    RBRPBCP_AIDY_CODE, RBRPBCP_PBCP_CODE, RBRPBCP_DEFAULT_IND, 
    RBRPBCP_PELL_LT_HALF_IND, RBRPBCP_DIRECT_COST_IND, RBRPBCP_BCAT_CODE, 
    RBRPBCP_LONG_DESC, RBRPBCP_COMMENT, RBRPBCP_AMT_DFLT, 
    RBRPBCP_ABRC_CODE_DFLT, RBRPBCP_AMT_PELL_DFLT, RBRPBCP_ABRC_CODE_PELL_DFLT, 
    RBRPBCP_ACTIVITY_DATE
) VALUES (
    '2627', '22DF', 'Y', 'N', 'N', 'FEES', 'Doisy College Technology Fee', NULL, 
    NULL, '22DF', NULL, '22DF_PELL', 
    TO_DATE('12/12/2025 08:34:58', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBCP (
    RBRPBCP_AIDY_CODE, RBRPBCP_PBCP_CODE, RBRPBCP_DEFAULT_IND, 
    RBRPBCP_PELL_LT_HALF_IND, RBRPBCP_DIRECT_COST_IND, RBRPBCP_BCAT_CODE, 
    RBRPBCP_LONG_DESC, RBRPBCP_COMMENT, RBRPBCP_AMT_DFLT, 
    RBRPBCP_ABRC_CODE_DFLT, RBRPBCP_AMT_PELL_DFLT, RBRPBCP_ABRC_CODE_PELL_DFLT, 
    RBRPBCP_ACTIVITY_DATE
) VALUES (
    '2627', '23PF', 'Y', 'N', 'N', 'FEES', 'Parks Technology Fee', NULL, NULL, 
    '23PF', NULL, '23PF_PELL', 
    TO_DATE('12/12/2025 08:35:10', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBCP (
    RBRPBCP_AIDY_CODE, RBRPBCP_PBCP_CODE, RBRPBCP_DEFAULT_IND, 
    RBRPBCP_PELL_LT_HALF_IND, RBRPBCP_DIRECT_COST_IND, RBRPBCP_BCAT_CODE, 
    RBRPBCP_LONG_DESC, RBRPBCP_COMMENT, RBRPBCP_AMT_DFLT, 
    RBRPBCP_ABRC_CODE_DFLT, RBRPBCP_AMT_PELL_DFLT, RBRPBCP_ABRC_CODE_PELL_DFLT, 
    RBRPBCP_ACTIVITY_DATE
) VALUES (
    '2627', '24SF', 'Y', 'N', 'N', 'FEES', 'Study Abroad', NULL, NULL, '24SF', 
    NULL, '24SF_PELL', TO_DATE('12/12/2025 08:35:21', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBCP (
    RBRPBCP_AIDY_CODE, RBRPBCP_PBCP_CODE, RBRPBCP_DEFAULT_IND, 
    RBRPBCP_PELL_LT_HALF_IND, RBRPBCP_DIRECT_COST_IND, RBRPBCP_BCAT_CODE, 
    RBRPBCP_LONG_DESC, RBRPBCP_COMMENT, RBRPBCP_AMT_DFLT, 
    RBRPBCP_ABRC_CODE_DFLT, RBRPBCP_AMT_PELL_DFLT, RBRPBCP_ABRC_CODE_PELL_DFLT, 
    RBRPBCP_ACTIVITY_DATE
) VALUES (
    '2627', '2FEE', 'Y', 'N', 'N', 'FEES', 'Fees', NULL, NULL, '2FEE', NULL, 
    '2FEE_PELL', TO_DATE('12/12/2025 08:35:50', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBCP (
    RBRPBCP_AIDY_CODE, RBRPBCP_PBCP_CODE, RBRPBCP_DEFAULT_IND, 
    RBRPBCP_PELL_LT_HALF_IND, RBRPBCP_DIRECT_COST_IND, RBRPBCP_BCAT_CODE, 
    RBRPBCP_LONG_DESC, RBRPBCP_COMMENT, RBRPBCP_AMT_DFLT, 
    RBRPBCP_ABRC_CODE_DFLT, RBRPBCP_AMT_PELL_DFLT, RBRPBCP_ABRC_CODE_PELL_DFLT, 
    RBRPBCP_ACTIVITY_DATE
) VALUES (
    '2627', '3HSM', 'Y', 'N', 'N', 'HSML', 'Housing and Meals', NULL, NULL, 
    '3HSM', NULL, '3HSM_PELL', 
    TO_DATE('12/12/2025 08:35:50', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBCP (
    RBRPBCP_AIDY_CODE, RBRPBCP_PBCP_CODE, RBRPBCP_DEFAULT_IND, 
    RBRPBCP_PELL_LT_HALF_IND, RBRPBCP_DIRECT_COST_IND, RBRPBCP_BCAT_CODE, 
    RBRPBCP_LONG_DESC, RBRPBCP_COMMENT, RBRPBCP_AMT_DFLT, 
    RBRPBCP_ABRC_CODE_DFLT, RBRPBCP_AMT_PELL_DFLT, RBRPBCP_ABRC_CODE_PELL_DFLT, 
    RBRPBCP_ACTIVITY_DATE
) VALUES (
    '2627', '4COM', 'Y', 'N', 'N', 'COMM', 'Commuter Meal Plan', NULL, NULL, 
    '4COM', 0.0, NULL, TO_DATE('12/17/2025 10:06:12', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBCP (
    RBRPBCP_AIDY_CODE, RBRPBCP_PBCP_CODE, RBRPBCP_DEFAULT_IND, 
    RBRPBCP_PELL_LT_HALF_IND, RBRPBCP_DIRECT_COST_IND, RBRPBCP_BCAT_CODE, 
    RBRPBCP_LONG_DESC, RBRPBCP_COMMENT, RBRPBCP_AMT_DFLT, 
    RBRPBCP_ABRC_CODE_DFLT, RBRPBCP_AMT_PELL_DFLT, RBRPBCP_ABRC_CODE_PELL_DFLT, 
    RBRPBCP_ACTIVITY_DATE
) VALUES (
    '2627', '5CAF', 'Y', 'N', 'N', 'CAFE', 'Cafeteria Plan', NULL, NULL, '5CAF', 
    NULL, '5CAF_PELL', TO_DATE('12/12/2025 08:36:01', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBCP (
    RBRPBCP_AIDY_CODE, RBRPBCP_PBCP_CODE, RBRPBCP_DEFAULT_IND, 
    RBRPBCP_PELL_LT_HALF_IND, RBRPBCP_DIRECT_COST_IND, RBRPBCP_BCAT_CODE, 
    RBRPBCP_LONG_DESC, RBRPBCP_COMMENT, RBRPBCP_AMT_DFLT, 
    RBRPBCP_ABRC_CODE_DFLT, RBRPBCP_AMT_PELL_DFLT, RBRPBCP_ABRC_CODE_PELL_DFLT, 
    RBRPBCP_ACTIVITY_DATE
) VALUES (
    '2627', '6LIV', 'Y', 'N', 'N', 'LIVG', 'Living Expenses', NULL, NULL, 
    '6LIV', NULL, '3HSM_PELL', 
    TO_DATE('12/15/2025 13:02:47', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBCP (
    RBRPBCP_AIDY_CODE, RBRPBCP_PBCP_CODE, RBRPBCP_DEFAULT_IND, 
    RBRPBCP_PELL_LT_HALF_IND, RBRPBCP_DIRECT_COST_IND, RBRPBCP_BCAT_CODE, 
    RBRPBCP_LONG_DESC, RBRPBCP_COMMENT, RBRPBCP_AMT_DFLT, 
    RBRPBCP_ABRC_CODE_DFLT, RBRPBCP_AMT_PELL_DFLT, RBRPBCP_ABRC_CODE_PELL_DFLT, 
    RBRPBCP_ACTIVITY_DATE
) VALUES (
    '2627', '7BS', 'Y', 'Y', 'N', 'BS', 'Books and Supplies', NULL, NULL, '7BS', 
    NULL, '7BS_PELL', TO_DATE('12/12/2025 08:36:31', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBCP (
    RBRPBCP_AIDY_CODE, RBRPBCP_PBCP_CODE, RBRPBCP_DEFAULT_IND, 
    RBRPBCP_PELL_LT_HALF_IND, RBRPBCP_DIRECT_COST_IND, RBRPBCP_BCAT_CODE, 
    RBRPBCP_LONG_DESC, RBRPBCP_COMMENT, RBRPBCP_AMT_DFLT, 
    RBRPBCP_ABRC_CODE_DFLT, RBRPBCP_AMT_PELL_DFLT, RBRPBCP_ABRC_CODE_PELL_DFLT, 
    RBRPBCP_ACTIVITY_DATE
) VALUES (
    '2627', '8TRS', 'Y', 'Y', 'N', 'TRAN', 'Transportation', NULL, NULL, '8TRS', 
    NULL, '8TRS_PELL', TO_DATE('12/12/2025 08:36:31', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBCP (
    RBRPBCP_AIDY_CODE, RBRPBCP_PBCP_CODE, RBRPBCP_DEFAULT_IND, 
    RBRPBCP_PELL_LT_HALF_IND, RBRPBCP_DIRECT_COST_IND, RBRPBCP_BCAT_CODE, 
    RBRPBCP_LONG_DESC, RBRPBCP_COMMENT, RBRPBCP_AMT_DFLT, 
    RBRPBCP_ABRC_CODE_DFLT, RBRPBCP_AMT_PELL_DFLT, RBRPBCP_ABRC_CODE_PELL_DFLT, 
    RBRPBCP_ACTIVITY_DATE
) VALUES (
    '2627', '9MIS', 'Y', 'N', 'N', 'MISC', 'Miscellaneous', NULL, NULL, '9MIS', 
    NULL, '9MIS_PELL', TO_DATE('12/12/2025 08:36:41', 'MM/DD/YYYY HH24:MI:SS')
);

-- insert 8 rows into 4 FAISMGR.RBRPGPT fields
INSERT INTO FAISMGR.RBRPGPT (
    RBRPGPT_AIDY_CODE, RBRPGPT_PBGP_CODE, RBRPGPT_PBTP_CODE, 
    RBRPGPT_ACTIVITY_DATE
) VALUES (
    '2627', 'AC', 'CAMP', 
    TO_DATE('10/30/2025 08:23:23', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPGPT (
    RBRPGPT_AIDY_CODE, RBRPGPT_PBGP_CODE, RBRPGPT_PBTP_CODE, 
    RBRPGPT_ACTIVITY_DATE
) VALUES (
    '2627', 'GR', 'CAMP', 
    TO_DATE('12/10/2025 14:44:34', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPGPT (
    RBRPGPT_AIDY_CODE, RBRPGPT_PBGP_CODE, RBRPGPT_PBTP_CODE, 
    RBRPGPT_ACTIVITY_DATE
) VALUES (
    '2627', 'MR', 'CAMP', 
    TO_DATE('12/10/2025 14:45:13', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPGPT (
    RBRPGPT_AIDY_CODE, RBRPGPT_PBGP_CODE, RBRPGPT_PBTP_CODE, 
    RBRPGPT_ACTIVITY_DATE
) VALUES (
    '2627', 'MR', 'PELL', 
    TO_DATE('12/11/2025 15:48:39', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPGPT (
    RBRPGPT_AIDY_CODE, RBRPGPT_PBGP_CODE, RBRPGPT_PBTP_CODE, 
    RBRPGPT_ACTIVITY_DATE
) VALUES (
    '2627', 'PL', 'CAMP', 
    TO_DATE('12/10/2025 14:44:52', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPGPT (
    RBRPGPT_AIDY_CODE, RBRPGPT_PBGP_CODE, RBRPGPT_PBTP_CODE, 
    RBRPGPT_ACTIVITY_DATE
) VALUES (
    '2627', 'PM', 'CAMP', 
    TO_DATE('12/10/2025 14:45:04', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPGPT (
    RBRPGPT_AIDY_CODE, RBRPGPT_PBGP_CODE, RBRPGPT_PBTP_CODE, 
    RBRPGPT_ACTIVITY_DATE
) VALUES (
    '2627', 'UG', 'CAMP', 
    TO_DATE('12/10/2025 11:57:21', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPGPT (
    RBRPGPT_AIDY_CODE, RBRPGPT_PBGP_CODE, RBRPGPT_PBTP_CODE, 
    RBRPGPT_ACTIVITY_DATE
) VALUES (
    '2627', 'UG', 'PELL', 
    TO_DATE('12/10/2025 11:57:21', 'MM/DD/YYYY HH24:MI:SS')
);

-- insert 21 rows into 6 FAISMGR.RBRPELL fields
INSERT INTO FAISMGR.RBRPELL (
    RBRPELL_AIDY_CODE, RBRPELL_PBGP_CODE, RBRPELL_PBCP_CODE, RBRPELL_AMT, 
    RBRPELL_ABRC_CODE, RBRPELL_ACTIVITY_DATE
) VALUES (
    '2627', 'MR', '1TUI', NULL, '1TUI_UG_PELL', 
    TO_DATE('12/12/2025 08:40:09', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPELL (
    RBRPELL_AIDY_CODE, RBRPELL_PBGP_CODE, RBRPELL_PBCP_CODE, RBRPELL_AMT, 
    RBRPELL_ABRC_CODE, RBRPELL_ACTIVITY_DATE
) VALUES (
    '2627', 'MR', '24SF', NULL, '24SF_PELL', 
    TO_DATE('12/12/2025 08:40:09', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPELL (
    RBRPELL_AIDY_CODE, RBRPELL_PBGP_CODE, RBRPELL_PBCP_CODE, RBRPELL_AMT, 
    RBRPELL_ABRC_CODE, RBRPELL_ACTIVITY_DATE
) VALUES (
    '2627', 'MR', '2FEE', NULL, '2FEE_PELL', 
    TO_DATE('12/12/2025 08:40:09', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPELL (
    RBRPELL_AIDY_CODE, RBRPELL_PBGP_CODE, RBRPELL_PBCP_CODE, RBRPELL_AMT, 
    RBRPELL_ABRC_CODE, RBRPELL_ACTIVITY_DATE
) VALUES (
    '2627', 'MR', '3HSM', NULL, '3HSM_PELL', 
    TO_DATE('12/12/2025 08:40:09', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPELL (
    RBRPELL_AIDY_CODE, RBRPELL_PBGP_CODE, RBRPELL_PBCP_CODE, RBRPELL_AMT, 
    RBRPELL_ABRC_CODE, RBRPELL_ACTIVITY_DATE
) VALUES (
    '2627', 'MR', '4COM', NULL, '4COM_PELL', 
    TO_DATE('12/12/2025 08:40:09', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPELL (
    RBRPELL_AIDY_CODE, RBRPELL_PBGP_CODE, RBRPELL_PBCP_CODE, RBRPELL_AMT, 
    RBRPELL_ABRC_CODE, RBRPELL_ACTIVITY_DATE
) VALUES (
    '2627', 'MR', '5CAF', NULL, '5CAF_PELL', 
    TO_DATE('12/12/2025 08:40:09', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPELL (
    RBRPELL_AIDY_CODE, RBRPELL_PBGP_CODE, RBRPELL_PBCP_CODE, RBRPELL_AMT, 
    RBRPELL_ABRC_CODE, RBRPELL_ACTIVITY_DATE
) VALUES (
    '2627', 'MR', '6LIV', NULL, '6LIV_PELL', 
    TO_DATE('12/12/2025 08:40:09', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPELL (
    RBRPELL_AIDY_CODE, RBRPELL_PBGP_CODE, RBRPELL_PBCP_CODE, RBRPELL_AMT, 
    RBRPELL_ABRC_CODE, RBRPELL_ACTIVITY_DATE
) VALUES (
    '2627', 'MR', '7BS', NULL, '7BS_PELL', 
    TO_DATE('12/12/2025 08:40:09', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPELL (
    RBRPELL_AIDY_CODE, RBRPELL_PBGP_CODE, RBRPELL_PBCP_CODE, RBRPELL_AMT, 
    RBRPELL_ABRC_CODE, RBRPELL_ACTIVITY_DATE
) VALUES (
    '2627', 'MR', '8TRS', NULL, '8TRS_PELL', 
    TO_DATE('12/12/2025 08:40:09', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPELL (
    RBRPELL_AIDY_CODE, RBRPELL_PBGP_CODE, RBRPELL_PBCP_CODE, RBRPELL_AMT, 
    RBRPELL_ABRC_CODE, RBRPELL_ACTIVITY_DATE
) VALUES (
    '2627', 'MR', '9MIS', NULL, '9MIS_PELL', 
    TO_DATE('12/12/2025 08:40:09', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPELL (
    RBRPELL_AIDY_CODE, RBRPELL_PBGP_CODE, RBRPELL_PBCP_CODE, RBRPELL_AMT, 
    RBRPELL_ABRC_CODE, RBRPELL_ACTIVITY_DATE
) VALUES (
    '2627', 'UG', '1TUI', NULL, '1TUI_UG_PELL', 
    TO_DATE('12/12/2025 08:39:52', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPELL (
    RBRPELL_AIDY_CODE, RBRPELL_PBGP_CODE, RBRPELL_PBCP_CODE, RBRPELL_AMT, 
    RBRPELL_ABRC_CODE, RBRPELL_ACTIVITY_DATE
) VALUES (
    '2627', 'UG', '21BF', NULL, '21BF_PELL', 
    TO_DATE('12/12/2025 08:39:52', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPELL (
    RBRPELL_AIDY_CODE, RBRPELL_PBGP_CODE, RBRPELL_PBCP_CODE, RBRPELL_AMT, 
    RBRPELL_ABRC_CODE, RBRPELL_ACTIVITY_DATE
) VALUES (
    '2627', 'UG', '22DF', NULL, '22DF_PELL', 
    TO_DATE('12/12/2025 08:39:52', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPELL (
    RBRPELL_AIDY_CODE, RBRPELL_PBGP_CODE, RBRPELL_PBCP_CODE, RBRPELL_AMT, 
    RBRPELL_ABRC_CODE, RBRPELL_ACTIVITY_DATE
) VALUES (
    '2627', 'UG', '23PF', NULL, '23PF_PELL', 
    TO_DATE('12/12/2025 08:39:52', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPELL (
    RBRPELL_AIDY_CODE, RBRPELL_PBGP_CODE, RBRPELL_PBCP_CODE, RBRPELL_AMT, 
    RBRPELL_ABRC_CODE, RBRPELL_ACTIVITY_DATE
) VALUES (
    '2627', 'UG', '24SF', NULL, '24SF_PELL', 
    TO_DATE('12/12/2025 08:39:52', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPELL (
    RBRPELL_AIDY_CODE, RBRPELL_PBGP_CODE, RBRPELL_PBCP_CODE, RBRPELL_AMT, 
    RBRPELL_ABRC_CODE, RBRPELL_ACTIVITY_DATE
) VALUES (
    '2627', 'UG', '2FEE', NULL, '2FEE_PELL', 
    TO_DATE('12/12/2025 08:39:52', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPELL (
    RBRPELL_AIDY_CODE, RBRPELL_PBGP_CODE, RBRPELL_PBCP_CODE, RBRPELL_AMT, 
    RBRPELL_ABRC_CODE, RBRPELL_ACTIVITY_DATE
) VALUES (
    '2627', 'UG', '3HSM', NULL, '3HSM_PELL', 
    TO_DATE('12/12/2025 08:39:52', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPELL (
    RBRPELL_AIDY_CODE, RBRPELL_PBGP_CODE, RBRPELL_PBCP_CODE, RBRPELL_AMT, 
    RBRPELL_ABRC_CODE, RBRPELL_ACTIVITY_DATE
) VALUES (
    '2627', 'UG', '5CAF', NULL, '5CAF_PELL', 
    TO_DATE('12/12/2025 08:39:52', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPELL (
    RBRPELL_AIDY_CODE, RBRPELL_PBGP_CODE, RBRPELL_PBCP_CODE, RBRPELL_AMT, 
    RBRPELL_ABRC_CODE, RBRPELL_ACTIVITY_DATE
) VALUES (
    '2627', 'UG', '7BS', NULL, '7BS_PELL', 
    TO_DATE('12/12/2025 08:39:52', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPELL (
    RBRPELL_AIDY_CODE, RBRPELL_PBGP_CODE, RBRPELL_PBCP_CODE, RBRPELL_AMT, 
    RBRPELL_ABRC_CODE, RBRPELL_ACTIVITY_DATE
) VALUES (
    '2627', 'UG', '8TRS', NULL, '8TRS_PELL', 
    TO_DATE('12/12/2025 08:39:52', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPELL (
    RBRPELL_AIDY_CODE, RBRPELL_PBGP_CODE, RBRPELL_PBCP_CODE, RBRPELL_AMT, 
    RBRPELL_ABRC_CODE, RBRPELL_ACTIVITY_DATE
) VALUES (
    '2627', 'UG', '9MIS', NULL, '9MIS_PELL', 
    TO_DATE('12/12/2025 08:39:52', 'MM/DD/YYYY HH24:MI:SS')
);

-- insert 48 rows into 8 FAISMGR.RBRPBDR fields
INSERT INTO FAISMGR.RBRPBDR (
    RBRPBDR_AIDY_CODE, RBRPBDR_PBGP_CODE, RBRPBDR_PBTP_CODE, RBRPBDR_PBCP_CODE, 
    RBRPBDR_PERIOD, RBRPBDR_AMT, RBRPBDR_ABRC_CODE, RBRPBDR_ACTIVITY_DATE
) VALUES (
    '2627', 'UG', 'CAMP', '21BF', NULL, NULL, '21BF', 
    TO_DATE('12/10/2025 14:43:37', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBDR (
    RBRPBDR_AIDY_CODE, RBRPBDR_PBGP_CODE, RBRPBDR_PBTP_CODE, RBRPBDR_PBCP_CODE, 
    RBRPBDR_PERIOD, RBRPBDR_AMT, RBRPBDR_ABRC_CODE, RBRPBDR_ACTIVITY_DATE
) VALUES (
    '2627', 'UG', 'CAMP', '4COM', NULL, NULL, '4COM', 
    TO_DATE('12/10/2025 14:43:37', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBDR (
    RBRPBDR_AIDY_CODE, RBRPBDR_PBGP_CODE, RBRPBDR_PBTP_CODE, RBRPBDR_PBCP_CODE, 
    RBRPBDR_PERIOD, RBRPBDR_AMT, RBRPBDR_ABRC_CODE, RBRPBDR_ACTIVITY_DATE
) VALUES (
    '2627', 'UG', 'CAMP', '9MIS', NULL, NULL, '9MIS', 
    TO_DATE('12/10/2025 14:43:37', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBDR (
    RBRPBDR_AIDY_CODE, RBRPBDR_PBGP_CODE, RBRPBDR_PBTP_CODE, RBRPBDR_PBCP_CODE, 
    RBRPBDR_PERIOD, RBRPBDR_AMT, RBRPBDR_ABRC_CODE, RBRPBDR_ACTIVITY_DATE
) VALUES (
    '2627', 'UG', 'CAMP', '7BS', NULL, NULL, '7BS', 
    TO_DATE('12/10/2025 14:43:37', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBDR (
    RBRPBDR_AIDY_CODE, RBRPBDR_PBGP_CODE, RBRPBDR_PBTP_CODE, RBRPBDR_PBCP_CODE, 
    RBRPBDR_PERIOD, RBRPBDR_AMT, RBRPBDR_ABRC_CODE, RBRPBDR_ACTIVITY_DATE
) VALUES (
    '2627', 'UG', 'CAMP', '2FEE', NULL, NULL, '2FEE', 
    TO_DATE('12/10/2025 14:43:37', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBDR (
    RBRPBDR_AIDY_CODE, RBRPBDR_PBGP_CODE, RBRPBDR_PBTP_CODE, RBRPBDR_PBCP_CODE, 
    RBRPBDR_PERIOD, RBRPBDR_AMT, RBRPBDR_ABRC_CODE, RBRPBDR_ACTIVITY_DATE
) VALUES (
    '2627', 'UG', 'CAMP', '3HSM', NULL, NULL, '3HSM', 
    TO_DATE('12/10/2025 14:43:37', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBDR (
    RBRPBDR_AIDY_CODE, RBRPBDR_PBGP_CODE, RBRPBDR_PBTP_CODE, RBRPBDR_PBCP_CODE, 
    RBRPBDR_PERIOD, RBRPBDR_AMT, RBRPBDR_ABRC_CODE, RBRPBDR_ACTIVITY_DATE
) VALUES (
    '2627', 'UG', 'CAMP', '6LIV', NULL, NULL, '6LIV', 
    TO_DATE('12/10/2025 14:43:37', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBDR (
    RBRPBDR_AIDY_CODE, RBRPBDR_PBGP_CODE, RBRPBDR_PBTP_CODE, RBRPBDR_PBCP_CODE, 
    RBRPBDR_PERIOD, RBRPBDR_AMT, RBRPBDR_ABRC_CODE, RBRPBDR_ACTIVITY_DATE
) VALUES (
    '2627', 'UG', 'CAMP', '5CAF', NULL, NULL, '5CAF', 
    TO_DATE('12/10/2025 14:43:37', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBDR (
    RBRPBDR_AIDY_CODE, RBRPBDR_PBGP_CODE, RBRPBDR_PBTP_CODE, RBRPBDR_PBCP_CODE, 
    RBRPBDR_PERIOD, RBRPBDR_AMT, RBRPBDR_ABRC_CODE, RBRPBDR_ACTIVITY_DATE
) VALUES (
    '2627', 'UG', 'CAMP', '24SF', NULL, NULL, '24SF', 
    TO_DATE('12/10/2025 14:43:37', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBDR (
    RBRPBDR_AIDY_CODE, RBRPBDR_PBGP_CODE, RBRPBDR_PBTP_CODE, RBRPBDR_PBCP_CODE, 
    RBRPBDR_PERIOD, RBRPBDR_AMT, RBRPBDR_ABRC_CODE, RBRPBDR_ACTIVITY_DATE
) VALUES (
    '2627', 'UG', 'CAMP', '8TRS', NULL, NULL, '8TRS', 
    TO_DATE('12/10/2025 14:43:37', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBDR (
    RBRPBDR_AIDY_CODE, RBRPBDR_PBGP_CODE, RBRPBDR_PBTP_CODE, RBRPBDR_PBCP_CODE, 
    RBRPBDR_PERIOD, RBRPBDR_AMT, RBRPBDR_ABRC_CODE, RBRPBDR_ACTIVITY_DATE
) VALUES (
    '2627', 'UG', 'CAMP', '22DF', NULL, NULL, '22DF', 
    TO_DATE('12/10/2025 14:43:37', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBDR (
    RBRPBDR_AIDY_CODE, RBRPBDR_PBGP_CODE, RBRPBDR_PBTP_CODE, RBRPBDR_PBCP_CODE, 
    RBRPBDR_PERIOD, RBRPBDR_AMT, RBRPBDR_ABRC_CODE, RBRPBDR_ACTIVITY_DATE
) VALUES (
    '2627', 'UG', 'CAMP', '23PF', NULL, NULL, '23PF', 
    TO_DATE('12/10/2025 14:43:37', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBDR (
    RBRPBDR_AIDY_CODE, RBRPBDR_PBGP_CODE, RBRPBDR_PBTP_CODE, RBRPBDR_PBCP_CODE, 
    RBRPBDR_PERIOD, RBRPBDR_AMT, RBRPBDR_ABRC_CODE, RBRPBDR_ACTIVITY_DATE
) VALUES (
    '2627', 'UG', 'CAMP', '1TUI', NULL, NULL, '1TUI_UG', 
    TO_DATE('12/10/2025 14:43:56', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBDR (
    RBRPBDR_AIDY_CODE, RBRPBDR_PBGP_CODE, RBRPBDR_PBTP_CODE, RBRPBDR_PBCP_CODE, 
    RBRPBDR_PERIOD, RBRPBDR_AMT, RBRPBDR_ABRC_CODE, RBRPBDR_ACTIVITY_DATE
) VALUES (
    '2627', 'MR', 'CAMP', '21BF', NULL, NULL, '21BF', 
    TO_DATE('12/10/2025 14:45:29', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBDR (
    RBRPBDR_AIDY_CODE, RBRPBDR_PBGP_CODE, RBRPBDR_PBTP_CODE, RBRPBDR_PBCP_CODE, 
    RBRPBDR_PERIOD, RBRPBDR_AMT, RBRPBDR_ABRC_CODE, RBRPBDR_ACTIVITY_DATE
) VALUES (
    '2627', 'MR', 'CAMP', '4COM', NULL, NULL, '4COM', 
    TO_DATE('12/10/2025 14:45:29', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBDR (
    RBRPBDR_AIDY_CODE, RBRPBDR_PBGP_CODE, RBRPBDR_PBTP_CODE, RBRPBDR_PBCP_CODE, 
    RBRPBDR_PERIOD, RBRPBDR_AMT, RBRPBDR_ABRC_CODE, RBRPBDR_ACTIVITY_DATE
) VALUES (
    '2627', 'MR', 'CAMP', '9MIS', NULL, NULL, '9MIS', 
    TO_DATE('12/10/2025 14:45:29', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBDR (
    RBRPBDR_AIDY_CODE, RBRPBDR_PBGP_CODE, RBRPBDR_PBTP_CODE, RBRPBDR_PBCP_CODE, 
    RBRPBDR_PERIOD, RBRPBDR_AMT, RBRPBDR_ABRC_CODE, RBRPBDR_ACTIVITY_DATE
) VALUES (
    '2627', 'MR', 'CAMP', '7BS', NULL, NULL, '7BS', 
    TO_DATE('12/10/2025 14:45:29', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBDR (
    RBRPBDR_AIDY_CODE, RBRPBDR_PBGP_CODE, RBRPBDR_PBTP_CODE, RBRPBDR_PBCP_CODE, 
    RBRPBDR_PERIOD, RBRPBDR_AMT, RBRPBDR_ABRC_CODE, RBRPBDR_ACTIVITY_DATE
) VALUES (
    '2627', 'MR', 'CAMP', '2FEE', NULL, NULL, '2FEE', 
    TO_DATE('12/10/2025 14:45:29', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBDR (
    RBRPBDR_AIDY_CODE, RBRPBDR_PBGP_CODE, RBRPBDR_PBTP_CODE, RBRPBDR_PBCP_CODE, 
    RBRPBDR_PERIOD, RBRPBDR_AMT, RBRPBDR_ABRC_CODE, RBRPBDR_ACTIVITY_DATE
) VALUES (
    '2627', 'MR', 'CAMP', '3HSM', NULL, NULL, '3HSM', 
    TO_DATE('12/10/2025 14:45:29', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBDR (
    RBRPBDR_AIDY_CODE, RBRPBDR_PBGP_CODE, RBRPBDR_PBTP_CODE, RBRPBDR_PBCP_CODE, 
    RBRPBDR_PERIOD, RBRPBDR_AMT, RBRPBDR_ABRC_CODE, RBRPBDR_ACTIVITY_DATE
) VALUES (
    '2627', 'MR', 'CAMP', '6LIV', NULL, NULL, '6LIV', 
    TO_DATE('12/10/2025 14:45:29', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBDR (
    RBRPBDR_AIDY_CODE, RBRPBDR_PBGP_CODE, RBRPBDR_PBTP_CODE, RBRPBDR_PBCP_CODE, 
    RBRPBDR_PERIOD, RBRPBDR_AMT, RBRPBDR_ABRC_CODE, RBRPBDR_ACTIVITY_DATE
) VALUES (
    '2627', 'MR', 'CAMP', '5CAF', NULL, NULL, '5CAF', 
    TO_DATE('12/10/2025 14:45:29', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBDR (
    RBRPBDR_AIDY_CODE, RBRPBDR_PBGP_CODE, RBRPBDR_PBTP_CODE, RBRPBDR_PBCP_CODE, 
    RBRPBDR_PERIOD, RBRPBDR_AMT, RBRPBDR_ABRC_CODE, RBRPBDR_ACTIVITY_DATE
) VALUES (
    '2627', 'MR', 'CAMP', '24SF', NULL, NULL, '24SF', 
    TO_DATE('12/10/2025 14:45:29', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBDR (
    RBRPBDR_AIDY_CODE, RBRPBDR_PBGP_CODE, RBRPBDR_PBTP_CODE, RBRPBDR_PBCP_CODE, 
    RBRPBDR_PERIOD, RBRPBDR_AMT, RBRPBDR_ABRC_CODE, RBRPBDR_ACTIVITY_DATE
) VALUES (
    '2627', 'MR', 'CAMP', '8TRS', NULL, NULL, '8TRS', 
    TO_DATE('12/10/2025 14:45:29', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBDR (
    RBRPBDR_AIDY_CODE, RBRPBDR_PBGP_CODE, RBRPBDR_PBTP_CODE, RBRPBDR_PBCP_CODE, 
    RBRPBDR_PERIOD, RBRPBDR_AMT, RBRPBDR_ABRC_CODE, RBRPBDR_ACTIVITY_DATE
) VALUES (
    '2627', 'MR', 'CAMP', '22DF', NULL, NULL, '22DF', 
    TO_DATE('12/10/2025 14:45:29', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBDR (
    RBRPBDR_AIDY_CODE, RBRPBDR_PBGP_CODE, RBRPBDR_PBTP_CODE, RBRPBDR_PBCP_CODE, 
    RBRPBDR_PERIOD, RBRPBDR_AMT, RBRPBDR_ABRC_CODE, RBRPBDR_ACTIVITY_DATE
) VALUES (
    '2627', 'MR', 'CAMP', '23PF', NULL, NULL, '23PF', 
    TO_DATE('12/10/2025 14:45:29', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBDR (
    RBRPBDR_AIDY_CODE, RBRPBDR_PBGP_CODE, RBRPBDR_PBTP_CODE, RBRPBDR_PBCP_CODE, 
    RBRPBDR_PERIOD, RBRPBDR_AMT, RBRPBDR_ABRC_CODE, RBRPBDR_ACTIVITY_DATE
) VALUES (
    '2627', 'MR', 'CAMP', '1TUI', NULL, NULL, '1TUI_MR', 
    TO_DATE('12/10/2025 14:45:40', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBDR (
    RBRPBDR_AIDY_CODE, RBRPBDR_PBGP_CODE, RBRPBDR_PBTP_CODE, RBRPBDR_PBCP_CODE, 
    RBRPBDR_PERIOD, RBRPBDR_AMT, RBRPBDR_ABRC_CODE, RBRPBDR_ACTIVITY_DATE
) VALUES (
    '2627', 'PL', 'CAMP', '9MIS', NULL, NULL, '9MIS', 
    TO_DATE('12/10/2025 14:45:55', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBDR (
    RBRPBDR_AIDY_CODE, RBRPBDR_PBGP_CODE, RBRPBDR_PBTP_CODE, RBRPBDR_PBCP_CODE, 
    RBRPBDR_PERIOD, RBRPBDR_AMT, RBRPBDR_ABRC_CODE, RBRPBDR_ACTIVITY_DATE
) VALUES (
    '2627', 'PL', 'CAMP', '7BS', NULL, NULL, '7BS', 
    TO_DATE('12/10/2025 14:45:55', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBDR (
    RBRPBDR_AIDY_CODE, RBRPBDR_PBGP_CODE, RBRPBDR_PBTP_CODE, RBRPBDR_PBCP_CODE, 
    RBRPBDR_PERIOD, RBRPBDR_AMT, RBRPBDR_ABRC_CODE, RBRPBDR_ACTIVITY_DATE
) VALUES (
    '2627', 'PL', 'CAMP', '2FEE', NULL, NULL, '2FEE', 
    TO_DATE('12/10/2025 14:45:55', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBDR (
    RBRPBDR_AIDY_CODE, RBRPBDR_PBGP_CODE, RBRPBDR_PBTP_CODE, RBRPBDR_PBCP_CODE, 
    RBRPBDR_PERIOD, RBRPBDR_AMT, RBRPBDR_ABRC_CODE, RBRPBDR_ACTIVITY_DATE
) VALUES (
    '2627', 'PL', 'CAMP', '3HSM', NULL, NULL, '3HSM', 
    TO_DATE('12/10/2025 14:45:55', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBDR (
    RBRPBDR_AIDY_CODE, RBRPBDR_PBGP_CODE, RBRPBDR_PBTP_CODE, RBRPBDR_PBCP_CODE, 
    RBRPBDR_PERIOD, RBRPBDR_AMT, RBRPBDR_ABRC_CODE, RBRPBDR_ACTIVITY_DATE
) VALUES (
    '2627', 'PL', 'CAMP', '6LIV', NULL, NULL, '6LIV', 
    TO_DATE('12/10/2025 14:45:55', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBDR (
    RBRPBDR_AIDY_CODE, RBRPBDR_PBGP_CODE, RBRPBDR_PBTP_CODE, RBRPBDR_PBCP_CODE, 
    RBRPBDR_PERIOD, RBRPBDR_AMT, RBRPBDR_ABRC_CODE, RBRPBDR_ACTIVITY_DATE
) VALUES (
    '2627', 'PL', 'CAMP', '8TRS', NULL, NULL, '8TRS', 
    TO_DATE('12/10/2025 14:45:55', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBDR (
    RBRPBDR_AIDY_CODE, RBRPBDR_PBGP_CODE, RBRPBDR_PBTP_CODE, RBRPBDR_PBCP_CODE, 
    RBRPBDR_PERIOD, RBRPBDR_AMT, RBRPBDR_ABRC_CODE, RBRPBDR_ACTIVITY_DATE
) VALUES (
    '2627', 'PL', 'CAMP', '1TUI', NULL, NULL, '1TUI_PL', 
    TO_DATE('12/10/2025 14:46:09', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBDR (
    RBRPBDR_AIDY_CODE, RBRPBDR_PBGP_CODE, RBRPBDR_PBTP_CODE, RBRPBDR_PBCP_CODE, 
    RBRPBDR_PERIOD, RBRPBDR_AMT, RBRPBDR_ABRC_CODE, RBRPBDR_ACTIVITY_DATE
) VALUES (
    '2627', 'PM', 'CAMP', '9MIS', NULL, NULL, '9MIS', 
    TO_DATE('12/10/2025 14:46:16', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBDR (
    RBRPBDR_AIDY_CODE, RBRPBDR_PBGP_CODE, RBRPBDR_PBTP_CODE, RBRPBDR_PBCP_CODE, 
    RBRPBDR_PERIOD, RBRPBDR_AMT, RBRPBDR_ABRC_CODE, RBRPBDR_ACTIVITY_DATE
) VALUES (
    '2627', 'PM', 'CAMP', '7BS', NULL, NULL, '7BS', 
    TO_DATE('12/10/2025 14:46:16', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBDR (
    RBRPBDR_AIDY_CODE, RBRPBDR_PBGP_CODE, RBRPBDR_PBTP_CODE, RBRPBDR_PBCP_CODE, 
    RBRPBDR_PERIOD, RBRPBDR_AMT, RBRPBDR_ABRC_CODE, RBRPBDR_ACTIVITY_DATE
) VALUES (
    '2627', 'PM', 'CAMP', '2FEE', NULL, NULL, '2FEE', 
    TO_DATE('12/10/2025 14:46:16', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBDR (
    RBRPBDR_AIDY_CODE, RBRPBDR_PBGP_CODE, RBRPBDR_PBTP_CODE, RBRPBDR_PBCP_CODE, 
    RBRPBDR_PERIOD, RBRPBDR_AMT, RBRPBDR_ABRC_CODE, RBRPBDR_ACTIVITY_DATE
) VALUES (
    '2627', 'PM', 'CAMP', '3HSM', NULL, NULL, '3HSM', 
    TO_DATE('12/10/2025 14:46:16', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBDR (
    RBRPBDR_AIDY_CODE, RBRPBDR_PBGP_CODE, RBRPBDR_PBTP_CODE, RBRPBDR_PBCP_CODE, 
    RBRPBDR_PERIOD, RBRPBDR_AMT, RBRPBDR_ABRC_CODE, RBRPBDR_ACTIVITY_DATE
) VALUES (
    '2627', 'PM', 'CAMP', '6LIV', NULL, NULL, '6LIV', 
    TO_DATE('12/10/2025 14:46:16', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBDR (
    RBRPBDR_AIDY_CODE, RBRPBDR_PBGP_CODE, RBRPBDR_PBTP_CODE, RBRPBDR_PBCP_CODE, 
    RBRPBDR_PERIOD, RBRPBDR_AMT, RBRPBDR_ABRC_CODE, RBRPBDR_ACTIVITY_DATE
) VALUES (
    '2627', 'PM', 'CAMP', '8TRS', NULL, NULL, '8TRS', 
    TO_DATE('12/10/2025 14:46:17', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBDR (
    RBRPBDR_AIDY_CODE, RBRPBDR_PBGP_CODE, RBRPBDR_PBTP_CODE, RBRPBDR_PBCP_CODE, 
    RBRPBDR_PERIOD, RBRPBDR_AMT, RBRPBDR_ABRC_CODE, RBRPBDR_ACTIVITY_DATE
) VALUES (
    '2627', 'PM', 'CAMP', '1TUI', NULL, NULL, '1TUI_PM', 
    TO_DATE('12/10/2025 14:46:26', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBDR (
    RBRPBDR_AIDY_CODE, RBRPBDR_PBGP_CODE, RBRPBDR_PBTP_CODE, RBRPBDR_PBCP_CODE, 
    RBRPBDR_PERIOD, RBRPBDR_AMT, RBRPBDR_ABRC_CODE, RBRPBDR_ACTIVITY_DATE
) VALUES (
    '2627', 'GR', 'CAMP', '9MIS', NULL, NULL, '9MIS', 
    TO_DATE('12/10/2025 14:46:37', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBDR (
    RBRPBDR_AIDY_CODE, RBRPBDR_PBGP_CODE, RBRPBDR_PBTP_CODE, RBRPBDR_PBCP_CODE, 
    RBRPBDR_PERIOD, RBRPBDR_AMT, RBRPBDR_ABRC_CODE, RBRPBDR_ACTIVITY_DATE
) VALUES (
    '2627', 'GR', 'CAMP', '7BS', NULL, NULL, '7BS', 
    TO_DATE('12/10/2025 14:46:37', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBDR (
    RBRPBDR_AIDY_CODE, RBRPBDR_PBGP_CODE, RBRPBDR_PBTP_CODE, RBRPBDR_PBCP_CODE, 
    RBRPBDR_PERIOD, RBRPBDR_AMT, RBRPBDR_ABRC_CODE, RBRPBDR_ACTIVITY_DATE
) VALUES (
    '2627', 'GR', 'CAMP', '2FEE', NULL, NULL, '2FEE', 
    TO_DATE('12/10/2025 14:46:37', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBDR (
    RBRPBDR_AIDY_CODE, RBRPBDR_PBGP_CODE, RBRPBDR_PBTP_CODE, RBRPBDR_PBCP_CODE, 
    RBRPBDR_PERIOD, RBRPBDR_AMT, RBRPBDR_ABRC_CODE, RBRPBDR_ACTIVITY_DATE
) VALUES (
    '2627', 'GR', 'CAMP', '3HSM', NULL, NULL, '3HSM', 
    TO_DATE('12/10/2025 14:46:37', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBDR (
    RBRPBDR_AIDY_CODE, RBRPBDR_PBGP_CODE, RBRPBDR_PBTP_CODE, RBRPBDR_PBCP_CODE, 
    RBRPBDR_PERIOD, RBRPBDR_AMT, RBRPBDR_ABRC_CODE, RBRPBDR_ACTIVITY_DATE
) VALUES (
    '2627', 'GR', 'CAMP', '6LIV', NULL, NULL, '6LIV', 
    TO_DATE('12/10/2025 14:46:37', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBDR (
    RBRPBDR_AIDY_CODE, RBRPBDR_PBGP_CODE, RBRPBDR_PBTP_CODE, RBRPBDR_PBCP_CODE, 
    RBRPBDR_PERIOD, RBRPBDR_AMT, RBRPBDR_ABRC_CODE, RBRPBDR_ACTIVITY_DATE
) VALUES (
    '2627', 'GR', 'CAMP', '8TRS', NULL, NULL, '8TRS', 
    TO_DATE('12/10/2025 14:46:37', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBDR (
    RBRPBDR_AIDY_CODE, RBRPBDR_PBGP_CODE, RBRPBDR_PBTP_CODE, RBRPBDR_PBCP_CODE, 
    RBRPBDR_PERIOD, RBRPBDR_AMT, RBRPBDR_ABRC_CODE, RBRPBDR_ACTIVITY_DATE
) VALUES (
    '2627', 'GR', 'CAMP', '22DF', NULL, NULL, '22DF', 
    TO_DATE('12/10/2025 14:46:37', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPBDR (
    RBRPBDR_AIDY_CODE, RBRPBDR_PBGP_CODE, RBRPBDR_PBTP_CODE, RBRPBDR_PBCP_CODE, 
    RBRPBDR_PERIOD, RBRPBDR_AMT, RBRPBDR_ABRC_CODE, RBRPBDR_ACTIVITY_DATE
) VALUES (
    '2627', 'GR', 'CAMP', '1TUI', NULL, NULL, '1TUI_GR', 
    TO_DATE('12/10/2025 14:46:47', 'MM/DD/YYYY HH24:MI:SS')
);


