-- insert 5 rows into 4 FAISMGR.RTVPBGP fields
INSERT INTO FAISMGR.RTVPBGP (
    RTVPBGP_CODE, RTVPBGP_DESC, RTVPBGP_ACTIVE_IND, RTVPBGP_ACTIVITY_DATE
) VALUES (
    'UG', 'Undergraduate', 'Y', 
    TO_DATE('12/10/2025 11:16:59', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RTVPBGP (
    RTVPBGP_CODE, RTVPBGP_DESC, RTVPBGP_ACTIVE_IND, RTVPBGP_ACTIVITY_DATE
) VALUES (
    'GR', 'Graduate', 'Y', 
    TO_DATE('12/10/2025 11:15:25', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RTVPBGP (
    RTVPBGP_CODE, RTVPBGP_DESC, RTVPBGP_ACTIVE_IND, RTVPBGP_ACTIVITY_DATE
) VALUES (
    'PL', 'LAW', 'Y', TO_DATE('12/10/2025 11:15:25', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RTVPBGP (
    RTVPBGP_CODE, RTVPBGP_DESC, RTVPBGP_ACTIVE_IND, RTVPBGP_ACTIVITY_DATE
) VALUES (
    'PM', 'MED', 'Y', TO_DATE('12/10/2025 11:15:25', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RTVPBGP (
    RTVPBGP_CODE, RTVPBGP_DESC, RTVPBGP_ACTIVE_IND, RTVPBGP_ACTIVITY_DATE
) VALUES (
    'MR', 'Madrid', 'Y', 
    TO_DATE('12/10/2025 11:15:25', 'MM/DD/YYYY HH24:MI:SS')
);

-- insert 14 rows into 4 FAISMGR.RTVPBCP fields
INSERT INTO FAISMGR.RTVPBCP (
    RTVPBCP_CODE, RTVPBCP_DESC, RTVPBCP_ACTIVE_IND, RTVPBCP_ACTIVITY_DATE
) VALUES (
    '1TUI', 'Tuition', 'Y', 
    TO_DATE('05/02/2023 09:39:29', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RTVPBCP (
    RTVPBCP_CODE, RTVPBCP_DESC, RTVPBCP_ACTIVE_IND, RTVPBCP_ACTIVITY_DATE
) VALUES (
    '2FEE', 'Fees', 'Y', 
    TO_DATE('05/02/2023 09:39:29', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RTVPBCP (
    RTVPBCP_CODE, RTVPBCP_DESC, RTVPBCP_ACTIVE_IND, RTVPBCP_ACTIVITY_DATE
) VALUES (
    '7BS', 'Books and Supplies', 'Y', 
    TO_DATE('05/02/2023 09:39:29', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RTVPBCP (
    RTVPBCP_CODE, RTVPBCP_DESC, RTVPBCP_ACTIVE_IND, RTVPBCP_ACTIVITY_DATE
) VALUES (
    '8TRS', 'Transportation', 'Y', 
    TO_DATE('05/02/2023 09:39:29', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RTVPBCP (
    RTVPBCP_CODE, RTVPBCP_DESC, RTVPBCP_ACTIVE_IND, RTVPBCP_ACTIVITY_DATE
) VALUES (
    '9MIS', 'Miscellaneous', 'Y', 
    TO_DATE('05/02/2023 09:39:30', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RTVPBCP (
    RTVPBCP_CODE, RTVPBCP_DESC, RTVPBCP_ACTIVE_IND, RTVPBCP_ACTIVITY_DATE
) VALUES (
    '3HSM', 'Housing and Food', 'Y', 
    TO_DATE('09/25/2025 14:13:34', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RTVPBCP (
    RTVPBCP_CODE, RTVPBCP_DESC, RTVPBCP_ACTIVE_IND, RTVPBCP_ACTIVITY_DATE
) VALUES (
    '4COM', 'Commuter Meal Plan', 'Y', 
    TO_DATE('05/02/2023 09:39:30', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RTVPBCP (
    RTVPBCP_CODE, RTVPBCP_DESC, RTVPBCP_ACTIVE_IND, RTVPBCP_ACTIVITY_DATE
) VALUES (
    '5CAF', 'Cafeteria Plan', 'Y', 
    TO_DATE('05/02/2023 09:39:30', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RTVPBCP (
    RTVPBCP_CODE, RTVPBCP_DESC, RTVPBCP_ACTIVE_IND, RTVPBCP_ACTIVITY_DATE
) VALUES (
    '6LIV', 'Living Expenses', 'Y', 
    TO_DATE('05/02/2023 09:39:30', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RTVPBCP (
    RTVPBCP_CODE, RTVPBCP_DESC, RTVPBCP_ACTIVE_IND, RTVPBCP_ACTIVITY_DATE
) VALUES (
    '21BF', 'Business Technology Fee', 'Y', 
    TO_DATE('05/04/2023 12:29:35', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RTVPBCP (
    RTVPBCP_CODE, RTVPBCP_DESC, RTVPBCP_ACTIVE_IND, RTVPBCP_ACTIVITY_DATE
) VALUES (
    '22DF', 'Doisy College Technology Fee', 'Y', 
    TO_DATE('05/04/2023 12:29:35', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RTVPBCP (
    RTVPBCP_CODE, RTVPBCP_DESC, RTVPBCP_ACTIVE_IND, RTVPBCP_ACTIVITY_DATE
) VALUES (
    '23PF', 'SSE Technology Fee', 'Y', 
    TO_DATE('12/12/2025 09:57:57', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RTVPBCP (
    RTVPBCP_CODE, RTVPBCP_DESC, RTVPBCP_ACTIVE_IND, RTVPBCP_ACTIVITY_DATE
) VALUES (
    '24SF', 'Study Abroad', 'Y', 
    TO_DATE('05/04/2023 12:29:35', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RTVPBCP (
    RTVPBCP_CODE, RTVPBCP_DESC, RTVPBCP_ACTIVE_IND, RTVPBCP_ACTIVITY_DATE
) VALUES (
    '20FE', 'Fees', 'Y', 
    TO_DATE('05/04/2023 12:30:39', 'MM/DD/YYYY HH24:MI:SS')
);

-- insert 31 rows into 4 FAISMGR.RTVABRC fields
INSERT INTO FAISMGR.RTVABRC (
    RTVABRC_CODE, RTVABRC_DESC, RTVABRC_ACTIVE_IND, RTVABRC_ACTIVITY_DATE
) VALUES (
    'LFEE', 'Loan Fees', 'Y', 
    TO_DATE('04/06/2023 13:28:22', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RTVABRC (
    RTVABRC_CODE, RTVABRC_DESC, RTVABRC_ACTIVE_IND, RTVABRC_ACTIVITY_DATE
) VALUES (
    '5CAF', 'Madrid Cafeteria', 'Y', 
    TO_DATE('12/09/2025 15:12:35', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RTVABRC (
    RTVABRC_CODE, RTVABRC_DESC, RTVABRC_ACTIVE_IND, RTVABRC_ACTIVITY_DATE
) VALUES (
    '5CAF_PELL', 'Madrid Cafeteria (PELL)', 'Y', 
    TO_DATE('12/09/2025 15:12:35', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RTVABRC (
    RTVABRC_CODE, RTVABRC_DESC, RTVABRC_ACTIVE_IND, RTVABRC_ACTIVITY_DATE
) VALUES (
    '2FEE', 'Fees', 'Y', 
    TO_DATE('12/09/2025 16:02:30', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RTVABRC (
    RTVABRC_CODE, RTVABRC_DESC, RTVABRC_ACTIVE_IND, RTVABRC_ACTIVITY_DATE
) VALUES (
    '2FEE_PELL', 'Fees (PELL)', 'Y', 
    TO_DATE('12/09/2025 16:02:30', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RTVABRC (
    RTVABRC_CODE, RTVABRC_DESC, RTVABRC_ACTIVE_IND, RTVABRC_ACTIVITY_DATE
) VALUES (
    '9MIS_PELL', 'Miscellaneous (PELL)', 'Y', 
    TO_DATE('12/09/2025 16:11:47', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RTVABRC (
    RTVABRC_CODE, RTVABRC_DESC, RTVABRC_ACTIVE_IND, RTVABRC_ACTIVITY_DATE
) VALUES (
    '21BF', 'Business Software Fee', 'Y', 
    TO_DATE('12/09/2025 16:14:37', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RTVABRC (
    RTVABRC_CODE, RTVABRC_DESC, RTVABRC_ACTIVE_IND, RTVABRC_ACTIVITY_DATE
) VALUES (
    '21BF_PELL', 'Business Software Fee (PELL)', 'Y', 
    TO_DATE('12/09/2025 16:14:37', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RTVABRC (
    RTVABRC_CODE, RTVABRC_DESC, RTVABRC_ACTIVE_IND, RTVABRC_ACTIVITY_DATE
) VALUES (
    '23PF', 'Parks Tech Fee', 'Y', 
    TO_DATE('12/09/2025 16:14:37', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RTVABRC (
    RTVABRC_CODE, RTVABRC_DESC, RTVABRC_ACTIVE_IND, RTVABRC_ACTIVITY_DATE
) VALUES (
    '23PF_PELL', 'Parks Tech Fee (PELL)', 'Y', 
    TO_DATE('12/09/2025 16:14:37', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RTVABRC (
    RTVABRC_CODE, RTVABRC_DESC, RTVABRC_ACTIVE_IND, RTVABRC_ACTIVITY_DATE
) VALUES (
    '24SF', 'Study Abroad Fee', 'Y', 
    TO_DATE('12/09/2025 16:14:37', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RTVABRC (
    RTVABRC_CODE, RTVABRC_DESC, RTVABRC_ACTIVE_IND, RTVABRC_ACTIVITY_DATE
) VALUES (
    '8TRS', 'Transportation', 'Y', 
    TO_DATE('12/09/2025 16:03:37', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RTVABRC (
    RTVABRC_CODE, RTVABRC_DESC, RTVABRC_ACTIVE_IND, RTVABRC_ACTIVITY_DATE
) VALUES (
    '8TRS_PELL', 'Transportation (PELL)', 'Y', 
    TO_DATE('12/09/2025 16:03:37', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RTVABRC (
    RTVABRC_CODE, RTVABRC_DESC, RTVABRC_ACTIVE_IND, RTVABRC_ACTIVITY_DATE
) VALUES (
    '3HSM', 'Housing and Meals', 'Y', 
    TO_DATE('12/09/2025 16:09:58', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RTVABRC (
    RTVABRC_CODE, RTVABRC_DESC, RTVABRC_ACTIVE_IND, RTVABRC_ACTIVITY_DATE
) VALUES (
    '3HSM_PELL', 'Housing and Meals (PELL)', 'Y', 
    TO_DATE('12/09/2025 16:09:58', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RTVABRC (
    RTVABRC_CODE, RTVABRC_DESC, RTVABRC_ACTIVE_IND, RTVABRC_ACTIVITY_DATE
) VALUES (
    '4COM', 'Commuter Meal Plan', 'Y', 
    TO_DATE('12/09/2025 16:09:58', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RTVABRC (
    RTVABRC_CODE, RTVABRC_DESC, RTVABRC_ACTIVE_IND, RTVABRC_ACTIVITY_DATE
) VALUES (
    '4COM_PELL', 'Commuter Meal Plan (PELL)', 'Y', 
    TO_DATE('12/09/2025 16:09:58', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RTVABRC (
    RTVABRC_CODE, RTVABRC_DESC, RTVABRC_ACTIVE_IND, RTVABRC_ACTIVITY_DATE
) VALUES (
    '6LIV', 'Off Campus Living Expenses', 'Y', 
    TO_DATE('12/09/2025 16:09:58', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RTVABRC (
    RTVABRC_CODE, RTVABRC_DESC, RTVABRC_ACTIVE_IND, RTVABRC_ACTIVITY_DATE
) VALUES (
    '6LIV_PELL', 'Off Campus Living Expenses (PELL)', 'Y', 
    TO_DATE('12/09/2025 16:09:58', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RTVABRC (
    RTVABRC_CODE, RTVABRC_DESC, RTVABRC_ACTIVE_IND, RTVABRC_ACTIVITY_DATE
) VALUES (
    '7BS', 'Books and Supplies', 'Y', 
    TO_DATE('12/09/2025 16:11:14', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RTVABRC (
    RTVABRC_CODE, RTVABRC_DESC, RTVABRC_ACTIVE_IND, RTVABRC_ACTIVITY_DATE
) VALUES (
    '7BS_PELL', 'Books and Supplies (PELL)', 'Y', 
    TO_DATE('12/09/2025 16:11:14', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RTVABRC (
    RTVABRC_CODE, RTVABRC_DESC, RTVABRC_ACTIVE_IND, RTVABRC_ACTIVITY_DATE
) VALUES (
    '9MIS', 'Miscellaneous', 'Y', 
    TO_DATE('12/09/2025 16:11:47', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RTVABRC (
    RTVABRC_CODE, RTVABRC_DESC, RTVABRC_ACTIVE_IND, RTVABRC_ACTIVITY_DATE
) VALUES (
    '24SF_PELL', 'Study Abroad Fee (PELL)', 'Y', 
    TO_DATE('12/09/2025 16:14:37', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RTVABRC (
    RTVABRC_CODE, RTVABRC_DESC, RTVABRC_ACTIVE_IND, RTVABRC_ACTIVITY_DATE
) VALUES (
    '22DF', 'Doisy College Software Fee', 'Y', 
    TO_DATE('12/09/2025 16:14:37', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RTVABRC (
    RTVABRC_CODE, RTVABRC_DESC, RTVABRC_ACTIVE_IND, RTVABRC_ACTIVITY_DATE
) VALUES (
    '22DF_PELL', 'Doisy College Software Fee (PELL)', 'Y', 
    TO_DATE('12/09/2025 16:14:37', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RTVABRC (
    RTVABRC_CODE, RTVABRC_DESC, RTVABRC_ACTIVE_IND, RTVABRC_ACTIVITY_DATE
) VALUES (
    '1TUI_UG', 'Tuition UG', 'Y', 
    TO_DATE('12/10/2025 11:43:11', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RTVABRC (
    RTVABRC_CODE, RTVABRC_DESC, RTVABRC_ACTIVE_IND, RTVABRC_ACTIVITY_DATE
) VALUES (
    '1TUI_UG_PELL', 'Tuition (PELL)', 'Y', 
    TO_DATE('12/10/2025 11:43:11', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RTVABRC (
    RTVABRC_CODE, RTVABRC_DESC, RTVABRC_ACTIVE_IND, RTVABRC_ACTIVITY_DATE
) VALUES (
    '1TUI_GR', 'Tuition GR', 'Y', 
    TO_DATE('12/10/2025 11:43:25', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RTVABRC (
    RTVABRC_CODE, RTVABRC_DESC, RTVABRC_ACTIVE_IND, RTVABRC_ACTIVITY_DATE
) VALUES (
    '1TUI_PM', 'Tuition MED', 'Y', 
    TO_DATE('12/10/2025 11:43:52', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RTVABRC (
    RTVABRC_CODE, RTVABRC_DESC, RTVABRC_ACTIVE_IND, RTVABRC_ACTIVITY_DATE
) VALUES (
    '1TUI_PL', 'Tuition LAW', 'Y', 
    TO_DATE('12/10/2025 11:43:52', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RTVABRC (
    RTVABRC_CODE, RTVABRC_DESC, RTVABRC_ACTIVE_IND, RTVABRC_ACTIVITY_DATE
) VALUES (
    '1TUI_MR', 'Tuition Madrid', 'Y', 
    TO_DATE('12/10/2025 11:44:13', 'MM/DD/YYYY HH24:MI:SS')
);

-- insert 8 rows into 4 FAISMGR.RBRPGPT fields
INSERT INTO FAISMGR.RBRPGPT (
    RBRPGPT_AIDY_CODE, RBRPGPT_PBGP_CODE, RBRPGPT_PBTP_CODE, 
    RBRPGPT_ACTIVITY_DATE
) VALUES (
    '2627', 'AC', 'CAMP', 
    TO_DATE('10/30/2025 08:23:23', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPGPT (
    RBRPGPT_AIDY_CODE, RBRPGPT_PBGP_CODE, RBRPGPT_PBTP_CODE, 
    RBRPGPT_ACTIVITY_DATE
) VALUES (
    '2627', 'GR', 'CAMP', 
    TO_DATE('12/10/2025 14:44:34', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPGPT (
    RBRPGPT_AIDY_CODE, RBRPGPT_PBGP_CODE, RBRPGPT_PBTP_CODE, 
    RBRPGPT_ACTIVITY_DATE
) VALUES (
    '2627', 'MR', 'CAMP', 
    TO_DATE('12/10/2025 14:45:13', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPGPT (
    RBRPGPT_AIDY_CODE, RBRPGPT_PBGP_CODE, RBRPGPT_PBTP_CODE, 
    RBRPGPT_ACTIVITY_DATE
) VALUES (
    '2627', 'MR', 'PELL', 
    TO_DATE('12/11/2025 15:48:39', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPGPT (
    RBRPGPT_AIDY_CODE, RBRPGPT_PBGP_CODE, RBRPGPT_PBTP_CODE, 
    RBRPGPT_ACTIVITY_DATE
) VALUES (
    '2627', 'PL', 'CAMP', 
    TO_DATE('12/10/2025 14:44:52', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPGPT (
    RBRPGPT_AIDY_CODE, RBRPGPT_PBGP_CODE, RBRPGPT_PBTP_CODE, 
    RBRPGPT_ACTIVITY_DATE
) VALUES (
    '2627', 'PM', 'CAMP', 
    TO_DATE('12/10/2025 14:45:04', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPGPT (
    RBRPGPT_AIDY_CODE, RBRPGPT_PBGP_CODE, RBRPGPT_PBTP_CODE, 
    RBRPGPT_ACTIVITY_DATE
) VALUES (
    '2627', 'UG', 'CAMP', 
    TO_DATE('12/10/2025 11:57:21', 'MM/DD/YYYY HH24:MI:SS')
);

INSERT INTO FAISMGR.RBRPGPT (
    RBRPGPT_AIDY_CODE, RBRPGPT_PBGP_CODE, RBRPGPT_PBTP_CODE, 
    RBRPGPT_ACTIVITY_DATE
) VALUES (
    '2627', 'UG', 'PELL', 
    TO_DATE('12/10/2025 11:57:21', 'MM/DD/YYYY HH24:MI:SS')
);

