-- PL PB RORRULE
SELECT A.RORSTAT_PIDM
FROM RORSTAT A
INNER JOIN ROBINST R ON R.ROBINST_AIDY_CODE = A.RORSTAT_AIDY_CODE
WHERE A.RORSTAT_AIDY_CODE = :AIDY 
-- AND RORSTAT_PIDM = :PIDM 
AND (
    EXISTS (
        SELECT 1
        FROM SGBSTDN B
        WHERE B.SGBSTDN_PIDM = A.RORSTAT_PIDM
        AND B.SGBSTDN_LEVL_CODE = 'PL'
        AND B.SGBSTDN_CAMP_CODE <> 'SP'
        AND B.SGBSTDN_STST_CODE IN ('AS', 'IL', 'P1')
        AND B.SGBSTDN_TERM_CODE_EFF = (
            SELECT MAX(Z.SGBSTDN_TERM_CODE_EFF) FROM SGBSTDN Z
            WHERE Z.SGBSTDN_PIDM = B.SGBSTDN_PIDM
            AND Z.SGBSTDN_LEVL_CODE = B.SGBSTDN_LEVL_CODE
            AND Z.SGBSTDN_CAMP_CODE = B.SGBSTDN_CAMP_CODE
            AND Z.SGBSTDN_STST_CODE = B.SGBSTDN_STST_CODE
        )
        AND NOT EXISTS ( -- NO NEWER SARADAP RECORD FOR A DIFFERENT LEVEL
            SELECT 1
            FROM SARADAP C
            INNER JOIN SARAPPD D 
                ON D.SARAPPD_PIDM = C.SARADAP_PIDM
                AND D.SARAPPD_APPL_NO = C.SARADAP_APPL_NO
                AND D.SARAPPD_TERM_CODE_ENTRY = C.SARADAP_TERM_CODE_ENTRY
            INNER JOIN STVAPDC E
                ON E.STVAPDC_CODE = D.SARAPPD_APDC_CODE
                AND E.STVAPDC_INST_ACC_IND = 'Y'
                AND E.STVAPDC_SIGNF_IND = 'Y'
            WHERE C.SARADAP_PIDM = A.RORSTAT_PIDM
            AND D.SARAPPD_SEQ_NO = (
                SELECT MAX(Z.SARAPPD_SEQ_NO) FROM SARAPPD Z
                WHERE Z.SARAPPD_PIDM = D.SARAPPD_PIDM
                AND Z.SARAPPD_TERM_CODE_ENTRY = D.SARAPPD_TERM_CODE_ENTRY
                AND Z.SARAPPD_APPL_NO = D.SARAPPD_APPL_NO
            )
            AND C.SARADAP_LEVL_CODE <> 'PL'
            AND C.SARADAP_TERM_CODE_ENTRY BETWEEN (R.ROBINST_AIDY_END_YEAR || '00') AND :PERIOD 
        )
    )
    OR EXISTS (
        SELECT 1
        FROM SARADAP C
        INNER JOIN SARAPPD D 
            ON D.SARAPPD_PIDM = C.SARADAP_PIDM
            AND D.SARAPPD_APPL_NO = C.SARADAP_APPL_NO
            AND D.SARAPPD_TERM_CODE_ENTRY = C.SARADAP_TERM_CODE_ENTRY
        INNER JOIN STVAPDC E
            ON E.STVAPDC_CODE = D.SARAPPD_APDC_CODE
            AND E.STVAPDC_INST_ACC_IND = 'Y'
            AND E.STVAPDC_SIGNF_IND = 'Y'
        WHERE C.SARADAP_PIDM = A.RORSTAT_PIDM
        AND C.SARADAP_LEVL_CODE = 'PL'
        AND C.SARADAP_CAMP_CODE <> 'SP'
        AND C.SARADAP_TERM_CODE_ENTRY = (
            SELECT MAX(Z.SARADAP_TERM_CODE_ENTRY) FROM SARADAP Z
            WHERE Z.SARADAP_PIDM = C.SARADAP_PIDM
            AND Z.SARADAP_TERM_CODE_ENTRY BETWEEN (R.ROBINST_AIDY_END_YEAR || '00') AND :PERIOD 
            AND Z.SARADAP_APPL_NO = C.SARADAP_APPL_NO
        )
        AND D.SARAPPD_SEQ_NO = (
            SELECT MAX(Z.SARAPPD_SEQ_NO) FROM SARAPPD Z
            WHERE Z.SARAPPD_PIDM = D.SARAPPD_PIDM
            AND Z.SARAPPD_TERM_CODE_ENTRY = D.SARAPPD_TERM_CODE_ENTRY
            AND Z.SARAPPD_APPL_NO = D.SARAPPD_APPL_NO
        ) 
    )
);