SELECT RORALGS_AMT --assume full time
FROM SARADAP a
CROSS JOIN RORALGS
INNER JOIN SARAPPD b
    ON b.SARAPPD_PIDM = a.SARADAP_PIDM
    AND b.SARAPPD_TERM_CODE_ENTRY = a.SARADAP_TERM_CODE_ENTRY
    AND b.SARAPPD_APPL_NO = a.SARADAP_APPL_NO 
INNER JOIN STVAPDC c
    ON c.STVAPDC_PIDM = a.SARADAP_PIDM
    AND c.STVAPDC_CODE = b.SARAPPD_APDC_CODE
INNER JOIN ROBINST r
    ON r.ROBINST_AIDY_CODE = :AIDY
LEFT JOIN SARAATT d
    ON d.SARAATT_PIDM = a.SARADAP_PIDM
    AND d.SARAATT_APPL_NO = a.SARADAP_APPL_NO
    AND d.SARAATT_TERM_CODE = a.SARADAP_TERM_CODE_ENTRY
WHERE RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '1TUI' -- budget component
AND CASE -- level code
    WHEN a.SARADAP_LEVL_CODE = 'UG' THEN 'UG'
END = RORALGS_KEY_5
AND CASE -- campus code
    WHEN a.SARADAP_CAMP_CODE = 'SP' THEN 'SP'
END = RORALGS_KEY_6
--SPTR ATTRIBUTE ONLY STAYS ACTIVE FOR FIRST TERM	
AND CASE -- attribute code
    WHEN d.SARAATT_ATTS_CODE = 'SPTR' THEN 'SPTR'
	WHEN (d.SARAATT_ATTS_CODE = 'SPDE' OR d.SARAATT_ATTS_CODE IS NULL) THEN 'SPDE'
END = RORALGS_KEY_10
AND RORALGS_KEY_12 = 'FT'

-- maa.SARADAP term <= passed period
AND a.SARADAP_TERM_CODE_ENTRY = (
    SELECT MAX(SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP
    WHERE SARADAP_PIDM = a.SARADAP_PIDM
    AND SARADAP_TERM_CODE_ENTRY >= (r.ROBINST_AIDY_END_YEAR || '00')   	
	AND SARADAP_TERM_CODE_ENTRY <= :PERIOD
)
--max application decision code sequence number
AND b.SARAPPD_SEQ_NO = (
    SELECT MAX (SARAPPD_SEQ_NO)
    FROM SARAPPD
    WHERE SARAPPD_PIDM = b.SARAPPD_PIDM
    AND SARAPPD_SEQ_NO < 99
    AND SARAPPD_TERM_CODE_ENTRY >= (r.ROBINST_AIDY_END_YEAR || '00')
    AND SARAPPD_TERM_CODE_ENTRY <= :PERIOD
    AND SARAPPD_APPL_NO = b.SARAPPD_APPL_NO
) 
AND RORALGS_AIDY_CODE = :AIDY
--AND a.SARADAP_PIDM = :PIDM;





-- new test - 546
SELECT s.SPRIDEN_ID, RORALGS_AMT, d.SARAATT_ATTS_CODE, a.SARADAP_CAMP_CODE --assume full time
FROM SARADAP a
CROSS JOIN RORALGS
INNER JOIN SPRIDEN s 
    ON s.SPRIDEN_PIDM = a.SARADAP_PIDM AND s.SPRIDEN_CHANGE_IND IS NULL
INNER JOIN SARAPPD b
    ON b.SARAPPD_PIDM = a.SARADAP_PIDM
    AND b.SARAPPD_TERM_CODE_ENTRY = a.SARADAP_TERM_CODE_ENTRY
    AND b.SARAPPD_APPL_NO = a.SARADAP_APPL_NO 
INNER JOIN STVAPDC c
    ON c.STVAPDC_CODE = b.SARAPPD_APDC_CODE
INNER JOIN ROBINST r
    ON r.ROBINST_AIDY_CODE = :AIDY
LEFT JOIN SARAATT d
    ON d.SARAATT_PIDM = a.SARADAP_PIDM
    AND d.SARAATT_APPL_NO = a.SARADAP_APPL_NO
    AND d.SARAATT_TERM_CODE = a.SARADAP_TERM_CODE_ENTRY
WHERE RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '1TUI' -- budget component
AND CASE -- level code
    WHEN a.SARADAP_LEVL_CODE = 'UG' THEN 'UG'
END = RORALGS_KEY_5
AND CASE -- campus code
    WHEN a.SARADAP_CAMP_CODE = 'SP' THEN 'SP'
END = RORALGS_KEY_6
--SPTR ATTRIBUTE ONLY STAYS ACTIVE FOR FIRST TERM	
AND CASE -- attribute code
    WHEN d.SARAATT_ATTS_CODE = 'SPTR' THEN 'SPTR'
	WHEN (d.SARAATT_ATTS_CODE = 'SPDE' OR d.SARAATT_ATTS_CODE IS NULL) THEN 'SPDE'
END = RORALGS_KEY_10
AND RORALGS_KEY_12 = 'FT'

-- maa.SARADAP term <= passed period
AND a.SARADAP_TERM_CODE_ENTRY = (
    SELECT MAX(SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP
    WHERE SARADAP_PIDM = a.SARADAP_PIDM
    AND SARADAP_TERM_CODE_ENTRY >= (r.ROBINST_AIDY_END_YEAR || '00')   	
	AND SARADAP_TERM_CODE_ENTRY <= :PERIOD
)
--max application decision code sequence number
AND b.SARAPPD_SEQ_NO = (
    SELECT MAX (SARAPPD_SEQ_NO)
    FROM SARAPPD
    WHERE SARAPPD_PIDM = b.SARAPPD_PIDM
    AND SARAPPD_SEQ_NO < 99
    AND SARAPPD_TERM_CODE_ENTRY >= (r.ROBINST_AIDY_END_YEAR || '00')
    AND SARAPPD_TERM_CODE_ENTRY <= :PERIOD
    AND SARAPPD_APPL_NO = b.SARAPPD_APPL_NO
) 
AND RORALGS_AIDY_CODE = :AIDY;
--AND a.SARADAP_PIDM = :PIDM;