-- MADRID GRAD ENROLLED
SELECT CASE
    WHEN NVL(ROKMISC.F_CALC_STUD_CREDIT_HRS(:PERIOD, X.SGBSTDN_PIDM, 'N'), 0) > 0 
        THEN round(roralgs_amt * NVL(ROKMISC.F_CALC_STUD_CREDIT_HRS(:PERIOD, X.SGBSTDN_PIDM, 'N'), 0))
    END as calc_amt
FROM SGBSTDN X, RORALGS
WHERE RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
    WHEN X.SGBSTDN_LEVL_CODE = 'GR' THEN 'GR'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SGBSTDN_CAMP_CODE = 'SP' THEN 'SP'
END = RORALGS_KEY_6
	
-- max sgbstdn term <= passed period
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(X.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
-- END

-- MADRID GRAD NOT ENROLLED WITH SGASTDN
SELECT (RORALGS_AMT * 6) 
FROM SGBSTDN X, RORALGS
WHERE RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
    WHEN X.SGBSTDN_LEVL_CODE = 'GR' THEN 'GR'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SGBSTDN_CAMP_CODE = 'SP' THEN 'SP'
END = RORALGS_KEY_6
	
-- max sgbstdn term <= passed period
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(X.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
--END

-- MADRID GRAD NOT ENROLLED NO SGASTDN
SELECT (RORALGS_AMT * 6) 
FROM SARADAP X, SARAPPD X, RORALGS, STVAPDC
WHERE RORALGS_KEY_1 = 'PBDG'

AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
    WHEN X.SARADAP_LEVL_CODE = 'GR' THEN 'GR'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SARADAP_CAMP_CODE = 'SP' THEN 'SP'
END = RORALGS_KEY_6

-- max saradap term <= passed period
AND X.SARADAP_TERM_CODE_ENTRY = (
    SELECT MAX(X.SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP Y, ROBINST
    WHERE Y.SARADAP_PIDM = X.SARADAP_PIDM
    AND Y.SARADAP_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')   	
	AND Y.SARADAP_TERM_CODE_ENTRY <= :PERIOD
	AND ROBINST_AIDY_CODE = :AIDY   
)
--max application decision code sequence number
AND X.SARAPPD_SEQ_NO = (SELECT MAX (X.SARAPPD_SEQ_NO)
             FROM SARAPPD Y, ROBINST
              WHERE     Y.SARAPPD_PIDM = X.SARAPPD_PIDM
              AND Y.SARAPPD_SEQ_NO < 99
              AND Y.SARAPPD_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
              AND Y.SARAPPD_TERM_CODE_ENTRY <= :PERIOD
              AND ROBINST_AIDY_CODE = :AIDY           
              AND X.SARADAP_APPL_NO = Y.SARAPPD_APPL_NO) 
   
--   AND STVAPDC_INST_ACC_IND = 'Y'
--   AND STVAPDC_SIGNF_IND = 'Y'
--   AND SARAPPD_APDC_CODE IN ('DD','DW','DZ')
   
	
AND X.SARAPPD_APDC_CODE = STVAPDC_CODE	
AND X.SARADAP_APPL_NO = X.SARAPPD_APPL_NO
AND X.SARADAP_TERM_CODE_ENTRY = X.SARAPPD_TERM_CODE_ENTRY
AND RORALGS_AIDY_CODE = :AIDY
AND X.SARAPPD_PIDM = X.SARADAP_PIDM	
AND X.SARADAP_PIDM = :PIDM
--END

--MADRID UNDERGRAD ENROLLED FULL TIME
SELECT CASE
    WHEN NVL(ROKMISC.F_CALC_STUD_CREDIT_HRS(:PERIOD, X.SGBSTDN_PIDM, 'N'), 0) >= 12
        THEN RORALGS_AMT
    END as calc_amt
FROM SGBSTDN X, RORALGS, SGRSATT X
WHERE RORALGS_KEY_1 = 'PBDG'

AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
    WHEN X.SGBSTDN_LEVL_CODE = 'UG' THEN 'UG'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SGBSTDN_CAMP_CODE = 'SP' THEN 'SP'
END = RORALGS_KEY_6

--SPTR ATTRIBUTE ONLY STAYS ACTIVE FOR FIRST TERM	
AND CASE -- attribute code
    WHEN X.SGRSATT_ATTS_CODE = 'SPTR' THEN 'SPTR'
	WHEN X.SGRSATT_ATTS_CODE = 'SPDE' THEN 'SPDE'
END = RORALGS_KEY_10
	
AND RORALGS_KEY_12 = 'FT'
		
-- max sgbstdn term <= passed period
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
--max attribute term
AND X.SGRSATT_TERM_CODE_EFF = (
SELECT MAX(Y.SGRSATT_TERM_CODE_EFF)
    FROM SGRSATT Y
    WHERE Y.SGRSATT_TERM_CODE_EFF <= :PERIOD
	AND X.SGRSATT_PIDM =  Y.SGRSATT_PIDM
)
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_PIDM = X.SGRSATT_PIDM
AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
-- END

--MADRID UNDERGRAD ENROLLED PART TIME
SELECT CASE
    WHEN NVL(ROKMISC.F_CALC_STUD_CREDIT_HRS(:PERIOD, X.SGBSTDN_PIDM, 'N'), 0) < 12
	AND  NVL(ROKMISC.F_CALC_STUD_CREDIT_HRS(:PERIOD, X.SGBSTDN_PIDM, 'N'), 0) > 0
        THEN round(roralgs_amt * NVL(ROKMISC.F_CALC_STUD_CREDIT_HRS(:PERIOD, X.SGBSTDN_PIDM, 'N'), 0))
    END as calc_amt
FROM SGBSTDN X, RORALGS, SGRSATT X
WHERE RORALGS_KEY_1 = 'PBDG'

AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
    WHEN X.SGBSTDN_LEVL_CODE = 'UG' THEN 'UG'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SGBSTDN_CAMP_CODE = 'SP' THEN 'SP'
END = RORALGS_KEY_6
	
--SPTR ATTRIBUTE ONLY STAYS ACTIVE FOR FIRST TERM	
AND CASE -- attribute code
    WHEN X.SGRSATT_ATTS_CODE = 'SPTR' THEN 'SPTR'
	WHEN X.SGRSATT_ATTS_CODE = 'SPDE' THEN 'SPDE'
END = RORALGS_KEY_10
	
AND RORALGS_KEY_12 = 'PT'
		
-- max sgbstdn term <= passed period
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
--max attribute term is fall term
AND X.SGRSATT_TERM_CODE_EFF = (
SELECT MAX(Y.SGRSATT_TERM_CODE_EFF)
    FROM SGRSATT Y
    WHERE Y.SGRSATT_TERM_CODE_EFF <= :PERIOD
	AND X.SGRSATT_PIDM =  Y.SGRSATT_PIDM
)
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_PIDM = X.SGRSATT_PIDM
AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
-- END

-- MADRID UNDERGRAD NOT ENROLLED WITH SGASTDN
SELECT RORALGS_AMT --assume full time
FROM SGBSTDN X, SGRSATT X, RORALGS
WHERE RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
    WHEN X.SGBSTDN_LEVL_CODE = 'UG' THEN 'UG'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SGBSTDN_CAMP_CODE = 'SP' THEN 'SP'
END = RORALGS_KEY_6

--SPTR ATTRIBUTE ONLY STAYS ACTIVE FOR FIRST TERM	
AND CASE -- attribute code
    WHEN X.SGRSATT_ATTS_CODE = 'SPTR' THEN 'SPTR'
	WHEN X.SGRSATT_ATTS_CODE = 'SPDE' THEN 'SPDE'
END = RORALGS_KEY_10
	
AND RORALGS_KEY_12 = 'FT'
	
	--max attribute term <= passed term
AND X.SGRSATT_TERM_CODE_EFF = (
SELECT MAX(Y.SGRSATT_TERM_CODE_EFF)
    FROM SGRSATT Y
    WHERE Y.SGRSATT_TERM_CODE_EFF <= :PERIOD
	AND X.SGRSATT_PIDM =  Y.SGRSATT_PIDM
)
-- max sgbstdn term <= passed period
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(X.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_PIDM = X.SGRSATT_PIDM
AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
--END



-- MADRID UNDERGRAD NOT ENROLLED NO SGASTDN
SELECT RORALGS_AMT --assume full time
FROM SARADAP a
CROSS JOIN RORALGS
INNER JOIN SPRIDEN s 
    ON s.SPRIDEN_PIDM = a.SARADAP_PIDM AND s.SPRIDEN_CHANGE_IND IS NULL
INNER JOIN SARAPPD b
    ON b.SARAPPD_PIDM = a.SARADAP_PIDM
    AND b.SARAPPD_TERM_CODE_ENTRY = a.SARADAP_TERM_CODE_ENTRY
    AND b.SARAPPD_APPL_NO = a.SARADAP_APPL_NO 
INNER JOIN STVAPDC c
    ON c.STVAPDC_CODE = b.SARAPPD_APDC_CODE
INNER JOIN ROBINST r
    ON r.ROBINST_AIDY_CODE = :AIDY
LEFT JOIN SARAATT d
    ON d.SARAATT_PIDM = a.SARADAP_PIDM
    AND d.SARAATT_APPL_NO = a.SARADAP_APPL_NO
    AND d.SARAATT_TERM_CODE = a.SARADAP_TERM_CODE_ENTRY
WHERE RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '1TUI' -- budget component
AND CASE -- level code
    WHEN a.SARADAP_LEVL_CODE = 'UG' THEN 'UG'
END = RORALGS_KEY_5
AND CASE -- campus code
    WHEN a.SARADAP_CAMP_CODE = 'SP' THEN 'SP'
END = RORALGS_KEY_6
--SPTR ATTRIBUTE ONLY STAYS ACTIVE FOR FIRST TERM	
AND CASE -- attribute code
    WHEN d.SARAATT_ATTS_CODE = 'SPTR' THEN 'SPTR'
	WHEN (d.SARAATT_ATTS_CODE = 'SPDE' OR d.SARAATT_ATTS_CODE IS NULL) THEN 'SPDE'
END = RORALGS_KEY_10
AND RORALGS_KEY_12 = 'FT'

-- maa.SARADAP term <= passed period
AND a.SARADAP_TERM_CODE_ENTRY = (
    SELECT MAX(SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP
    WHERE SARADAP_PIDM = a.SARADAP_PIDM
    AND SARADAP_TERM_CODE_ENTRY >= (r.ROBINST_AIDY_END_YEAR || '00')   	
	AND SARADAP_TERM_CODE_ENTRY <= :PERIOD
)
--max application decision code sequence number
AND b.SARAPPD_SEQ_NO = (
    SELECT MAX (SARAPPD_SEQ_NO)
    FROM SARAPPD
    WHERE SARAPPD_PIDM = b.SARAPPD_PIDM
    AND SARAPPD_SEQ_NO < 99
    AND SARAPPD_TERM_CODE_ENTRY >= (r.ROBINST_AIDY_END_YEAR || '00')
    AND SARAPPD_TERM_CODE_ENTRY <= :PERIOD
    AND SARAPPD_APPL_NO = b.SARAPPD_APPL_NO
) 
AND RORALGS_AIDY_CODE = :AIDY
AND a.SARADAP_PIDM = :PIDM

-- ;
-- SELECT RORALGS_AMT --assume full time
-- FROM SARADAP X, SARAPPD X, RORALGS, STVAPDC, SARAATT
-- WHERE RORALGS_KEY_1 = 'PBDG'

-- AND RORALGS_KEY_4 = '1TUI' -- budget component

-- AND CASE -- level code
--     WHEN X.SARADAP_LEVL_CODE = 'UG' THEN 'UG'
-- END = RORALGS_KEY_5
	
-- AND CASE -- campus code
--     WHEN X.SARADAP_CAMP_CODE = 'SP' THEN 'SP'
-- END = RORALGS_KEY_6

-- --SPTR ATTRIBUTE ONLY STAYS ACTIVE FOR FIRST TERM	
-- AND CASE -- attribute code
--     WHEN SARAATT_ATTS_CODE = 'SPTR' THEN 'SPTR'
-- 	WHEN SARAATT_ATTS_CODE = 'SPDE' THEN 'SPDE'
-- END = RORALGS_KEY_10
	
-- AND RORALGS_KEY_12 = 'FT'

-- -- max saradap term <= passed period
-- AND X.SARADAP_TERM_CODE_ENTRY = (
--     SELECT MAX(X.SARADAP_TERM_CODE_ENTRY)
--     FROM SARADAP Y, ROBINST
--     WHERE Y.SARADAP_PIDM = X.SARADAP_PIDM
--     AND Y.SARADAP_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')   	
-- 	AND Y.SARADAP_TERM_CODE_ENTRY <= :PERIOD
-- 	AND ROBINST_AIDY_CODE = :AIDY   
-- )
-- --max application decision code sequence number
-- AND X.SARAPPD_SEQ_NO = (SELECT MAX (X.SARAPPD_SEQ_NO)
--              FROM SARAPPD Y, ROBINST
--               WHERE     Y.SARAPPD_PIDM = X.SARAPPD_PIDM
--               AND Y.SARAPPD_SEQ_NO < 99
--               AND Y.SARAPPD_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
--               AND Y.SARAPPD_TERM_CODE_ENTRY <= :PERIOD
--               AND ROBINST_AIDY_CODE = :AIDY           
--               AND X.SARADAP_APPL_NO = Y.SARAPPD_APPL_NO) 
   
-- --   AND STVAPDC_INST_ACC_IND = 'Y'
-- --   AND STVAPDC_SIGNF_IND = 'Y'
-- --   AND SARAPPD_APDC_CODE IN ('DD','DW','DZ')
	
-- AND X.SARAPPD_APDC_CODE = STVAPDC_CODE	
-- AND X.SARADAP_APPL_NO = X.SARAPPD_APPL_NO
-- AND X.SARADAP_APPL_NO = SARAATT_APPL_NO
-- AND X.SARADAP_TERM_CODE_ENTRY = X.SARAPPD_TERM_CODE_ENTRY
-- AND X.SARADAP_TERM_CODE_ENTRY = SARAATT_TERM_CODE
-- AND RORALGS_AIDY_CODE = :AIDY
-- AND X.SARAPPD_PIDM = X.SARADAP_PIDM	
-- AND X.SARADAP_PIDM = SARAATT_PIDM
-- AND X.SARADAP_PIDM = :PIDM
--END



--SPSA ENROLLED 12-18 HOURS 
SELECT CASE
    WHEN NVL(ROKMISC.F_CALC_STUD_CREDIT_HRS(:PERIOD, X.SGBSTDN_PIDM, 'N'), 0) >= 12
	AND  NVL(ROKMISC.F_CALC_STUD_CREDIT_HRS(:PERIOD, X.SGBSTDN_PIDM, 'N'), 0) <= 18
        THEN RORALGS_AMT
    END as calc_amt
FROM SGBSTDN X, RORALGS, SGRSATT X
WHERE RORALGS_KEY_1 = 'PBDG'

AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
    WHEN X.SGBSTDN_LEVL_CODE = 'UG' THEN 'UG'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SGBSTDN_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
	
--attribute for Madrid study abroad
AND CASE -- attribute code
    WHEN X.SGRSATT_ATTS_CODE = 'SPSA' THEN 'SPSA'
END = RORALGS_KEY_10
		
AND RORALGS_KEY_12 = '12TO18'
	
--max attribute term <= passed term	
AND X.SGRSATT_TERM_CODE_EFF = (
SELECT MAX(Y.SGRSATT_TERM_CODE_EFF)
    FROM SGRSATT Y
    WHERE Y.SGRSATT_TERM_CODE_EFF <= :PERIOD
	AND X.SGRSATT_PIDM =  Y.SGRSATT_PIDM
)
-- max sgbstdn term <= passed period
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_PIDM = X.SGRSATT_PIDM
AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
-- END

--SPSA ENROLLED 19+ HOURS 
SELECT CASE
    WHEN NVL(ROKMISC.F_CALC_STUD_CREDIT_HRS(:PERIOD, X.SGBSTDN_PIDM, 'N'), 0) > 18
        THEN round(roralgs_amt + ((NVL(ROKMISC.F_CALC_STUD_CREDIT_HRS(:PERIOD, X.SGBSTDN_PIDM, 'N'), 0) - 18) * roralgs_comment_12)) 
    END as calc_amt

--need to add text to RORALGS_COMMENT SAYING DO NOT CHANGE TEXT IN RORALGS_COMMENT_12 BECASUE IT'S USED IN THE ALGO CALC
--VALUE TO ADD TO ADD TO RORALGS_COMMENT_12 IS OVERLOAD RATE, ALL NUMERIC, WOULD BE 1830 BASED ON FY2024 RATE
	
FROM SGBSTDN X, RORALGS, SGRSATT X
WHERE RORALGS_KEY_1 = 'PBDG'

AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
    WHEN X.SGBSTDN_LEVL_CODE = 'UG' THEN 'UG'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SGBSTDN_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6

--attribute for Madrid study abroad
AND CASE -- attribute code
    WHEN X.SGRSATT_ATTS_CODE = 'SPSA' THEN 'SPSA'
END = RORALGS_KEY_10
	
AND RORALGS_KEY_12 = '19+'

--max attribute term <= passed term	
AND X.SGRSATT_TERM_CODE_EFF = (
SELECT MAX(Y.SGRSATT_TERM_CODE_EFF)
    FROM SGRSATT Y
    WHERE Y.SGRSATT_TERM_CODE_EFF <= :PERIOD
	AND X.SGRSATT_PIDM =  Y.SGRSATT_PIDM
)
-- max sgbstdn term <= passed period
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_PIDM = X.SGRSATT_PIDM
AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
-- END

--SPSA NOT ENROLLED WITH SGASTDN
SELECT RORALGS_AMT --assume fulltime (12TO18 hours)
    FROM SGBSTDN X, RORALGS, SGRSATT X
WHERE RORALGS_KEY_1 = 'PBDG'

AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
    WHEN X.SGBSTDN_LEVL_CODE = 'UG' THEN 'UG'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SGBSTDN_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
	
--attribute for Madrid study abroad
AND CASE -- attribute code
    WHEN X.SGRSATT_ATTS_CODE = 'SPSA' THEN 'SPSA'
END = RORALGS_KEY_10
		
AND RORALGS_KEY_12 = '12TO18'
	
--max attribute term <= passed term	
AND X.SGRSATT_TERM_CODE_EFF = (
SELECT MAX(Y.SGRSATT_TERM_CODE_EFF)
    FROM SGRSATT Y
    WHERE Y.SGRSATT_TERM_CODE_EFF <= :PERIOD
	AND X.SGRSATT_PIDM =  Y.SGRSATT_PIDM
)
-- max sgbstdn term <= passed period
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_PIDM = X.SGRSATT_PIDM
AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
-- END

--SPSA NOT ENROLLED NO SGASTDN
--NOT SURE IF THIS WOUDL EVER HAPPEN, CHECK WITH SLU
SELECT RORALGS_AMT --assume fulltime (12TO18 hours)
    FROM SARADAP X, SARAPPD X, SARAATT, RORALGS, STVAPDC
WHERE RORALGS_KEY_1 = 'PBDG'

AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
    WHEN X.SARADAP_LEVL_CODE = 'UG' THEN 'UG'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SARADAP_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
	
--attribute for Madrid study abroad
AND CASE -- attribute code
    WHEN SARAATT_ATTS_CODE = 'SPSA' THEN 'SPSA'
END = RORALGS_KEY_10
		
AND RORALGS_KEY_12 = '12TO18'
	
-- max saradap term <= passed period	
AND X.SARADAP_TERM_CODE_ENTRY = (
     SELECT MAX(Y.SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP Y, ROBINST
    WHERE Y.SARADAP_PIDM = X.SARADAP_PIDM
	AND Y.SARADAP_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
    AND Y.SARADAP_TERM_CODE_ENTRY <= :PERIOD
	AND ROBINST_AIDY_CODE = :AIDY
)
--max application decision code sequence number
AND X.SARAPPD_SEQ_NO = (SELECT MAX (X.SARAPPD_SEQ_NO)
             FROM SARAPPD Y, ROBINST
              WHERE     Y.SARAPPD_PIDM = X.SARAPPD_PIDM
              AND Y.SARAPPD_SEQ_NO < 99
              AND Y.SARAPPD_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
              AND Y.SARAPPD_TERM_CODE_ENTRY <= :PERIOD
              AND ROBINST_AIDY_CODE = :AIDY           
              AND X.SARADAP_APPL_NO = Y.SARAPPD_APPL_NO) 
      
AND STVAPDC_INST_ACC_IND = 'Y'
AND STVAPDC_SIGNF_IND = 'Y'

AND X.SARAPPD_APDC_CODE = STVAPDC_CODE	
AND X.SARADAP_APPL_NO = X.SARAPPD_APPL_NO
AND X.SARADAP_APPL_NO = SARAATT_APPL_NO
AND X.SARADAP_TERM_CODE_ENTRY = X.SARAPPD_TERM_CODE_ENTRY
AND X.SARADAP_TERM_CODE_ENTRY = SARAATT_TERM_CODE
AND RORALGS_AIDY_CODE = :AIDY
AND X.SARADAP_PIDM = X.SARAPPD_PIDM
AND X.SARADAP_PIDM = SARAATT_PIDM
AND X.SARADAP_PIDM = :PIDM
--END