
--GRAD WITH SELECT EDUCATION PROGRAM CODES ENROLLED
SELECT CASE
    WHEN NVL(ROKMISC.F_CALC_STUD_BILL_HRS(:PERIOD, X.SGBSTDN_PIDM, 'N'), 0) > 0
        THEN round(roralgs_amt * NVL(ROKMISC.F_CALC_STUD_BILL_HRS(:PERIOD, X.SGBSTDN_PIDM, 'N'), 0))
    END as calc_amt
FROM SGBSTDN X, RORALGS
WHERE RORALGS_KEY_1 = 'PBDG'

AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
    WHEN X.SGBSTDN_LEVL_CODE = 'UG' THEN 'UG'
END = RORALGS_KEY_5

AND CASE -- campus code
    WHEN X.SGBSTDN_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6

AND CASE -- major/program code
	WHEN X.SGBSTDN_PROGRAM_1 IN ('NR06', 'NR02') THEN 'ABSN'
END = RORALGS_KEY_9		

-- max sgbstdn term <= passed period
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
-- END


--GRAD WITH SELECT EDUCATION PROGRAM CODES NOT ENROLLED WITH SGASTDN
SELECT (RORALGS_AMT * 18)                                                           
FROM SGBSTDN X, RORALGS
WHERE RORALGS_KEY_1 = 'PBDG'

AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
    WHEN X.SGBSTDN_LEVL_CODE = 'UG' THEN 'UG'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SGBSTDN_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
	
AND CASE -- major/program code
	WHEN X.SARADAP_PROGRAM_1 IN ('NR06', 'NR02') THEN 'ABSN'

END = RORALGS_KEY_9		
		
-- max sgbstdn term <= passed period
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
-- END



--GRAD WITH SELECT EDUCATION PROGRAM CODES NO SGASTDN ENROLLED
SELECT (RORALGS_AMT * 18)                                                           
FROM SARADAP X, SARAPPD X, RORALGS, STVAPDC
WHERE RORALGS_KEY_1 = 'PBDG'

AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
    WHEN X.SARADAP_LEVL_CODE = 'UG' THEN 'UG'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SARADAP_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
	
AND CASE -- major/program code
	WHEN X.SARADAP_PROGRAM_1 IN ('NR06', 'NR02') THEN 'ABSN'
END = RORALGS_KEY_9		
		
-- max saradap term <= passed period	
AND X.SARADAP_TERM_CODE_ENTRY = (
     SELECT MAX(Y.SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP Y, ROBINST
    WHERE Y.SARADAP_PIDM = X.SARADAP_PIDM
	AND Y.SARADAP_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
    AND Y.SARADAP_TERM_CODE_ENTRY <= :PERIOD
	AND ROBINST_AIDY_CODE = :AIDY
)
--max application decision code sequence number
AND X.SARAPPD_SEQ_NO = (SELECT MAX (X.SARAPPD_SEQ_NO)
	FROM SARAPPD Y, ROBINST
	WHERE     Y.SARAPPD_PIDM = X.SARAPPD_PIDM
	AND Y.SARAPPD_SEQ_NO < 99
	AND Y.SARAPPD_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
	AND Y.SARAPPD_TERM_CODE_ENTRY <= :PERIOD
	AND ROBINST_AIDY_CODE = :AIDY           
	AND X.SARADAP_APPL_NO = Y.SARAPPD_APPL_NO) 
      
AND STVAPDC_INST_ACC_IND = 'Y'
AND STVAPDC_SIGNF_IND = 'Y'

AND X.SARAPPD_APDC_CODE = STVAPDC_CODE	
AND X.SARADAP_APPL_NO = X.SARAPPD_APPL_NO
AND X.SARADAP_TERM_CODE_ENTRY = X.SARAPPD_TERM_CODE_ENTRY
AND RORALGS_AIDY_CODE = :AIDY
AND X.SARAPPD_PIDM = X.SARADAP_PIDM	
AND X.SARADAP_PIDM = :PIDM
-- END