--MED ENROLLED OR NOT ENROLLED WITH SGASTDN
SELECT RORALGS_AMT 
    FROM SGBSTDN X, RORALGS
WHERE RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '1TUI' -- budget component
AND CASE -- level code
    WHEN X.SGBSTDN_LEVL_CODE = 'PM' THEN 'PM'
END = RORALGS_KEY_5
	
-- max sgbstdn term <= passed period
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
	
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND RORALGS_AIDY_CODE = :AIDY
AND X.SGBSTDN_PIDM = :PIDM
--END

--MED NOT ENROLLED no SGASTDN
SELECT RORALGS_AMT 
    FROM SARADAP X, SARAPPD X, RORALGS, STVAPDC
WHERE RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
	WHEN X.SARADAP_LEVL_CODE = 'PM' THEN 'PM'
END = RORALGS_KEY_5
	
-- max saradap term <= passed period
AND X.SARADAP_TERM_CODE_ENTRY = (
    SELECT MAX(X.SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP Y, ROBINST
    WHERE Y.SARADAP_PIDM = X.SARADAP_PIDM
    AND Y.SARADAP_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')   	
	AND Y.SARADAP_TERM_CODE_ENTRY <= :PERIOD
	AND ROBINST_AIDY_CODE = :AIDY   
)

--max application decision code sequence number
AND X.SARAPPD_SEQ_NO = (
    SELECT MAX (X.SARAPPD_SEQ_NO)
    FROM SARAPPD Y, ROBINST
    WHERE     Y.SARAPPD_PIDM = X.SARAPPD_PIDM
    AND Y.SARAPPD_SEQ_NO < 99
    AND Y.SARAPPD_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
    AND Y.SARAPPD_TERM_CODE_ENTRY <= :PERIOD
    AND ROBINST_AIDY_CODE = :AIDY           
    AND X.SARADAP_APPL_NO = Y.SARAPPD_APPL_NO
) 
   
AND STVAPDC_INST_ACC_IND = 'Y'
AND STVAPDC_SIGNF_IND = 'Y'
AND X.SARAPPD_APDC_CODE = STVAPDC_CODE	
AND X.SARADAP_APPL_NO = X.SARAPPD_APPL_NO
AND X.SARADAP_TERM_CODE_ENTRY = X.SARAPPD_TERM_CODE_ENTRY
AND RORALGS_AIDY_CODE = :AIDY
AND X.SARAPPD_PIDM = X.SARADAP_PIDM	
AND X.SARADAP_PIDM = :PIDM
--END