-- LAW ENROLLED <=7
SELECT CASE
    WHEN NVL(ROKMISC.F_CALC_STUD_CREDIT_HRS(:PERIOD, X.SGBSTDN_PIDM, 'N'), 0) > 0
	AND  NVL(ROKMISC.F_CALC_STUD_CREDIT_HRS(:PERIOD, X.SGBSTDN_PIDM, 'N'), 0) <= 7
        THEN RORALGS_AMT 
    END as calc_amt
FROM SGBSTDN X, RORALGS
WHERE RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '1TUI' -- budget component
AND CASE -- level code
    WHEN X.SGBSTDN_LEVL_CODE = 'PL' THEN 'PL'
END = RORALGS_KEY_5
	AND RORALGS_KEY_12 = '1TO7'
	
-- max sgbstdn term <= passed period
AND X.SGBSTDN_TERM_CODE_EFF = (
 SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
-- END

-- LAW ENROLLED 8 to 11
SELECT CASE
    WHEN NVL(ROKMISC.F_CALC_STUD_CREDIT_HRS(:PERIOD, X.SGBSTDN_PIDM, 'N'), 0) >= 8
	AND  NVL(ROKMISC.F_CALC_STUD_CREDIT_HRS(:PERIOD, X.SGBSTDN_PIDM, 'N'), 0) <= 11
        THEN RORALGS_AMT 
    END as calc_amt
FROM SGBSTDN X, RORALGS
WHERE RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '1TUI' -- budget component
AND CASE -- level code
    WHEN X.SGBSTDN_LEVL_CODE = 'PL' THEN 'PL'
END = RORALGS_KEY_5
	AND RORALGS_KEY_12 = '8TO11'
	
-- max sgbstdn term <= passed period
AND X.SGBSTDN_TERM_CODE_EFF = (
 SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
-- END

-- LAW ENROLLED 12+
SELECT CASE
    WHEN NVL(ROKMISC.F_CALC_STUD_CREDIT_HRS(:PERIOD, X.SGBSTDN_PIDM, 'N'), 0) >= 12
        THEN RORALGS_AMT 
    END as calc_amt
FROM SGBSTDN X, RORALGS
WHERE RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '1TUI' -- budget component
AND CASE -- level code
    WHEN X.SGBSTDN_LEVL_CODE = 'PL' THEN 'PL'
END = RORALGS_KEY_5
	AND RORALGS_KEY_12 = '12+'
	
-- max sgbstdn term <= passed period
AND X.SGBSTDN_TERM_CODE_EFF = (
 SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
-- END

--LAW NOT ENROLLED WITH SGASTDN
SELECT RORALGS_AMT 
    FROM SGBSTDN X, RORALGS
WHERE RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '1TUI' -- budget component
AND CASE -- level code
    WHEN X.SGBSTDN_LEVL_CODE = 'PL' THEN 'PL'
END = RORALGS_KEY_5

AND CASE
	WHEN X.SGBSTDN_FULL_PART_IND = 'P' THEN '8TO11'
	WHEN X.SGBSTDN_FULL_PART_IND = 'F' THEN '12+'
END = RORALGS_KEY_12
	
 -- max sgbstdn term <= passed period	
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND RORALGS_AIDY_CODE = :AIDY
AND X.SGBSTDN_PIDM = :PIDM
--END

--LAW NOT ENROLLED NO SGASTDN PART TIME SARADAP
SELECT RORALGS_AMT 
    FROM SARADAP X, SARAPPD X, RORALGS, STVAPDC
WHERE RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '1TUI' -- budget component
AND CASE -- level code
	WHEN X.SARADAP_LEVL_CODE = 'PL' THEN 'PL'
END = RORALGS_KEY_5
	
	AND CASE
	WHEN X.SARADAP_FULL_PART_IND = 'P' THEN '8TO11'
	WHEN X.SARADAP_FULL_PART_IND = 'F' THEN '12+'
END = RORALGS_KEY_12

-- max saradap term <= passed period	
AND X.SARADAP_TERM_CODE_ENTRY = (
     SELECT MAX(Y.SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP Y, ROBINST
    WHERE Y.SARADAP_PIDM = X.SARADAP_PIDM
	AND Y.SARADAP_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
    AND Y.SARADAP_TERM_CODE_ENTRY <= :PERIOD
	AND ROBINST_AIDY_CODE = :AIDY
)
--max application decision code sequence number
AND X.SARAPPD_SEQ_NO = (SELECT MAX (X.SARAPPD_SEQ_NO)
             FROM SARAPPD Y, ROBINST
              WHERE     Y.SARAPPD_PIDM = X.SARAPPD_PIDM
              AND Y.SARAPPD_SEQ_NO < 99
              AND Y.SARAPPD_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
              AND Y.SARAPPD_TERM_CODE_ENTRY <= :PERIOD
              AND ROBINST_AIDY_CODE = :AIDY           
              AND X.SARADAP_APPL_NO = Y.SARAPPD_APPL_NO) 
   
   AND STVAPDC_INST_ACC_IND = 'Y'
   AND STVAPDC_SIGNF_IND = 'Y'

AND X.SARAPPD_APDC_CODE = STVAPDC_CODE	
AND X.SARADAP_APPL_NO = X.SARAPPD_APPL_NO
AND X.SARADAP_TERM_CODE_ENTRY = X.SARAPPD_TERM_CODE_ENTRY
AND RORALGS_AIDY_CODE = :AIDY
AND X.SARAPPD_PIDM = X.SARADAP_PIDM	
AND X.SARADAP_PIDM = :PIDM