SELECT RCVEDEA_PIDM
FROM RCVEDEA
JOIN RCRAPP1 on RCRAPP1_PIDM = RCVEDEA_PIDM
    and RCRAPP1_AIDY_CODE = RCVEDEA_AIDY_CODE
    and RCRAPP1_INFC_CODE = RCVEDEA_INFC_CODE
    and RCRAPP1_SEQ_NO = RCVEDEA_SEQ_NO
JOIN RCRAPP2 on RCRAPP2_PIDM = RCVEDEA_PIDM
    and RCRAPP2_AIDY_CODE = RCVEDEA_AIDY_CODE
    and RCRAPP2_INFC_CODE = RCVEDEA_INFC_CODE
    and RCRAPP2_SEQ_NO = RCVEDEA_SEQ_NO
JOIN RCRAPP3 on RCRAPP3_PIDM = RCVEDEA_PIDM
    and RCRAPP3_AIDY_CODE = RCVEDEA_AIDY_CODE
    and RCRAPP3_INFC_CODE = RCVEDEA_INFC_CODE
    and RCRAPP3_SEQ_NO = RCVEDEA_SEQ_NO
JOIN RORSTAT on RORSTAT_PIDM = RCVEDEA_PIDM and RORSTAT_AIDY_CODE = RCVEDEA_AIDY_CODE
JOIN ROBNYUD on ROBNYUD_PIDM = RCVEDEA_PIDM
WHERE RCVEDEA_AIDY_CODE = :AIDY
-- AND RCVEDEA_PIDM = :PIDM
AND RCVEDEA_CURR_REC_IND = 'Y'
AND RCVEDEA_INFC_CODE = 'EDE'
AND RCRAPP2_PELL_PGI <= 0
AND RCRAPP3_YR_IN_COLL_2 <> '4'
AND RCRAPP1_DEGREE_BY_JULY = '2'
AND RCRAPP1_RCPT_DATE <= '02-FEB-2026'
AND RORSTAT_PGRP_CODE =  'UG-CO'
AND RORSTAT_TGRP_CODE IN ('DEPV1', 'DEPV4', 'DEPV5', 'DEPNVR', 'INDV1', 'INDV4', 'INDV5', 'INDNVR', 'DEPMAN', 'INDMAN')
AND (
    (ROBNYUD_VALUE_1 IS NULL OR ROBNYUD_VALUE_1 NOT IN ('FACHEX','TEN-CS','TEN-ST','EXCHNG','REM-ST','REM-CS', 'UMGST','UMG-CS','PRES-T'))
    OR (ROBNYUD_VALUE_6 IS NULL OR ROBNYUD_VALUE_6 NOT IN ('FACHEX','TEN-CS','TEN-ST','EXCHNG','REM-ST','REM-CS',' UMG-ST','UMG-CS','PRES-T'))
    OR (ROBNYUD_VALUE_11 IS NULL OR ROBNYUD_VALUE_11 NOT IN ('FACHEX','TEN-CS','TEN-ST','EXCHNG','REM-ST','REM-CS', 'UMG-ST','UMG-CS','PRES-T'))
    OR (ROBNYUD_VALUE_16 IS NULL OR ROBNYUD_VALUE_16 NOT IN ('FACHEX','TEN-CS','TEN-ST','EXCHNG','REM-ST','REM-CS', 'UMG-ST','UMG-CS','PRES-T'))
)
AND EXISTS (
    SELECT 1 FROM RBRAPBG
    WHERE RBRAPBG_PIDM = RCVEDEA_PIDM
    AND RBRAPBG_AIDY_CODE = RCVEDEA_AIDY_CODE
    AND RBRAPBG_PBGP_CODE = 'UG'
    AND RBRAPBG_RUN_NAME = 'ACTUAL'
)
;

SELECT RCVEDEA_PIDM, RCRAPP2_PELL_PGI, RCRAPP3_YR_IN_COLL_2, RCRAPP1_DEGREE_BY_JULY, RCRAPP1_RCPT_DATE, RORSTAT_TGRP_CODE, RORSTAT_PGRP_CODE, ROBNYUD_VALUE_1, ROBNYUD_VALUE_6, ROBNYUD_VALUE_11, ROBNYUD_VALUE_16
FROM RCVEDEA
JOIN RCRAPP1 on RCRAPP1_PIDM = RCVEDEA_PIDM
    and RCRAPP1_AIDY_CODE = RCVEDEA_AIDY_CODE
    and RCRAPP1_INFC_CODE = RCVEDEA_INFC_CODE
    and RCRAPP1_SEQ_NO = RCVEDEA_SEQ_NO
JOIN RCRAPP2 on RCRAPP2_PIDM = RCVEDEA_PIDM
    and RCRAPP2_AIDY_CODE = RCVEDEA_AIDY_CODE
    and RCRAPP2_INFC_CODE = RCVEDEA_INFC_CODE
    and RCRAPP2_SEQ_NO = RCVEDEA_SEQ_NO
JOIN RCRAPP3 on RCRAPP3_PIDM = RCVEDEA_PIDM
    and RCRAPP3_AIDY_CODE = RCVEDEA_AIDY_CODE
    and RCRAPP3_INFC_CODE = RCVEDEA_INFC_CODE
    and RCRAPP3_SEQ_NO = RCVEDEA_SEQ_NO
JOIN RORSTAT on RORSTAT_PIDM = RCVEDEA_PIDM and RORSTAT_AIDY_CODE = RCVEDEA_AIDY_CODE
JOIN ROBNYUD on ROBNYUD_PIDM = RCVEDEA_PIDM
where rcvedea_pidm = (select spriden_pidm from spriden where spriden_change_ind is null and spriden_id = '001357302')
and RCVEDEA_AIDY_CODE = '2627'
AND RCVEDEA_CURR_REC_IND = 'Y'
AND RCVEDEA_INFC_CODE = 'EDE'
-- AND RCRAPP1_RCPT_DATE <= '02-FEB-2026';
AND RCRAPP2_PELL_PGI <= 0
AND (
    (ROBNYUD_VALUE_1 IS NULL OR ROBNYUD_VALUE_1 NOT IN ('FACHEX','TEN-CS','TEN-ST','EXCHNG','REM-ST','REM-CS', 'UMGST','UMG-CS','PRES-T'))
    OR (ROBNYUD_VALUE_6 IS NULL OR ROBNYUD_VALUE_6 NOT IN ('FACHEX','TEN-CS','TEN-ST','EXCHNG','REM-ST','REM-CS',' UMG-ST','UMG-CS','PRES-T'))
    OR (ROBNYUD_VALUE_11 IS NULL OR ROBNYUD_VALUE_11 NOT IN ('FACHEX','TEN-CS','TEN-ST','EXCHNG','REM-ST','REM-CS', 'UMG-ST','UMG-CS','PRES-T'))
    OR (ROBNYUD_VALUE_16 IS NULL OR ROBNYUD_VALUE_16 NOT IN ('FACHEX','TEN-CS','TEN-ST','EXCHNG','REM-ST','REM-CS', 'UMG-ST','UMG-CS','PRES-T'))
)
AND EXISTS (
    SELECT 1 FROM RBRAPBG
    WHERE RBRAPBG_PIDM = RCVEDEA_PIDM
    AND RBRAPBG_AIDY_CODE = RCVEDEA_AIDY_CODE
    AND RBRAPBG_PBGP_CODE = 'UG'
    AND RBRAPBG_RUN_NAME = 'ACTUAL'
);