-- access missouri (ROBUSDF_VALUE_169)
SELECT DISTINCT RORSTAT_PIDM
FROM RORSTAT a
INNER JOIN ROBINST r ON r.ROBINST_AIDY_CODE = a.RORSTAT_AIDY_CODE
INNER JOIN RORPRST b ON b.RORPRST_PIDM = a.RORSTAT_PIDM
    AND b.RORPRST_PERIOD BETWEEN r.ROBINST_AIDY_END_YEAR || '10' 
        AND r.ROBINST_AIDY_END_YEAR || '20'
    AND b.RORPRST_XES = '1'
INNER JOIN ROBNYUD c ON c.ROBNYUD_PIDM = a.RORSTAT_PIDM
    AND c.ROBNYUD_VALUE_38 IS NULL
INNER JOIN ROBUSDF d ON d.ROBUSDF_PIDM = a.RORSTAT_PIDM
    AND d.ROBUSDF_VALUE_170 IS NOT NULL
INNER JOIN RCRAPP1 e ON e.RCRAPP1_PIDM = a.RORSTAT_PIDM
    AND e.RCRAPP1_CURR_REC_IND = 'Y'
    AND e.RCRAPP1_INFC_CODE = 'EDE'
    and e.RCRAPP1_AIDY_CODE = a.RORSTAT_AIDY_CODE
    AND e.RCRAPP1_RCPT_DATE <= TO_DATE(('02/01/' || r.ROBINST_AIDY_START_YEAR), 'MM-DD-YYYY')
    AND e.RCRAPP1_ORIG_COMP_DATE <= TO_DATE(('07/31/' || r.ROBINST_AIDY_START_YEAR), 'MM-DD-YYYY')
WHERE a.RORSTAT_AIDY_CODE = :AIDY
AND a.RORSTAT_PIDM = :PIDM
AND (
    a.RORSTAT_PGRP_CODE LIKE 'U%' 
    OR a.RORSTAT_PGRP_CODE LIKE 'FULL%' 
    OR a.RORSTAT_PGRP_CODE LIKE 'MAD%'
) AND a.RORSTAT_PGRP_CODE NOT IN ('UG-PL', 'UG-PLC') 
AND a.RORSTAT_PIDM NOT IN (
    SELECT SARADAP_PIDM
    FROM SARADAP
    INNER JOIN SARAPPD 
        ON SARAPPD_PIDM = SARADAP_PIDM 
        AND SARAPPD_APPL_NO = SARADAP_APPL_NO
        AND SARAPPD_TERM_CODE_ENTRY = SARADAP_TERM_CODE_ENTRY
        AND SARAPPD_SEQ_NO = (
            SELECT MAX(y.SARAPPD_SEQ_NO)
            FROM SARAPPD y
            WHERE y.SARAPPD_SEQ_NO < 99
            AND y.SARAPPD_TERM_CODE_ENTRY = SARAPPD_TERM_CODE_ENTRY
            AND y.SARAPPD_APPL_NO = SARADAP_APPL_NO
        )
    INNER JOIN ROBINST x ON x.ROBINST_AIDY_CODE = :AIDY
    WHERE SARADAP_MAJR_CODE_1 = 'THEO' 
    AND SARADAP_TERM_CODE_ENTRY = (
        SELECT MAX(z.SARADAP_TERM_CODE_ENTRY)
        FROM SARADAP z
        WHERE z.SARADAP_PIDM = SARADAP_PIDM
        AND z.SARADAP_TERM_CODE_ENTRY BETWEEN x.ROBINST_AIDY_END_YEAR || '10' 
            AND x.ROBINST_AIDY_END_YEAR || '20'
    )
) AND a.RORSTAT_PIDM NOT IN (
    SELECT SGBSTDN_PIDM
    FROM SGBSTDN
    INNER JOIN ROBINST v ON v.ROBINST_AIDY_CODE = :AIDY
    WHERE SGBSTDN_MAJR_CODE_1 = 'THEO' 
    AND SGBSTDN_TERM_CODE_EFF = (
        SELECT MAX(w.SGBSTDN_TERM_CODE_EFF)
        FROM SGBSTDN w
        WHERE w.SGBSTDN_PIDM = SGBSTDN_PIDM
        AND w.SGBSTDN_TERM_CODE_EFF BETWEEN v.ROBINST_AIDY_END_YEAR || '10' 
            AND v.ROBINST_AIDY_END_YEAR || '20'
    )    
)