-- RETURNING GRAD PACKAGING GROUP
-- 247 rows
SELECT RORSTAT_PIDM
FROM RORSTAT
JOIN ROBINST on ROBINST_AIDY_CODE = RORSTAT_AIDY_CODE and ROBINST_STATUS_IND = 'A'
JOIN ROBNYUD on ROBNYUD_PIDM = RORSTAT_PIDM
WHERE RORSTAT_AIDY_CODE = :AIDY
AND RORSTAT_PIDM = :PIDM
AND EXISTS (
    SELECT 1
    FROM SATURN.SGBSTDN E
    WHERE E.SGBSTDN_PIDM = RORSTAT_PIDM
    AND E.SGBSTDN_LEVL_CODE = 'PL'
    AND E.SGBSTDN_STST_CODE IN ('AS', 'IL', 'P1')
    AND E.SGBSTDN_TERM_CODE_EFF = (
        SELECT MAX(F.SGBSTDN_TERM_CODE_EFF)
        FROM SGBSTDN F 
	    WHERE F.SGBSTDN_PIDM = E.SGBSTDN_PIDM
        AND F.SGBSTDN_TERM_CODE_EFF <= ROBINST_AIDY_END_YEAR || '20'
    )
)
AND NOT EXISTS (
    SELECT 1
    FROM SARADAP C
    INNER JOIN SARAPPD D 
        ON D.SARAPPD_PIDM = C.SARADAP_PIDM
        AND D.SARAPPD_APPL_NO = C.SARADAP_APPL_NO
        AND D.SARAPPD_TERM_CODE_ENTRY = C.SARADAP_TERM_CODE_ENTRY
    INNER JOIN STVAPDC E
        ON E.STVAPDC_CODE = D.SARAPPD_APDC_CODE
        AND E.STVAPDC_INST_ACC_IND = 'Y'
        AND E.STVAPDC_SIGNF_IND = 'Y'
    WHERE C.SARADAP_PIDM = RORSTAT_PIDM
    AND C.SARADAP_LEVL_CODE = 'PL'
    AND C.SARADAP_TERM_CODE_ENTRY = (
        SELECT MAX(Z.SARADAP_TERM_CODE_ENTRY) FROM SARADAP Z
        WHERE Z.SARADAP_PIDM = C.SARADAP_PIDM
        AND Z.SARADAP_TERM_CODE_ENTRY BETWEEN (ROBINST_AIDY_END_YEAR || '10') AND ((ROBINST_AIDY_END_YEAR + 1) || '00')   
        AND Z.SARADAP_APPL_NO = C.SARADAP_APPL_NO
    )
    AND D.SARAPPD_SEQ_NO = (
        SELECT MAX(Z.SARAPPD_SEQ_NO) FROM SARAPPD Z
        WHERE Z.SARAPPD_PIDM = D.SARAPPD_PIDM
        AND Z.SARAPPD_TERM_CODE_ENTRY = D.SARAPPD_TERM_CODE_ENTRY
        AND Z.SARAPPD_APPL_NO = D.SARAPPD_APPL_NO
    )
)
;

-- OLD RULE TAKEN FROM BANNER 06/17/2026
-- 239 rows
SELECT RORSTAT_PIDM
  FROM RORSTAT, ROBINST
 WHERE ROBINST_STATUS_IND = 'A'
   AND ROBINST_AIDY_CODE = RORSTAT_AIDY_CODE
   AND (EXISTS
(SELECT 'X'
   FROM SATURN.SGBSTDN E
  WHERE E.SGBSTDN_PIDM = RORSTAT_PIDM
    AND E.SGBSTDN_LEVL_CODE = 'PL'
    AND E.SGBSTDN_COLL_CODE_1 = 'LW'
    AND E.SGBSTDN_STST_CODE IN ('AS', 'IL', 'P1')
    AND E.SGBSTDN_TERM_CODE_EFF =
     (SELECT MAX(F.SGBSTDN_TERM_CODE_EFF)
        FROM SGBSTDN F 
	WHERE SUBSTR(F.SGBSTDN_TERM_CODE_EFF,0,4) <= SUBSTR(ROBINST_AIDY_END_YEAR,0,4)
         AND F.SGBSTDN_PIDM = E.SGBSTDN_PIDM))
 AND NOT EXISTS (SELECT 'X'
  FROM SARAPPD A, STVAPDC
 WHERE A.SARAPPD_PIDM = RORSTAT_PIDM
   AND A.SARAPPD_APDC_CODE = STVAPDC_CODE
   AND STVAPDC_INST_ACC_IND = 'Y'
   AND STVAPDC_SIGNF_IND = 'Y'
   AND A.SARAPPD_TERM_CODE_ENTRY = 
    (SELECT MAX(B.SARAPPD_TERM_CODE_ENTRY) 
       FROM SARAPPD B
      WHERE B.SARAPPD_PIDM = A.SARAPPD_PIDM
	    AND SUBSTR(B.SARAPPD_TERM_CODE_ENTRY,0,4) >= SUBSTR(ROBINST_AIDY_END_YEAR,0,4))
   AND A.SARAPPD_APPL_NO = 
    (SELECT MAX(C.SARAPPD_APPL_NO) 
       FROM SARAPPD C
      WHERE C.SARAPPD_PIDM = A.SARAPPD_PIDM
	    AND C.SARAPPD_TERM_CODE_ENTRY = A.SARAPPD_TERM_CODE_ENTRY)
   AND A.SARAPPD_SEQ_NO = 
    (SELECT MAX(D.SARAPPD_SEQ_NO) 
       FROM SARAPPD D
      WHERE D.SARAPPD_PIDM = A.SARAPPD_PIDM
	    AND D.SARAPPD_TERM_CODE_ENTRY = A.SARAPPD_TERM_CODE_ENTRY
	    AND D.SARAPPD_APPL_NO = A.SARAPPD_APPL_NO)))
AND RORSTAT_AIDY_CODE            = :AIDY                                               
-- AND RORSTAT_PIDM    =:PIDM  
;