-- HOUSING AND MEALS - WRITTEN BY BUDDY

--less than half time time housing and food
SELECT case when  
nvl(rokmisc.f_calc_stud_bill_hrs(:PERIOD,X.SGBSTDN_PIDM,'N'),0) < RORCRHR_HALF_TIME_CR_HRS and
nvl(rokmisc.f_calc_stud_bill_hrs(:PERIOD,X.SGBSTDN_PIDM,'N'),0) >0  then 0
            end as calc_amt

FROM SGBSTDN X, RORCRHR, RORALGS
WHERE     RORALGS_KEY_1 = 'PBDG'
    AND RORALGS_KEY_4 = '3HSM' -- budget component                        


AND X.SGBSTDN_TERM_CODE_EFF = (SELECT MAX (Y.SGBSTDN_TERM_CODE_EFF)
            FROM SGBSTDN Y
                WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
                    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD)

AND RORCRHR_AIDY_CODE = :AIDY
AND RORCRHR_LEVL_CODE = X.SGBSTDN_LEVL_CODE
AND RORCRHR_PERIOD = :PERIOD

AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
--END



--UNDERGRAD FRESHMEN ENROLLED WITH SGASTDN AND CHANGED SGASTDN RECORD AFTER FIRST TERM
SELECT CASE
    WHEN NVL(ROKMISC.F_CALC_STUD_CREDIT_HRS(:PERIOD, Y.SGBSTDN_PIDM, 'N'), 0) >= RORCRHR_HALF_TIME_CR_HRS
        THEN RORALGS_AMT
    END as calc_amt
FROM SGBSTDN X, SGBSTDN Y, RORCRHR, RORALGS, RORPRST
WHERE RORALGS_KEY_1 = 'PBDG'

AND CASE -- freshmen student type
    WHEN X.SGBSTDN_STYP_CODE = 'F' THEN 'F' 
END = RORALGS_KEY_2 

AND RORALGS_KEY_4 = '3HSM' -- budget component                        

AND CASE -- level code
    WHEN Y.SGBSTDN_LEVL_CODE = 'UG' THEN 'UG'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN Y.SGBSTDN_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
		
-- max sgbstdn term <= passed period
AND Y.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y1.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y1
    WHERE Y1.SGBSTDN_PIDM = Y.SGBSTDN_PIDM
    AND Y1.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
-- has freshmen sgastdn record in the aid year	
AND X.SGBSTDN_TERM_CODE_EFF BETWEEN TRIM(TO_CHAR ('20'||SUBSTR(:AIDY, 3,2) || '00')) AND TRIM(TO_CHAR ('20'||SUBSTR(:AIDY, 3,2)+1 || '00'))	
 AND X.SGBSTDN_STYP_CODE = 'F' 
  AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1') 

  AND Y.SGBSTDN_TERM_CODE_EFF > X.SGBSTDN_TERM_CODE_EFF
  AND Y.SGBSTDN_LEVL_CODE = 'UG'
  AND Y.SGBSTDN_STST_CODE IN  ('AS','IL','P1')

AND RORCRHR_AIDY_CODE = :AIDY
AND RORCRHR_LEVL_CODE = Y.SGBSTDN_LEVL_CODE
AND RORCRHR_PERIOD = :PERIOD

AND RORPRST_XHS_LOCK_IND <> 'Y'
AND X.SGBSTDN_PIDM = RORPRST_PIDM
AND RORPRST_PERIOD = :PERIOD
AND X.SGBSTDN_PIDM = Y.SGBSTDN_PIDM
AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
-- END



--UNDERGRAD FRESHMEN ENROLLED WITH SGASTDN
SELECT CASE
    WHEN NVL(ROKMISC.F_CALC_STUD_CREDIT_HRS(:PERIOD, X.SGBSTDN_PIDM, 'N'), 0) >= RORCRHR_HALF_TIME_CR_HRS
        THEN RORALGS_AMT
    END as calc_amt
FROM SGBSTDN X, RORCRHR, RORALGS, RORPRST
WHERE RORALGS_KEY_1 = 'PBDG'

AND CASE -- freshmen student type
    WHEN X.SGBSTDN_STYP_CODE = 'F' THEN 'F'                   
END = RORALGS_KEY_2 

AND RORALGS_KEY_4 = '3HSM' -- budget component                        

AND CASE -- level code
    WHEN X.SGBSTDN_LEVL_CODE = 'UG' THEN 'UG'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SGBSTDN_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
																						
-- max sgbstdn term <= passed period
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN
    WHERE SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND RORCRHR_AIDY_CODE = :AIDY
AND RORCRHR_LEVL_CODE = X.SGBSTDN_LEVL_CODE
AND RORCRHR_PERIOD = :PERIOD

AND RORPRST_XHS_LOCK_IND <> 'Y'
AND X.SGBSTDN_PIDM = RORPRST_PIDM
AND RORPRST_PERIOD = :PERIOD
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
-- END



--UNDERGRAD FRESHMEN NOT ENROLLED WITH SGASTDN
SELECT RORALGS_AMT
FROM SGBSTDN X, RORALGS, RORPRST
WHERE RORALGS_KEY_1 = 'PBDG'

AND CASE -- freshmen student type
    WHEN X.SGBSTDN_STYP_CODE = 'F' THEN 'F' 
END = RORALGS_KEY_2 

AND RORALGS_KEY_4 = '3HSM' -- budget component                        

AND CASE -- level code
    WHEN X.SGBSTDN_LEVL_CODE = 'UG' THEN 'UG'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SGBSTDN_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
		
-- max sgbstdn term <= passed period
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD)

AND RORPRST_XHS_LOCK_IND <> 'Y'
AND X.SGBSTDN_PIDM = RORPRST_PIDM
AND RORPRST_PERIOD = :PERIOD	
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
-- END



--UNDERGRAD FRESHMEN NOT ENROLLED NO SGASTDN
SELECT RORALGS_AMT
FROM SARADAP X, SARAPPD X, RORALGS, STVAPDC, RORPRST
WHERE RORALGS_KEY_1 = 'PBDG'

AND CASE -- freshmen student type
    WHEN X.SARADAP_STYP_CODE = 'F' THEN 'F' 
END = RORALGS_KEY_2 

AND RORALGS_KEY_4 = '3HSM' -- budget component                 

AND CASE -- level code
    WHEN X.SARADAP_LEVL_CODE = 'UG' THEN 'UG'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SARADAP_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
		
-- max saradap term <= passed period	
AND X.SARADAP_TERM_CODE_ENTRY = (
     SELECT MAX(Y.SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP Y, ROBINST
    WHERE Y.SARADAP_PIDM = X.SARADAP_PIDM
	AND Y.SARADAP_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
    AND Y.SARADAP_TERM_CODE_ENTRY <= :PERIOD
	AND ROBINST_AIDY_CODE = :AIDY
)
--max application decision code sequence number
AND X.SARAPPD_SEQ_NO = (SELECT MAX (X.SARAPPD_SEQ_NO)
             FROM SARAPPD Y, ROBINST
              WHERE     Y.SARAPPD_PIDM = X.SARAPPD_PIDM
              AND Y.SARAPPD_SEQ_NO < 99
              AND Y.SARAPPD_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
              AND Y.SARAPPD_TERM_CODE_ENTRY <= :PERIOD
              AND ROBINST_AIDY_CODE = :AIDY           
              AND X.SARADAP_APPL_NO = Y.SARAPPD_APPL_NO) 
      
   AND STVAPDC_INST_ACC_IND = 'Y'
   AND STVAPDC_SIGNF_IND = 'Y'

AND RORPRST_XHS_LOCK_IND <> 'Y'
AND X.SARADAP_PIDM = RORPRST_PIDM
AND RORPRST_PERIOD = :PERIOD
AND X.SARAPPD_APDC_CODE = STVAPDC_CODE	
AND X.SARADAP_APPL_NO = X.SARAPPD_APPL_NO
AND X.SARADAP_TERM_CODE_ENTRY = X.SARAPPD_TERM_CODE_ENTRY
AND RORALGS_AIDY_CODE = :AIDY
AND X.SARAPPD_PIDM = X.SARADAP_PIDM	
AND X.SARADAP_PIDM = :PIDM
-- END

--UNDERGRAD TRANSFER ENROLLED WITH SGASTDN AND CHANGED SGASTDN RECORD AFTER FIRST TERM
SELECT CASE
    WHEN NVL(ROKMISC.F_CALC_STUD_CREDIT_HRS(:PERIOD, Y.SGBSTDN_PIDM, 'N'), 0) >= RORCRHR_HALF_TIME_CR_HRS
        THEN RORALGS_AMT
    END as calc_amt
FROM SGBSTDN X, SGBSTDN Y, RORCRHR, RORALGS, ROBNYUD
WHERE RORALGS_KEY_1 = 'PBDG'

AND CASE -- freshmen student type
    WHEN (X.SGBSTDN_STYP_CODE IN ('1','T')) THEN 'T' 
END = RORALGS_KEY_2 

AND RORALGS_KEY_4 = '3HSM' -- budget component                        

AND CASE -- level code
    WHEN Y.SGBSTDN_LEVL_CODE = 'UG' THEN 'UG'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN Y.SGBSTDN_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
		
-- max sgbstdn term <= passed period
AND Y.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y1.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y1
    WHERE Y1.SGBSTDN_PIDM = Y.SGBSTDN_PIDM
    AND Y1.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
-- has transfer sgastdn record in the aid year	
AND X.SGBSTDN_TERM_CODE_EFF BETWEEN TRIM(TO_CHAR ('20'||SUBSTR(:AIDY, 3,2) || '00')) AND TRIM(TO_CHAR ('20'||SUBSTR(:AIDY, 3,2)+1 || '00'))	
 AND X.SGBSTDN_STYP_CODE IN ('1','T') 
  AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1') 

  AND Y.SGBSTDN_TERM_CODE_EFF > X.SGBSTDN_TERM_CODE_EFF
  AND Y.SGBSTDN_LEVL_CODE = 'UG'
  AND Y.SGBSTDN_STST_CODE IN  ('AS','IL','P1')

AND RORCRHR_AIDY_CODE = :AIDY
AND RORCRHR_LEVL_CODE = Y.SGBSTDN_LEVL_CODE
AND RORCRHR_PERIOD = :PERIOD

AND ROBNYUD_VALUE_120 = 'C'
AND Y.SGBSTDN_PIDM = ROBNYUD_PIDM 

AND X.SGBSTDN_PIDM = Y.SGBSTDN_PIDM
AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
-- END



--UNDERGRAD TRANSFER ENROLLED WITH SGASTDN
SELECT CASE
    WHEN NVL(ROKMISC.F_CALC_STUD_CREDIT_HRS(:PERIOD, X.SGBSTDN_PIDM, 'N'), 0) >= RORCRHR_HALF_TIME_CR_HRS
        THEN RORALGS_AMT
    END as calc_amt
FROM SGBSTDN X, RORCRHR, RORALGS, ROBNYUD
WHERE RORALGS_KEY_1 = 'PBDG'

AND CASE -- freshmen student type
    WHEN (X.SGBSTDN_STYP_CODE IN ('1','T')) THEN 'T'                   
END = RORALGS_KEY_2 

AND RORALGS_KEY_4 = '3HSM' -- budget component                        

AND CASE -- level code
    WHEN X.SGBSTDN_LEVL_CODE = 'UG' THEN 'UG'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SGBSTDN_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
																						
-- max sgbstdn term <= passed period
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND RORCRHR_AIDY_CODE = :AIDY
AND RORCRHR_LEVL_CODE = X.SGBSTDN_LEVL_CODE
AND RORCRHR_PERIOD = :PERIOD

AND ROBNYUD_VALUE_120 = 'C'
AND X.SGBSTDN_PIDM = ROBNYUD_PIDM 

AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
-- END



--UNDERGRAD TRANSFER NOT ENROLLED WITH SGASTDN
SELECT RORALGS_AMT
FROM SGBSTDN X, RORALGS, ROBNYUD
WHERE RORALGS_KEY_1 = 'PBDG'

AND CASE -- freshmen student type
    WHEN (X.SGBSTDN_STYP_CODE IN ('1','T')) THEN 'T'
END = RORALGS_KEY_2 

AND RORALGS_KEY_4 = '3HSM' -- budget component                        

AND CASE -- level code
    WHEN X.SGBSTDN_LEVL_CODE = 'UG' THEN 'UG'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SGBSTDN_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
		
-- max sgbstdn term <= passed period
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND ROBNYUD_VALUE_120 = 'C'
AND X.SGBSTDN_PIDM = ROBNYUD_PIDM 

AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
-- END



--UNDERGRAD TRANSFER NOT ENROLLED NO SGASTDN
SELECT RORALGS_AMT
FROM SARADAP X, SARAPPD X, RORALGS, STVAPDC, ROBNYUD
WHERE RORALGS_KEY_1 = 'PBDG'

AND CASE -- freshmen student type
    WHEN (X.SARADAP_STYP_CODE IN ('1','T')) THEN 'T'
END = RORALGS_KEY_2 

AND RORALGS_KEY_4 = '3HSM' -- budget component                 

AND CASE -- level code
    WHEN X.SARADAP_LEVL_CODE = 'UG' THEN 'UG'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SARADAP_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
		
-- max saradap term <= passed period	
AND X.SARADAP_TERM_CODE_ENTRY = (
     SELECT MAX(Y.SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP Y, ROBINST
    WHERE Y.SARADAP_PIDM = X.SARADAP_PIDM
	AND Y.SARADAP_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
    AND Y.SARADAP_TERM_CODE_ENTRY <= :PERIOD
	AND ROBINST_AIDY_CODE = :AIDY
)
--max application decision code sequence number
AND X.SARAPPD_SEQ_NO = (SELECT MAX (X.SARAPPD_SEQ_NO)
             FROM SARAPPD Y, ROBINST
              WHERE     Y.SARAPPD_PIDM = X.SARAPPD_PIDM
              AND Y.SARAPPD_SEQ_NO < 99
              AND Y.SARAPPD_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
              AND Y.SARAPPD_TERM_CODE_ENTRY <= :PERIOD
              AND ROBINST_AIDY_CODE = :AIDY           
              AND X.SARADAP_APPL_NO = Y.SARAPPD_APPL_NO) 
      
   AND STVAPDC_INST_ACC_IND = 'Y'
   AND STVAPDC_SIGNF_IND = 'Y'
   
AND ROBNYUD_VALUE_120 = 'C'
AND X.SARADAP_PIDM = ROBNYUD_PIDM 

AND X.SARAPPD_APDC_CODE = STVAPDC_CODE	
AND X.SARADAP_APPL_NO = X.SARAPPD_APPL_NO
AND X.SARADAP_TERM_CODE_ENTRY = X.SARAPPD_TERM_CODE_ENTRY
AND RORALGS_AIDY_CODE = :AIDY
AND X.SARAPPD_PIDM = X.SARADAP_PIDM	
AND X.SARADAP_PIDM = :PIDM
-- END







--UNDERGRAD, GRAD, LAW, MED ENROLLED WITH RORPRST_XHS '2' AND SGASTDN RECORD
SELECT CASE
    WHEN NVL(ROKMISC.F_CALC_STUD_CREDIT_HRS(:PERIOD, X.SGBSTDN_PIDM, 'N'), 0) >= RORCRHR_HALF_TIME_CR_HRS
        THEN RORALGS_AMT
    END as calc_amt
FROM SGBSTDN X, RORPRST, RORCRHR, RORALGS
WHERE RORALGS_KEY_1 = 'PBDG'

AND CASE -- ON CAMPUS HOUSING FLAG IN RORPRST
    WHEN (RORPRST_XHS = '2') THEN '2' 
END = RORALGS_KEY_3 

AND RORALGS_KEY_4 = '3HSM' -- budget component                    

AND CASE -- level code
    WHEN X.SGBSTDN_LEVL_CODE = 'UG' THEN 'UG'
	WHEN X.SGBSTDN_LEVL_CODE = 'GR' THEN 'GR'
	WHEN X.SGBSTDN_LEVL_CODE = 'PL' THEN 'PL'
	WHEN X.SGBSTDN_LEVL_CODE = 'PM' THEN 'PM'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SGBSTDN_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6

-- max sgbstdn term <= passed period
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND RORCRHR_AIDY_CODE = :AIDY
AND RORCRHR_LEVL_CODE = X.SGBSTDN_LEVL_CODE
AND RORCRHR_PERIOD = :PERIOD
	
AND X.SGBSTDN_PIDM = RORPRST_PIDM
AND RORPRST_PERIOD = :PERIOD
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
-- END



--UNDERGRAD, GRAD, LAW, MED NOT ENROLLED WITH RORPRST_XHS '2' AND SGASTDN RECORD                   
SELECT RORALGS_AMT
FROM SGBSTDN X, RORALGS, RORPRST
WHERE RORALGS_KEY_1 = 'PBDG'

AND CASE -- HOUSING FLAG IN RORPRST
    WHEN (RORPRST_XHS = '2') THEN '2' 
END = RORALGS_KEY_3 

AND RORALGS_KEY_4 = '3HSM' -- budget component                        

AND CASE -- level code
    WHEN X.SGBSTDN_LEVL_CODE = 'UG' THEN 'UG'
	WHEN X.SGBSTDN_LEVL_CODE = 'GR' THEN 'GR'
	WHEN X.SGBSTDN_LEVL_CODE = 'PL' THEN 'PL'
	WHEN X.SGBSTDN_LEVL_CODE = 'PM' THEN 'PM'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SGBSTDN_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6

-- max sgbstdn term <= passed period
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND X.SGBSTDN_PIDM = RORPRST_PIDM
AND RORPRST_PERIOD = :PERIOD
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
-- END



--UNDERGRAD, GRAD, LAW, MED NOT ENROLLED WITH RORPRST_XHS '2' NO SGASTDN RECORD         
SELECT RORALGS_AMT
FROM SARADAP X, SARAPPD X, RORALGS, STVAPDC, RORPRST
WHERE RORALGS_KEY_1 = 'PBDG'

AND CASE -- HOUSING FLAG IN RORPRST
    WHEN (RORPRST_XHS = '2') THEN '2' 
END = RORALGS_KEY_3 

AND RORALGS_KEY_4 = '3HSM' -- budget component                     

AND CASE -- level code
    WHEN X.SARADAP_LEVL_CODE = 'UG' THEN 'UG'
	WHEN X.SARADAP_LEVL_CODE = 'GR' THEN 'GR'
	WHEN X.SARADAP_LEVL_CODE = 'PL' THEN 'PL'
	WHEN X.SARADAP_LEVL_CODE = 'PM' THEN 'PM'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SARADAP_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6

-- max saradap term <= passed period	
AND X.SARADAP_TERM_CODE_ENTRY = (
     SELECT MAX(Y.SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP Y, ROBINST
    WHERE Y.SARADAP_PIDM = X.SARADAP_PIDM
	AND Y.SARADAP_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
    AND Y.SARADAP_TERM_CODE_ENTRY <= :PERIOD
	AND ROBINST_AIDY_CODE = :AIDY
)
--max application decision code sequence number
AND X.SARAPPD_SEQ_NO = (SELECT MAX (X.SARAPPD_SEQ_NO)
             FROM SARAPPD Y, ROBINST
              WHERE     Y.SARAPPD_PIDM = X.SARAPPD_PIDM
              AND Y.SARAPPD_SEQ_NO < 99
              AND Y.SARAPPD_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
              AND Y.SARAPPD_TERM_CODE_ENTRY <= :PERIOD
              AND ROBINST_AIDY_CODE = :AIDY           
              AND X.SARADAP_APPL_NO = Y.SARAPPD_APPL_NO) 
      
   AND STVAPDC_INST_ACC_IND = 'Y'
   AND STVAPDC_SIGNF_IND = 'Y'
		
AND X.SARADAP_PIDM = RORPRST_PIDM
AND RORPRST_PERIOD = :PERIOD

AND X.SARAPPD_APDC_CODE = STVAPDC_CODE	
AND X.SARADAP_APPL_NO = X.SARAPPD_APPL_NO
AND X.SARADAP_TERM_CODE_ENTRY = X.SARAPPD_TERM_CODE_ENTRY
AND RORALGS_AIDY_CODE = :AIDY
AND X.SARAPPD_PIDM = X.SARADAP_PIDM	
AND X.SARADAP_PIDM = :PIDM
-- END
