select * from (
select rorstat_pgrp_code, count(*) as cnt
from rorstat
where rorstat_aidy_code = '2627'
group by rorstat_pgrp_code
) order by cnt desc;

-- UFH1 banner 08/18
SELECT RORSTAT_PIDM
  FROM RORSTAT, ROBINST,ROBNYUD
WHERE ROBINST_STATUS_IND = 'A'
    AND ROBINST_AIDY_CODE = RORSTAT_AIDY_CODE
    AND RORSTAT_PIDM = ROBNYUD_PIDM
    AND (RORSTAT_APPL_RCVD_DATE IS NULL
    OR   RORSTAT_TGRP_CODE = 'REJSAR'
    OR EXISTS (
            SELECT 1
            FROM RRRAREQ
            WHERE RRRAREQ_PIDM = RORSTAT_PIDM
            AND RRRAREQ_AIDY_CODE = RORSTAT_AIDY_CODE
            AND ((RRRAREQ_TREQ_CODE =  'INDV27'
            AND  RRRAREQ_TRST_CODE = 'M')
            OR  (RRRAREQ_TREQ_CODE = 'DHSC'
            AND RRRAREQ_TRST_CODE = 'M'))
        )
    )
     AND ROBNYUD_VALUE_27 BETWEEN (ROBINST_AIDY_END_YEAR || '00') AND (ROBINST_AIDY_END_YEAR || '20')
   AND ROBNYUD_VALUE_23 IS NOT NULL
   AND (EXISTS
(SELECT 'X'
  FROM SARAPPD A, STVAPDC
WHERE A.SARAPPD_PIDM = RORSTAT_PIDM
   AND A.SARAPPD_APDC_CODE = STVAPDC_CODE
   AND STVAPDC_INST_ACC_IND = 'Y'
   AND STVAPDC_SIGNF_IND = 'Y'
   AND A.SARAPPD_TERM_CODE_ENTRY||LPAD(A.SARAPPD_APPL_NO,2,0)||LPAD(A.SARAPPD_SEQ_NO,2,0) =
    (SELECT MAX(B.SARAPPD_TERM_CODE_ENTRY||LPAD(B.SARAPPD_APPL_NO,2,0)||LPAD(B.SARAPPD_SEQ_NO,2,0))
       FROM SARAPPD B
      WHERE B.SARAPPD_PIDM = A.SARAPPD_PIDM
        AND B.SARAPPD_TERM_CODE_ENTRY IN
                (SELECT SORXREF_EDI_QLFR
                    FROM SORXREF
                WHERE SORXREF_EDI_VALUE = 'ALL_TERMS'
                  AND SORXREF_XLBL_CODE = 'ZSFS_VAR'
                  AND SORXREF_BANNER_VALUE = RORSTAT_AIDY_CODE)
            AND B.SARAPPD_PIDM=RORSTAT_PIDM)
   AND EXISTS
    (SELECT 'X'
       FROM SARADAP
      WHERE SARADAP_LEVL_CODE = 'UG'
            AND SARADAP_STYP_CODE IN ('F','1')
          AND SARADAP_COLL_CODE_1 <> 'ZA'
        AND SARADAP_PIDM = A.SARAPPD_PIDM
        AND SARADAP_TERM_CODE_ENTRY = A.SARAPPD_TERM_CODE_ENTRY
        AND SARADAP_APPL_NO = A.SARAPPD_APPL_NO)))
 
AND RORSTAT_AIDY_CODE            = :AIDY                                                           
-- AND RORSTAT_PIDM    =:PIDM
;

-- rework
SELECT RORSTAT_PIDM
FROM RORSTAT
JOIN ROBINST on ROBINST_AIDY_CODE = RORSTAT_AIDY_CODE 
    and ROBINST_STATUS_IND = 'A'
JOIN ROBNYUD on ROBNYUD_PIDM = RORSTAT_PIDM
    and ROBNYUD_VALUE_27 BETWEEN (ROBINST_AIDY_END_YEAR || '00') AND (ROBINST_AIDY_END_YEAR || '20')
    and ROBNYUD_VALUE_23 IS NOT NULL
WHERE RORSTAT_AIDY_CODE = :AIDY
AND RORSTAT_PIDM = :PIDM
AND (
    RORSTAT_APPL_RCVD_DATE IS NULL
    OR RORSTAT_TGRP_CODE = 'REJSAR'
    OR EXISTS (
        SELECT 1
        FROM RRRAREQ
        WHERE RRRAREQ_PIDM = RORSTAT_PIDM
        AND RRRAREQ_AIDY_CODE = RORSTAT_AIDY_CODE
        AND (
            (
                RRRAREQ_TREQ_CODE =  'INDV27'
                AND RRRAREQ_TRST_CODE = 'M'
            ) OR (
                RRRAREQ_TREQ_CODE = 'DHSC'
                AND RRRAREQ_TRST_CODE = 'M'
            )
        )
    )
)
AND (
    EXISTS (
        SELECT 1
        FROM SARADAP a
        JOIN SARAPPD b on b.SARAPPD_PIDM = a.SARADAP_PIDM
            and b.SARAPPD_TERM_CODE_ENTRY = a.SARADAP_TERM_CODE_ENTRY
            and b.SARAPPD_APPL_NO = a.SARADAP_APPL_NO
        JOIN STVAPDC c on c.STVAPDC_CODE = b.SARAPPD_APDC_CODE
            and c.STVAPDC_INST_ACC_IND = 'Y'
            and c.STVAPDC_SIGNF_IND = 'Y'
        WHERE a.SARADAP_PIDM = RORSTAT_PIDM
        AND a.SARADAP_LEVL_CODE = 'UG'
        and a.SARADAP_STYP_CODE in ('F', '1')
        and a.SARADAP_COLL_CODE_1 <> 'ZA'
        AND a.SARADAP_TERM_CODE_ENTRY = (
            SELECT MAX(z.SARADAP_TERM_CODE_ENTRY) 
            FROM SARADAP z
            WHERE z.SARADAP_PIDM = a.SARADAP_PIDM
            AND SUBSTR(z.SARADAP_TERM_CODE_ENTRY,0,4) = SUBSTR(ROBINST_AIDY_END_YEAR,0,4)
        )
        AND a.SARADAP_APPL_NO = (
            SELECT MAX(z.SARADAP_APPL_NO) 
            FROM SARADAP z
            WHERE z.SARADAP_PIDM = a.SARADAP_PIDM
            AND z.SARADAP_TERM_CODE_ENTRY = a.SARADAP_TERM_CODE_ENTRY
        )
        AND b.SARAPPD_SEQ_NO = (
            SELECT MAX(z.SARAPPD_SEQ_NO) 
            FROM SARAPPD z
            WHERE z.SARAPPD_PIDM = b.SARAPPD_PIDM
            AND z.SARAPPD_TERM_CODE_ENTRY = b.SARAPPD_TERM_CODE_ENTRY
            AND z.SARAPPD_APPL_NO = b.SARAPPD_APPL_NO
        )
    )
)
 

;