SELECT DISTINCT(RORSTAT_PIDM) 
  FROM RORSTAT, RBRAPBG
 WHERE RBRAPBG_PBGP_CODE = 'UG'
        AND  RBRAPBG_RUN_NAME = 'ACTUAL'
        AND RORSTAT_PIDM = RBRAPBG_PIDM
        AND RORSTAT_AIDY_CODE = RBRAPBG_AIDY_CODE
   AND RORSTAT_AIDY_CODE = :AIDY         
--    AND RORSTAT_PIDM    =:PIDM
;
-- rework
SELECT DISTINCT RORSTAT_PIDM
FROM RORSTAT
JOIN RBRAPBG on RBRAPBG_PIDM = RORSTAT_PIDM
    and RBRAPBG_AIDY_CODE = RORSTAT_AIDY_CODE
    and RBRAPBG_RUN_NAME = 'ACTUAL'
    and RBRAPBG_PBGP_CODE = 'UG'
WHERE RORSTAT_AIDY_CODE = :AIDY
AND RORSTAT_PIDM = :PIDM
;