-- banner 8/18
SELECT DISTINCT(RORSTAT_PIDM) 
  FROM RORSTAT, RBRAPBG
 WHERE RBRAPBG_PBGP_CODE = 'UG'
        AND  RBRAPBG_RUN_NAME = 'ACTUAL'
        AND RORSTAT_PIDM = RBRAPBG_PIDM
        AND RORSTAT_AIDY_CODE = RBRAPBG_AIDY_CODE
   AND EXISTS
   (SELECT 'X'
      FROM RCRAPP1,RCRAPP3
	 WHERE (RCRAPP1_DEGREE_BY_JULY <> '1'
                    OR RCRAPP3_DEGREE_TYPE <> '8'
                    OR RCRAPP3_YR_IN_COLL_2 IN ('0','1','2','3','4','5'))
          AND RCRAPP1_PIDM = RCRAPP3_PIDM
          AND RCRAPP1_AIDY_CODE = RCRAPP3_AIDY_CODE
          AND RCRAPP1_SEQ_NO = RCRAPP3_SEQ_NO
          AND RCRAPP1_INFC_CODE = RCRAPP3_INFC_CODE
          AND RCRAPP1_PIDM = RORSTAT_PIDM
	   AND RCRAPP1_AIDY_CODE = RORSTAT_AIDY_CODE
       AND RCRAPP1_CURR_REC_IND = 'Y'
       AND RCRAPP1_INFC_CODE = 'EDE')
   AND RORSTAT_AIDY_CODE = :AIDY        
   AND RORSTAT_PIDM    =:PIDM

;

-- rework
SELECT DISTINCT RORSTAT_PIDM
FROM RORSTAT
JOIN RBRAPBG on RBRAPBG_PIDM = RORSTAT_PIDM
    and RBRAPBG_AIDY_CODE = RORSTAT_AIDY_CODE
    and RBRAPBG_RUN_NAME = 'ACTUAL'
    and RBRAPBG_PBGP_CODE = 'UG'
JOIN RCRAPP1 on RCRAPP1_PIDM = RORSTAT_PIDM
    and RCRAPP1_AIDY_CODE = RORSTAT_AIDY_CODE
    and RCRAPP1_INFC_CODE = 'EDE'
    and RCRAPP1_CURR_REC_IND = 'Y'
JOIN RCRAPP3 on RCRAPP3_PIDM = RCRAPP1_PIDM
    and RCRAPP3_AIDY_CODE = RCRAPP1_AIDY_CODE
    and RCRAPP3_INFC_CODE = RCRAPP1_INFC_CODE
    and RCRAPP3_SEQ_NO = RCRAPP1_SEQ_NO
WHERE RORSTAT_AIDY_CODE = :AIDY
AND (
    RCRAPP1_DEGREE_BY_JULY <> '1'
    OR RCRAPP3_DEGREE_TYPE <> '8'
    OR RCRAPP3_YR_IN_COLL_2 IN ('0','1','2','3','4','5')
)
;