
-- GRAD WITH SELECT PROGRAM CODES (MOSTLY EDUCATION) ENROLLED
SELECT CASE
    WHEN NVL(ROKMISC.F_CALC_STUD_BILL_HRS(:PERIOD, X.SGBSTDN_PIDM, 'N'), 0) > 0
        THEN round(roralgs_amt * NVL(ROKMISC.F_CALC_STUD_BILL_HRS(:PERIOD, X.SGBSTDN_PIDM, 'N'), 0))
    END as calc_amt
FROM SGBSTDN X, RORALGS
WHERE RORALGS_KEY_1 = 'PBDG'
AND RORALGS_KEY_4 = '1TUI'
AND CASE
    WHEN X.SGBSTDN_LEVL_CODE = 'GR' THEN 'GR'
END = RORALGS_KEY_5
AND CASE
    WHEN X.SGBSTDN_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
AND CASE
    WHEN X.SGBSTDN_PROGRAM_1 in ('RLED11', 'RLED12' ) THEN 'RLED'
    WHEN X.SGBSTDN_PROGRAM_1 = 'SPAN11' THEN 'SPAN11'
	WHEN X.SGBSTDN_PROGRAM_1 = 'EALM42' THEN 'EALM42'
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDHA23' THEN 'EDHA23'
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDI11' THEN 'EDI11'
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDI21' THEN 'EDI21'
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDI24' THEN 'EDI24'
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDI25' THEN 'EDI25'
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDL19' THEN 'EDL19'
    WHEN X.SGBSTDN_PROGRAM_1 = 'EDL191' THEN 'EDL191'
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDL192' THEN 'EDL192'
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDL193' THEN 'EDL193'
    WHEN X.SGBSTDN_PROGRAM_1 = 'EDL194' THEN 'EDL194'
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDL26' THEN 'EDL26'
    WHEN X.SGBSTDN_PROGRAM_1 = 'EDL27' THEN 'EDL27'
    WHEN X.SGBSTDN_PROGRAM_1 = 'EDL28' THEN 'EDL28'
    WHEN X.SGBSTDN_PROGRAM_1 = 'EDS22' THEN 'EDS22'
    WHEN X.SGBSTDN_PROGRAM_1 = 'EIP41' THEN 'EIP41'
    WHEN X.SGBSTDN_PROGRAM_1 = 'ELCE10' THEN 'ELCE10'
    WHEN X.SGBSTDN_PROGRAM_1 = 'ELCE19' THEN 'ELCE19'
    WHEN X.SGBSTDN_PROGRAM_1 = 'ELCE24' THEN 'ELCE24'
    WHEN X.SGBSTDN_PROGRAM_1 = 'ELCE25' THEN 'ELCE25'
    WHEN X.SGBSTDN_PROGRAM_1 = 'EPE22' THEN 'EPE22'
    WHEN X.SGBSTDN_PROGRAM_1 = 'EPP14' THEN 'EPP14'
    WHEN X.SGBSTDN_PROGRAM_1 = 'EPP15' THEN 'EPP15'
    WHEN X.SGBSTDN_PROGRAM_1 = 'EPP16' THEN 'EPP16'
    WHEN X.SGBSTDN_PROGRAM_1 = 'EPP17' THEN 'EPP17'
    WHEN X.SGBSTDN_PROGRAM_1 = 'HESA12' THEN 'HESA12'
    WHEN X.SGBSTDN_PROGRAM_1 = 'TEAC116' THEN 'TEAC116'
    WHEN X.SGBSTDN_PROGRAM_1 = 'TEAC117' THEN 'TEAC117'
    WHEN X.SGBSTDN_PROGRAM_1 = 'TEAC118' THEN 'TEAC118'
    WHEN X.SGBSTDN_PROGRAM_1 = 'UNCD85' THEN 'UNCD85'
    WHEN X.SGBSTDN_PROGRAM_1 = 'UNCD86' THEN 'UNCD86'
    WHEN X.SGBSTDN_PROGRAM_1 = 'UNCD87' THEN 'UNCD87'
    WHEN X.SGBSTDN_PROGRAM_1 = 'DAHE42' THEN 'DAHE42'
    WHEN X.SGBSTDN_PROGRAM_1 = 'EDE42' THEN 'EDE42'
END = RORALGS_KEY_9		
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
-- END

;

--GRAD WITH SELECT EDUCATION PROGRAM CODES NOT ENROLLED WITH SGASTDN
SELECT (RORALGS_AMT * 6)                                                           
FROM SGBSTDN X, RORALGS
WHERE RORALGS_KEY_1 = 'PBDG'

AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
    WHEN X.SGBSTDN_LEVL_CODE = 'GR' THEN 'GR'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SGBSTDN_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
	
AND CASE -- major/program code
    WHEN X.SGBSTDN_PROGRAM_1 in ('RLED11', 'RLED12' ) THEN 'RLED'
    WHEN X.SGBSTDN_PROGRAM_1 = 'SPAN11' THEN 'SPAN11'
	WHEN X.SGBSTDN_PROGRAM_1 = 'EALM42' THEN 'EALM42'
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDHA23' THEN 'EDHA23'
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDI11' THEN 'EDI11'
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDI21' THEN 'EDI21'
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDI24' THEN 'EDI24'
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDI25' THEN 'EDI25'
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDL19' THEN 'EDL19'
    WHEN X.SGBSTDN_PROGRAM_1 = 'EDL191' THEN 'EDL191'
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDL192' THEN 'EDL192'
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDL193' THEN 'EDL193'
    WHEN X.SGBSTDN_PROGRAM_1 = 'EDL194' THEN 'EDL194'
	WHEN X.SGBSTDN_PROGRAM_1 = 'EDL26' THEN 'EDL26'
    WHEN X.SGBSTDN_PROGRAM_1 = 'EDL27' THEN 'EDL27'
    WHEN X.SGBSTDN_PROGRAM_1 = 'EDL28' THEN 'EDL28'
    WHEN X.SGBSTDN_PROGRAM_1 = 'EDS22' THEN 'EDS22'
    WHEN X.SGBSTDN_PROGRAM_1 = 'EIP41' THEN 'EIP41'
    WHEN X.SGBSTDN_PROGRAM_1 = 'ELCE10' THEN 'ELCE10'
    WHEN X.SGBSTDN_PROGRAM_1 = 'ELCE19' THEN 'ELCE19'
    WHEN X.SGBSTDN_PROGRAM_1 = 'ELCE24' THEN 'ELCE24'
    WHEN X.SGBSTDN_PROGRAM_1 = 'ELCE25' THEN 'ELCE25'
    WHEN X.SGBSTDN_PROGRAM_1 = 'EPE22' THEN 'EPE22'
    WHEN X.SGBSTDN_PROGRAM_1 = 'EPP14' THEN 'EPP14'
    WHEN X.SGBSTDN_PROGRAM_1 = 'EPP15' THEN 'EPP15'
    WHEN X.SGBSTDN_PROGRAM_1 = 'EPP16' THEN 'EPP16'
    WHEN X.SGBSTDN_PROGRAM_1 = 'EPP17' THEN 'EPP17'
    WHEN X.SGBSTDN_PROGRAM_1 = 'HESA12' THEN 'HESA12'
    WHEN X.SGBSTDN_PROGRAM_1 = 'TEAC116' THEN 'TEAC116'
    WHEN X.SGBSTDN_PROGRAM_1 = 'TEAC117' THEN 'TEAC117'
    WHEN X.SGBSTDN_PROGRAM_1 = 'TEAC118' THEN 'TEAC118'
    WHEN X.SGBSTDN_PROGRAM_1 = 'UNCD85' THEN 'UNCD85'
    WHEN X.SGBSTDN_PROGRAM_1 = 'UNCD86' THEN 'UNCD86'
    WHEN X.SGBSTDN_PROGRAM_1 = 'UNCD87' THEN 'UNCD87'
    WHEN X.SGBSTDN_PROGRAM_1 = 'DAHE42' THEN 'DAHE42'
    WHEN X.SGBSTDN_PROGRAM_1 = 'EDE42' THEN 'EDE42'
END = RORALGS_KEY_9		
		
-- max sgbstdn term <= passed period
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND NOT EXISTS (
    SELECT 1
    FROM SARADAP
    INNER JOIN SARAPPD
        ON SARAPPD_PIDM = SARADAP_PIDM
        AND SARAPPD_APPL_NO = SARADAP_APPL_NO
        AND SARAPPD_TERM_CODE_ENTRY = SARADAP_TERM_CODE_ENTRY
    INNER JOIN STVAPDC
        ON STVAPDC_CODE = SARAPPD_APDC_CODE
        AND STVAPDC_INST_ACC_IND = 'Y'
        AND STVAPDC_SIGNF_IND = 'Y'
    WHERE SARADAP_PIDM = X.SGBSTDN_PIDM
    AND SARADAP_TERM_CODE_ENTRY > X.SGBSTDN_TERM_CODE_EFF 
    AND SARADAP_TERM_CODE_ENTRY <= ('20' || cast(substr(:AIDY, 2, 2) as int) + 1 || '00')
    AND SARADAP_PROGRAM_1 <> X.SGBSTDN_PROGRAM_1
)
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_PIDM = :PIDM
AND RORALGS_AIDY_CODE = :AIDY
-- END

;

--GRAD WITH SELECT EDUCATION PROGRAM CODES NO SGASTDN ENROLLED
SELECT (RORALGS_AMT * 6)                                                           
FROM SARADAP X, SARAPPD X, RORALGS, STVAPDC
WHERE RORALGS_KEY_1 = 'PBDG'

AND RORALGS_KEY_4 = '1TUI' -- budget component

AND CASE -- level code
    WHEN X.SARADAP_LEVL_CODE = 'GR' THEN 'GR'
END = RORALGS_KEY_5
	
AND CASE -- campus code
    WHEN X.SARADAP_CAMP_CODE = 'FR' THEN 'FR'
END = RORALGS_KEY_6
	
AND CASE -- major/program code
    WHEN X.SARADAP_PROGRAM_1 in ('RLED11', 'RLED12' ) THEN 'RLED'
    WHEN X.SARADAP_PROGRAM_1 = 'SPAN11' THEN 'SPAN11'
	WHEN X.SARADAP_PROGRAM_1 = 'EALM42' THEN 'EALM42'
	WHEN X.SARADAP_PROGRAM_1 = 'EDHA23' THEN 'EDHA23'
	WHEN X.SARADAP_PROGRAM_1 = 'EDI11' THEN 'EDI11'
	WHEN X.SARADAP_PROGRAM_1 = 'EDI21' THEN 'EDI21'
	WHEN X.SARADAP_PROGRAM_1 = 'EDI24' THEN 'EDI24'
	WHEN X.SARADAP_PROGRAM_1 = 'EDI25' THEN 'EDI25'
	WHEN X.SARADAP_PROGRAM_1 = 'EDL19' THEN 'EDL19'
    WHEN X.SARADAP_PROGRAM_1 = 'EDL191' THEN 'EDL191'
	WHEN X.SARADAP_PROGRAM_1 = 'EDL192' THEN 'EDL192'
	WHEN X.SARADAP_PROGRAM_1 = 'EDL193' THEN 'EDL193'
    WHEN X.SARADAP_PROGRAM_1 = 'EDL194' THEN 'EDL194'
	WHEN X.SARADAP_PROGRAM_1 = 'EDL26' THEN 'EDL26'
    WHEN X.SARADAP_PROGRAM_1 = 'EDL27' THEN 'EDL27'
    WHEN X.SARADAP_PROGRAM_1 = 'EDL28' THEN 'EDL28'
    WHEN X.SARADAP_PROGRAM_1 = 'EDS22' THEN 'EDS22'
    WHEN X.SARADAP_PROGRAM_1 = 'EIP41' THEN 'EIP41'
    WHEN X.SARADAP_PROGRAM_1 = 'ELCE10' THEN 'ELCE10'
    WHEN X.SARADAP_PROGRAM_1 = 'ELCE19' THEN 'ELCE19'
    WHEN X.SARADAP_PROGRAM_1 = 'ELCE24' THEN 'ELCE24'
    WHEN X.SARADAP_PROGRAM_1 = 'ELCE25' THEN 'ELCE25'
    WHEN X.SARADAP_PROGRAM_1 = 'EPE22' THEN 'EPE22'
    WHEN X.SARADAP_PROGRAM_1 = 'EPP14' THEN 'EPP14'
    WHEN X.SARADAP_PROGRAM_1 = 'EPP15' THEN 'EPP15'
    WHEN X.SARADAP_PROGRAM_1 = 'EPP16' THEN 'EPP16'
    WHEN X.SARADAP_PROGRAM_1 = 'EPP17' THEN 'EPP17'
    WHEN X.SARADAP_PROGRAM_1 = 'HESA12' THEN 'HESA12'
    WHEN X.SARADAP_PROGRAM_1 = 'TEAC116' THEN 'TEAC116'
    WHEN X.SARADAP_PROGRAM_1 = 'TEAC117' THEN 'TEAC117'
    WHEN X.SARADAP_PROGRAM_1 = 'TEAC118' THEN 'TEAC118'
    WHEN X.SARADAP_PROGRAM_1 = 'UNCD85' THEN 'UNCD85'
    WHEN X.SARADAP_PROGRAM_1 = 'UNCD86' THEN 'UNCD86'
    WHEN X.SARADAP_PROGRAM_1 = 'UNCD87' THEN 'UNCD87'
    WHEN X.SARADAP_PROGRAM_1 = 'DAHE42' THEN 'DAHE42'
    WHEN X.SARADAP_PROGRAM_1 = 'EDE42' THEN 'EDE42'
END = RORALGS_KEY_9		

AND X.SARADAP_TERM_CODE_ENTRY = (
     SELECT MAX(Y.SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP Y, ROBINST
    WHERE Y.SARADAP_PIDM = X.SARADAP_PIDM
	AND Y.SARADAP_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
    AND Y.SARADAP_TERM_CODE_ENTRY <= :PERIOD
	AND ROBINST_AIDY_CODE = :AIDY
)
--max application decision code sequence number
AND X.SARAPPD_SEQ_NO = (SELECT MAX (X.SARAPPD_SEQ_NO)
	FROM SARAPPD Y, ROBINST
	WHERE     Y.SARAPPD_PIDM = X.SARAPPD_PIDM
	AND Y.SARAPPD_SEQ_NO < 99
	AND Y.SARAPPD_TERM_CODE_ENTRY >= (ROBINST_AIDY_END_YEAR || '00')
	AND Y.SARAPPD_TERM_CODE_ENTRY <= :PERIOD
	AND ROBINST_AIDY_CODE = :AIDY           
	AND X.SARADAP_APPL_NO = Y.SARAPPD_APPL_NO) 
      
AND STVAPDC_INST_ACC_IND = 'Y'
AND STVAPDC_SIGNF_IND = 'Y'

AND X.SARAPPD_APDC_CODE = STVAPDC_CODE	
AND X.SARADAP_APPL_NO = X.SARAPPD_APPL_NO
AND X.SARADAP_TERM_CODE_ENTRY = X.SARAPPD_TERM_CODE_ENTRY
AND RORALGS_AIDY_CODE = :AIDY
AND X.SARAPPD_PIDM = X.SARADAP_PIDM	
AND X.SARADAP_PIDM = :PIDM
-- END

;