SELECT RORALGS_AMT
FROM SGBSTDN X
INNER JOIN RORALGS on RORALGS_AIDY_CODE = :AIDY
    AND RORALGS_KEY_1 = 'PBDG'
    AND RORALGS_KEY_4 = '1TUI'    
    AND RORALGS_KEY_5 = X.SGBSTDN_LEVL_CODE
    AND RORALGS_KEY_9 = X.SGBSTDN_PROGRAM_1
WHERE X.SGBSTDN_LEVL_CODE = 'GR'
AND X.SGBSTDN_COLL_CODE_1 = 'MD'
AND X.SGBSTDN_PROGRAM_1 in ('AN11', 'MDSC11')
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
-- AND X.SGBSTDN_PIDM = :PIDM
--END
;

SELECT RORALGS_AMT
FROM SARADAP a
INNER JOIN ROBINST on ROBINST_AIDY_CODE = :AIDY
INNER JOIN SARAPPD b
    ON SARAPPD_PIDM = SARADAP_PIDM
    AND SARAPPD_APPL_NO = SARADAP_APPL_NO
    AND SARAPPD_TERM_CODE_ENTRY = SARADAP_TERM_CODE_ENTRY
INNER JOIN STVAPDC c
    ON STVAPDC_CODE = SARAPPD_APDC_CODE
    AND STVAPDC_INST_ACC_IND = 'Y'
    AND STVAPDC_SIGNF_IND = 'Y'
INNER JOIN RORALGS on RORALGS_AIDY_CODE = :AIDY
    AND RORALGS_KEY_1 = 'PBDG'
    AND RORALGS_KEY_4 = '1TUI'    
    AND RORALGS_KEY_5 = a.SARADAP_LEVL_CODE
    AND RORALGS_KEY_9 = a.SARADAP_PROGRAM_1
WHERE a.SARADAP_LEVL_CODE = 'GR'
AND a.SARADAP_COLL_CODE_1 = 'MD'
AND a.SARADAP_PROGRAM_1 in ('AN11', 'MDSC11')
AND SARADAP_TERM_CODE_ENTRY = (
    SELECT MAX(Y.SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP Y
    WHERE Y.SARADAP_PIDM = a.SARADAP_PIDM
    AND Y.SARADAP_TERM_CODE_ENTRY between (ROBINST_AIDY_END_YEAR || '00') and :PERIOD
)
AND SARAPPD_SEQ_NO = (
    SELECT MAX(Y.SARAPPD_SEQ_NO)
    FROM SARAPPD Y
    WHERE Y.SARAPPD_PIDM = b.SARAPPD_PIDM
    AND Y.SARAPPD_TERM_CODE_ENTRY = b.SARAPPD_TERM_CODE_ENTRY
    AND Y.SARAPPD_APPL_NO = b.SARAPPD_APPL_NO
) 

;

-- HOR23 SEQUENCES
SELECT RORALGS_AMT * rokmisc.F_CALC_STUD_BILL_HRS(X.SGBSTDN_PIDM, :PERIOD, 'N')
FROM SGBSTDN X
INNER JOIN RORALGS on RORALGS_AIDY_CODE = :AIDY
    AND RORALGS_KEY_1 = 'PBDG'
    AND RORALGS_KEY_4 = '1TUI'
    AND RORALGS_KEY_5 = X.SGBSTDN_LEVL_CODE
    AND RORALGS_KEY_9 = X.SGBSTDN_PROGRAM_1
WHERE X.SGBSTDN_LEVL_CODE = 'GR'
AND X.SGBSTDN_COLL_CODE_1 = 'MD'
AND X.SGBSTDN_PROGRAM_1 = 'HOR23'
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND rokmisc.F_CALC_STUD_BILL_HRS(X.SGBSTDN_PIDM, :PERIOD, 'N') > 0;


SELECT RORALGS_AMT * 6
FROM SGBSTDN X
INNER JOIN RORALGS on RORALGS_AIDY_CODE = :AIDY
    AND RORALGS_KEY_1 = 'PBDG'
    AND RORALGS_KEY_4 = '1TUI'
    AND RORALGS_KEY_5 = X.SGBSTDN_LEVL_CODE
    AND RORALGS_KEY_9 = X.SGBSTDN_PROGRAM_1
WHERE X.SGBSTDN_LEVL_CODE = 'GR'
AND X.SGBSTDN_COLL_CODE_1 = 'MD'
AND X.SGBSTDN_PROGRAM_1 = 'HOR23'
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND sysdate <= (select cutoff from sfs_utility.PBDG_CUTOFF_DATES where period = :PERIOD);

SELECT RORALGS_AMT * 6
FROM SARADAP a
INNER JOIN ROBINST on ROBINST_AIDY_CODE = :AIDY
INNER JOIN SARAPPD b
    ON SARAPPD_PIDM = SARADAP_PIDM
    AND SARAPPD_APPL_NO = SARADAP_APPL_NO
    AND SARAPPD_TERM_CODE_ENTRY = SARADAP_TERM_CODE_ENTRY
INNER JOIN STVAPDC c
    ON STVAPDC_CODE = SARAPPD_APDC_CODE
    AND STVAPDC_INST_ACC_IND = 'Y'
    AND STVAPDC_SIGNF_IND = 'Y'
INNER JOIN RORALGS on RORALGS_AIDY_CODE = :AIDY
    AND RORALGS_KEY_1 = 'PBDG'
    AND RORALGS_KEY_4 = '1TUI'    
    AND RORALGS_KEY_5 = a.SARADAP_LEVL_CODE
    AND RORALGS_KEY_9 = a.SARADAP_PROGRAM_1
WHERE a.SARADAP_LEVL_CODE = 'GR'
AND a.SARADAP_COLL_CODE_1 = 'MD'
AND a.SARADAP_PROGRAM_1 = 'HOR23'
AND SARADAP_TERM_CODE_ENTRY = (
    SELECT MAX(Y.SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP Y
    WHERE Y.SARADAP_PIDM = a.SARADAP_PIDM
    AND Y.SARADAP_TERM_CODE_ENTRY between (ROBINST_AIDY_END_YEAR || '00') and :PERIOD
)
AND SARAPPD_SEQ_NO = (
    SELECT MAX(Y.SARAPPD_SEQ_NO)
    FROM SARAPPD Y
    WHERE Y.SARAPPD_PIDM = b.SARAPPD_PIDM
    AND Y.SARAPPD_TERM_CODE_ENTRY = b.SARAPPD_TERM_CODE_ENTRY
    AND Y.SARAPPD_APPL_NO = b.SARAPPD_APPL_NO
) ;

-- SS PBC/PHD SEQUENCES
SELECT RORALGS_AMT * rokmisc.F_CALC_STUD_BILL_HRS(X.SGBSTDN_PIDM, :PERIOD, 'N')
FROM SGBSTDN X
INNER JOIN RORALGS on RORALGS_AIDY_CODE = :AIDY
    AND RORALGS_KEY_1 = 'PBDG'
    AND RORALGS_KEY_4 = '1TUI'
    AND RORALGS_KEY_5 = X.SGBSTDN_LEVL_CODE
    AND RORALGS_KEY_6 = X.SGBSTDN_CAMP_CODE
    AND RORALGS_KEY_7 = X.SGBSTDN_COLL_CODE_1
    AND RORALGS_KEY_8 = X.SGBSTDN_DEGC_CODE_1
WHERE X.SGBSTDN_LEVL_CODE = 'GR'
AND X.SGBSTDN_CAMP_CODE = 'FR'
AND X.SGBSTDN_COLL_CODE_1 = 'SS'
AND X.SGBSTDN_DEGC_CODE_1 IN ('PBC', 'PHD')
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND rokmisc.F_CALC_STUD_BILL_HRS(X.SGBSTDN_PIDM, :PERIOD, 'N') > 0
AND X.SGBSTDN_PIDM = :PIDM
;

SELECT RORALGS_AMT * 6
FROM SGBSTDN X
INNER JOIN RORALGS on RORALGS_AIDY_CODE = :AIDY
    AND RORALGS_KEY_1 = 'PBDG'
    AND RORALGS_KEY_4 = '1TUI'
    AND RORALGS_KEY_5 = X.SGBSTDN_LEVL_CODE
    AND RORALGS_KEY_6 = X.SGBSTDN_CAMP_CODE
    AND RORALGS_KEY_7 = X.SGBSTDN_COLL_CODE_1
    AND RORALGS_KEY_8 = X.SGBSTDN_DEGC_CODE_1
WHERE X.SGBSTDN_LEVL_CODE = 'GR'
AND X.SGBSTDN_CAMP_CODE = 'FR'
AND X.SGBSTDN_COLL_CODE_1 = 'SS'
AND X.SGBSTDN_DEGC_CODE_1 IN ('PBC', 'PHD')
AND X.SGBSTDN_STST_CODE IN  ('AS','IL','P1')
AND X.SGBSTDN_TERM_CODE_EFF = (
    SELECT MAX(Y.SGBSTDN_TERM_CODE_EFF)
    FROM SGBSTDN Y
    WHERE Y.SGBSTDN_PIDM = X.SGBSTDN_PIDM
    AND Y.SGBSTDN_TERM_CODE_EFF <= :PERIOD
)
AND sysdate <= (select cutoff from sfs_utility.PBDG_CUTOFF_DATES where period = :PERIOD)
AND X.SGBSTDN_PIDM = :PIDM
;

SELECT RORALGS_AMT * 6
FROM SARADAP a
INNER JOIN ROBINST on ROBINST_AIDY_CODE = :AIDY
INNER JOIN SARAPPD b
    ON SARAPPD_PIDM = SARADAP_PIDM
    AND SARAPPD_APPL_NO = SARADAP_APPL_NO
    AND SARAPPD_TERM_CODE_ENTRY = SARADAP_TERM_CODE_ENTRY
INNER JOIN STVAPDC c
    ON STVAPDC_CODE = SARAPPD_APDC_CODE
    AND STVAPDC_INST_ACC_IND = 'Y'
    AND STVAPDC_SIGNF_IND = 'Y'
INNER JOIN RORALGS on RORALGS_AIDY_CODE = :AIDY
    AND RORALGS_KEY_1 = 'PBDG'
    AND RORALGS_KEY_4 = '1TUI'    
    AND RORALGS_KEY_5 = a.SARADAP_LEVL_CODE
    AND RORALGS_KEY_6 = a.SARADAP_CAMP_CODE
    AND RORALGS_KEY_7 = a.SARADAP_COLL_CODE_1
    AND RORALGS_KEY_8 = a.SARADAP_DEGC_CODE_1
WHERE a.SARADAP_LEVL_CODE = 'GR'
AND a.SARADAP_CAMP_CODE = 'FR'
AND a.SARADAP_COLL_CODE_1 = 'SS'
AND a.SARADAP_DEGC_CODE_1 IN ('PBC', 'PHD')
AND SARADAP_TERM_CODE_ENTRY = (
    SELECT MAX(Y.SARADAP_TERM_CODE_ENTRY)
    FROM SARADAP Y
    WHERE Y.SARADAP_PIDM = a.SARADAP_PIDM
    AND Y.SARADAP_TERM_CODE_ENTRY between (ROBINST_AIDY_END_YEAR || '00') and :PERIOD
)
AND SARAPPD_SEQ_NO = (
    SELECT MAX(Y.SARAPPD_SEQ_NO)
    FROM SARAPPD Y
    WHERE Y.SARAPPD_PIDM = b.SARAPPD_PIDM
    AND Y.SARAPPD_TERM_CODE_ENTRY = b.SARAPPD_TERM_CODE_ENTRY
    AND Y.SARAPPD_APPL_NO = b.SARAPPD_APPL_NO
) 
AND a.SARADAP_PIDM = :PIDM
;

select * from rbrabrc where rbrabrc_abrc_code = '1TUI_GR' and rbrabrc_validated_ind = 'N';